### ISSUE TITLE
🐛css issue with images and empty text

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1001]
### Description

🐛css issue with images and empty text

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website and check the post card 

### Screenshots

before :- 
<img width="723" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/31dbf482-665c-4fd5-a3fc-c3bc0174ba59">

After :- 
<img width="693" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/dc660e9a-b162-4f7b-b2b1-0849cbae88da">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you mean their fitness? yes you can definitely work on this and please ensure, images don't get cropped out

**Comment by narayan954** [comment]
> ### Description
> bugcss issue with images and empty text
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website and check the post card
> 
> ### Screenshots
> before :- <img alt="image" width="723" src="https://user-images.githubusercontent.com/68702055/256512526-31dbf482-665c-4fd5-a3fc-c3bc0174ba59.png">
> 
> After :- <img alt="image" width="693" src="https://user-images.githubusercontent.com/68702055/256513320-dc660e9a-b162-4f7b-b2b1-0849cbae88da.png">
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

I didn't understand the images you provided, you're just comparing two different images

**Comment by biplavmz** [comment]
bro @narayan954 if you see when there is no images only text on gride view images alignment get uneven so i have fix that issue i will raise mr for that and i will also ensure no to crop the images.

**Comment by narayan954** [comment]
> bro @narayan954 if you see when there is no images only text on gride view images alignment get uneven so i have fix that issue i will raise mr for that and i will also ensure no to crop the images.

Thanks bro, you can go ahead!
