### ISSUE TITLE
🐛id text breaking on hover on profile card

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1002]
### Description

🐛id text breaking on hover on profile card
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website and hover on card profile 

### Screenshots

<img width="292" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/2c3e8045-2438-4fab-b92c-89bcb86fc304">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
this seems like a one line fix, can you please add some more little issues into this one! :)
