### ISSUE TITLE
No loader on chat room

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1007]
### Description

Initially the chat room appears as a blank page. I want to add a loader to it until it fetches data.

### Steps to reproduce

Go to community chat
It will appear blank until the data id fetched.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
right, you can work on this! :)

**Comment by narayan954** [comment]
Btw about that older loader issue, I think we can add a shimmer effect for the loading posts, how'd that be??

**Comment by Palakkgoyal** [comment]
Yes I think they are fantastic. Can I create a issue for it?

**Comment by narayan954** [comment]
> Yes I think they are fantastic. Can I create a issue for it?

I think there's already an issue for loader, maybe you can edit it to include this. If we work on this, we wont need those issue

**Comment by Palakkgoyal** [comment]
Yes there is issue for loader but I think that is for the common loader and shimmer effect would be specific to post
