### ISSUE TITLE
[FEATURE] New user section on search page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1008]
### Description

Below the search bar we can give show new users on dummygram and also give add friend button to make a direct and easy contact.

### Screenshots

![Screenshot 2023-07-28 143232](https://github.com/narayan954/dummygram/assets/116902573/80d01251-76c4-49f4-b017-575076cdd77c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
search bar is gone unfortunately :/ btw there exists an showing that focuses on adding such content on opposite of sidebar for recommendations! :) and I think you've commented there actually. will check

**Comment by narayan954** [comment]
closing as not planned right now

**Comment by Palakkgoyal** [comment]
Yes, there is an issue for showing them on the opposite side of sidebar but I thought that is only for the home page and not for whole website.

**Comment by narayan954** [comment]
> Yes, there is an issue for showing them on the opposite side of sidebar but I thought that is only for the home page and not for whole website.

that's not just for home page,even I didn't knew ;-;

**Comment by Palakkgoyal** [comment]
Let's see.
