### ISSUE TITLE
[FEATURE] Alter button of setting page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1009]
### Description

Instead of this simple enable button I want to add a toggle switch here (on/off). I think that would look more good.

### Screenshots

![Screenshot 2023-07-28 143749](https://github.com/narayan954/dummygram/assets/116902573/4006f697-450f-4ea6-b505-91668f4c6897)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
alright, you can work on this!
