### ISSUE TITLE
[FEATURE] Completely alter the post page view

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1011]
### Description

Current view of post page is not very attractive and a lot buggy. Such as it is based on the old implementation and not showing name when someone comment there. I want to work on its UI and solve this bug.

### Screenshots

![Screenshot (626)](https://github.com/narayan954/dummygram/assets/116902573/e30c2272-c296-4184-a042-0f6398c9dab2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
I think this issue already exists @Palakkgoyal , can you please recheck?
I am currently going through the prs, will check these issues and assign them, right after

**Comment by narayan954** [comment]
#806 exists, closing this as duplicate ;-;
