### ISSUE TITLE
Error on notification page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1012]
### Description

Notification page throws error of DOM nesting

### Steps to reproduce

Go to notification page
Open console
You will see an error

### Screenshots

![Screenshot (627)](https://github.com/narayan954/dummygram/assets/116902573/811f4e24-46f5-4408-b2fb-64a6b8e8e301)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Notification page throws error of DOM nesting
> 
> ### Steps to reproduce
> Go to notification page Open console You will see an error
> 
> ### Screenshots
> ![Screenshot (627)](https://user-images.githubusercontent.com/116902573/256780274-811f4e24-46f5-4408-b2fb-64a6b8e8e301.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @Palakkgoyal can you please recheck and confirm, I am not getting this error?

**Comment by narayan954** [comment]
I confirmed the error in code, you can go ahead, it's a really easy fix! :)
