### ISSUE TITLE
404 page darkmode

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1014]
### Description

- 404 page is not darkmode compatible.
- Search page also not showing content in darkmode

### Steps to reproduce

visit these pages in darkmode

### 404 page
<img width="440" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/dd352d79-3290-46c2-a74a-c7038dd02ca5">

### Search page
![image](https://github.com/narayan954/dummygram/assets/66116440/af82da1e-b18b-4f49-a07e-c815be36caf0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can go ahead!
