### ISSUE TITLE
[FEATURE] Login/signup ui

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1015]
### Description

- Currently, both UIs are not looking good
- Sign up UI seems cluttered.
- Also, both UI are filled with blue color
- I would like to display relevant image in the background

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> * I would like to display relevant image in the background

I agree on all of this :') and especially the blue colour, earlier it was pink XD.
But actually there're already issues and prs regarding both colour and the UI look. let's hope they solve them asap! :)
Closing this as duplicate
