### ISSUE TITLE
Change the look of setting and logout button

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1017]
### Description

The current logout and setting button have poor text visibility and also doesn't look good. I want to give them a new look.

### Screenshots

![Screenshot 2023-07-28 194928](https://github.com/narayan954/dummygram/assets/116902573/02d1a36f-3f2e-445c-9afa-c0a9d8b91a80)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal  I was instead thinking this profile/settings/logout options to be like this, what do you think?
![image](https://github.com/narayan954/dummygram/assets/77617189/e6c642d4-a6e6-47cb-9110-7976203f6260)

**Comment by Palakkgoyal** [comment]
Yes, I think this would be good idea but it will need some modification with the sidebar profile button. Can I move ahead with that?

**Comment by narayan954** [comment]
> Yes, I think this would be good idea but it will need some modification with the sidebar profile button. Can I move ahead with that?

Sure, you can!
