### ISSUE TITLE
[FEATURE] Change the background image

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1018]
### Description

Currenlty, the background image is static. I want to give the user some in-built options to choose from or alternatively select from his own gallery.

### Screenshots

![Screenshot 2023-07-28 195301](https://github.com/narayan954/dummygram/assets/116902573/729c977a-8d7e-4705-82b1-db7283c8798c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal , this issue has been raised already as well and is assigned currently :) . Closing this as duplicate
