### ISSUE TITLE
Highlight on notification page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1019]
### Description

In the notification message only the name should be highlighted but here the `from` word is also highlighted.
I want to fix this.

### Steps to reproduce

Go to notificaiton page
If you have any notification you will see that from with name is also highlighted.

### Screenshots
![Screenshot 2023-07-28 200517](https://github.com/narayan954/dummygram/assets/116902573/3f9bf665-259c-4162-b8f1-06a5209323b9)
_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In the notification message only the name should be highlighted but here the `from` word is also highlighted. I want to fix this.
> 
> ### Steps to reproduce
> Go to notificaiton page If you have any notification you will see that from with name is also highlighted.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

now that's too small issue for you @Palakkgoyal XD please add more small issue maybe #1012  along with this?

**Comment by Palakkgoyal** [comment]
Yes I know but scores ke liye kya kuch nahi karna padta XD. Its small for me but if you think it will go ok for gssoc then let me do it. As 10 points are for very lil issues and every 10 point count at this stage. Or I will merge it with other. What do you think?

**Comment by narayan954** [comment]
> Yes I know but scores ke liye kya kuch nahi karna padta XD. Its small for me but if you think it will go ok for gssoc then let me do it. As 10 points are for very lil issues and every 10 point count at this stage. Or I will merge it with other. What do you think?

Alright it's okay XD, it's a valid issue, btw on that link, can you add `to` attricbute forwarding to notification.username. I'll handle the part to change  sent notifications to include username as an attribute

**Comment by Palakkgoyal** [comment]
Yes sure.

**Comment by Palakkgoyal** [comment]
I will add the profile image there as well

**Comment by Palakkgoyal** [comment]
But there will be a problem as if you set username as an attribute then further you would also need to add notification sender profile image.

**Comment by narayan954** [comment]
> But there will be a problem as if you set username as an attribute then further you would also need to add notification sender profile image.

I think sending data won't be feasible as profile pic can change.

**Comment by Palakkgoyal** [comment]
Yes, exactly.
