### ISSUE TITLE
[FEATURE] <Creating a dotenv file for storing API keys >

### ISSUE THREAD

**Issue by ansharora28** [narayan954/dummygram#102]
### Description

The script.js file is currently exposing the firebase API key.
I think it would be a good practice to secure our key( a free one too) by creating a dotenv file in .gitignore to secure the keys to prevent any possible security issue ( bots may scan for API keys and access/use resources)

**Comment by ansharora28** [comment]
I would like to work on it if you think the issue is valid

**Comment by narayan954** [comment]
Correct indeed! sure you can work on it in the coding period :)

**Comment by kshitij01042002** [comment]
@ansharora28 are you still working on this issue?

**Comment by ansharora28** [comment]
@kshitij01042002 Hi,yes I'm working on it.

**Comment by kshitij01042002** [comment]
@ansharora28  have you created .env file it? if yes please raise a PR soo that I can document it for issue #113

**Comment by ansharora28** [comment]
@kshitij01042002 I am facing some some problems after moving the keys to the dotenv file. I will take a look at it again and ask the mentor to unassign me if I'm not able to work it out. 
You can proceed with the issue then

**Comment by kshitij01042002** [comment]
Okay Works!

**Comment by ansharora28** [comment]
@narayan954 I was not able to figure out the problem with my code. Hence,I would like to explore other issues. You can assign it to @kshitij01042002

**Comment by kshitij01042002** [comment]
@narayan954 can you assign me this under codepeak?

**Comment by kshitij01042002** [comment]
@narayan954 while creating .env file and accessing it. The application is crashing which seems to be a common problem with no solid solution.Soo I suggest rather than creating a dotenv file we should document how to integrate app with firebase and modify firebase.js

**Comment by narayan954** [comment]
> @narayan954 while creating .env file and accessing it. The application is crashing which seems to be a common problem with no solid solution.Soo I suggest rather than creating a dotenv file we should document how to integrate app with firebase and modify firebase.js

Okay, we can add instruction to generate own API key as you're saying for now. This issue remains open till a solution is found I guess.

**Comment by 1010varun** [comment]
Hey, @narayan954 please assign this issue to me

**Comment by narayan954** [comment]
> Hey, @narayan954 please assign this issue to me
> 

under iwoc?

**Comment by 1010varun** [comment]
Yess

**Comment by narayan954** [comment]
Great! go ahead :)

**Comment by 1010varun** [comment]
![Screenshot from 2023-02-16 18-58-39](https://user-images.githubusercontent.com/104075461/219378220-5c8042fb-b358-4b85-898d-8f910ae71120.png)


@narayan954 I have added all the env variables and they are coming correctly as I console. logged them. But firebase is giving me an error saying "invalid API key"

**Comment by 1010varun** [comment]
![Screenshot from 2023-02-16 18-58-39](https://user-images.githubusercontent.com/104075461/219378220-5c8042fb-b358-4b85-898d-8f910ae71120.png)


@narayan954 I have added all the env variables and they are coming correctly as I console. logged them. But firebase is giving me an error saying "invalid API key"
