### ISSUE TITLE
Username must be small case

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1020]
### Description

As we know that fetching data from firebase is case sensitive so having username in capital letter could lead to problem further if we add username fetching also in the search bar. So, I think we should not let the user to use capital letter in their username.
I want to alter this on edit profile and also on the signup page.

### Steps to reproduce

Try to edit your profile
You will see the you can also add uppercase letters in username.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal let's add all the validations as required in any username we pick anywhere, like consisting of only small letter,maybe hyphen/underscore,number and no special character. What do you think? you may chose any of those options to improve the username validation :)

**Comment by Palakkgoyal** [comment]
The username can only consist of alphabets, number and underscore. Is there anything else you would like to add?

**Comment by narayan954** [comment]
> The username can only consist of alphabets, number and underscore. Is there anything else you would like to add?

nah, that's fine and let them be a maximum length of perhaps 20?

**Comment by Palakkgoyal** [comment]
Yes, that would be ok. And also can I change the minimum length of displayName as it is 6 and its long for my name and might be for other that. Due to this I have to write my Palakg or Palak goyal XD

**Comment by narayan954** [comment]
> Yes, that would be ok. And also can I change the minimum length of displayName as it is 6 and its long for my name and might be for other as well. Due to this I have to write my Palakg or Palak goyal XD

ohho correct! UX must be taken care of!
