### ISSUE TITLE
Profile feed is not based on time

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1021]
### Description

Currently the profile feed is getting fetched abruptly and is not in new to old format. I want to fix this.

### Steps to reproduce

Explore some feeds
You will see that they are not fetched based on timestamp.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently the profile feed is getting fetched abruptly and is not in new to old format. I want to fix this.
> 
> ### Steps to reproduce
> Explore some feeds You will see that they are not fetched based on timestamp.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can go ahead! :)
