### ISSUE TITLE
[FEATURE] Profile Post view

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1024]
### Description

- currently only post image is showing. I want to display no.of likes, save button, share button also.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> * currently only post image is showing. I want to display no.of likes, save button, share button also.
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

I think we can add that as on hover, just like youtube videos, what do you think? like when we hover the post we get three icons "heart icon with likes below", "save button" and "share button" or maybe "comment icon with number of comments"
