### ISSUE TITLE
Profile posts responsiveness

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1028]
### Description

posts are not responsive

### Steps to reproduce

inspect profile page for different screen sizes

### Screenshots

<img width="399" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/8ab4b4e4-48b6-4feb-b09e-5c28687ef6a4">

<img width="364" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/1013fee9-027a-40f1-9373-a156213cab8f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
yes, seems like caption is overflowing even more in case of this feed's post. Can you please fix that ? If you mean another issue as well, please add

**Comment by Keshav-0907** [comment]
Can I Work on this issue ??

**Comment by narayan954** [comment]
> Can I Work on this issue ??

It's registered by @anamika7153 , let's wait and see if she doesn't want to work on this! :)
