### ISSUE TITLE
UI of search dialog box

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1032]
### Description

I think the text is not clearly visible in light mode in the search dialog box and it also require some padding at the bottom and the search bar should be aligned at the top.

### Screenshots

![Screenshot 2023-07-29 131038](https://github.com/narayan954/dummygram/assets/116902573/aa8789c9-ad2e-44de-9d2b-e8399352f43d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I think the text is not clearly visible in light mode in the search dialog box and it also require some padding at the bottom and the search bar should be aligned at the top.
> 
> ### Screenshots
> ![Screenshot 2023-07-29 131038](https://user-images.githubusercontent.com/116902573/256970776-aa8789c9-ad2e-44de-9d2b-e8399352f43d.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

correct, and I was thinking, maybe we need to blur the background of this box instead of this box itself, what do you think?

**Comment by Palakkgoyal** [comment]
> > ### Description
> > I think the text is not clearly visible in light mode in the search dialog box and it also require some padding at the bottom and the search bar should be aligned at the top.
> > ### Screenshots
> > ![Screenshot 2023-07-29 131038](https://user-images.githubusercontent.com/116902573/256970776-aa8789c9-ad2e-44de-9d2b-e8399352f43d.png)
> > ### Additional information
> > _No response_
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [x]   I have checked the existing issues
> > * [x]   I'm a GSSoC'23 contributor
> > * [x]   I want to work on this issue
> 
> correct, you can go ahead... btw I was thinking, maybe we need to blur the background of this box instead of this box itself, what do you think?

Yes, I think the same. I will give glassmorphism effect to it or anything else you would like.

**Comment by narayan954** [comment]
> > > ### Description
> > > I think the text is not clearly visible in light mode in the search dialog box and it also require some padding at the bottom and the search bar should be aligned at the top.
> > > ### Screenshots
> > > ![Screenshot 2023-07-29 131038](https://user-images.githubusercontent.com/116902573/256970776-aa8789c9-ad2e-44de-9d2b-e8399352f43d.png)
> > > ### Additional information
> > > _No response_
> > > ### Record
> > > 
> > > * [x]    I agree to follow this project's Code of Conduct
> > > * [x]    I have checked the existing issues
> > > * [x]    I'm a GSSoC'23 contributor
> > > * [x]    I want to work on this issue
> > 
> > 
> > correct, you can go ahead... btw I was thinking, maybe we need to blur the background of this box instead of this box itself, what do you think?
> 
> Yes, I think the same. I will give glassmorphism effect to it or anything else you would like.

feel free to add it! It'd look really good to this!
