### ISSUE TITLE
[FEATURE] Add click away listener to the emoji tab.

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1034]
### Description

On the chat page the emoji box can only be closed in the user click again on the emoji icon. I want to click away listener to it to enhance UX.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
sure,you can go ahead!
