### ISSUE TITLE
Shimmer effect on home and profile page for posts

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1035]
### Description

I want to add a shimmer effect on the posts until they are loading. I think this would look cool and beautiful.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
sure you can go ahead!
