### ISSUE TITLE
<bug>: Reloading issue

### ISSUE THREAD

**Issue by dheeraj1129** [narayan954/dummygram#1043]
### Description

when we reload the website the URL matching issue appears 

### Steps to reproduce

there are some URL issue check again the website URL

### Screenshots

![Screenshot (102)](https://github.com/narayan954/dummygram/assets/72201773/2743de3e-6213-4f71-81f8-06263152607a)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can work on this!

**Comment by dheeraj1129** [comment]
Ok

**Comment by love-sonkar** [comment]
hey @dheeraj1129  are you working on this issue or not because i wanted to work on this issue

**Comment by narayan954** [comment]
> hey @dheeraj1129 are you working on this issue or not because i wanted to work on this issue

I think you may work on this as the OP isn't active anymore
