### ISSUE TITLE
alignment issue placeholder

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1044]
### Description

alignment issue in search placeholder 

### Steps to reproduce

go to website and go on contributor page.

### Screenshots

<img width="269" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/ffd68b46-75f0-4f20-8d37-25986087f857">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @biplavmz, please add some more minor issues to this or solve this with another minor issue as this is a one line fix

**Comment by biplavmz** [comment]
ok @narayan954

**Comment by biplavmz** [comment]
Hii @narayan954 
want to redesign search result 
before:-
<img width="468" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/c01444b4-0332-4ca3-9337-2c8165e77417">
 
After :- 
<img width="406" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/32e887e3-05e1-4e2d-a39d-1cfcccf360c7">

**Comment by narayan954** [comment]
> Hii @narayan954 want to redesign search result before:- <img alt="image" width="468" src="https://user-images.githubusercontent.com/68702055/257602860-c01444b4-0332-4ca3-9337-2c8165e77417.png">
> 
> After :- <img alt="image" width="406" src="https://user-images.githubusercontent.com/68702055/257602237-32e887e3-05e1-4e2d-a39d-1cfcccf360c7.png">

Hi @biplavmz instead of changing border radius, try to fix the card alignment, as they're not completely at center, there's some space off on one side

**Comment by biplavmz** [comment]
ok @narayan954
