### ISSUE TITLE
Change dummygram logo on share modal

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1054]
### Description

The share modal contain the old dummygram logo.

### Steps to reproduce

Click on share button on a post
You will see the old logo on the modal

### Screenshots

![Screenshot 2023-07-31 184552](https://github.com/narayan954/dummygram/assets/116902573/651567e5-89df-4527-9650-de666bf78439)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can fix that!
