### ISSUE TITLE
[OTHER] Profile page codebase refactor

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1058]
### What would you like to share?

Profile page code is burdened with redundancy and superfluous code which might make it difficult for the developers to read, understand and contribute efficiently.
As a seasoned open-source enthusiast and an ardent advocate of clean and efficient code, I firmly believe that "less is more" when it comes to software development. My aim is to meticulously analyze, streamline, and refactor this component, preserving its exceptional functionality while eliminating any extraneous code that hinders its performance and clarity. 
I envision a streamlined component that empowers users with its improved performance and readability. With careful attention to detail and adherence to best practices, I am confident that the result will not only be a cleaner look but also a testament to the commitment of this project to maintain excellence.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### What would you like to share?
> Profile page code is burdened with redundancy and superfluous code which might make it difficult for the developers to read, understand and contribute efficiently. As a seasoned open-source enthusiast and an ardent advocate of clean and efficient code, I firmly believe that "less is more" when it comes to software development. My aim is to meticulously analyze, streamline, and refactor this component, preserving its exceptional functionality while eliminating any extraneous code that hinders its performance and clarity. I envision a streamlined component that empowers users with its improved performance and readability. With careful attention to detail and adherence to best practices, I am confident that the result will not only be a cleaner look but also a testament to the commitment of this project to maintain excellence.
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Kudos to you for donning the 'Code Detective' hat! Our profile page might have a PhD in redundancy, but we'll teach it the art of simplicity. Get ready for the code makeover of a lifetime – welcome to the 'Less is More' Academy! 🎓💻
