### ISSUE TITLE
[Image preview] <Image Preview before uploading>

### ISSUE THREAD

**Issue by kshitij01042002** [narayan954/dummygram#106]
### Description

User cannot see the image before uploading it. Adding a image preview will help the user to confirm the selected image.

### Screenshots

![image](https://user-images.githubusercontent.com/91470808/205611103-2bb742a0-b553-4a8e-b963-2b2a84440ec6.png)

### Additional information

Would like to work on this for kwoc

**Comment by Kruthikesh** [comment]
I want solve this issue....please assign this to me!!
