### ISSUE TITLE
[FEATURE] Add delete post on post page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1060]
### Description

On the post page currently, the user can't delete the post. I want to add the delete post also there so that he/she doesn't need to navigate to the home page for deleting post.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> On the post page currently, the user can't delete the post. I want to add the delete post also there so that he/she doesn't need to navigate to the home page for deleting post.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

sure, you can go ahead!
