### ISSUE TITLE
Show user data on notification page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1061]
### Description

Currently the notif page only show a static image and also do not navigate the user anywhere. I want to update it such that it shows the image of request sender and also navigate to user id.
I also want to update the profile function of friend request such that it will contain only the id of sender and not other unnecessary data.

### Screenshots

![Screenshot 2023-08-01 000751](https://github.com/narayan954/dummygram/assets/116902573/29d73c4b-f717-43f5-98cd-53de5f9c0a55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently the notif page only show a static image and also do not navigate the user anywhere. I want to update it such that it shows the image of request sender and also navigate to user id. I also want to update the profile function of friend request such that it will contain only the id of sender and not other unnecessary data.
> 
> ### Screenshots
> ![Screenshot 2023-08-01 000751](https://user-images.githubusercontent.com/116902573/257315679-29d73c4b-f717-43f5-98cd-53de5f9c0a55.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Alright, you can go ahead and fix these :)
