### ISSUE TITLE
Use DB transaction for post cleanup

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1063]
### Description

As you said in the previous issue, as a next step I want to use db transaction for the cleanup of post.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> As you said in the previous issue, as a next step I want to use db transaction for the cleanup of post.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sure, go ahead!
