### ISSUE TITLE
BUG: Profile page - user posts losing its original resolution.

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#1068]
### Description

Users post img are losing its original resolution like they are streched top bottom 

### Steps to reproduce

1.Go to users profile page
2.See users post

### Screenshots

For e.g in home page the picture it's showing fine:
![Screenshot (18)](https://github.com/narayan954/dummygram/assets/64495368/6defb1a5-d405-419c-842d-fd46bc6d61de)

But in the profile page the posts looks a little bit off like theyre streched from top to bottom: 
![Screenshot (19)](https://github.com/narayan954/dummygram/assets/64495368/8b6f8d52-1290-41cb-8b76-9da9aa50b4c8)

And now with the fix maintaining the resolution:
![Screenshot (21)](https://github.com/narayan954/dummygram/assets/64495368/16cd7e80-9e86-4584-b555-844afafe37de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can go ahead!!
