### ISSUE TITLE
[FEATURE] Add a profile page

### ISSUE THREAD

**Issue by SudhansuuRanjan** [narayan954/dummygram#107]
### Description

Adding a profile page whare it Photo, name, joined date and all the posts by the user will be shown.

### Screenshots

NA

### Additional information

In near future we can add follow user functionality and can also show followers and following stats on profile.

**Comment by SudhansuuRanjan** [comment]
If its fine assign this issue to me.

**Comment by Anil123K** [comment]
@narayan954 Can you please assign this issue to me as I am a beginner and have taken part in CodePeak by coding club IITG and want to contribute in your project ?

**Comment by narayan954** [comment]
Sure @SudhansuuRanjan go ahead :) and please mention your program name for the scores and labels.

**Comment by narayan954** [comment]
> @narayan954 Can you please assign this issue to me as I am a beginner and have taken part in CodePeak by coding club IITG and want to contribute to your project?

@Anil123K, Sudhanshu already claimed the issue, please try for another one.
Hope you understand.
Thanks

**Comment by Anil123K** [comment]
Ok no problem

**Comment by SudhansuuRanjan** [comment]
I am from program CODEPEAK.

**Comment by narayan954** [comment]
@SudhansuuRanjan there already exists this issue #49, so this is a duplicate issue and unfortunately, I have to close it :(
