### ISSUE TITLE
[FEATURE] want to add on Scroll loading like Instagram

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1076]
### Description

write now we are showing all post at once but I would like to add infinite scroll first it will show 10-20 post after that Loding... animation on scroll it will come after some seconds like Instagram feeds 

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> write now we are showing all post at once but I would like to add infinite scroll first it will show 10-20 post after that Loding... animation on scroll it will come after some seconds like Instagram feeds
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @biplavmz we already have infinite scrolling and we're loading only 10 posts at once :)

**Comment by narayan954** [comment]
closing this as not required
