### ISSUE TITLE
[FEATURE] Show all users and search results are delaying 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1077]
### Description

we have to show all users like contributor section and also we have to improve the search timing 

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Screenshots

<img width="526" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/9702dad8-2366-41a6-8ad7-3131332a2cc2">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> we have to show all users like contributor section and also we have to improve the search timing
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Screenshots
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/68702055/257605321-9702dad8-2366-41a6-8ad7-3131332a2cc2.png">
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

This issue of showing all users has been claimed as well unfortunately @biplavmz 
and The search delay is for a reason to avoid extra calls to db

**Comment by narayan954** [comment]
closing as not planned right now
