### ISSUE TITLE
Post are Breaking in Profile Section

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1078]
### Description

Post are Breaking in Profile Section

### Steps to reproduce

go to post profile section.
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Screenshots

<img width="733" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/01dcceb8-a7a4-4a6f-8a6d-e54a3273c6cb">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
This is a duplicate issue @biplavmz closing as duplicate
