### ISSUE TITLE
Cleanup of profile image

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1079]
### Description

When user changes their profile image its ref is deleted from the user collection but the image is still available in the cloud storage. And the same goes for background image I believe. I want to cleanup both of them.

### Steps to reproduce

Check the function for changing image. It just update the photoURL and nothing else.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> 

sure you can go ahead!
