### ISSUE TITLE
search and card

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#1081]
### Description

Contributor search bar not search search letter start all contributors and also need to reduce card margin.

### Steps to reproduce

1. I would like to write logic to search all cards
 2. Reduce the card margin.

### Screenshots

![Screenshot 2023-08-02 135202](https://github.com/narayan954/dummygram/assets/104631882/588c7fd2-af47-44e1-bf40-d6012513e034)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Contributor search bar not search search letter start all contributors and also need to reduce card margin.
> 
> ### Steps to reproduce
> 1. I would like to write logic to search all cards
> 2. Reduce the card margin.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 135202](https://user-images.githubusercontent.com/104631882/257749618-588c7fd2-af47-44e1-bf40-d6012513e034.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sure, go ahead!
