### ISSUE TITLE
Shimmer on dark mode

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1082]
### Description

The shimmer effect is perfectly visible on light mode. But, on dark mode it is not visible. I want to fix that.
![Screenshot 2023-08-02 135922](https://github.com/narayan954/dummygram/assets/116902573/863956df-256f-4439-ad1e-d2b8e812a9bc)

### Steps to reproduce

- Change theme to dark mode
- Reload the page
- Shimmer is not visible.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The shimmer effect is perfectly visible on light mode. But, on dark mode it is not visible. I want to fix that. ![Screenshot 2023-08-02 135922](https://user-images.githubusercontent.com/116902573/257751354-863956df-256f-4439-ad1e-d2b8e812a9bc.png)
> 
> ### Steps to reproduce
> * Change theme to dark mode
> * Reload the page
> * Shimmer is not visible.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

sure, go ahead!
