### ISSUE TITLE
Post alignment

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1084]
### Description

The post in row mode are not aligned properly. I want to fix their alignment.

### Steps to reproduce

- Go to home page.
- Change to column mode.
- You will see some post that are not aligned properly.

### Screenshots

![Uploading Screenshot 2023-08-02 141249.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
sure, you can go ahead!
