### ISSUE TITLE
Nothing on 0 likes

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1086]
### Description

If the post is not liked by anyone then, the like box appears like it is still loading or there is some error.
I want to show No Likes if there are 0 likes.

### Steps to reproduce

Click on likes of a post which has 0 likes.

### Screenshots

![Screenshot 2023-08-02 142156](https://github.com/narayan954/dummygram/assets/116902573/86b3e9d2-3958-45bf-a49d-ac5e2df08d9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> 

sure, go ahead
