### ISSUE TITLE
[FEATURE] Centralize user data

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1087]
### Description

Every page of the website require current user data and every page fetch that seperately.
I want to make the fetch request from a single page and share it in the whole website. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Every page of the website require current user data and every page fetch that seperately. I want to make the fetch request from a single page and share it in the whole website.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

I think this'd be a good idea!
