### ISSUE TITLE
Delete story

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1089]
### Description

Currently, anyone can delete story of other users.

### Steps to reproduce

Visit any user's profile, see their story, Delete icon is visible and on clicking it, story gets deleted

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Palakkgoyal** [comment]
Hey @anamika7153 I have already opened a issue for it.
