### ISSUE TITLE
Hover effect on menu

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1091]
### Description

Currently the hover effect of scale icon in the menu is only on profile and not on the other two. I want to add it on all.

### Steps to reproduce

- Click on your name in the sidebar
- A menu will open
- Hover over the three
- You will see that only image is getting scaled

### Screenshots

![Screenshot 2023-08-02 183144](https://github.com/narayan954/dummygram/assets/116902573/6c20f809-909a-47cf-b348-8d8fb6e65270)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently the hover effect of scale icon in the menu is only on profile and not on the other two. I want to add it on all.
> 
> ### Steps to reproduce
> * Click on your name in the sidebar
> * A menu will open
> * Hover over the three
> * You will see that only image is getting scaled
> 
> ### Screenshots
> ![Screenshot 2023-08-02 183144](https://user-images.githubusercontent.com/116902573/257822161-6c20f809-909a-47cf-b348-8d8fb6e65270.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

alright, you can go ahead!
