### ISSUE TITLE
Data overflow from profile dialog box

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1092]
### Description

In some profile cards the data is overflowing from the card.

### Steps to reproduce

- Try to hover over some profile
- You will see that they are overflowing.

### Screenshots

![Screenshot 2023-08-02 183839](https://github.com/narayan954/dummygram/assets/116902573/fda48b2b-609b-4f42-a555-dc61a26124ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In some profile cards the data is overflowing from the card.
> 
> ### Steps to reproduce
> * Try to hover over some profile
> * You will see that they are overflowing.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 183839](https://user-images.githubusercontent.com/116902573/257822910-fda48b2b-609b-4f42-a555-dc61a26124ac.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

This issue is being addressed by pr #929 closing as duplicate
