### ISSUE TITLE
[FEATURE] Alignment of post text

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1093]
### Description

Currently the post's text that doesn't include pictures is aligned at the top of the card. I think it is more suitable at center.

### Screenshots

![Screenshot 2023-08-02 184058](https://github.com/narayan954/dummygram/assets/116902573/26896a5b-74a2-4c01-b06d-7c79dd69296d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently the post's text that doesn't include pictures is aligned at the top of the card. I think it is more suitable at center.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 184058](https://user-images.githubusercontent.com/116902573/257823735-26896a5b-74a2-4c01-b06d-7c79dd69296d.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

sure, you can go ahead!
