### ISSUE TITLE
[FEATURE] Too long bio on profile dialog box

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1094]
### Description

I think if the bio of a person is long then, we should not show it completely on the profile dialog box. Instead we should add here spread syntax after a certain char limit.

### Screenshots

![Screenshot 2023-08-02 184330](https://github.com/narayan954/dummygram/assets/116902573/e712753b-f583-4824-baa6-3d6347a98da7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I think if the bio of a person is long then, we should not show it completely on the profile dialog box. Instead we should add here spread syntax after a certain char limit.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 184330](https://user-images.githubusercontent.com/116902573/257824582-e712753b-f583-4824-baa6-3d6347a98da7.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

That'd be great! you can go ahead!
