### ISSUE TITLE
[FEATURE] Search bar animation

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1096]
### Description

I think instead of opening a seperate dialog box for search bar we should make it work on the navbar itself.
I want to make it such that the icon will be still there. When someone click on the icon the search bar will open with a animation in the navbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I think instead of opening a seperate dialog box for search bar we should make it work on the navbar itself. I want to make it such that the icon will be still there. When someone click on the icon the search bar will open with a animation in the navbar.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

If that improves UI/UX I'm definitely up for it! XD you can go ahead!
