### ISSUE TITLE
Error on chat alignment

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1097]
### Description

There is some error in the chat alignment as the user's chat must be on the right side but it is also appearing on the left.

### Steps to reproduce

- Go to chat
- Do a message

### Screenshots

![Screenshot 2023-08-02 190723](https://github.com/narayan954/dummygram/assets/116902573/7c4aba61-40dc-44f2-ae05-47f20260033b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> There is some error in the chat alignment as the user's chat must be on the right side but it is also appearing on the left.
> 
> ### Steps to reproduce
> * Go to chat
> * Do a message
> 
> ### Screenshots
> ![Screenshot 2023-08-02 190723](https://user-images.githubusercontent.com/116902573/257831382-7c4aba61-40dc-44f2-ae05-47f20260033b.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

That's an really unexpected, feel free to look into the issue!

**Comment by Palakkgoyal** [comment]
This is a silly mistake by me. Actually I was testing for a PR from another profile and I was habitual of this one. So, I thought that chat is misaligned. Look at sidebar, the id is tester.

**Comment by narayan954** [comment]
> This is a silly mistake by me. Actually I was testing for a PR from another profile and I was habitual of this one. So, I thought that chat is misaligned. Look at sidebar, the id is tester.

It's alright! I also didn't verify, it's my mistake as well...
