### ISSUE TITLE
Add a section "How to get started with open source?" in the readme

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#11]
You can take inspiration from the picture below.
![open source](https://user-images.githubusercontent.com/57909583/192442620-cbae0822-03e0-4351-8854-f9373997fb90.png)

**Comment by Dun-sin** [comment]
Do you need the same info on the website in the README? If that's it, can I work it out

**Comment by narayan954** [comment]
I need this as a separate section on the readme . Like we can replace  old data like cloning and forking instructions from readme with a dedicated section on how to contribute to the open source. This would improve the readme

**Comment by Dun-sin** [comment]
Why not both?

**Comment by sambhavgupta0705** [comment]
Hey can I work on this issue?

**Comment by narayan954** [comment]
> Why not both?

yes that'd do , r u going to work on that?

**Comment by narayan954** [comment]
> Hey can I work on this issue?

depends if @Dun-sin doesn't, till then you can look for other issues or raise some :)

**Comment by Dun-sin** [comment]
> > Why not both?
> 
> yes that'd do , r u going to work on that?

I will💪🏽

**Comment by narayan954** [comment]
That's the spirit !

**Comment by sambhavgupta0705** [comment]
Hey ,Please assign it to me also
I want to work on this one

**Comment by KarthikS373** [comment]
Is this issue still open. If yes can you please assign it to me?

**Comment by Dun-sin** [comment]
> Is this issue still open. If yes can you please assign it to me?

It is, I'm working on it
