### ISSUE TITLE
Animation effect on background image

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1100]
### What would you like to share?

Currently, their is no effect on the background image. I want to give a zoom effect on scroll which will look really amazing on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> Currently, their is no effect on the background image. I want to give a zoom effect on scroll which will look really amazing on it.
> 
> ### Additional information

sure go ahead!
