### ISSUE TITLE
[FEATURE] Remove saved posts from sidebar and move to profile

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1101]
### Description

Currently, the saved posts icon is on the sidebar. I want to move it to profile like instagram. So, their will be two options for the current user one is saved and second is feed and only one for other user that is feed if they visit other user profile.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently, the saved posts icon is on the sidebar. I want to move it to profile like instagram. So, their will be two options for the current user one is saved and second is feed and only one for other user that is feed if they visit other user profile.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

that'd look awesome, you can go ahead!
