### ISSUE TITLE
Visibility of theme button

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1102]
### Description

The moon icon is not visible on hover.

### Steps to reproduce

- Toggle the theme
- Where there is moon icon, hover over it
- You will see that it has very low visibility.

### Screenshots

![Screenshot 2023-08-02 224111](https://github.com/narayan954/dummygram/assets/116902573/e1ae557f-0516-4c5a-bf02-b5563e7f6427)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The moon icon is not visible on hover.
> 
> ### Steps to reproduce
> * Toggle the theme
> * Where there is moon icon, hover over it
> * You will see that it has very low visibility.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 224111](https://user-images.githubusercontent.com/116902573/257890032-e1ae557f-0516-4c5a-bf02-b5563e7f6427.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

can you change this to be toggle like in settings, but for dark mode instead?

**Comment by Palakkgoyal** [comment]
Yes, for sure.
