### ISSUE TITLE
[DOCS] Add GSSOC in the program list

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1104]
### Description

In the documentation program list there are so many programs but not GSSOC. I want to add GSSOC there.

### Screenshots

![Screenshot 2023-08-02 225321](https://github.com/narayan954/dummygram/assets/116902573/9040be20-fdb7-4677-b909-de09f0cc984a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In the documentation program list there are so many programs but not GSSOC. I want to add GSSOC there.
> 
> ### Screenshots
> ![Screenshot 2023-08-02 225321](https://user-images.githubusercontent.com/116902573/257892804-9040be20-fdb7-4677-b909-de09f0cc984a.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hehe I missed it, and no one noticed until now XD, you can go ahead!
