### ISSUE TITLE
[FEATURE] <Enhanced like button>

### ISSUE THREAD

**Issue by Aarize29** [narayan954/dummygram#111]
### Description

Workable Like button (Hover, like count on clicking, etc, etc)

**Comment by Aarize29** [comment]
> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Hello ,I would like to work on this issue

**Comment by narayan954** [comment]
Go ahead! @Aarize29  and please mention your program name for labels and point distribution!

**Comment by Aarize29** [comment]
> Go ahead! @Aarize29 and please mention your program name for labels and point distribution!

Kwoc

**Comment by itsajay1029** [comment]
Are you working on this or if possible assign me the issue @narayan954 @Aarize29 ?

**Comment by narayan954** [comment]
> Are you working on this or if possible assign me the issue @narayan954 @Aarize29 ?

You can go ahead :)

**Comment by narayan954** [comment]
@praduman8435 you're already assigned on two tasks, please complete them first, thank you :)

**Comment by praduman8435** [comment]
> @praduman8435 you're already assigned on two tasks, please complete them first, thank you :)

Ok 👍

**Comment by aashi01kh** [comment]
I want to work on this under JWOC

**Comment by 1010varun** [comment]
@narayan954 assign can you please assign this issue to me under iwoc

**Comment by narayan954** [comment]
> I want to work on this under JWOC

Aashi, you're already assigned an issue, please finish that first, thanks!

**Comment by narayan954** [comment]
> @narayan954 assign can you please assign this issue to me under iwoc

sure you can go ahead!

**Comment by 1010varun** [comment]
@narayan954 you haven't assigned this issue to me can you please assign this to me?
