### ISSUE TITLE
🐛 Enter Button is not working 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1113]
### Description

Enter Button is not working when we click on enter button.
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website and click the post

### Screenshots

<img width="367" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/08cf6db8-337d-4835-ab0c-62683c41670c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Enter Button is not working when we click on enter button. I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website and click the post
> 
> ### Screenshots
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/68702055/258212369-08cf6db8-337d-4835-ab0c-62683c41670c.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can work on this!
