### ISSUE TITLE
🐛 Emoji is breaking 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1114]
### Description

Emoji css is breaking 
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website click on post

### Screenshots

<img width="368" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/442a09e1-4031-44d1-b4ba-5d531cef5e31">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Emoji css is breaking I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website click on post
> 
> ### Screenshots
> <img alt="image" width="368" src="https://user-images.githubusercontent.com/68702055/258212830-442a09e1-4031-44d1-b4ba-5d531cef5e31.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

sure, you can work on this! :)
