### ISSUE TITLE
Fix alignment of Program images 

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#1117]
### Description

program images are not aligned in mobile devices

### Steps to reproduce

check for yourself

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77617189/fb2ed1f0-d24a-4485-91e6-9136bab85964)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Palakkgoyal** [comment]
Can I work on this?

**Comment by narayan954** [comment]
> Steps to reproduce

sure you can!
