### ISSUE TITLE
[FEATURE] Upgrading UI in login page

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [narayan954/dummygram#1132]
### Description

Hello @narayan954 ,
The login section is not looking attractive at all, and the login page is the main page because after login the tasks happens so please assign me this issue so I can make the login page more attractive with the hover and the roper alignments.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/121503426/f8684d32-f713-4b3e-9b41-498b384b170f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Hello @narayan954 , The login section is not looking attractive at all, and the login page is the main page because after login the tasks happens so please assign me this issue so I can make the login page more attractive with the hover and the roper alignments.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/121503426/258451895-f8684d32-f713-4b3e-9b41-498b384b170f.png)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can go ahead! :)

**Comment by narayan954** [comment]
Hi @SyedImtiyaz-1  issue #1003 already raised this issue, why did you not check that? closing this issue
