### ISSUE TITLE
[FEATURE] I want to improve ui of login signup for better look

### ISSUE THREAD

**Issue by Swapnil-2503** [narayan954/dummygram#1136]
### Description

- UI is the key to get more traffic on website 

Assign this issue to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> * UI is the key to get more traffic on website
> 
> Assign this issue to me
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @Swapnil-2503 this is a duplicate issue, closing it.
