### ISSUE TITLE
[Bug]: Proper Gap is not Occurred in Logout Card like Logout and Cancel Buttons [Observe Screenshot]

### ISSUE THREAD

**Issue by NarendraKoya999** [narayan954/dummygram#1137]
### Description

- In User Profile Page , Whenever User wants to Logout off Main Page, Logout and Cancel Options there.
- But, in that, No gap is their in between Logout and Cancel Buttons.

### Steps to reproduce

- Go To 'Main Dashboard Page after Login Successfully'
- Click on User Profile Dropdown Option.
- Then, Click on Logout Option.
- See Error on Popup of Logout Card.

### Screenshots

![dummygram-4](https://github.com/narayan954/dummygram/assets/84512164/34b33955-3a4a-42f7-bdcc-34f9bd19f980)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by NarendraKoya999** [comment]
Hi @narayan954 . Please Review on this Issue as soon as Possible. Thank You !

**Comment by narayan954** [comment]
Sure, go ahead! :)

**Comment by NarendraKoya999** [comment]
Hi @narayan954 . Where Can I found this Logout Card. Still I did not Get That Information related File in Project Directory😊
