### ISSUE TITLE
[FEATURE] : Noticed No styles.yml File is not in GitHub ISSUE_TEMPLATES for Raising Enhancement Requests

### ISSUE THREAD

**Issue by NarendraKoya999** [narayan954/dummygram#1140]
### Purpose of Raising This Issue
**styles.yml (Custom ISSUE_TEMPLATE):**
- The styles.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.
- The contents of styles.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by NarendraKoya999** [comment]
Hi @narayan954 . Please Review on this Issue. Thank You !

**Comment by narayan954** [comment]
You can go ahead! thank you!
