### ISSUE TITLE
Update UI of sidebar

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1141]
### Description

I want to give a new look to sidebar. I want to make it somewhat similar to instagram sidebar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
what about the poor footer tho? You can go ahead!

**Comment by Palakkgoyal** [comment]
Let's see which place the poor footer get from the hands of this cruel developer.
