### ISSUE TITLE
Memory leak due to event listener

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1142]
### Description

There is a event listener in the App.jsx file that is running and not getting cleared. It could cause memory leaking.

### Steps to reproduce

- Use the website for some time
- In the DevTools => elements => event listeners => scroll
- You will see there are so many scroll event listeners are triggered.

### Screenshots
![Screenshot 2023-08-04 223722](https://github.com/narayan954/dummygram/assets/116902573/6dbe3bb2-c4ee-4b67-a9f9-92bdab21e3df)

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Thanks for fixing/finding!

**Comment by Palakkgoyal** [comment]
No worries.
