### ISSUE TITLE
[DOCS] Update dummygram logo

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1143]
### Description

In the docs the old dummygram logo is used. I want to update it to new one.

### Screenshots

![Screenshot 2023-08-05 140927](https://github.com/narayan954/dummygram/assets/116902573/137801a6-4d96-4ff5-b012-373129a79b41)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!
