### ISSUE TITLE
[FEATURE] Add validation on Edit profile section

### ISSUE THREAD

**Issue by Geeta259** [narayan954/dummygram#1147]
Validation add for empty fields . right now no validation add even blank name also going to update when click on submit.
Error message shown below of each fields.

![Screenshot (51)](https://github.com/narayan954/dummygram/assets/75520947/7c1d7e76-9303-4e77-8948-2065d8921883)

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

@narayan954 I would like to work on this issue under GSSOC'23 . Please assign this to me.

**Comment by nimesh-choudhary** [comment]
Hey @Geeta259 
I want to work on this issue so could you please assign this to me 😊?

**Comment by narayan954** [comment]
> Validation add for empty fields . right now no validation add even blank name also going to update when click on submit. Error message shown below of each fields.
> 
> ![Screenshot (51)](https://user-images.githubusercontent.com/75520947/258582707-7c1d7e76-9303-4e77-8948-2065d8921883.png)
> 
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue
> 
> @narayan954 I would like to work on this issue under GSSOC'23 . Please assign this to me.

you can go ahead!
