### ISSUE TITLE
[FEATURE] <Displaying post with all the comments and also able to comment while seeing other comments>

### ISSUE THREAD

**Issue by kshitij01042002** [narayan954/dummygram#115]
### Description

Displaying post with all the comments and also able to comment while seeing other comments

### Screenshots

![image](https://user-images.githubusercontent.com/91470808/206399494-cb3c1422-4617-422f-bd16-8fb1a88f09cd.png)
Something like this

### Additional information

Make this issue under codepeak

**Comment by narayan954** [comment]
Did you mean when a user single clicks on the post it maximizes along with comments?

**Comment by kshitij01042002** [comment]
Yes similar to Instagram's web view. You can refer that
