### ISSUE TITLE
[FEATURE] User profile pic

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1151]
### Description

I would like to render default profile image in case of no user profile pic.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I would like to render default profile image in case of no user profile pic.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

I am assuming you've checked existing issues. Go ahead!
