### ISSUE TITLE
[DOCS] Fix formatting in README

### ISSUE THREAD

**Issue by Sriparno08** [narayan954/dummygram#1153]
### Description

The below formatting:

![image](https://github.com/narayan954/dummygram/assets/89148144/70dd5474-37d0-4e5e-88f6-5ca3807e37c7)

can be changed to:

![image](https://github.com/narayan954/dummygram/assets/89148144/ad496a44-2cc5-4e09-a54d-3db9f0c13fc3)

It decreases nesting of li items and makes the section look more logical.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The below formatting:
> 
> ![image](https://user-images.githubusercontent.com/89148144/258589651-70dd5474-37d0-4e5e-88f6-5ca3807e37c7.png)
> 
> can be changed to:
> 
> ![image](https://user-images.githubusercontent.com/89148144/258589706-ad496a44-2cc5-4e09-a54d-3db9f0c13fc3.png)
> 
> It decreases nesting of li items and makes the section look more logical.
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @Sriparno08 this seems like a level 0 issue, can you add more small issue to this to upgrade this to level1 ?

**Comment by Sriparno08** [comment]
Sure, @narayan954.

We can bold the titles of this section to make them distinct and separate them from their descriptions.

![image](https://github.com/narayan954/dummygram/assets/89148144/5f1ec3ec-1063-4a2a-9470-ee924ec6049b)

**Comment by narayan954** [comment]
> Sure, @narayan954.
> 
> We can bold the titles of this section to make them distinct and separate them from their descriptions.
> 
> ![image](https://user-images.githubusercontent.com/89148144/258713541-5f1ec3ec-1063-4a2a-9470-ee924ec6049b.png)

alright, you can go ahead!
