### ISSUE TITLE
PRofile section not responsive

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1154]
### Description

Profile section is not responsive. I want to make it responsive for all screen sizes.

### Steps to reproduce

Go to your profile and inspect it.  

### Screenshots

<img width="416" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/3f0b17ad-6ea0-404a-9a98-958870526cab">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Profile section is not responsive. I want to make it responsive for all screen sizes.
> 
> ### Steps to reproduce
> Go to your profile and inspect it.
> 
> ### Screenshots
> <img alt="image" width="416" src="https://user-images.githubusercontent.com/66116440/258589826-3f0b17ad-6ea0-404a-9a98-958870526cab.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sure, you can go ahead!
