### ISSUE TITLE
[FEATURE] feed

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1157]
### Description

I want to change the UI of the profile page feed for better user interaction.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I want to change the UI of the profile page feed for better user interaction.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

how do you intend on changing it? Can you please elaborate?
