### ISSUE TITLE
[FEATURE] Changing reaction feat to telegram like rxn

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#1161]
### Description

Currently, only one reaction is displayed on the message, I want to display more reactions just like telegram

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently, only one reaction is displayed on the message, I want to display more reactions just like telegram
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

You can go ahead! :)
