### ISSUE TITLE
[FEATURE] Add feature for remove profile image

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1165]
### Description

In the profile there is option to change profile image but not the option to remove it. I want to add profile image deletion feature to it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In the profile there is option to change profile image but not the option to remove it. I want to add profile image deletion feature to it.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

so if we remove it, would we show an empty indicating image or the one we assign by default?

**Comment by Palakkgoyal** [comment]
I think we should keep it empty as assigning it a default image would take extra memory. We can easily handle it here.

**Comment by narayan954** [comment]
> I think we should keep it empty as assigning it a default image would take extra memory. We can easily handle it here.

alright
