### ISSUE TITLE
[FEATURE] Save post option on post page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1166]
### Description

There is no option to save post on post page which is really a problem. As if the user has a saved posts then, the only way to remove that post from saved is to find it in the home feed and nothing else. I want to add save and remove post feature there.

### Screenshots

![Screenshot 2023-08-05 235903](https://github.com/narayan954/dummygram/assets/116902573/82e0b36c-deb6-4953-ae67-d56b0d822423)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> There is no option to save post on post page which is really a problem. As if the user has a saved posts then, the only way to remove that post from saved is to find it in the home feed and nothing else. I want to add save and remove post feature there.
> 
> ### Screenshots
> ![Screenshot 2023-08-05 235903](https://user-images.githubusercontent.com/116902573/258602206-82e0b36c-deb6-4953-ae67-d56b0d822423.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

this save/remove feature exists, please make sure to reuse it / make it reusable :)

**Comment by narayan954** [comment]
you can go ahead!
