### ISSUE TITLE
[FEATURE]: Convert png, jpg Image Files Format into WebP Format 🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [narayan954/dummygram#1168]
### Purpose of Raising this Issue
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**

### I have Taken Sample Image in Your Project Assets Directory for the  Proof of My Issue Description
<img width="1280" alt="2" src="https://github.com/narayan954/dummygram/assets/84512164/41857abe-460b-448a-93c0-cef773d418b0">

### After Conversion:

![Screenshot 2023-08-06 114012](https://github.com/narayan954/dummygram/assets/84512164/484292e9-1aee-4c8e-8abd-7b34d1e2c2ed)

### Additional information

- **I have taken 1 png File from Your Assets Section in Project Directory.**
- **Before Converting to WebP File Format, Actual File Size is 160KB.** 
- **After Conerting into webp File Format, this Same File Size is 73KB without Quality lossy.**
- **I want to change these All Changes in Codebase and Assets Sections**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> ### Purpose of Raising this Issue
> * **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**
> 
> ### Screenshots
> ### I have Taken Sample Image in Your Project Assets Directory for the Proof of My Issue Description
> <img alt="2" width="1280" src="https://user-images.githubusercontent.com/84512164/258624564-41857abe-460b-448a-93c0-cef773d418b0.png">
> ### After Conversion:
> ![Screenshot 2023-08-06 114012](https://user-images.githubusercontent.com/84512164/258624676-484292e9-1aee-4c8e-8abd-7b34d1e2c2ed.jpg)
> 
> ### Additional information
> * **I have taken 1 png File from Your Assets Section in Project Directory.**
> * **Before Converting to WebP File Format, Actual File Size is 160KB.**
> * **After Conerting into webp File Format, this Same File Size is 73KB without Quality lossy.**
> * **I want to change these All Changes in Codebase and Assets Sections**
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @NarendraKoya999  you can go ahead!
