### ISSUE TITLE
🐛Emoji breaking in mobile 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1170]
### Description

Emoji is breaking in Mobile 

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.

### Steps to reproduce

go to website click on any post comment 

### Screenshots

<img width="208" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/9e14cbaf-26a4-4193-b3c0-95c912de3aea">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Emoji is breaking in Mobile
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website click on any post comment
> 
> ### Screenshots
> <img alt="image" width="208" src="https://user-images.githubusercontent.com/68702055/258646377-9e14cbaf-26a4-4193-b3c0-95c912de3aea.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can go ahead
