### ISSUE TITLE
[FEATURE] -Sign Up Button Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [narayan954/dummygram#1171]
### Description

The design of the button is nice but it can be improved by working on the styling of the button in order to create good impact on whole page of the website.

### Screenshots

Current Design

![ip](https://github.com/narayan954/dummygram/assets/115794049/f08c8182-6ed2-414e-8ca0-48eaeb98700b)

Expected Updated Design

![ip (3)](https://github.com/narayan954/dummygram/assets/115794049/ccef277d-1d41-4525-b10c-8f12b51b6dda)

### Additional information

No

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The design of the button is nice but it can be improved by working on the styling of the button in order to create good impact on whole page of the website.
> 
> ### Screenshots
> Current Design
> 
> ![ip](https://user-images.githubusercontent.com/115794049/258649923-f08c8182-6ed2-414e-8ca0-48eaeb98700b.png)
> 
> Expected Updated Design
> 
> ![ip (3)](https://user-images.githubusercontent.com/115794049/258649930-ccef277d-1d41-4525-b10c-8f12b51b6dda.png)
> 
> ### Additional information
> No
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

yeah, sure you can work on that, also there's an issue when suggestions come around on the right side, button overlaps with the suggestion, see if you can fix that as well :)
