### ISSUE TITLE
[FEATURE] Make routes relative

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#1179]
### Description

Currently, the routes are absolute paths. I want to make them relative such that they will have a simple route setup and also common layout would be shared easily. Currently, we have to add seperate CSS on every page to make it compatible with sidebar and navbar.
I want to remove all those CSS and centralize it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently, the routes are absolute paths. I want to make them relative such that they will have a simple route setup and also common layout would be shared easily. Currently, we have to add seperate CSS on every page to make it compatible with sidebar and navbar. I want to remove all those CSS and centralize it.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

that'd be really awesome!!

**Comment by narayan954** [comment]
This requires / corresponds to refactoring as well so I think this should be level 3
