### ISSUE TITLE
Post background changes color on switching to dark mode

### ISSUE THREAD

**Issue by ansharora28** [narayan954/dummygram#118]
### Description

![image](https://user-images.githubusercontent.com/89684245/206708638-9a1af16a-444b-4280-a1ba-470fe7e49016.png)
![image](https://user-images.githubusercontent.com/89684245/206708658-ca5e695c-7c92-476b-8078-b7c0da961cd7.png)

On switching to dark mode background color of some posts changes .

### Steps to reproduce

Switch to dark mode

**Comment by narayan954** [comment]
That's a problem with current implementation of dark mode, it just inverts the colors. Can you re-implement and fix the dark mode?

**Comment by ansharora28** [comment]
Yes,i would like to work on this under KWOC

**Comment by narayan954** [comment]
Sure go ahead :)

**Comment by praduman8435** [comment]
hello @narayan954 please assign this to me

**Comment by narayan954** [comment]
> hello @narayan954 please assign this to me

sure, best of luck

**Comment by TheXro** [comment]
@narayan954 please assign this to me

**Comment by narayan954** [comment]
> @narayan954 please assign this to me 

iwoc right, can you confirm?
 thanks

**Comment by TheXro** [comment]
@narayan954 yes iwoc

**Comment by narayan954** [comment]
Great, Keep going!
