### ISSUE TITLE
Dark Mode button not functioning properly

### ISSUE THREAD

**Issue by ansharora28** [narayan954/dummygram#119]
### Description

When switching back to light mode,sometimes the button takes you to top instead of changing the color mode.

Uploading DummyGram - Google Chrome 2022-12-09 18-37-27.mp4…

### Steps to reproduce

Switch to dark mode
Scroll down
Switch back to light mode

**Comment by narayan954** [comment]
problem lies with the position of the scroll to top button, it overlaps with some(bottom) part of the dark mode button. It's an easy fix, would you like to work on it?

**Comment by ansharora28** [comment]
Sure,i want to take this up under KWOC

**Comment by narayan954** [comment]
Great go ahead!

**Comment by ansharora28** [comment]
@narayan954 is it okay if i just change the width of the button to 10% and take it to the left side? It wont overlap with darkmode in that case.

![image](https://user-images.githubusercontent.com/89684245/206803321-49366ae8-54d3-44a3-a69b-61ddee6986b3.png)

![image](https://user-images.githubusercontent.com/89684245/206803359-d711e4a0-4ce1-435b-819c-7f482f0ed7b7.png)

Not sure if this is the right way to do it,hence asking before hand

**Comment by narayan954** [comment]
> @narayan954 is it okay if i just change the width of the button to 10% and take it to the left side? It wont overlap with darkmode in that case.
> 
> ![image](https://user-images.githubusercontent.com/89684245/206803321-49366ae8-54d3-44a3-a69b-61ddee6986b3.png)
> 
> ![image](https://user-images.githubusercontent.com/89684245/206803359-d711e4a0-4ce1-435b-819c-7f482f0ed7b7.png)
> 
> Not sure if this is the right way to do it,hence asking before hand

Or you can move the dark mode button upwards, works? scroll to top button seems to be good in position. :)

**Comment by narayan954** [comment]
> > @narayan954 is it okay if i just change the width of the button to 10% and take it to the left side? It wont overlap with darkmode in that case.
> > ![image](https://user-images.githubusercontent.com/89684245/206803321-49366ae8-54d3-44a3-a69b-61ddee6986b3.png)
> > ![image](https://user-images.githubusercontent.com/89684245/206803359-d711e4a0-4ce1-435b-819c-7f482f0ed7b7.png)
> > Not sure if this is the right way to do it,hence asking before hand
> 
> Or you can move the dark mode button upwards (btw does increasing z index of dark mode button helps? Asking as I haven't tried), works? scroll to top button seems to be good in position. :)

**Comment by ansharora28** [comment]
Sure,ill move it a bit upwards. 
I tried playing around with z index but it didn't seem to work for me

**Comment by narayan954** [comment]
> Sure,ill move it a bit upwards. I tried playing around with z index but it didn't seem to work for me

Okay fine

**Comment by narayan954** [comment]
> Sure,ill move it a bit upwards. I tried playing around with z index but it didn't seem to work for me

I just checked zindex works

**Comment by ansharora28** [comment]
I see,should i do it using z index instead?
Already created a pr for moving dark mode button upwards.
Let me know how you want it done!

**Comment by narayan954** [comment]
> I see,should i do it using z index instead? Already created a pr for moving dark mode button upwards. Let me know how you want it done!

Yeah, please use z index, it's too upwards

**Comment by ansharora28** [comment]
![image](https://user-images.githubusercontent.com/89684245/207667534-db23e43e-4364-4ffb-99a8-582274537fde.png)
Hi,while changing z-index for the dark mode button will solve that problem,another bug would arise. The scroll top button covers the entirety of the footer (highlighted),so if I click anywhere in that area I would go to the top which would be weird. 
So should we instead make changes in the scroll to top property instead?

**Comment by narayan954** [comment]
> ![image](https://user-images.githubusercontent.com/89684245/207667534-db23e43e-4364-4ffb-99a8-582274537fde.png) Hi,while changing z-index for the dark mode button will solve that problem,another bug would arise. The scroll top button covers the entirety of the footer (highlighted),so if I click anywhere in that area I would go to the top which would be weird. So should we instead make changes in the scroll to top property instead?

Hello, yes that's a feature of the scroll to top button that when you click on bottom you can go to top, anyways we don't have any other feature downwards so current implementation can be considered okay and dark mode button can be fixed instead. :)

**Comment by ansharora28** [comment]
I meant that the scroll to top occupies the entire width so if I click anywhere in that region,we move to the top. Technically that should only work for clicking the button right?

Attaching a video for reference

https://user-images.githubusercontent.com/89684245/207924273-68c160f4-ee93-4578-8d3b-f531d5d83fa2.mp4

**Comment by narayan954** [comment]
> I meant that the scroll to top occupies the entire width so if I click anywhere in that region,we move to the top. Technically that should only work for clicking the button right?
> 
> Attaching a video for reference
> 
>  DummyGram.-.Google.Chrome.2022-12-15.22-40-27.mp4

Yes, you're right. You can work on this button :)
