### ISSUE TITLE
Form breaking in feedback page

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1196]
### Description

form breaking in feedback page

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

click on feedback 

### Screenshots

<img width="642" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/0bf2b583-7084-4d6e-ba43-471216b7991c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @biplavmz #939 raises this issue, claim that please. Closing this as duplicate
