### ISSUE TITLE
[FEATURE] Want to Add Faq Section in help center page

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1197]
### Description

I woukd like  to Add Faq Section in help center page

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

we are getting 404 

### Screenshots

<img width="873" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/f92d4a1f-2e3a-4c31-b361-2b95fed13ca7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> gssoc

Hi @biplavmz , can you make it in consistency with styles of other footer pages? I mean the structure/design must be similar.

**Comment by biplavmz** [comment]
hii @narayan954 can you pls check and merge my pr
