### ISSUE TITLE
On login page descprition of dummygram is not visible in dark mode

### ISSUE THREAD

**Issue by ManashAnand** [narayan954/dummygram#1198]
### Description

Hey,
I am surfing the site and found out that On login Page 
Description is not visible in dark mode
I will add the screen shot below
When selecting certain part it is visible
Which is breaking UI/UX 

I want to fix the bug and style the component a bit?

Please assign me this issue 
So that I can start working on it.

### Steps to reproduce

I will add some styling on description in dark mode

### Screenshots

![q1](https://github.com/narayan954/dummygram/assets/91553087/b768a2dd-f062-4c90-8ce9-53a98bf0a8e5)
![q2](https://github.com/narayan954/dummygram/assets/91553087/36eb2b1d-b479-4859-9c83-6825da7bd975)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Hey, I am surfing the site and found out that On login Page Description is not visible in dark mode I will add the screen shot below When selecting certain part it is visible Which is breaking UI/UX
> 
> I want to fix the bug and style the component a bit?
> 
> Please assign me this issue So that I can start working on it.
> 
> ### Steps to reproduce
> I will add some styling on description in dark mode
> 
> ### Screenshots
> ![q1](https://user-images.githubusercontent.com/91553087/258878945-b768a2dd-f062-4c90-8ce9-53a98bf0a8e5.png) ![q2](https://user-images.githubusercontent.com/91553087/258879047-36eb2b1d-b479-4859-9c83-6825da7bd975.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @ManashAnand  thanks for spotting that, you can fix that, also, can you add a cool border to the login form to make it like a box, if that looks good?
