### ISSUE TITLE
[FEATURE] Improve Ui for Post Card. 

### ISSUE THREAD

**Issue by MaYaNkKashyap681** [narayan954/dummygram#120]
### Description

Make the ui of card component look better.
#kwoc

**Comment by MaYaNkKashyap681** [comment]
Assign this to me please.

**Comment by narayan954** [comment]
Great go ahead!

**Comment by MaYaNkKashyap681** [comment]
do you also need a user profile page

**Comment by narayan954** [comment]
> do you also need a user profile page ?

It's a Wip

**Comment by MaYaNkKashyap681** [comment]
> > do you also need a user profile page ?
> 
> It's a Wip

Do you want me to work on the user Profile Page?

**Comment by narayan954** [comment]
ping me in that issue, so I can assign if that issue's inactive
