### ISSUE TITLE
[FEATURE] - Sidebar Options Design Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [narayan954/dummygram#1201]
### Description

Working on the styling of the side navbar options styling to improve their design.

### Screenshots

_Current Design_

![i (1)](https://github.com/narayan954/dummygram/assets/115794049/0ead6315-ccf1-4302-8a37-c9f92f797189)

_Expected Updated Design_

![i (2)](https://github.com/narayan954/dummygram/assets/115794049/485a9b8b-b07a-467e-b694-a133d0d917da)

### Additional information

No

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by iamRabia-N** [comment]
Hi @narayan954 
Kindly assign me this issue.

**Comment by narayan954** [comment]
Hi @iamRabia-N pr #1193 is in progress for this section currently. Let's wait out before we work on this component. 
Also I'm not sure if this color looks nice here. Closing this as not planned right now
