### ISSUE TITLE
feedback page is breaking 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#1208]
### Description

feedback page is breaking 
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to feedback page 

### Screenshots

<img width="632" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/3b2f3675-cf32-47d3-8e6a-861221da7b3f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
I closed this issue as duplicate already, why are you creating another duplicate?
