### ISSUE TITLE
Text is not visible in dark mode

### ISSUE THREAD

**Issue by Prajwal0225** [narayan954/dummygram#1218]
### Description

In light mode 

![image](https://github.com/narayan954/dummygram/assets/103810119/faa00c2c-1cc8-433f-b15f-5dcf1a9f0b00)

### Steps to reproduce

change the color of the text in dark mode

### Screenshots

Dark mode
![image](https://github.com/narayan954/dummygram/assets/103810119/dacfeb89-2790-49b0-952f-e7419f50896a)

### Desktop (please complete the following information)

Windows,Chrome

### Smartphone (please complete the following information)

realme 3 pro, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In light mode
> 
> ![image](https://user-images.githubusercontent.com/103810119/259187072-faa00c2c-1cc8-433f-b15f-5dcf1a9f0b00.png)
> 
> ### Steps to reproduce
> change the color of the text in dark mode
> 
> ### Screenshots
> Dark mode ![image](https://user-images.githubusercontent.com/103810119/259187377-dacfeb89-2790-49b0-952f-e7419f50896a.png)
> 
> ### Desktop (please complete the following information)
> Windows,Chrome
> 
> ### Smartphone (please complete the following information)
> realme 3 pro, Chrome
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

hi @Prajwal0225 actually this issue has already been raised, so I've to close this as duplicate. Meanwhile you can explore other issues :)
