### ISSUE TITLE
[FEATURE] Adding a functional share button

### ISSUE THREAD

**Issue by ShivanshAr97** [narayan954/dummygram#123]
### Description

I would like to contribute by making a functional share button, clicking on which, we will have options to share the post via Whatsapp, Linkedin, Telegram, etc. having the link of the post and some information about the post.

**Comment by ShivanshAr97** [comment]
Hey @narayan954 please assign it to me

**Comment by narayan954** [comment]
Good idea but how'd you get/provide link for a post?

**Comment by ShivanshAr97** [comment]
I have not gone through the complete code base but I think there will be an id or post name which is stored which is used for mapping the list of posts. This id can be used as params in the URL.

**Comment by narayan954** [comment]
> I have not gone through the complete code base but I think there will be an id or post name which is stored which is used for mapping the list of posts. This id can be used as params in the URL.

Yes, that'll do, currently it's not implemented, would you like to work on this?

**Comment by narayan954** [comment]
Also, there's already a share button commented out in post component, make use of that

**Comment by praduman8435** [comment]
what you want to share through share button

**Comment by narayan954** [comment]
> what you want to share through share button

Posts, the share button should link to the exact post

**Comment by praduman8435** [comment]
> > what you want to share through share button
> 
> Posts, the share button should link to the exact post

Ok

**Comment by praduman8435** [comment]
I have created the button now how can I add social media links to that button suggest me

**Comment by narayan954** [comment]
> @narayan954  I have created the button now how can I add social media links to that button suggest me

you can read this conversation, it's mentioned already

**Comment by praduman8435** [comment]
Hello @narayan954  I have done most of the work the thing last that remain is how can I find the link of the post that I want to share

**Comment by praduman8435** [comment]
please help me

**Comment by narayan954** [comment]
> Hello @narayan954 I have done most of the work the thing last that remain is how can I find the link of the post that I want to share

there will be an id which is used for mapping the list of posts. This id can be used as params in the URL. You can share posts with that id as parameter in the URL.

**Comment by narayan954** [comment]
You'll need to configure that route.

**Comment by narayan954** [comment]
Hi @praduman8435 , are you still working?

**Comment by narayan954** [comment]
Please, pick only 1 issue at a time. For now pick the one out of three issues you're assigned currently so I can open them for contributions

**Comment by praduman8435** [comment]
Currently I am working on this you can open other two for the contributors

**Comment by narayan954** [comment]
are you working on this? @praduman8435

**Comment by praduman8435** [comment]
No, I'm not

**Comment by narayan954** [comment]
> No, I'm not

okay thanks for confirming

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
You can be assigned to only one issue at a time, finish the assigned issue first. Thank you

**Comment by sarkartanmay393** [comment]
@narayan954 Hey Narayan, I raised PR #218 on the functionality of the share button, and this issue is close to my work. I would like to take it over after my current PR.

**Comment by sarkartanmay393** [comment]
@narayan954 Assign me on it under jwoc

**Comment by narayan954** [comment]
> @narayan954 Assign me on it under jwoc

Great, go ahead!
