### ISSUE TITLE
Prevent Unsupported formats in Post Upload

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#124]
### Description

Currently while uploading posts, there's no validation of upload formats and hence anything can be uploaded in that.
We need to check the format before uploading/creating post.
Also mention this near the upload option in new post button like "Only jpg,... formats are accepted"

### Steps to reproduce

Anytime you upload a post, you can select any format and upload it, though it won't be available to preview but will create a blank space as well as consume unnecessary database storage.

**Comment by kshitij01042002** [comment]
Assign me this issue.

**Comment by kshitij01042002** [comment]
@narayan954 you can close this issue ig
