### ISSUE TITLE
semicolon added on every comment

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#1266]
### Description

semicolon is being added to every comment

### Steps to reproduce

craft a comment on any post

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by leabuende** [comment]
Hello ! I want to fix this issue, can you assign it to me ? 🚀

**Comment by narayan954** [comment]
> Hello ! I want to fix this issue, can you assign it to me ? 🚀

sure go ahead!
