### ISSUE TITLE
[Bug] : In singup page profile picture is overflowing

### ISSUE THREAD

**Issue by love-sonkar** [narayan954/dummygram#1268]
### Description

when you go to singup page the profile picture is overflowing.

### Steps to reproduce

go to singup page
and the profile picture is overflowing in header section

### Screenshots

![margin issue](https://github.com/narayan954/dummygram/assets/82786865/bc28f446-95e4-4b4c-8bfc-fe6280895cee)
![mmm](https://github.com/narayan954/dummygram/assets/82786865/0f261dac-0785-4cb6-8167-245ea4f01955)

### Desktop (please complete the following information)

windows 7
Chrome Browser

### Additional information

i wanted to fix this issue please assing to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by love-sonkar** [comment]
no worries bro 🙂

**Comment by narayan954** [comment]
> no worries bro 🙂

Hi bro, actually this is affecting the login page as well. Can you please check that?

**Comment by love-sonkar** [comment]
okay bro let me check
