### ISSUE TITLE
[UX] <Displaying posts in comment box in slider format>

### ISSUE THREAD

**Issue by kshitij01042002** [narayan954/dummygram#127]
### Description

Currently the posts are displayed in Grid format in view all comment dialog box, we can modify it to display the posts in image slider as shown in #126 

### Screenshots

![image](https://user-images.githubusercontent.com/91470808/207719784-91bb0625-b3f5-4314-b2d9-068a10a24f07.png)

**Comment by narayan954** [comment]
you can go ahead :)

**Comment by narayan954** [comment]
check points for this issue

**Comment by kshitij01042002** [comment]
Got them!
