### ISSUE TITLE
Improve alignment of register page

### ISSUE THREAD

**Issue by singodiyashubham87** [narayan954/dummygram#1270]
### Description

The navbar is overflowing the register box

### Steps to reproduce

I will reposition the register box

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/93720428/f0ad48f5-ade8-4e77-903d-ad1a6ee8bc26)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The navbar is overflowing the register box
> 
> ### Steps to reproduce
> I will reposition the register box
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/93720428/273368783-f0ad48f5-ade8-4e77-903d-ad1a6ee8bc26.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @singodiyashubham87 first of all, navbar shouldn't be present in login/register page itself :) (it can be fixed by fixing the condition of checking url for navbar component display)
Secondly, I can't regenerate this issue, can you please confirm if this is because you've scaled the window to below 80% or more than 150%?

**Comment by singodiyashubham87** [comment]
@narayan954 I haven't scaled the screen, It's just simple 100% of screen size in brave browser.

**Comment by singodiyashubham87** [comment]
@narayan954 There is some issue with the search box too when we click it then it opens but when I again click on it to close then its size is abruptly increased before closing..Have a look

https://github.com/narayan954/dummygram/assets/93720428/9aafbde6-5282-424e-b209-2551e7b87625

**Comment by narayan954** [comment]
> @narayan954 There is some issue with the search box too when we click it then it opens but when I again click on it to close then its size is abruptly increased before closing..Have a look
> 
> I want to fix this issue, kindly assign me under Hacktoberfest'23
> 
>  out-1.mp4



> @narayan954 There is some issue with the search box too when we click it then it opens but when I again click on it to close then its size is abruptly increased before closing..Have a look
> 
> I want to fix this issue, kindly assign me under Hacktoberfest'23
> 


Hi, @singodiyashubham87 the intended 100% scale is this view, 
 ![intended 100%](https://github.com/narayan954/dummygram/assets/77617189/e3dacb4d-8e37-40eb-b3b8-f4f2546ec78f)

I just checked in safari as well, your screenshot is the default scale..... 
we need to take a look at this problem as well, as it's not the UI we'd want to show users. 

Anyways you can work on this issue! :)
