### ISSUE TITLE
Card content overflow from card

### ISSUE THREAD

**Issue by love-sonkar** [narayan954/dummygram#1278]
### Description

in post card the save icon is overflow from card

### Steps to reproduce

go to main page of dummygram
you can see post card the save icon is overflowing 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/82786865/2a1c7a11-6a6c-4187-9fd3-5c8cabf9e123)

### Desktop (please complete the following information)

windows 11 latest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> in post card the save icon is overflow from card
> 
> ### Steps to reproduce
> go to main page of dummygram you can see post card the save icon is overflowing
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/82786865/275619704-2a1c7a11-6a6c-4187-9fd3-5c8cabf9e123.png)
> 
> ### Desktop (please complete the following information)
> windows 11 latest
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

hi @love-sonkar , can you please check again as i can't repro the issue
![image](https://github.com/narayan954/dummygram/assets/77617189/e43d5522-dfc5-458a-ac1e-8d37be8bb890)
 regards

**Comment by love-sonkar** [comment]
I just checked and found that you only see this bug if you go over 900px

# video 

https://github.com/narayan954/dummygram/assets/82786865/0dccc4aa-ac3b-474a-8ac2-203ade27e03a

**Comment by narayan954** [comment]
> I just checked and found that you only see this bug if you go over 900px
> 
> # video
>  Untitled.video.-.Made.with.Clipchamp.1.mp4

fair enough :)
