### ISSUE TITLE
Caption hidden

### ISSUE THREAD

**Issue by 0xNunana** [narayan954/dummygram#1281]
### Description

Captions written alongside an uploaded image in portrait hides behind the image. Kindly assign under hacktoberfest label

### Steps to reproduce

Upload a picture in portrait mode, Add a caption, click on post. On the homepage, the image overshadows it

### Screenshots

![Screenshot from 2023-10-18 09-39-26](https://github.com/narayan954/dummygram/assets/94549530/6f3459b0-c88d-4043-8310-9aa4c3541ca5)

### Desktop (please complete the following information)

ubuntu, Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Captions written alongside an uploaded image in portrait hides behind the image. Kindly assign under hacktoberfest label
> 
> ### Steps to reproduce
> Upload a picture in portrait mode, Add a caption, click on post. On the homepage, the image overshadows it
> 
> ### Screenshots
> ![Screenshot from 2023-10-18 09-39-26](https://user-images.githubusercontent.com/94549530/276206300-6f3459b0-c88d-4043-8310-9aa4c3541ca5.png)
> 
> ### Desktop (please complete the following information)
> ubuntu, Firefox
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

thanks for spotting this, you can work on this :)
