### ISSUE TITLE
Login form isnt centered

### ISSUE THREAD

**Issue by Afterdie** [narayan954/dummygram#1293]
### Description

The login form content isnt centered vertically.

### Steps to reproduce

Visit the url and view the login form.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/82810411/e575fc22-e07c-4777-9af8-d3be2ba036c7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

**Comment by Afterdie** [comment]
I'd like to work on this issue

**Comment by narayan954** [comment]
Sure, go ahead! :)

**Comment by narayan954** [comment]
Thanks for your contribution :)
