### ISSUE TITLE
Unnecessary scroll on login page

### ISSUE THREAD

**Issue by Afterdie** [narayan954/dummygram#1295]
### Description

This [line ](https://github.com/narayan954/dummygram/blob/07ea065694fd33c1f15b72971d0d4f3ab31f94a2/src/App.jsx#L337)adds the darkmode toggle to signup and login pages, this causes y-scroll on the login even though the content can be shown on a single page.

### Steps to reproduce

Go to the login page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

**Comment by Afterdie** [comment]
I'd like to work on this issue

**Comment by narayan954** [comment]
> ### Description
> This [line ](https://github.com/narayan954/dummygram/blob/07ea065694fd33c1f15b72971d0d4f3ab31f94a2/src/App.jsx#L337)adds the darkmode toggle to signup and login pages, this causes y-scroll on the login even though the content can be shown on a single page.
> 
> ### Steps to reproduce
> Go to the login page
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> _No response_

Hi @Afterdie , should we not have a darkmode toggle? Or can this issue be resolved without removing the dark mode toggle?

**Comment by Afterdie** [comment]
> > ### Description
> 
> > This [line ](https://github.com/narayan954/dummygram/blob/07ea065694fd33c1f15b72971d0d4f3ab31f94a2/src/App.jsx#L337)adds the darkmode toggle to signup and login pages, this causes y-scroll on the login even though the content can be shown on a single page.
> 
> > 
> 
> > ### Steps to reproduce
> 
> > Go to the login page
> 
> > 
> 
> > ### Screenshots
> 
> > _No response_
> 
> > 
> 
> > ### Desktop (please complete the following information)
> 
> > _No response_
> 
> > 
> 
> > ### Smartphone (please complete the following information)
> 
> > _No response_
> 
> > 
> 
> > ### Additional information
> 
> > _No response_
> 
> > 
> 
> > ### Record
> 
> > * [x]  I agree to follow this project's Code of Conduct
> 
> > * [x]  I have checked the existing issues
> 
> > * [x]  I am a participant of a program
> 
> > * [x]  I want to work on this issue
> 
> > 
> 
> > ### Optional information
> 
> > _No response_
> 
> 
> 
> Hi @Afterdie , should we not have a darkmode toggle? Or can this issue be resolved without removing the dark mode toggle?

It can be accomplished without removing the toggle just a few style attribute changes

**Comment by narayan954** [comment]
> > > ### Description
> > 
> > 
> > > This [line ](https://github.com/narayan954/dummygram/blob/07ea065694fd33c1f15b72971d0d4f3ab31f94a2/src/App.jsx#L337)adds the darkmode toggle to signup and login pages, this causes y-scroll on the login even though the content can be shown on a single page.
> > 
> > 
> > > 
> > 
> > 
> > > ### Steps to reproduce
> > 
> > 
> > > Go to the login page
> > 
> > 
> > > 
> > 
> > 
> > > ### Screenshots
> > 
> > 
> > > _No response_
> > 
> > 
> > > 
> > 
> > 
> > > ### Desktop (please complete the following information)
> > 
> > 
> > > _No response_
> > 
> > 
> > > 
> > 
> > 
> > > ### Smartphone (please complete the following information)
> > 
> > 
> > > _No response_
> > 
> > 
> > > 
> > 
> > 
> > > ### Additional information
> > 
> > 
> > > _No response_
> > 
> > 
> > > 
> > 
> > 
> > > ### Record
> > 
> > 
> > > * [x]   I agree to follow this project's Code of Conduct
> > 
> > 
> > > * [x]   I have checked the existing issues
> > 
> > 
> > > * [x]   I am a participant of a program
> > 
> > 
> > > * [x]   I want to work on this issue
> > 
> > 
> > > 
> > 
> > 
> > > ### Optional information
> > 
> > 
> > > _No response_
> > 
> > 
> > Hi @Afterdie , should we not have a darkmode toggle? Or can this issue be resolved without removing the dark mode toggle?
> 
> It can be accomplished without removing the toggle just a few style attribute changes

That'd be great! Go ahead! :)
