### ISSUE TITLE
Error when visiting someone's or my profile

### ISSUE THREAD

**Issue by tushar-daiya** [narayan954/dummygram#1297]
### Description

There is an error thrown whenever I visit my or someone's profile.

### Steps to reproduce

Login in the dummygram website and then click on the menu near your profile pic and click on profile.. It throws an error and returns 404 not found page

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/108505673/89aac1aa-2751-464c-90eb-149f71340c9a)

### Desktop (please complete the following information)

Windows 11.
Google Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> There is an error thrown whenever I visit my or someone's profile.
> 
> ### Steps to reproduce
> Login in the dummygram website and then click on the menu near your profile pic and click on profile.. It throws an error and returns 404 not found page
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/108505673/289223726-89aac1aa-2751-464c-90eb-149f71340c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTA2NDksIm5iZiI6MTcwMjExMDM0OSwicGF0aCI6Ii8xMDg1MDU2NzMvMjg5MjIzNzI2LTg5YWFjMWFhLTI3NTEtNDY0Yy05MGViLTE0OWY3MTM0MGM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwODI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDE2MjRmOWQ5MDVlZmZhNzAzZTBjOWM4NGRmYWUwNDQzZWEyMzczODFhZmUxODQ5YjQ0OTJhOThmZGI3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R4zNhGvDAA7uJ4YKX_awN92UO_9uVNmBrzOlZHQfGuY)
> 
> ### Desktop (please complete the following information)
> Windows 11. Google Chrome
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> _No response_

Seems like there's an issue with your profile, can you please share your signup method?

**Comment by narayan954** [comment]
> I signed up using the default method.. and the error is only showing when the url has the username in it if it have the user id then the profile is shown

As per the implementation, we assign user id as the default username. There must be some error in between this conversion and accessing the profile information. Can you try to resolve it? Thanks a lot for raising the issue.
