### ISSUE TITLE
[OTHER] Having a dummy email for contributer to test this project 

### ISSUE THREAD

**Issue by Ayusht777** [narayan954/dummygram#1298]
### What would you like to share?

Suggesting the inclusion of a dummy email or login system for contributors on the website would be a great addition.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by narayan954** [comment]
> ### What would you like to share?
> Suggesting the inclusion of a dummy email or login system for contributors on the website would be a great addition.
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [ ]  I want to work on this issue

Hi @Ayusht777 please checkout the guest login in signup page and confirm if that resonates with these requirements

**Comment by Ayusht777** [comment]
ok
