### ISSUE TITLE
[FEATURE] User Profile Page.

### ISSUE THREAD

**Issue by MaYaNkKashyap681** [narayan954/dummygram#130]
### Description

A user profile page where the user can check his details as well his posts.

### Additional information

KWOC Program

**Comment by MaYaNkKashyap681** [comment]
Assign this to me.

**Comment by narayan954** [comment]
@MaYaNkKashyap681 don't create duplicate issues, I asked you to comment on the issue to check if it's unattended and claim it. But instead, you are creating a duplicate issue. Check #49 and comment there only, about this issue.
Thank you

**Comment by MaYaNkKashyap681** [comment]
> @MaYaNkKashyap681 don't create duplicate issues, I asked you to comment on the issue to check if it's unattended and claim it. But instead, you are creating a duplicate issue. Check #49 and comment there only, about this issue. Thank you

So Sorry, I forget about that I am closing it immediately.

**Comment by narayan954** [comment]
> > @MaYaNkKashyap681 don't create duplicate issues, I asked you to comment on the issue to check if it's unattended and claim it. But instead, you are creating a duplicate issue. Check #49 and comment there only, about this issue. Thank you
> 
> So Sorry, I forget about that I am closing it immediately.

It's okay :)
