### ISSUE TITLE
Old account data remains in the app even after logout

### ISSUE THREAD

**Issue by tushar-daiya** [narayan954/dummygram#1308]
### Description

When I login with a account say X and then logout and then login with account Y, then also when visiting the profile page the X account data shows up and not the Y account.

### Steps to reproduce

Login with a account now logout . then login with another account and then visit profile you will see your old account profile and not the current one.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> When I login with a account say X and then logout and then login with account Y, then also when visiting the profile page the X account data shows up and not the Y account.
> 
> ### Steps to reproduce
> Login with a account now logout . then login with another account and then visit profile you will see your old account profile and not the current one.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> _No response_

Sure, you can go ahead! :)
