### ISSUE TITLE
Display Username Rules

### ISSUE THREAD

**Issue by devArghya-0155** [narayan954/dummygram#1311]
### Description

It would be better if a new user is displayed the rules of a valid username while signing up. If a user types a new username while signing up and it is invalid, the user should be showed the rules so that he/she can understand and rectify their mistakes. 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/128981505/15569650-033a-4032-8db9-cc28f294e7d9)

### Additional information
The rules could be displayed in the form of a popup just below the message 'Username is invalid'. The popup would disappear once a valid username is inputted. Additionally, it would be very helpful if we could prompt a valid username to a user if he/she is short of ideas.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> It would be better if a new user is displayed the rules of a valid username while signing up. If a user types a new username while signing up and it is invalid, the user should be showed the rules so that he/she can understand and rectify their mistakes.
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/128981505/289755258-15569650-033a-4032-8db9-cc28f294e7d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjEyNTEsIm5iZiI6MTcwMjM2MDk1MSwicGF0aCI6Ii8xMjg5ODE1MDUvMjg5NzU1MjU4LTE1NTY5NjUwLTAzM2EtNDAzMi04ZGI5LWNjMjhmMjk0ZTdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNjAyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWYzYjhmNmU0ZWNjM2ExYjFjYTQwMGExY2FjY2NkOTE2YTM3MDAyNjBhOTIzNjUyZThhZDI3NzJjMWFmYmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fem9Qq4L4gfd-Q523cGmehE_yenYzmw3jDPLBGBrjuE)
> 
> ### Additional information
> The rules could be displayed in the form of a popup just below the message 'Username is invalid'. The popup would disappear once a valid username is inputted. Additionally, it would be very helpful if we could prompt a valid username to a user if he/she is short of ideas.
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

You can go ahead @devArghya-0155 :)
