### ISSUE TITLE
Enhancement Request - Date Indication in Messaging Section

### ISSUE THREAD

**Issue by Swetha-Baskaran** [narayan954/dummygram#1314]
### Description

Issue: 
In the messaging section of the app, there is currently no clear indication or separation to identify messages by date, making it challenging for users to distinguish between different days.

Request: 
I propose the implementation of a date indication feature to enhance user experience and provide clarity in message organization. This feature would help users quickly identify the group of messages corresponding to a specific date, yesterday, or today.

@narayan954 

### Steps to reproduce

1) Login to the app (this will redirect to home page).
2) click on the message icon on the top right of the homepagethe 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/74134426/70c706a5-f5c3-46f6-b40f-0834ed5eeb6a)

### Smartphone (please complete the following information)

![image](https://github.com/narayan954/dummygram/assets/74134426/c06e6e75-56ad-45b9-8b28-b0447fd5bfbc)
![image](https://github.com/narayan954/dummygram/assets/74134426/9c535b71-a81a-424d-bc3c-f59013b5fc8e)

### Additional information

Feel free to reach out if you need any more information. Implementing this enhancement will significantly improve the user experience in the messaging section. 

And we can also implement one and one messaging in the future.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I am a participant of a program
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Issue: In the messaging section of the app, there is currently no clear indication or separation to identify messages by date, making it challenging for users to distinguish between different days.
> 
> Request: I propose the implementation of a date indication feature to enhance user experience and provide clarity in message organization. This feature would help users quickly identify the group of messages corresponding to a specific date, yesterday, or today.
> 
> @narayan954
> 
> ### Steps to reproduce
> 1. Login to the app (this will redirect to home page).
> 2. click on the message icon on the top right of the homepagethe
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/74134426/290924965-70c706a5-f5c3-46f6-b40f-0834ed5eeb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzQ4NjUsIm5iZiI6MTcwMjY3NDU2NSwicGF0aCI6Ii83NDEzNDQyNi8yOTA5MjQ5NjUtNzBjNzA2YTUtZjVjMy00NmY2LWI0MGYtMDgzNGVkNWVlYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIxMDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YmRmMjllNGI0NTRhN2Y0YmNmNjU3MjAwMzlmNjNlZmViMGIzNThiM2M3MjY1MjAxMmFkNGY5NzZhZmRlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TCRyPXVBqlpOAq9VLNRiqOwO1mkOL_9hbUlvLz0ybuo)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> ![image](https://private-user-images.githubusercontent.com/74134426/290925673-c06e6e75-56ad-45b9-8b28-b0447fd5bfbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzQ4NjUsIm5iZiI6MTcwMjY3NDU2NSwicGF0aCI6Ii83NDEzNDQyNi8yOTA5MjU2NzMtYzA2ZTZlNzUtNTZhZC00NWI5LThiMjgtYjA0NDdmZDViZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIxMDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNDNmYmExNDFhZTI1NjcyNjAyMzRmOWM1ODYyNGUxMzc4OGFiNzViOGZjZTNhZGU4ZTY5ZmJmNWRkMDkwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmKMavDwVExhMQ-bnDa9FfzfzUH5jVqIcC-AtSigRVQ) ![image](https://private-user-images.githubusercontent.com/74134426/290925707-9c535b71-a81a-424d-bc3c-f59013b5fc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NzQ4NjUsIm5iZiI6MTcwMjY3NDU2NSwicGF0aCI6Ii83NDEzNDQyNi8yOTA5MjU3MDctOWM1MzViNzEtYTgxYS00MjRkLWJjM2MtZjU5MDEzYjVmYzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDIxMDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiODIyZDdiNDI0MTYzYjE2NDhjYzAxNTRmZGJlZGRlMDk4YjllNzYwMmZkNGRkMzg0M2VjNDhkMmE1NDMxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7wxJNmhDBabCFUPpLArwAsYolyS5r7PQFciKjihHLB4)
> 
> ### Additional information
> Feel free to reach out if you need any more information. Implementing this enhancement will significantly improve the user experience in the messaging section.
> 
> And we can also implement one and one messaging in the future.
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> _No response_

Hi @Swetha-Baskaran that'd be really good to implement! Would you like to work on this? Also do lmk if you're a participant of codepeak so I can assign points :)

**Comment by narayan954** [comment]
also as I think of the space utilization for this time display... I say, if posts are older than 24 hours , we display date? else "hours before" , what do you think of this?

**Comment by Swetha-Baskaran** [comment]
Hi @narayan954 I wish to contribute to this project.

First I would like to fix the date seperation for messages. 

And If you wish I could do the one and one messaging part. 

I'm not the part of codefest

**Comment by narayan954** [comment]
> Hi @narayan954 I wish to contribute to this project.
> 
> First I would like to fix the date seperation for messages.
> 
> And If you wish I could do the one and one messaging part.
> 
> I'm not the part of codepeek

That's great!
Sure you can go ahead! :)
We can do one on one messaging in next issue, also just fyi, we have friends array in user collection with friend's uuids as in ss below 
![image](https://github.com/narayan954/dummygram/assets/77617189/7c858b04-c196-4b7a-b0a6-3d15eed135db)
I'm thinking, we can show them all as options to message (also a heads up, some of those friend ids might not exist)
