### ISSUE TITLE
add a footer to this website

### ISSUE THREAD

**Issue by GAGANRAGHAV** [narayan954/dummygram#1316]
### Description

i want to add a footer to codetalk website as it is essential

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/120806356/663b6214-cd06-4b9d-ae0f-77064227a57e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> i want to add a footer to codetalk website as it is essential
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/120806356/291328741-663b6214-cd06-4b9d-ae0f-77064227a57e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDQ5NTUsIm5iZiI6MTcwMjk0NDY1NSwicGF0aCI6Ii8xMjA4MDYzNTYvMjkxMzI4NzQxLTY2M2I2MjE0LWNkMDYtNGI5ZC1hZTBmLTc3MDY0MjI3YTU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwMDEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTlmMmE1MDgwMjdlY2Y3YTA1NWVkOTlmNGMzYzgzNGRmODY2NDYxNDc1NzRmODNlM2UzMjYzZTcwYTZjMjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LqVItcbgMTUAX33VvHK1QT2R8-t0Zdd-vJRIP87j-LI)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @GAGANRAGHAV can you please double check if this is the project you're referring to, as you're talking about codetalk website
