### ISSUE TITLE
Hovering on clickables must have cursor - pointer

### ISSUE THREAD

**Issue by AaadityaG** [narayan954/dummygram#1318]
### Description

The problem is occures on the right side profile hoverings. 

### Steps to reproduce

Add the css property - cursor: pointer;

### **for this section -**

![Capture](https://github.com/narayan954/dummygram/assets/114663382/b3e5aa2a-1e18-445a-86c8-c34374ba24ec)

### Desktop (please complete the following information)

https://github.com/narayan954/dummygram/assets/114663382/3056ca5a-f5f4-43ad-acc4-616a320c0ec6

### Smartphone (please complete the following information)

Not in smartphone

### Additional information

checkout at https://narayan954.github.io/dummygram/ by hovering right side profiles 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

### Optional information

codepeak

**Comment by narayan954** [comment]
> ### Description
> The problem is occures on the right side profile hoverings.
> 
> ### Steps to reproduce
> Add the css property - cursor: pointer;
> 
> ### Screenshots
> ### **for this section -**
> ![Capture](https://private-user-images.githubusercontent.com/114663382/292514819-b3e5aa2a-1e18-445a-86c8-c34374ba24ec.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjE4NDcsIm5iZiI6MTcwMzI2MTU0NywicGF0aCI6Ii8xMTQ2NjMzODIvMjkyNTE0ODE5LWIzZTVhYTJhLTFlMTgtNDQ1YS04NmM4LWMzNDM3NGJhMjRlYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxNjEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWMzOWY0NDgxM2VmNzk4ZTNmMTc5MDkwZThiNDg3YjI4NTYyNzlmZDNjMTJhN2VjZDIyYTUyNDc3YmQ4NjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0hW2RrbNn7H5P37DtYxM6XBsUbifKsEPbFCWg_uHRDQ)
> 
> ### Desktop (please complete the following information)
>  DummyGram.Mozilla.Firefox.2023-12-22.20-24-52.mp4 
> ### Smartphone (please complete the following information)
> Not in smartphone
> 
> ### Additional information
> checkout at https://narayan954.github.io/dummygram/ by hovering right side profiles
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> codepeak

you can go ahead! :)
