### ISSUE TITLE
[DOCS] Installation Step is missing 

### ISSUE THREAD

**Issue by AaadityaG** [narayan954/dummygram#1319]
### Description

If someone go through the project setup guide from readme. 

The step -

###  **`cd dummygram`**

after clonning of repo.

### Screenshots

![Capture](https://github.com/narayan954/dummygram/assets/114663382/4151979e-c46c-4071-9fb9-97ab8e22dfff)

### Additional information

I am codepeak contributor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> If someone go through the project setup guide from readme.
> 
> The step -
> 
> ### **`cd dummygram`**
> after clonning of repo.
> 
> ### Screenshots
> ![Capture](https://private-user-images.githubusercontent.com/114663382/292616818-4151979e-c46c-4071-9fb9-97ab8e22dfff.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDM1NTEsIm5iZiI6MTcwMzQwMzI1MSwicGF0aCI6Ii8xMTQ2NjMzODIvMjkyNjE2ODE4LTQxNTE5NzllLWM0NmMtNDA3MS05ZmI5LTk3YWI4ZTIyZGZmZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwNzM0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGFlMjFlMGU5YzY3NmY4ODNjZjY1OGZiY2ExZTc1MjkxYWIwZmZhNzA3OTJlNTZlMzdlMGNkODRjYzViY2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yZObBWOQeDgQwfTCbAySN40FE5GLMVtIDIyX0HEfa-g)
> 
> ### Additional information
> I am codepeak contributor
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue



> ### Description
> If someone go through the project setup guide from readme.
> 
> The step -
> 
> ### **`cd dummygram`**
> after clonning of repo.
> 
> ### Screenshots
> ![Capture](https://private-user-images.githubusercontent.com/114663382/292616818-4151979e-c46c-4071-9fb9-97ab8e22dfff.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDM1NTEsIm5iZiI6MTcwMzQwMzI1MSwicGF0aCI6Ii8xMTQ2NjMzODIvMjkyNjE2ODE4LTQxNTE5NzllLWM0NmMtNDA3MS05ZmI5LTk3YWI4ZTIyZGZmZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwNzM0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGFlMjFlMGU5YzY3NmY4ODNjZjY1OGZiY2ExZTc1MjkxYWIwZmZhNzA3OTJlNTZlMzdlMGNkODRjYzViY2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yZObBWOQeDgQwfTCbAySN40FE5GLMVtIDIyX0HEfa-g)
> 
> ### Additional information
> I am codepeak contributor
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can go ahead! :) also you may consider adding option for yarn users ( ` yarn install ` or `yarn`)

**Comment by AaadityaG** [comment]
ok thanks
