### ISSUE TITLE
Login Page is not responsive

### ISSUE THREAD

**Issue by itsmeabhishek03** [narayan954/dummygram#1321]
### Description

hey @narayan954 Login Page of your app is not responsive for mobile S - 320px and smaller devices

### Steps to reproduce

Add the css property to fix it 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104294494/c0276e58-7f9f-4503-8529-24f0ac5ac3da)

you can see the pink arrows aiming towards the issue 

### Desktop (please complete the following information)

Windows -> Chrome -> Version 120.0.6099.129 (Official Build) (64-bit)

### Smartphone (please complete the following information)

Not in smartphone

### Additional information

No

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

### Optional information

Codepeak'23 and JWOC

**Comment by narayan954** [comment]
> ### Description
> hey @narayan954 Login Page of your app is not responsive for mobile S - 320px and smaller devices
> 
> ### Steps to reproduce
> Add the css property to fix it
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/104294494/292657428-c0276e58-7f9f-4503-8529-24f0ac5ac3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDM1NTMsIm5iZiI6MTcwMzQwMzI1MywicGF0aCI6Ii8xMDQyOTQ0OTQvMjkyNjU3NDI4LWMwMjc2ZTU4LTdmOWYtNDUwMy04NTI5LTI0ZjBhYzVhYzNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwNzM0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzViYTZlZGNjNDI0MDhkMWZiODMzYzJhNmNmMzExZjhkY2NjMGQ0YzgzMTgxZGE0Y2M0YTg5NzJlODEzNGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dl8uW6y1evfAnEi0t65JhO0hLFtZvjN13gOvHlQbwRc)
> 
> you can see the pink arrows aiming towards the issue
> 
> ### Desktop (please complete the following information)
> Windows -> Chrome -> Version 120.0.6099.129 (Official Build) (64-bit)
> 
> ### Smartphone (please complete the following information)
> Not in smartphone
> 
> ### Additional information
> No
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> Codepeak'23 and JWOC

Hi @itsmeabhishek03 you can go ahead!
Ps: I'd only be able to provide score for codepeak as this project is participating in codepeak 23
