### ISSUE TITLE
Chat Input should be down

### ISSUE THREAD

**Issue by AaadityaG** [narayan954/dummygram#1326]
### Description

The **input** of message should cover up the chat from **lower side**

### Steps to reproduce

Go to - https://narayan954.github.io/dummygram/#/chat

### Screenshots

![Capture1](https://github.com/narayan954/dummygram/assets/114663382/099ebbcb-9875-4a1b-b31c-339400d11bd0)

![Capture](https://github.com/narayan954/dummygram/assets/114663382/10f4cbc7-0547-42dc-b851-6225e582b865)

### Desktop (please complete the following information)

Same as above

### Smartphone (please complete the following information)

fine for samrtphones

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

### Optional information

Codepeak

**Comment by narayan954** [comment]
> ### Description
> The **input** of message should cover up the chat from **lower side**
> 
> ### Steps to reproduce
> Go to - https://narayan954.github.io/dummygram/#/chat
> 
> ### Screenshots
> ![Capture1](https://private-user-images.githubusercontent.com/114663382/292759466-099ebbcb-9875-4a1b-b31c-339400d11bd0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTEzMjYsIm5iZiI6MTcwMzYxMTAyNiwicGF0aCI6Ii8xMTQ2NjMzODIvMjkyNzU5NDY2LTA5OWViYmNiLTk4NzUtNGExYi1iMzFjLTMzOTQwMGQxMWJkMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNzE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjVmZGExMmU4OWMwNzVjN2FlYjBhZDY3MGIwZDM2MzhhNDM3ZGQwYzZkZTk4YTIxODhjOTZjNGVjMTZmYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7W-AD9sbL1L0ssfa_2ycEpglgsmF9J8Lln1VUj2Bu0I)
> 
> ![Capture](https://private-user-images.githubusercontent.com/114663382/292759479-10f4cbc7-0547-42dc-b851-6225e582b865.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTEzMjYsIm5iZiI6MTcwMzYxMTAyNiwicGF0aCI6Ii8xMTQ2NjMzODIvMjkyNzU5NDc5LTEwZjRjYmM3LTA1NDctNDJkYy1iODUxLTYyMjVlNTgyYjg2NS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNzE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzE3OTQzZDlmZGY3MzZiNDU4NzdmZjRkYmE1ZWY4OThkYjZiZDQwMjZlNGMyYmUwOWMxZmFhNzMwNDVmMDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iOcJlyQy82z9Ealbtv9rQLAKsZK8gZ5NPos4LQua1A4)
> 
> ### Desktop (please complete the following information)
> Same as above
> 
> ### Smartphone (please complete the following information)
> fine for samrtphones
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I am a participant of a program
> * [x]  I want to work on this issue
> 
> ### Optional information
> Codepeak

You can go ahead! :)
