### ISSUE TITLE
Adding Unit Test Cases for  React Project

### ISSUE THREAD

**Issue by Jagroop2000** [narayan954/dummygram#133]
### Description

Can I work on this Project?
I can add unit test scripts using jest in this Project.
Please allow me to continue with the same.
About Unit Testing :
Unit Testing is used to check whether the Input fields are working correctly without interaction of any Human.
Here I write a unit tests using Jest which is auto-installed which creating react app.

So I will write a test for each component and the good thing is the code is used for testing only while deploying app it doesn't effect the perfornce but it is useful to test our react app without human intraction.

Hoping to hear from you soon !!

**Comment by Jagroop2000** [comment]
Hi !! 
I can complete this in 1 day.

**Comment by narayan954** [comment]
okay go on :) and please mention your program

**Comment by 1010varun** [comment]
hey @narayan954 please assign this issue to me

**Comment by narayan954** [comment]
> hey @narayan954 please assign this issue to me
> 
> 

Hi @1010varun , you are already assigned an issue, please solve that first.
Thanks

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
> I want to work for on this issue under jwoc , please assign me

You can be assigned to only one issue at a time, finish the other issue first. Thank you

**Comment by sarkartanmay393** [comment]
@narayan954 Assign it to me under JWOC. And as you didn't raise this issue, I'm thinking to use Cypress and build a test suite with that. How's that sound like to you ?

**Comment by narayan954** [comment]
> @narayan954 Assign it to me under JWOC. And as you didn't raise this issue, I'm thinking to use Cypress and build a test suite with that. How's that sound like to you ?

Sounds cool. Best of luck!
