### ISSUE TITLE
UX Improvement: Add Loading Animations

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#14]
**Is your feature request related to a problem? Please describe.**
The UX is really poor. Currently, there is no indicator that shows if a process is running or not (i.e Logging in, Signing Up, New Post)

**Describe the solution you'd like**
Use loading animations to tell users if there's a running/loading process

**Describe alternatives you've considered**
[NONE]

**Additional context**
[NONE]

**Comment by narayan954** [comment]
Well that's a great idea!! You can go ahead!
