### ISSUE TITLE
[FEATURE] <Refresh on clicking on Logo>

### ISSUE THREAD

**Issue by kshitij01042002** [narayan954/dummygram#140]
### Description

Refresh the app on clicking the logo of the app

### Screenshots

![Screenshot 2022-12-20 232632](https://user-images.githubusercontent.com/91470808/208734477-cd1bf579-2920-48f0-99ff-6f8f49fd7399.png)

**Comment by narayan954** [comment]
It shouldn't be an actual browser refresh but "return to home".
