### ISSUE TITLE
[FEATURE] fix post's height

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#144]
### Description

Currently posts are of uneven lengths, and this is inconsistent, we can fix the post height, so the feed is consistent.
Also fix the height of posts in comments popup and set a minimum height as well.

**Comment by Rishav1707** [comment]
Could you tell me the max height you want in your post? @narayan954 
I think the `max-height: 550px;` in a post and `min-height: 40px;` in the comments popup would be a better choice.

**Comment by narayan954** [comment]
> Could you tell me the max height you want in your post? @narayan954 I think the `max-height: 550px;` in a post and `min-height: 40px;` in the comments popup would be a better choice.

Yes, you're right, would you like to work on this? and under which program kwoc or codepeak ?

**Comment by Rishav1707** [comment]
> under which program kwoc or codepeak ?

What does it mean ? @narayan954

**Comment by Rishav1707** [comment]
> Yes, you're right, would you like to work on this?

Yeah sure...

**Comment by narayan954** [comment]
> > under which program kwoc or codepeak ?
> 
> What does it mean ? @narayan954 

this project is also participating in kwoc and codepeak open source programs

**Comment by Rishav1707** [comment]
> > > under which program kwoc or codepeak ?
> > 
> > 
> > What does it mean ? @narayan954
> 
> this project is also participating in kwoc and codepeak open source programs

Ohh nice

**Comment by narayansoni** [comment]
> > > > under which program kwoc or codepeak ?
> > > 
> > > 
> > > What does it mean ? @narayan954
> > 
> > 
> > this project is also participating in kwoc and codepeak open source programs
> 
> Ohh nice

so are you working independent?

**Comment by Rishav1707** [comment]
> > > > > under which program kwoc or codepeak ?
> > > > 
> > > > 
> > > > What does it mean ? @narayan954
> > > 
> > > 
> > > this project is also participating in kwoc and codepeak open source programs
> > 
> > 
> > Ohh nice
> 
> so are you working independent?

Yaah

**Comment by narayan954** [comment]
> > > > > > under which program kwoc or codepeak ?
> > > > > 
> > > > > 
> > > > > What does it mean ? @narayan954
> > > > 
> > > > 
> > > > this project is also participating in kwoc and codepeak open source programs
> > > 
> > > 
> > > Ohh nice
> > 
> > so are you working independent?
> 
> Yaah

Great , go ahead! :)

**Comment by Rishav1707** [comment]
![comments](https://user-images.githubusercontent.com/97666287/209576320-e4ce79e0-8ee3-42e1-a333-8a689769b699.png)

What is the class name of this image? @narayan954 
I am unable to find.

**Comment by narayan954** [comment]
> ![comments](https://user-images.githubusercontent.com/97666287/209576320-e4ce79e0-8ee3-42e1-a333-8a689769b699.png)
> 
> What is the class name of this image? @narayan954 I am unable to find.

that's just a button with some inline css defined 
![image](https://user-images.githubusercontent.com/77617189/209646720-8c1d6bff-7847-49e3-a164-bded25f4570c.png)
I hope this img helps

**Comment by Rishav1707** [comment]
> > ![comments](https://user-images.githubusercontent.com/97666287/209576320-e4ce79e0-8ee3-42e1-a333-8a689769b699.png)
> > What is the class name of this image? @narayan954 I am unable to find.
> 
> that's just a button with some inline css defined ![image](https://user-images.githubusercontent.com/77617189/209646720-8c1d6bff-7847-49e3-a164-bded25f4570c.png) I hope this img helps

Thanks

**Comment by Rishav1707** [comment]
Why website is not running @narayan954

**Comment by narayan954** [comment]
> Why website is not running @narayan954

it's up and running https://narayan954.github.io/dummygram/

**Comment by Rishav1707** [comment]
> > Why website is not running @narayan954
> 
> it's up and running https://narayan954.github.io/dummygram/

See it's continuously loading:


https://user-images.githubusercontent.com/97666287/210075847-229534b9-ad45-434c-b703-fa18c20f0aca.mp4

**Comment by narayan954** [comment]
> > > Why website is not running @narayan954
> > 
> > it's up and running https://narayan954.github.io/dummygram/
> 
> See it's continuously loading:
> 
> 
> https://user-images.githubusercontent.com/97666287/210075847-229534b9-ad45-434c-b703-fa18c20f0aca.mp4

I don't think that's an issue with the site https://user-images.githubusercontent.com/77617189/210081746-2d9eb54d-eda5-455c-819f-8bbf21861043.mp4

**Comment by Rishav1707** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/97666287/210177063-2202b386-6c7d-4368-84b8-9e7d195ac78f.png)

See this error @narayan954

**Comment by narayan954** [comment]
> ![Screenshot (6)](https://user-images.githubusercontent.com/97666287/210177063-2202b386-6c7d-4368-84b8-9e7d195ac78f.png)
> 
> See this error @narayan954 

okay now I know the issue, rules are set to allow only authorised(logged in) users to access db , and neither you're logged in, nor the login/signup option is available for logging in. That's why you should always check the console.
I'm outstation,but will change rule temporarily till a solution is implemented

**Comment by narayan954** [comment]
> > ![Screenshot (6)](https://user-images.githubusercontent.com/97666287/210177063-2202b386-6c7d-4368-84b8-9e7d195ac78f.png)
> > 
> > See this error @narayan954 
> 
> okay now I know the issue, rules are set to allow only authorised(logged in) users to access db , and neither you're logged in, nor the login/signup option is available for logging in. That's why you should always check the console.
> I'm outstation,but will soon change rule temporarily till a solution is implemented , and inform you

**Comment by Rishav1707** [comment]
> > > ![Screenshot (6)](https://user-images.githubusercontent.com/97666287/210177063-2202b386-6c7d-4368-84b8-9e7d195ac78f.png)
> > > See this error @narayan954
> > 
> > 
> > okay now I know the issue, rules are set to allow only authorised(logged in) users to access db , and neither you're logged in, nor the login/signup option is available for logging in. That's why you should always check the console.
> > I'm outstation,but will soon change rule temporarily till a solution is implemented , and inform you

Ok

**Comment by narayan954** [comment]
@Rishav1707 I've pushed some changes and it should work now. Pull the changes.

**Comment by dostonnabotov** [comment]
Hi, @narayan954! If the issue hasn't been resolved, I would be happy to pick it up and fix it. I think setting only `min-height` on the posts will be sufficient enough to allow it grow. But, having `max-height` would cause overflows since you can tell how lengthy the posts can be. 

By the way, website isn't loading just like in @Rishav1707 case. I think, we could implement a welcome page for users who haven't logged in, perhaps.

**Comment by narayan954** [comment]
> Hi, @narayan954! If the issue hasn't been resolved, I would be happy to pick it up and fix it. I think setting only `min-height` on the posts will be sufficient enough to allow it grow. But, having `max-height` would cause overflows since you can tell how lengthy the posts can be. 
> 
> By the way, website isn't loading just like in @Rishav1707 case. I think, we could implement a welcome page for users who haven't logged in, perhaps. 

Hi @dostonnabotov @Rishav1707 is working on it , though you're right about the props , I recalled that images need to be cropped to make the max-height prop work and that seems not feasible right now as there's no crop functionality for users, so min-height should do. 

About loading issue, website is working now , you might need to refresh after signing in.
Welcome/login page was also assigned but no progress as of now.

**Comment by AgnishaDe** [comment]
I want to work on this issue under JWOC

**Comment by narayan954** [comment]
Sure, go ahead @AgnishaDe :)

**Comment by narayan954** [comment]
@AgnishaDe are you still working on this?

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
You can work on this issue

**Comment by Hritik1503** [comment]
Sir I can't display any post so please tell me what your main file I will send you screenshot to display on my screen
![Screenshot (15)](https://user-images.githubusercontent.com/67685634/221333398-0172192f-17a8-4f3b-a8ec-2729217d2ede.png)

**Comment by rhithesh** [comment]
please assign it to me as I am working on it.

**Comment by narayan954** [comment]
> please assign it to me as I am working on it.

Hi @rhithesh please mention how're you planning to solve this issue so I can confirm you understand the issue :)

**Comment by rhithesh** [comment]
In post.jsx there is a class for each part of the post like header, text ,and container, I have went inside  Imageslider and made the height a constant. I understood the Read more component seems to be not working properly so I am working on that. Also I guess we need to handle a case when thee is only a caption. thanks @narayan954

**Comment by narayan954** [comment]
> In post.jsx there is a class for each part of the post like header, text ,and container, I have went inside ImageSlider.jsx and made the height a constant. I understood the Read more component seems to be not working properly so I am working on that. Also I guess we need to handle a case when there is only a caption. thanks @narayan954

That's good Hithesh but did you check if making height a constant affecting the feed in a negative way, like some post images are being cropped out incorrectly or not?
Thanks for spotting other issues as well, you may create separate issues for them and get yourself assigned to them :)

Thank you

**Comment by narayan954** [comment]
I went through issue #59 I think that'd help with this issue as well
