### ISSUE TITLE
fix white space on mobile view and z axis of theme switcher

### ISSUE THREAD

**Issue by kshitij01042002** [narayan954/dummygram#146]
### Description

fixing white space on mobile view and z axis of theme switcher

### Steps to reproduce

View in mobile view

### Screenshots

![image](https://user-images.githubusercontent.com/77617189/216044411-a8e41c2a-94df-4a1c-8091-a702b2395140.png)

**Comment by narayan954** [comment]
also fix the dark theme button inside instead of that extra space

**Comment by kshitij01042002** [comment]
Sorry I didn't get what you want? like where eaxctly do you want that button?

**Comment by narayan954** [comment]
![image](https://user-images.githubusercontent.com/77617189/209648205-4bd7e1b0-fd3d-48e2-b376-627ff18bc732.png)
Mobile view should be like above image, instead of
![image](https://user-images.githubusercontent.com/77617189/209648340-b416342d-478a-4318-bad2-08db4f4c4020.png)
That's what I meant

**Comment by narayan954** [comment]
that overflow was disturbing but need to fix other components as well which get disturbed by that prop

**Comment by kshitij01042002** [comment]
![image](https://user-images.githubusercontent.com/91470808/209717756-7a097261-d880-4df3-880e-dc579f1f3fab.png)


Issue is not with the darkmode toggle button but with the mobile view which we can't really debug without actually using a mobile phone

**Comment by kshitij01042002** [comment]
@narayan954 can you assign me this issue under kwoc?

**Comment by narayan954** [comment]
> ![image](https://user-images.githubusercontent.com/91470808/209717756-7a097261-d880-4df3-880e-dc579f1f3fab.png)
> 
> Issue is not with the darkmode toggle button but with the mobile view which we can't really debug without actually using a mobile phone

actually, we can, you don't need a phone, it's not some android application but a web application and we can use media queries to customize the viewport and check the view in Phones through developer tools in browsers

**Comment by anshuman-com** [comment]
I can fix this issue can you please assign it to me under iwoc

**Comment by anshuman-com** [comment]
this fix is unnecessary its already working all right in mobile view

**Comment by narayan954** [comment]
> this fix is unnecessary its already working all right in mobile view

Yeah actually, the fix was done, but there're two issues , z axis of dark mode button and extra white space on right in mobile view, when you move to the right side.
image for your reference, we can update this issue with this problem or create a new issue
![extra blank space](https://user-images.githubusercontent.com/77617189/216044411-a8e41c2a-94df-4a1c-8091-a702b2395140.png)

**Comment by anshuman-com** [comment]
we can create a new issue , can you please tell where you have written code of  and themeswitch button , three dot button also i didn't get your second issue as their 
![Screenshot (8)](https://user-images.githubusercontent.com/42698592/216066185-ed0181fe-f0fc-49a9-96af-e1ce983b1a9f.png)
is equal space on left and right in mobile view.

**Comment by anshuman-com** [comment]
there is one more issue themeswitch button gets hidden under an image.

https://user-images.githubusercontent.com/42698592/216067626-f7e42040-c194-48cb-a5cb-41dc747ea2f4.mp4

**Comment by anshuman-com** [comment]
theme switch button doesn't work when it is on image or 3 dot button

https://user-images.githubusercontent.com/42698592/216068696-47872296-81ab-4b48-a2bc-7b5326144a3f.mp4

**Comment by narayan954** [comment]
> we can create a new issue , can you please tell where you have written code of and themeswitch button , three dot button also i didn't get your second issue as their ![Screenshot (8)](https://user-images.githubusercontent.com/42698592/216066185-ed0181fe-f0fc-49a9-96af-e1ce983b1a9f.png) is equal space on left and right in mobile view.

sure, we can. Try moving right by clicking and holding the screen.

**Comment by narayan954** [comment]
> there is one more issue themeswitch button gets hidden under an image.
> 
>  issues.mp4

that'd what i meant by z axis

**Comment by narayan954** [comment]
> theme switch button doesn't work when it is on image or 3 dot button
> 
>  issue1.mp4

well yes, because it's under that element

**Comment by narayan954** [comment]
> > we can create a new issue , can you please tell where you have written code of and themeswitch button , three dot button also i didn't get your second issue as their ![Screenshot (8)](https://user-images.githubusercontent.com/42698592/216066185-ed0181fe-f0fc-49a9-96af-e1ce983b1a9f.png) is equal space on left and right in mobile view.
> 
> sure, we can. Try moving right by clicking and holding the screen.





> > we can create a new issue , can you please tell where you have written code of and themeswitch button , three dot button also i didn't get your second issue as their ![Screenshot (8)](https://user-images.githubusercontent.com/42698592/216066185-ed0181fe-f0fc-49a9-96af-e1ce983b1a9f.png) is equal space on left and right in mobile view.
> 
> sure, we can. Try moving right by clicking and holding the screen.

https://user-images.githubusercontent.com/77617189/216112022-e0b0e534-f67f-4ec0-924e-e3dc7b28ae4a.mp4

**Comment by narayan954** [comment]
I have updated this issue only to address the problem

**Comment by TheXro** [comment]
@narayan954 i want to work on this can you please assign it to me under iwoc

**Comment by narayan954** [comment]
> @narayan954 i want to work on this can you please assign it to me under iwoc

sure go ahead! :)
