### ISSUE TITLE
Addition : Issue Templates

### ISSUE THREAD

**Issue by IAmTamal** [narayan954/dummygram#15]
## What i am suggesting to add ? 

Since it is an actual product, I am suggesting to add **Issue Templates** to the repository, it can be as many categories as needed - primary categories of issues are mostly : `bugs`, `docs`, `general feature` and so on.

## Why to add it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to add a new idea, organize the repository properly !
 - We can know if someone wants to write a test or maybe fix something in the website
 - Here's a general idea : 
 
![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

## Am i able to develop it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by narayan954** [comment]
Thanks for raising the issue, I'll assign you right away :)
