### ISSUE TITLE
[FEATURE] User Story feature

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#152]
### Description

Users can create and publish their stories and it should be accessible for 24 hours and then get deleted. Currently there's no public or private profile ,so just normal story should be fine.
Also, stories should consist of images only. 

### Additional information

Advance to this issue could be the ability to put posts as story, text-based stories(just like the posts), and many more

**Comment by Biswajit-Behera** [comment]
Could I work on this issue??

**Comment by Biswajit-Behera** [comment]
> Under which program are you participating? @Biswajit-Behera

Under JWOC-2023

**Comment by Biswajit-Behera** [comment]
I am a Mantee in this program.

**Comment by narayan954** [comment]
Sorry @Biswajit-Behera but coding period hasn't started yet. Please go through and follow the program guidelines.

**Comment by Biswajit-Behera** [comment]
> Sorry @Biswajit-Behera but coding period hasn't started yet. Please go through and follow the program guidelines.

Ok will comment on 15th of Feb-2023!

**Comment by TuhinBanerjee31** [comment]
Can I get assigned to this issue under JWOC ?

**Comment by narayan954** [comment]
> Can I get assigned to this issue under JWOC ?

sure, go ahead!

**Comment by narayan954** [comment]
are you still working on this? please update

**Comment by Bharadwajshivam28** [comment]
@narayan954  Hello please assign it to me , its not under any event i just want to fix it so please assign to me

**Comment by narayan954** [comment]
> @narayan954 Hello please assign it to me , its not under any event i just want to fix it so please assign to me

thank you! you can work on this. Feel free to connect in case there's anything I can help with. :)

**Comment by Bharadwajshivam28** [comment]
> > @narayan954 Hello please assign it to me , its not under any event i just want to fix it so please assign to me
> 
> thank you! you can work on this. Feel free to connect in case there's anything I can help with. :)


Thanks alot sir...

**Comment by dhruv8433** [comment]
I would like to work on this issue under GSSOC 23

**Comment by narayan954** [comment]
> I would like to work on this issue under GSSOC 23

sure go ahead!

**Comment by dhruv8433** [comment]
@narayan954 Thank You

**Comment by dhruv8433** [comment]
@narayan954  I am created a story section which have backdrop and valid till 24 hours

https://github.com/narayan954/dummygram/assets/114583978/bb67f2b5-56c7-4359-8f18-a35e34fb315a

if you want any other changes, tell me

**Comment by narayan954** [comment]
> @narayan954 I am created a story section which have backdrop and valid till 24 hours
> 
>  story-dummygram.mp4 
> if you want any other changes, tell me

Hi Dhruv, in stories we can have pictures/text status or both. Also let them be scroll-able like you see in Instagram. Avatar should contain the users profile picture for now.

**Comment by dhruv8433** [comment]
Sorry it's difficult for me...

**Comment by narayan954** [comment]
> Sorry it's difficult for me...

Ohhh, it's alright, I understand its difficult... don't take much stress, what can you do out of them?

**Comment by dhruv8433** [comment]
I'm created a add to story button but when user added their story it's overlap on posts

**Comment by narayan954** [comment]
> I'm created a add to story button but when user added their story it's overlap on posts

isn't that a problem display property: fixed can solve? or if you want to, create a different route to show stories, like perhaps instagram does.

**Comment by dhruv8433** [comment]
Ok, i will try

**Comment by dhruv8433** [comment]
@narayan954  
![image](https://github.com/narayan954/dummygram/assets/114583978/bb8dfee5-05f1-4a5c-97e6-b33713477b39)
i am created a add button on which user can add image and text. when user click on avatar, user see their story and on story click user see next user's story(same as instagram), but when i refresh page, it doesn't apper please suggest me something for that... how can i store it?

**Comment by narayan954** [comment]
> @narayan954 ![image](https://user-images.githubusercontent.com/114583978/242017780-bb8dfee5-05f1-4a5c-97e6-b33713477b39.png) i am created a add button on which user can add image and text. when user click on avatar, user see their story and on story click user see next user's story(same as instagram), but when i refresh page, it doesn't apper please suggest me something for that... how can i store it?

you'll need to store them in database. Just like posts are stored in database, you can create a stories collection and this segment of our website will be rendered from that storage. Adding a story will store that story on database and it should remain in memory for 24 hours or till a user will delete them.

**Comment by narayan954** [comment]
you may leave the 24 hours functionality for now

**Comment by dhruv8433** [comment]
Ok

**Comment by Palakkgoyal** [comment]
Hey @narayan954 Can I work on this?

**Comment by narayan954** [comment]
Go ahead!

**Comment by Palakkgoyal** [comment]
Let's try if there is any other way.

**Comment by narayan954** [comment]
> Let's try if there is any other way.

right, I'll check as well. Else, we would've to store em all and show the last 24 hours story and delete older stories manually or as a cron job XD

**Comment by Palakkgoyal** [comment]
No, we will not need to do any such task 😂. I have basically set up a structure for it. Let me tell you, User can add only one story at this point of time(we can work on it later), then, we will store the timestamp of story in user doc. Whenever the profile page get opened we will check whether its been more than 24 hours or not using the timestamp in user doc(This way we will not need to fetch data seperately for story) and if the story is older than 24 hours then we will run a function to delete it from the story collection. 
When someone click on user avatar to watch story then, if the story exists then only it get fetched from the server else not.
Downside: If noone visits user profile then, the story will remain there but I think it will not impact any user experience or server performance.
What do you think?

**Comment by Palakkgoyal** [comment]
> 

No worries rather I thank you cause you told so many issues to me. Now, I will go and create issues for all of them and send PR XD.

**Comment by narayan954** [comment]
> > 
> 
> No worries rather I thank you cause you told so many issues to me. Now, I will go and create issues for all of them and send PR XD.

lol nice
