### ISSUE TITLE
[DOCS] Flow of Control 

### ISSUE THREAD

**Issue by A91y** [narayan954/dummygram#153]
### Description

A **Flow of Control** need to be added in Readme to make user understand how to use the website and various functionalities of it.

**Comment by A91y** [comment]
Please assign me this issue under iwoc

**Comment by narayan954** [comment]
> Please assign me this issue under iwoc 

sure go ahead :)

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me .

**Comment by A91y** [comment]
@PARASnagpal99 I am already working on this issue and halfway done.

**Comment by Code1705** [comment]
@narayan954 , please assign me this issue under JWOC , i will be happy enough to contribute.

**Comment by narayan954** [comment]
@PARASnagpal99 and @Code1705 , it's assigned to @A91y under IWOC. Also, @PARASnagpal99 you're already assigned an issue.
