### ISSUE TITLE
[DOCS] Updating CONTRIBUTING.md

### ISSUE THREAD

**Issue by A91y** [narayan954/dummygram#154]
### Description

Few mistakes are found in CONTRIBUTING.md and need to be fixed.

### Additional information

Broken links and invalid md syntax is present in this file.

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by narayan954** [comment]
> Please assign me this issue under iwoc and easy/medium/hard.

sure go ahead, thanks

**Comment by Biswajit-Behera** [comment]
Could I work on this issue??

**Comment by A91y** [comment]
I am already working on this issue and halfway done.

**Comment by Biswajit-Behera** [comment]
> I am already working on this issue and halfway done.

Ok 👍
