### ISSUE TITLE
Footer of website

### ISSUE THREAD

**Issue by KrunalGupta02** [narayan954/dummygram#155]
### Description

To improve the ui i think website have its own footer

**Comment by KrunalGupta02** [comment]
Yes i will work on this issue kindly assign me

**Comment by narayan954** [comment]
> ### Description
> 
> To improve the ui i think website have its own footer 
> 
> ### Screenshots
> 
> _No response_
> 
> ### Additional information
> 
> _No response_

this is a duplicate issue, please find the original issue.
