### ISSUE TITLE
[Feature] Post Delete 

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#16]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to delete our old posts , but we are currently unable to do that here ( Unless I delete it from the dB) 

**Describe the solution you'd like**
We can implement the delete functionality for the posts (But only those which were posted by the user)

**Additional context**
It could be a prop passed to the card component of posts and rendered only with the eligible posts. Clicking on the button removes that post with its key/id.

**Comment by varun7singh** [comment]
Can i work on this?

**Comment by narayan954** [comment]
yes you can :)
