### ISSUE TITLE
Fix Firebase Hosting 

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#163]
### Description

With PR #110 Deployment to GitHub Pages was implemented successfully but that broke the deployment to firebase. 
Can someone help fix this issue such that project would get deployed properly to both?
You can create a clone and test there. You might need to create a firebase project to test hosting on firebase though and github pages is handled by the extension. Though base URL might need a change for that.

### Steps to reproduce

Anytime a deployment is pushed either by github action or manually.

### Additional information

One workaround is to remove firebase deployment completely and create a separate branch for this, but that might not help in the long run and we'd implement an actual fix.

**Comment by VaibhavTalkhande** [comment]
Can I work on it under JWOC

**Comment by narayan954** [comment]
> Can I work on it under JWOC 

sure, go ahead

**Comment by narayan954** [comment]
@VaibhavTalkhande are you working on this?

**Comment by VaibhavTalkhande** [comment]
I have tried to resolve issues but not successful.you can assign issue to other person

**Comment by narayan954** [comment]
> I have tried to resolve issues but not successful.you can assign issue to other person 

okay thanks for trying, by the way ,what do you think seems the issue? base url?

**Comment by singhalaman23** [comment]
Hi @narayan954 , please assign this issue to me under JWOC if it doesn't get resolved by the current assignee.

**Comment by narayan954** [comment]
You can work on this Aman! :)

**Comment by singhalaman23** [comment]
Hi @narayan954 ... are you talking about this error ? It is coming when trying to sign up using google authentication.
If yes, then will I need to ask your firebase account details to resolve it or do I have to create a new project in my own firebase dashboard and resolve it there ?
![image](https://user-images.githubusercontent.com/99071072/221391535-70bbe985-6671-491b-85eb-7b7f28a5ab06.png)

**Comment by narayan954** [comment]
> Hi @narayan954 ... are you talking about this error ? It is coming when trying to sign up using google authentication. If yes, then will I need to ask your firebase account details to resolve it or do I have to create a new project in my own firebase dashboard and resolve it there ? ![image](https://user-images.githubusercontent.com/99071072/221391535-70bbe985-6671-491b-85eb-7b7f28a5ab06.png)

nope, that's not related to the issue. Issue is with the hosting. You can check the main branch in which firebase hosting is working alright because of the base URL and other tiny configurations.But in this branch, firebase hosting isn't working simaltaneously with github pages hosting

**Comment by narayan954** [comment]
I wanted to find a workaround so both of them can work simaltaneously

**Comment by singhalaman23** [comment]
Sorry @narayan954 , due to some urgent college work, i will not be able to work on this issue currently. Please assign it to someone else.

**Comment by narayan954** [comment]
its okay @singhalaman23 , I'm happy you tried!

**Comment by narayan954** [comment]
i'm putting this as a later task.
