### ISSUE TITLE
Enhancing the sign up and sign in button

### ISSUE THREAD

**Issue by ritika728** [narayan954/dummygram#166]
### What would you like to share?

Hey, I would like to open this issue under JWOC. I wish to add hovering effect to the sign up and sign in buttons so that they look something like this:

https://user-images.githubusercontent.com/91181981/219144360-ccccd59b-b48f-4824-b0a4-6877f93ab61c.mp4

**Comment by OliWongDev** [comment]
Hi there!
I'd love to help assist with this issue if possible :)
Oli

**Comment by narayan954** [comment]
Great you can go ahead! :)
