### ISSUE TITLE
UI Change : Making a new Signup and Signin popup

### ISSUE THREAD

**Issue by 1010varun** [narayan954/dummygram#172]
### What would you like to share?

The Signup and Sign in Modals are not beautiful. Making new modals for them.

**Comment by 1010varun** [comment]
@narayan954 kindly assign this issue to me and label this issue under iwoc along with the difficulty rating.

**Comment by narayan954** [comment]
Hi @1010varun you can work on this :)
Do share some screenshots with the PR

**Comment by 1010varun** [comment]
@narayan954 can you please change the difficulty of this issue, from easy to medium.

**Comment by narayan954** [comment]
sure :)
