### ISSUE TITLE
[FEATURE] Previewing the user profile picture

### ISSUE THREAD

**Issue by 1010varun** [narayan954/dummygram#175]
### Description

User will be able to see and view the profile picture that he/she will upload.

**Comment by 1010varun** [comment]
@narayan954 assign this issue to me and label this with iwoc and difficulty rating.

**Comment by narayan954** [comment]
@1010varun comment under issue #59 only , don't create duplicate issues.

**Comment by narayan954** [comment]
sorry I misread, it's about the profile pic while signing up

**Comment by narayan954** [comment]
You changed the issue and that's not good, you shouldn't practice that. I'll have to decrease the difficulty rating according to the current issue.
