### ISSUE TITLE
Implement Google, Facebook and Twitter auth using firebase

### ISSUE THREAD

**Issue by MahirMahdi** [narayan954/dummygram#176]
### Description

It'll make the user experience of sign up and signin better.

**Comment by MahirMahdi** [comment]
Yes I would like to work on this issue.

**Comment by narayan954** [comment]
Great! go ahead and please confirm the program , jwoc?

**Comment by aashi01kh** [comment]
I want to work on this under JWOC

**Comment by narayan954** [comment]
> I want to work on this under JWOC

@MahirMahdi are you working on this? if not, please confirm so @aashi01kh can work on this issue :)

**Comment by MahirMahdi** [comment]
I'm working on this issue

**Comment by MahirMahdi** [comment]
I'm working on it

**Comment by MahirMahdi** [comment]
@narayan954 enable google as a sign in method in the firebase console. The pop up's not working because of that. Let me know when your're done 
😀

**Comment by narayan954** [comment]
> @narayan954 enable google as a sign in method in the firebase console. The pop up's not working because of that. Let me know when your're done grinning

Yeah sure, thanks for the reminder!

**Comment by narayan954** [comment]
I have enabled the google sign in method, and about those twitter and facebook login, they'd need some configurations/api keys . Should I enable them and what else would you require ? :)
Thanks

**Comment by MahirMahdi** [comment]
Enable both twitter and facebook. I'll test those using my credentials and create an environmental variable for each credential.
While redeploying you can just update it with your credentials. Let me know if it's okay.😀

**Comment by MahirMahdi** [comment]
@narayan954 Also please let me know if the localhost url is whitelisted in the oAuth page or not.

**Comment by narayan954** [comment]
okay i'll lyk

**Comment by narayan954** [comment]
> @narayan954 Also please let me know if the localhost url is whitelisted in the oAuth page or not. If not then whitelist it kindly, in the only domain section : "http://localhost:3000" and in the url section : "http://localhost:3000/dummygram".

localhost is already in the authorised domain, is there something else to do?

**Comment by narayan954** [comment]
> @narayan954 Also please let me know if the localhost url is whitelisted in the oAuth page or not. If not then whitelist it kindly, in the only domain section : "http://localhost:3000" and in the url section : "http://localhost:3000/dummygram".

localhost is already in the authorized domain, is there something else to do?

**Comment by MahirMahdi** [comment]
@narayan954 Sorry to bother you. Pop-ups and redirects were blocked in my browser.

**Comment by narayan954** [comment]
> @narayan954 Sorry to bother you. Pop-ups and redirects were blocked in my browser. It's working now. I'm gonna work on facebook and twitter now.
> 
> Oh yes another thing, when you enable facebook and twitter oAuth, you'll have to add credentials. Let me know when you're done.smiley

cool, it's okay, I'm happy to help and learn

**Comment by narayan954** [comment]
> @narayan954 Sorry to bother you. Pop-ups and redirects were blocked in my browser. It's working now. I'm gonna work on facebook and twitter now.
> 
> Oh yes another thing, when you enable facebook and twitter oAuth, you'll have to add credentials. Let me know when you're done.smiley

I have enabled facebook oAuth, but I don't think we need too many oAuths , two should do, and I think they can be facebook and google.
I enabled the redirect URI for facebook as https://narayan954.github.io/dummygram/auth/handler

**Comment by MahirMahdi** [comment]
@narayan954 Yes google and facebook are fine. I have implemented both of them and they work fine. I'm gonna make a PR now. 😃

**Comment by narayan954** [comment]
Thanks! will look into asap.
