### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by Code1705** [narayan954/dummygram#177]
### Description

Project maintainer and new features to ve added on point is Missing and contribution guidelines could be made attractive and point wise

**Comment by Code1705** [comment]
Definately I want to contribute please assign me under Jwoc with the label.

**Comment by narayan954** [comment]
Issue is great, but you can only work at one issue at a time, so you may have to finish the other issue first before you can be assigned this issue.

**Comment by Code1705** [comment]
Ok ,got your point.

**Comment by neokd** [comment]
I would like to work on this issue

**Comment by narayan954** [comment]
> I would like to work on this issue

you can go ahead! @neokd , sorry @Code1705 but you're assigned another issue

**Comment by neokd** [comment]
is there any format for it ?

**Comment by narayan954** [comment]
> is there any format for it, or specific changes that u want to be made?

well actually not really,as It's not my idea. I was just gonna accept his suggestions :), maybe you both can put your ideas on this.

**Comment by neokd** [comment]
Sure

**Comment by neokd** [comment]
@Code1705 , can you give some suggestion

**Comment by neokd** [comment]
Hey sorry, I couldn't work on this issue. I would like to unassign it

**Comment by narayan954** [comment]
@neokd cool, it's ok! 
@Code1705 would you like to work on this?

**Comment by Code1705** [comment]
@narayan954 definitely I would like to work.

**Comment by narayan954** [comment]
Good, you can work on this!
