### ISSUE TITLE
Use Vite

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#18]
**Is your feature request related to a problem? Please describe.**
The app was created using create-react-app, which is great, but there are so many dependency errors.
PS: This issue is related to #2

**Describe the solution you'd like**
Use [vite](https://vitejs.dev/) instead, which is super fast and has great dx

**Describe alternatives you've considered**
[NONE]

**Additional context**
[NONE]

**Comment by narayan954** [comment]
I don't have any idea about vite.js right now. Would you like to work on this?

**Comment by mathiasayivor** [comment]
> I don't have any idea about vite.js right now. Would you like to work on this?

Sure... Would work on when available

**Comment by narayan954** [comment]
Thanks!!, should I assign it to you or keep it open??

**Comment by mathiasayivor** [comment]
Sure
