### ISSUE TITLE
Fix scroll to top button

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#180]
### Description

Scroll to top button is not visible clearly in dark mode, it can be fixed to be visible in dark mode

**Comment by arjunchoudhury07** [comment]
i want to contribute

**Comment by Rubyseher** [comment]
I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

**Comment by narayan954** [comment]
> i want to contribute

you can work on this!

**Comment by narayan954** [comment]
> I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

arjun claimed the issue earlier, you can claim in case he's unable to solve the issue
