### ISSUE TITLE
Improve dark mode

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#182]
### Description

Current implementation of dark mode is incorrect, it just inverts the color of some part of the page and not according to react. We can remove the vanilla implementation and provide a correct react implementation of the dark mode, which includes all parts of the page.

### Steps to reproduce

clicking on the dark mode toggle and checking the codebase shows this.

**Comment by codemaniac-sahil** [comment]
@narayan954, I would like to work on this issue. Would you please assign this issue to me.

**Comment by arjunchoudhury07** [comment]
I want to contribute under JWOC

**Comment by narayan954** [comment]
Go ahead! best of luck!

**Comment by narayan954** [comment]
are you still working on this? please update

**Comment by arjunchoudhury07** [comment]
I am unable to solve this issue, Sorry.

**Comment by sarkartanmay393** [comment]
@narayan954 I would like to give it a try under JWOC

**Comment by narayan954** [comment]
> @narayan954 I would like to give it a try under JWOC

great, you can go ahead!
