### ISSUE TITLE
[DOC] Readme file UPDATE

### ISSUE THREAD

**Issue by Suryansh1720001** [narayan954/dummygram#183]
### Description

Hello @narayan954  

**Is your feature request related to a problem? Please describe.**
### Features that I want to add in README File

- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in readme file

**Describe the solution you'd like**

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by Suryansh1720001** [comment]
Hello @narayan954 
Kindly add the IWOC label instead of JWOC.
I wanted to work on this issue under IWOC Event.

**Comment by narayan954** [comment]
> Hello @narayan954 Kindly add the IWOC label instead of JWOC. I wanted to work on this issue under **IWOC Event**.

corrected!
