### ISSUE TITLE
[UI change] new post modal does not look good 

### ISSUE THREAD

**Issue by 1010varun** [narayan954/dummygram#191]
### What would you like to share?

The current design of the new post-modal is not looking good. The goal of the issue is to make a new modal.

@narayan954 please assign this issue to me, I have coded this issue as you will assign this to me I will make a pr.

**Comment by 1010varun** [comment]
@narayan954 please assign this to me and mark this under iwoc along with the difficulty rating

**Comment by 1010varun** [comment]
@narayan954 please assign this to me now as I have completed this and then I will make the pr of other issue.

**Comment by narayan954** [comment]
> @narayan954 please assign this to me now as I have completed this and then I will make the pr of other issue.

okay, there you go!
