### ISSUE TITLE
Logout confirmation dialogue

### ISSUE THREAD

**Issue by MahirMahdi** [narayan954/dummygram#193]
### Description

Instead of an alert, a dialogue would be better for UI.

**Comment by 1010varun** [comment]
@narayan954,

I am interested in working on this issue. Could you please assign it to me?

Thank you.

**Comment by narayan954** [comment]
> @narayan954,
> 
> I am interested in working on this issue. Could you please assign it to me?
> 
> Thank you.

you're already assigned an issue, Varun. Please work on that first :)

**Comment by 1010varun** [comment]
@narayan954,

I have completed the previously assigned issue. Could you please assign me the next issue to work on?

Also, I would appreciate it if you could increase the difficulty of this task as I will be creating a completely new modal.

Thank you.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
> @narayan954,
> 
> I have completed the previously assigned issue. Could you please assign me the next issue to work on?
> 
> Also, I would appreciate it if you could increase the difficulty of this task as I will be creating a completely new modal.
> 
> Thank you.

medium is a good difficulty for this issue.

**Comment by 1010varun** [comment]
@narayan954 please assign this issue to me.

Thank You

**Comment by narayan954** [comment]
> @narayan954 please assign this issue to me.
> 
> Thank You

Yes after earlier issue is resolved... it's still pending and having error as I'm reviewing it.

**Comment by 1010varun** [comment]
@narayan954 now can you please assign this issue to me

**Comment by narayan954** [comment]
> @narayan954 now can you please assign this issue to me
Go on but create a separate branch this time.

**Comment by 1010varun** [comment]
> > @narayan954 now can you please assign this issue to me
> 
> Go on but create a separate branch this time.

okay
