### ISSUE TITLE
security vulnerabilities in dependencies.

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#2]
This project has some potential security vulnerabilities in dependencies.
Can anyone please help me solve them.
Thank you.

**Comment by mathiasayivor** [comment]
@narayan954 Apparently, material-ui v4 is not compatible with react 18. We'd have to upgrade to mui v5 and even after upgrading to v5, we can't use `makeStyles` since it only supports react 17.

**Comment by narayan954** [comment]
Ohh, that's a real issue :( . So what can we do , find alternative/workaround to `makeStyles` ?

**Comment by narayan954** [comment]
I'll look into as well
