### ISSUE TITLE
[UI Update] Login, sinup buttons are not good

### ISSUE THREAD

**Issue by 1010varun** [narayan954/dummygram#203]
### What would you like to share?

The login and signup buttons are not looking good, the aim of this issue is to make these buttons more attractive than they present.

![image](https://user-images.githubusercontent.com/104075461/221343167-19903a08-94d6-4aee-9052-ea1d562c4dbb.png)

**Comment by 1010varun** [comment]
@narayan954 please assign this issue to me.

**Comment by narayan954** [comment]
Great go ahead!

**Comment by 1010varun** [comment]
@narayan954 sir please increase the difficulty of this task. 
Thank you

**Comment by narayan954** [comment]
> @narayan954 sir can you please increase the difficulty of this task to medium.
> 
> Thank you

Hi Varun,
current difficulty is fine enough.

**Comment by 1010varun** [comment]
@narayan954 please review and merge my pr #207 

Thank You
