### ISSUE TITLE
Add an animated Landing Page to the website

### ISSUE THREAD

**Issue by AK-shat-JAIN** [narayan954/dummygram#206]
### Description

The landing page looks very normal
Want to add an animation effect in it such that the text "Dummygram" will animate and come like in this website
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

**Comment by AK-shat-JAIN** [comment]
Yes I want to work under this

**Comment by narayan954** [comment]
wow that's really good Akshat! you can apply that here as well, we'll be very grateful!

**Comment by narayan954** [comment]
can you confirm, the program selected in label is correct?

**Comment by AK-shat-JAIN** [comment]
Yes I am under Jwoc

**Comment by AK-shat-JAIN** [comment]
> wow that's really good Akshat! you can apply that here as well, we'll be very grateful! and you'll add this as the loader right?

I will add three new pages landing.html, landing.css and landing.js then 
this animate for about 4 seconds and then redirects to index or home page

**Comment by AK-shat-JAIN** [comment]
Please assign issue to me then I further Resolve the issue 
I decided this background and font 
Please confirm will it?

![image](https://user-images.githubusercontent.com/84455686/221395562-bf7a3b2c-be31-465e-8d9b-c5a342443230.png)

**Comment by narayan954** [comment]
> > wow that's really good Akshat! you can apply that here as well, we'll be very grateful! and you'll add this as the loader right?
> 
> I will add three new pages landing.html, landing.css and landing.js then this animate for about 4 seconds and then redirects to index or home page

I was thinking,maybe instead of the loader that arrives when opening the webapp, we can put this dummygram logo / animation. Else with your approach, you'll have to add a mediator component between the webapp and client. And even with that component, the website will still have to load for a few second, fetching from the API.

**Comment by narayan954** [comment]
and sorry I forgot to assign you, you're free to suggest and work on it!

**Comment by narayan954** [comment]
> > wow that's really good Akshat! you can apply that here as well, we'll be very grateful! and you'll add this as the loader right?
> 
> I will add three new pages landing.html, landing.css and landing.js then this animate for about 4 seconds and then redirects to index or home page

it's a single page application. So it shouldn't actually work that way.

**Comment by narayan954** [comment]
> Please assign issue to me then I further Resolve the issue I decided this background and font Please confirm will it?
> 
> ![image](https://user-images.githubusercontent.com/84455686/221395562-bf7a3b2c-be31-465e-8d9b-c5a342443230.png)

looks good to me!

**Comment by AK-shat-JAIN** [comment]
Hello @narayan954 Sr 
please review my PR

**Comment by narayan954** [comment]
> Hello @narayan954 Sr please review my PR

I have upgraded the difficulty label!
