### ISSUE TITLE
Login Page need beter look

### ISSUE THREAD

**Issue by suman-tewary** [narayan954/dummygram#226]
### Description

The login page need beter look
https://narayan954.github.io/dummygram/login

### Screenshots

![image](https://user-images.githubusercontent.com/43510749/222441607-b368825c-0a5d-4ada-a623-64a0dddf1585.png)

**Comment by narayan954** [comment]
Yes @suman-tewary you're correct. How'd you like to improve it? Also, would you be working on both login and signup page or only login page for now?

**Comment by Aarav238** [comment]
@narayan954  hey i will add a new form with  great styling or i will done this using material-ui/chakra-ui for enhancing it . Please assign this to me under jwoc .

**Comment by narayan954** [comment]
> @narayan954 hey i will add a new form with great styling or i will done this using material-ui/chakra-ui for enhancing it . Please assign this to me under jwoc .

that's good, but @suman-tewary has already claimed the issue. If she doesn't reply before tonight, you can claim the issue.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by suman-tewary** [comment]
> Yes @suman-tewary you're correct. How'd you like to improve it? Also, would you be working on both login and signup page or only login page for now?

It would be better to create another issue for the signup page.
Please assign both of the issues and I will fix them by today.

**Comment by narayan954** [comment]
> > Yes @suman-tewary you're correct. How'd you like to improve it? Also, would you be working on both login and signup page or only login page for now?
> 
> It would be better to create another issue for the signup page. Please assign both of the issues and I will fix them by today.

okay, but you can only be assigned on one issue at a time, so after completing this issue, you can open other issue and get assigned.

**Comment by suman-tewary** [comment]
> > > Yes @suman-tewary you're correct. How'd you like to improve it? Also, would you be working on both login and signup page or only login page for now?
> > 
> > 
> > It would be better to create another issue for the signup page. Please assign both of the issues and I will fix them by today.
> 
> okay, but you can only be assigned on one issue at a time, so after completing this issue, you can open other issue and get assigned.

ok, do it

**Comment by narayan954** [comment]
> > > > Yes @suman-tewary you're correct. How'd you like to improve it? Also, would you be working on both login and signup page or only login page for now?
> > > 
> > > 
> > > It would be better to create another issue for the signup page. Please assign both of the issues and I will fix them by today.
> > 
> > 
> > okay, but you can only be assigned on one issue at a time, so after completing this issue, you can open other issue and get assigned.
> 
> ok, do it

you're assigned already, is there anything else?
