### ISSUE TITLE
Scroll to top button not at center

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#229]
### Description

As the title says, scroll to top button is not placed at bottom center of the screen but deviating slightly right.

### Steps to reproduce

scroll down a bit and you can see the button

### Screenshots

![image](https://user-images.githubusercontent.com/77617189/222879238-0a022754-46a0-4815-a120-527578870d80.png)

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by narayan954** [comment]
> I want to work on this issue under JWOC

great, you can go ahead!
