### ISSUE TITLE
[DOCS] Add Testing info in readme

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#235]
### Description

We can add Information about cypress and setting up testing environment for the latest addition of test cases in the project.
Also we can add info about adding more test cases and provide reference document for the same in case someone wants to test the project.

### Additional information

This could get big, so include only the necessary info in readme and separate more info in separate markdown

**Comment by sarkartanmay393** [comment]
Let me take care of it @narayan954, under JWOC.

**Comment by narayan954** [comment]
> Let me take care of it @narayan954, under JWOC.

it's all yours.
