### ISSUE TITLE
[FEATURE] Pull Request Template

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#238]
### Description

we may create pull request template for the pull requests to be in proper format and informative

some example templates can be seen in [article](https://axolo.co/blog/p/part-3-github-pull-request-template)

It should include at least screenshot, program name, issue solved, changes made.

**Comment by Laxmankohar** [comment]
Hey @narayan954 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by narayan954** [comment]
> Hey @narayan954 , I would like to work on this issue under JWOC. Can you please assign it to me?

sure,you can go ahead!

**Comment by Laxmankohar** [comment]
@narayan954 , Can you please check it and confirm

![image](https://user-images.githubusercontent.com/73365025/223031095-55509e00-6e3a-44b7-b9ce-f3fcad6f58d6.png)

**Comment by narayan954** [comment]
> @narayan954 , Can you please check it and confirm
> 
> ![image](https://user-images.githubusercontent.com/73365025/223031095-55509e00-6e3a-44b7-b9ce-f3fcad6f58d6.png)
> 

looks great!

**Comment by Laxmankohar** [comment]
Can i make PR?

**Comment by narayan954** [comment]
> Can i make PR?

sure , go ahead!

**Comment by narayan954** [comment]
> Should i put pr template inside .github folder or outside folder?

inside the .github folder
