### ISSUE TITLE
[FEATURE] Dynamic route for Posts

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#245]
### Description

Posts should be accesible with a parametrized route for example `dummygram/posts/:id`
React Router is already available in the components, so it can be implemented by it's route.You might need to modify the post component as well.

### Additional information

This feature is very useful and will be helpful in implementing future features such as saving posts, sharing posts, either as a link or message.

**Comment by Laxmankohar** [comment]
@narayan954 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by narayan954** [comment]
> @narayan954 , I would like to work on this issue under JWOC. Can you please assign it to me?

great! go ahead

**Comment by Laxmankohar** [comment]
@narayan954 bro, i am getting this error, could you please help me to resolve it?

![image](https://user-images.githubusercontent.com/73365025/223556082-f951f2f1-713e-45b6-885a-95c4a93fd18a.png)

**Comment by narayan954** [comment]
some post might have a null username, try to handle that case

**Comment by narayan954** [comment]
@Laxmankohar are you working on this? :)

**Comment by Laxmankohar** [comment]
https://user-images.githubusercontent.com/73365025/225015359-b39adad2-5a12-4c1c-aba9-3ab7ccec69fd.mp4

**Comment by ugpec79** [comment]
@narayan954  hope you are doing good, can i work on this issue

**Comment by TusharUtane07** [comment]
@narayan954 I would like to work on this issue under GSSoC 2023
