### ISSUE TITLE
[FEATURE] Enable posting without images

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#25]
### Description

Currently, users **must** upload an image when posting. Which is not a good UX.
It would be great to enable users post without uploading an image

**Comment by partik03** [comment]
I have added this functionality ,kindly review my pr

**Comment by narayan954** [comment]
> I have added this functionality ,kindly review my pr

Kindly follow a pattern or you'll get tagged as spam

**Comment by narayan954** [comment]
@partik03 bro, @mathiasayivor is the author of this issue, if he doesn't want to work on that , then you can. Or you can find bugs and raise a issue by yourself as well.

**Comment by mathiasayivor** [comment]
@narayan954 you can assign this to @partik03 since he's already created a pr.

**Comment by narayan954** [comment]
okay sure , @partik03 you have a green light!

**Comment by partik03** [comment]
@narayan954 @mathiasayivor I really apologize as this issue was opened and no one was assigned so I thought I could work on it.
@narayan954 I have already added my pr kindly review it.

**Comment by narayan954** [comment]
@partik03 its ok , even though no one was assigned , you could've dropped a message and then the pr. 
I commented on that PR , please check it.
