### ISSUE TITLE
[FEATURE] Enable uploading multiple images

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#26]
### Description

Currently, users are only able to upload one image at a time. It would be great to enable users to upload multiple images in the same post.

**Comment by narayan954** [comment]
Yeah , that'd be great, adding to this ,uploading menu could be sticky to the window.
Would you like to work on this or should others try?

**Comment by mathiasayivor** [comment]
Yh. I was even gonna create a new issue for making new post menu sticky

**Comment by narayan954** [comment]
Thanks for the help!

**Comment by mathiasayivor** [comment]
Can I work on this?

**Comment by narayan954** [comment]
Yeah ofcourse
