### ISSUE TITLE
UI improvement for login sign up page

### ISSUE THREAD

**Issue by 007aneesh** [narayan954/dummygram#265]
### Description

UI of login Sign up page is not soothing or eye catching. Work on UX design

**Comment by 007aneesh** [comment]
> > ### Description
> > UI of login Sign up page is not soothing or eye catching. Work on UX design
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> Hi Aneesh, I've to go through the program guidelines once before I take action on this issue, like tags, timeline, assignment etc.
> 
> Meanwhile can you elaborate, how'd you like to improve the design? You may also provide screenshots.
> 
> Regards

As you can see there's nothing on the login or signup page it's just white background and also login card is also too clean. I like to add some design to it.

**Comment by narayan954** [comment]
> > > ### Description
> > > UI of login Sign up page is not soothing or eye catching. Work on UX design
> > > ### Screenshots
> > > _No response_
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Hi Aneesh, I've to go through the program guidelines once before I take action on this issue, like tags, timeline, assignment etc.
> > Meanwhile can you elaborate, how'd you like to improve the design? You may also provide screenshots.
> > Regards
> 
> As you can see there's nothing on the login or signup page it's just white background and also login card is also too clean. I like to add some design to it.

Sure go ahead!

**Comment by narayan954** [comment]
> i would like to work on this issue to improve ui of login page can you please assign me this

Sorry Khushi, this one's taken as well. You may try other ones which are not commented upon

Regards

**Comment by dontwike** [comment]
Assign me this issue

**Comment by 007aneesh** [comment]
> Assign me this issue

I am working on it @dontwike
