### ISSUE TITLE
Login via google and facebook is not working

### ISSUE THREAD

**Issue by TusharUtane07** [narayan954/dummygram#266]
### Description

I would like to contribute to this bug under GSSoC 2023, If we try to login with google and facebook these doesn't work so I can fix this please assign me these issue.

### Steps to reproduce

I can fix these from firebase authorization tab.

**Comment by TusharUtane07** [comment]
Yes, I would like to work on these issue under GSSoC-2023

**Comment by dkvaja** [comment]
Hello, I have 2+ yoe in React.JS with Firebase. I can fix this issue. Please assign me this issue. Thanks

**Comment by narayan954** [comment]
@TusharUtane07 Hi there, thanks a lot for raising the issue. Actually after migration of app from firebase hosting to github pages, the trusted domains were not added and they caused this error of google sign in. I've added the domains and project should work fine. If issue still exists, or you find more errors feel free to address them and I'd be happy to assign.

Thank you.
