### ISSUE TITLE
 UI Improvement for "new post" section

### ISSUE THREAD

**Issue by dhrumishah** [narayan954/dummygram#267]
### What would you like to share?

The "Caption" text should be more visible and "upload" button is not eye catching.
Can I work on this?

![image](https://github.com/narayan954/dummygram/assets/84569241/2fe4978e-3333-41c1-bd7c-5245a6c79dfb)

**Comment by AbhishekPSingh07** [comment]
Can I work on this issue

**Comment by AbhishekPSingh07** [comment]
I am a GSSoC'23 Contributor

**Comment by narayan954** [comment]
> ### What would you like to share?
> The "Caption" text should be more visible and "upload" button is not eye catching. Can I work on this?
> 
> ![image](https://user-images.githubusercontent.com/84569241/239665553-2fe4978e-3333-41c1-bd7c-5245a6c79dfb.png)
> 
> ### Additional information
> _No response_

You can work on this :) . Also, please provide screenshot for both dark and light mode in the PR.

Regards

**Comment by narayan954** [comment]
> Can I work on this issue

Sorry Abhishek but this issue has been claimed already :(. But you might claim it if it becomes unattended :)

Regards
