### ISSUE TITLE
fire base config issue

### ISSUE THREAD

**Issue by rhithesh** [narayan954/dummygram#268]
### Description

not able to start the app in local server.

### Steps to reproduce

try running the app as per docs

**Comment by rhithesh** [comment]
yes I would

**Comment by narayan954** [comment]
Hi there, Can you be more precise where you're facing issues? You may provide screenshots, error log, etc so we may confirm the issue or help you with it :)

Regards

**Comment by rhithesh** [comment]
error sorry was mistake from my side.

thanks sorry again.

**Comment by narayan954** [comment]
It's fine, you're free to raise issues. :)
