### ISSUE TITLE
User Profile Feature

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#269]
### Description

After login, I am not able to show my profile. So, I would add a user profile page and update the user data feature.

Please assign this task to me under GSSOC 23. I would love to work on that.

**Comment by SubhamB2003** [comment]
Yes please assign it to me under GSSOC 23.

**Comment by narayan954** [comment]
Hi there this issue is a duplicate to #49 . Please check current issues before creating new issues. You may get yourself assigned over there :)

Regards

**Comment by narayan954** [comment]
Also, please allow some time before things get cleared about the mentors, point allocation and other guidelines before any review.

Thanks
