### ISSUE TITLE
Logo is rendering to a blank page at this route "https://narayan954.github.io/dummygram/login"

### ISSUE THREAD

**Issue by Sathvik902** [narayan954/dummygram#271]
### Description

If the user is at login and signup page, and still not signed in, Clicking on the Logo will navigate him to the blank page. That shouldn't happen.

### Steps to reproduce

Making the link inactive if the user has not logged in yet.

### Screenshots

**At this page,**

![image](https://github.com/narayan954/dummygram/assets/92165565/15ba3610-29f5-4ade-9547-494bab121462)

**When you click on the Logo, It will navigate to a blank page,**

![image](https://github.com/narayan954/dummygram/assets/92165565/19efd559-f103-4147-8145-278d5f7a7ba5)

@narayansoni I would like to contribute to the issue as a part of @GSSOC'23. Thank you.

**Comment by narayan954** [comment]
This is a good bug @Sathvik902 , thanks for raising it. You can work on this :)

**Comment by Sathvik902** [comment]
Please add gssoc tag to the issue, as I am contributing under it.
Thank you.
