### ISSUE TITLE
[FEATURE] Improving UI of the home page

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#272]
### Description

Hey @narayan954 I want to improve the UI of the home page. Please assign me this issue. Thank you!

**Comment by sumitkr2000** [comment]
I wish to work on this issue.

**Comment by narayan954** [comment]
Hi @sumitkr2000 , sure you can work on this. Also please provide screenshots of the improvement/changes you'll make in the PR or here.

**Comment by sumitkr2000** [comment]
Yeah sure!
