### ISSUE TITLE
Bug Text overflow which is given in caption

### ISSUE THREAD

**Issue by Shubham185y** [narayan954/dummygram#273]
### Description

I can very well work on this please assign this to me so that i can strt working on this

### Steps to reproduce

I'll give it a perfect place like instagram does by playing with some properties like overflow and i can get it done ASAP!

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100077254/43ed06e2-3afb-4d2d-94a3-a1e8ba3883fc)

### Desktop (please complete the following information)

Chrome , Windows

**Comment by Shubham185y** [comment]
> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Yes i have mentioned it , assign this to me

**Comment by narayan954** [comment]
Sure go ahead!
