### ISSUE TITLE
[UI Improvement] Improving navbar

### ISSUE THREAD

**Issue by mahekkg** [narayan954/dummygram#278]
### What would you like to share?

Title: Improve Navbar Design with Minimalist Approach

Description:
The current navbar design could benefit from an update to align with modern design trends and enhance the user experience. By adopting a minimalist design approach, we can achieve a cleaner and more streamlined navigation system.
Minimalist design focuses on simplicity, clarity, and removing unnecessary elements, resulting in a visually appealing and user-friendly interface. 
Please assign this task to me if you agree it will benefit our project under GSSoC'23. Excited to contribute!

Thank you 
Mahek Goswami

**Comment by mahekkg** [comment]
Yes I would like to work on this issue

**Comment by narayan954** [comment]
> ### What would you like to share?
> Title: Improve Navbar Design with Minimalist Approach
> 
> Description: The current navbar design could benefit from an update to align with modern design trends and enhance the user experience. By adopting a minimalist design approach, we can achieve a cleaner and more streamlined navigation system. Minimalist design focuses on simplicity, clarity, and removing unnecessary elements, resulting in a visually appealing and user-friendly interface. Please assign this task to me if you agree it will benefit our project under GSSoC'23. Excited to contribute!
> 
> Thank you Mahek Goswami
> 
> ### Additional information
> _No response_

Hi there @mahekkg , thanks for elaborating the issue beautifully. Yes, sure the project can definitely benefit with this improvement! You can work on this! :)

Thank you!

**Comment by mahekkg** [comment]
Thank you , I will promptly work on it
