### ISSUE TITLE
 Misaligned Comments in Social Media Post {GSSOC'23} 

### ISSUE THREAD

**Issue by Tahsin-Zaman-Jilan** [narayan954/dummygram#280]
### Description

Within our social media application, we have identified an issue with the alignment of comments in a post. Currently, comments appear misaligned, causing visual inconsistency and readability problems for users. This issue needs to be addressed to ensure a consistent and user-friendly experience.

Can you assign me this issue?

### Steps to reproduce

Log in to the social media application and navigate to a post with multiple comments.
Scroll through the comments section and observe the alignment of the comments.
Note the misalignment of comments, where they appear shifted or out of place.

### Screenshots

![Capture11111](https://github.com/narayan954/dummygram/assets/77837621/f0f156f3-c973-4a87-9deb-a387f8a04041)

**Comment by narayan954** [comment]
> ### Description
> Within our social media application, we have identified an issue with the alignment of comments in a post. Currently, comments appear misaligned, causing visual inconsistency and readability problems for users. This issue needs to be addressed to ensure a consistent and user-friendly experience.
> 
> Can you assign me this issue?
> 
> ### Steps to reproduce
> Log in to the social media application and navigate to a post with multiple comments. Scroll through the comments section and observe the alignment of the comments. Note the misalignment of comments, where they appear shifted or out of place.
> 
> ### Screenshots
> ![Capture11111](https://user-images.githubusercontent.com/77837621/239729178-f0f156f3-c973-4a87-9deb-a387f8a04041.PNG)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi @Tahsin-Zaman-Jilan thanks for raising the issue and describing it clearly. Yeah sure you can work on it!
You can go ahead!

Thank you!
