### ISSUE TITLE
[FEATURE] display dates on posts

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#282]
### Description

Currently posts don't have much details, we can add details like post time (for recent posts it should be like 1 hr ago, 1 min ago and for older posts it should be a date)

### Additional information

Posts already have this data with them, you just have to extract and utilise them

**Comment by Kalyan-velu** [comment]
I would be happy to work on implementing this solution. Please let me know if you agree and if there are any specific requirements or considerations I should keep in mind while making these changes.

Looking forward to contributing to this issue and improving the post details!

**Comment by narayan954** [comment]
> I would be happy to work on implementing this solution. Please let me know if you agree and if there are any specific requirements or considerations I should keep in mind while making these changes.
> 
> Looking forward to contributing to this issue and improving the post details!

go ahead!
