### ISSUE TITLE
[FEATURE] Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [narayan954/dummygram#283]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by M-A-N-I-K** [comment]
i would like to work on this issue myself!

**Comment by narayan954** [comment]
Hi Manik, thanks for describing the issue nicely. Just so you know, pagination and lazy loading already exists in the application at some places like loading posts and posts with multiple images, respectively. So on which areas would you like to implement lazy loading? 
You can work on this :)

**Comment by sumitkr2000** [comment]
@narayan954 It seems that he is not active. It's been 1 month now. Can you please assign me this issue? I can work on this issue. Thank you!
