### ISSUE TITLE
option for delete & edit  post 

### ISSUE THREAD

**Issue by warisamir** [narayan954/dummygram#284]
### Description

![image](https://github.com/narayan954/dummygram/assets/77074869/6bbf18af-72f2-4637-8dc8-074626f96436)
while clicking on the options menu it is not opening 
i think that page is not written yet 
i would like to add that page with crud menu please assing me under Gssoc' 23

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77074869/c327e356-f2ce-4c49-b375-8404c41ba651)
![image](https://github.com/narayan954/dummygram/assets/77074869/772ce88c-372c-47b7-abfb-bd8331001077)

### Additional information

please seee if it a network or if it is a bug then please assign it to me

**Comment by narayan954** [comment]
Hi there, only delete option exists for now, but even that is available to post owner only. If you created a post then only you can delete it. I think that's working fine. Can you provide more information to what other options you'd like to implement? Editing caption issue has already been created, delete feature is available.

**Comment by dhawansolanki** [comment]
@narayan954 As per my review You are right but not 100%. 
Currently it is like if you are the admin of that post than the 3 dots option will be activated which means when you click on it Delete option will be available. But if its others post than you will be able to see that 3 dots options but nothing will work on that click. @warisamir So you can make changes as you can hide that option when you are not that admin of that post.

I would like to work on this issue. Pls  assign me with this task under GSSOC 23.

**Comment by narayan954** [comment]
> @narayan954 As per my review You are right but not 100%. 
> Currently it is like if you are the admin of that post than the 3 dots option will be activated which means when you click on it Delete option will be available. But if its others post than you will be able to see that 3 dots options but nothing will work on that click. @warisamir So you can make changes as you can hide that option when you are not that admin of that post.
> 
> I would like to work on this issue. Pls  assign me with this task under GSSOC 23.
> 

Yes you're right as you're thinking just about edit and delete post option or to simply say current scenario of the application.
But if we think of app's future, then there may be feature to report post, mute user,hide post,etc. Even though the former feature (report) doesn't seem to be feasible latter features could be implemented to the app. Then we shall need these menu options. 
So it's a subjective choice and we can pick any of those options(to show or not to show)

Or we can add these options as placeholder and they would be available to non post owners post implementation.

What do you think of this?

**Comment by dhawansolanki** [comment]
> > @narayan954 As per my review You are right but not 100%.
> > Currently it is like if you are the admin of that post than the 3 dots option will be activated which means when you click on it Delete option will be available. But if its others post than you will be able to see that 3 dots options but nothing will work on that click. @warisamir So you can make changes as you can hide that option when you are not that admin of that post.
> > I would like to work on this issue. Pls  assign me with this task under GSSOC 23.
> 
> Yes you're right as you're thinking just about edit and delete post option or to simply say current scenario of the application. But if we think of app's future, then there may be feature to report post, mute/unfollow user,hide post,etc. Even though the former feature (report) doesn't seem to be feasible latter features could be implemented to the app. Then we shall need these menu options. So it's a subjective choice and we can pick any of those options(to show or not to show)
> 
> Or we can add these options as placeholder and they would be available to non post owners post implementation.
> 
> What do you think of this?


I do agree with your point but Currently we dont have any options. so if users click on this options for other admin post than it will not work which will not be a positive sign for User Experience. Another thing I can Suggest we can keep Share Button Inside that. So Both the scenarious will work and in future updates other options can be added to. what do you think of this?

**Comment by narayan954** [comment]
> > > @narayan954 As per my review You are right but not 100%.
> > > Currently it is like if you are the admin of that post than the 3 dots option will be activated which means when you click on it Delete option will be available. But if its others post than you will be able to see that 3 dots options but nothing will work on that click. @warisamir So you can make changes as you can hide that option when you are not that admin of that post.
> > > I would like to work on this issue. Pls  assign me with this task under GSSOC 23.
> > 
> > Yes you're right as you're thinking just about edit and delete post option or to simply say current scenario of the application. But if we think of app's future, then there may be feature to report post, mute/unfollow user,hide post,etc. Even though the former feature (report) doesn't seem to be feasible latter features could be implemented to the app. Then we shall need these menu options. So it's a subjective choice and we can pick any of those options(to show or not to show)
> > 
> > Or we can add these options as placeholder and they would be available to non post owners post implementation.
> > 
> > What do you think of this?
> 
> 
> I do agree with your point but Currently we dont have any options. so if users click on this options for other admin post than it will not work which will not be a positive sign for User Experience. Another thing I can Suggest we can keep Share Button Inside that. So Both the scenarious will work and in future updates other options can be added to. what do you think of this?

That works :) But here's one issue that who'd be assigned on this? The issue owner who came first or you? If @warisamir wants to work on this,  he is eligible right? as he pointed this issue.

**Comment by dhawansolanki** [comment]
Anything Works! @warisamir would like me to collaborate than sounds good anyways No issues for me. Happy to resolve errors.

**Comment by narayan954** [comment]
@dhawansolanki  you took another issue of warisamir and you're not supposed to work on multiple issues. Warisamir can take this issue and work on it

**Comment by dhawansolanki** [comment]
> @dhawansolanki you took another issue of warisamir and you're not supposed to work on multiple issues. Warisamir can take this issue and work on it

Cool.. No issues but in the previous Issue he just provided with issue So i worked on that. Anyways Pls Review that too. Thanks

**Comment by narayan954** [comment]
> > @dhawansolanki you took another issue of warisamir and you're not supposed to work on multiple issues. Warisamir can take this issue and work on it
> 
> Cool.. No issues but in the previous Issue he just provided with issue So i worked on that. Anyways Pls Review that too. Thanks

Yes you're right about that. Will review asap.

**Comment by narayan954** [comment]
@warisamir would you like to work on this or can I assign @dhawansolanki

**Comment by warisamir** [comment]
Facing some problem hope so resolve till today evening

**Comment by narayan954** [comment]
> Facing some problem hope so resolve till today evening

oh okay
