### ISSUE TITLE
improving the design of the new post button and the form.

### ISSUE THREAD

**Issue by JatinBisht2308** [narayan954/dummygram#285]
### Description

I will make a symmetric design that is easy to understand by the user which enhances the UX of the website and also add a clean style so that the user would be friendly to adding the new post.

### Steps to reproduce

Basics steps using css and clean colors.

### Additional information

@narayan954 sir you said to make a separate issue regarding the design of the new post section.
Please assign this issue to me under gssoc23.
Thank you, sir.

**Comment by JatinBisht2308** [comment]
Thank you sir @narayan954

**Comment by narayan954** [comment]
> Thank you sir @narayan954

It's okay, feel free to ask if you face any issues.

Regards
