### ISSUE TITLE
[DOCS] add back to top button

### ISSUE THREAD

**Issue by S-ishita** [narayan954/dummygram#286]
### Description

I want to add back to top button in readme file which will enhance user experience.

### Additional information

Please assign this issue to me under GSSOC

**Comment by S-ishita** [comment]
PLease assign this issue to me

**Comment by narayan954** [comment]
Hi @S-ishita , Yes that should enhance the user experience, you can work on this issue. Meanwhile, I was thinking we may have scroll to top button at checkpoints (like end of sections). If you feel that's right you may implement that, else it's fine whatever you wish.

**Comment by S-ishita** [comment]
> Hi @S-ishita , Yes that should enhance the user experience, you can work on this issue. Meanwhile, I was thinking we may have scroll to top button at checkpoints (like end of sections). If you feel that's right you may implement that, else it's fine whatever you wish.

At other points it wont look nice i guess..I have raised the pr kindly check it out if you want it after every section...

**Comment by narayan954** [comment]
> > Hi @S-ishita , Yes that should enhance the user experience, you can work on this issue. Meanwhile, I was thinking we may have scroll to top button at checkpoints (like end of sections). If you feel that's right you may implement that, else it's fine whatever you wish.
> 
> At other points it wont look nice i guess..I have raised the pr kindly check it out if you want it after every section...

it's alright then!
