### ISSUE TITLE
add logout icon in logout button.

### ISSUE THREAD

**Issue by Aarav238** [narayan954/dummygram#288]
### Description

I will add logout icon from react-icons in the logout button which will look more attractive.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/95538627/435b5be8-b17e-4e4c-9ed1-4c9864373d35)

**Comment by narayan954** [comment]
this issue is overlapping with the user profile issue, so I'll have to hold this one for now, though you can contribute on the other one

Thank you :)

**Comment by narayan954** [comment]
> @narayan954 can i work on this issue now ?

This issue is outdated now I believe

**Comment by dontwike** [comment]
Assign me this issue and also i have already made the pull request for this issue
