### ISSUE TITLE
likes and comment box down side of the comment bar 

### ISSUE THREAD

**Issue by warisamir** [narayan954/dummygram#292]
### Description

![image](https://github.com/narayan954/dummygram/assets/77074869/365e4f62-be53-4586-aa7d-855a5b2a766e)
in that way it would little attractive and ui become more pleasant 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77074869/78174a41-f3cf-4371-b93f-ce008ee4c13a)

**Comment by dhawansolanki** [comment]
Also Please Assign this task under GSSOC 23 . Thanks
