### ISSUE TITLE
[FEATURE] <Double-Tap Like feature >

### ISSUE THREAD

**Issue by Shubham185y** [narayan954/dummygram#293]
### Description

Double-Tap like feature as the Instagram. 
I can make that assign this to me.

**Comment by narayan954** [comment]
Sure go ahead!

**Comment by Deepanshu0703** [comment]
@narayan954  double tap like is working with images but not with text posts

**Comment by narayan954** [comment]
> @narayan954 double tap like is working with images but not with text posts

Right, you can work on this!
