### ISSUE TITLE
Change Background color of comment box 

### ISSUE THREAD

**Issue by aadityadike** [narayan954/dummygram#294]
### I see that comment box is not so good with designing part, I can make it better with changing the style & background color.

- I will make comment box more attractive than before.
![Screenshot from 2023-05-22 18-34-12](https://github.com/narayan954/dummygram/assets/117139914/636d0069-2796-4a69-ad2d-36fa38bb23a3)

**Comment by aadityadike** [comment]
yeah, i want to work on this issue, can you please assign to me and also add the gssoc23 label

**Comment by narayan954** [comment]
sure go ahead!
