### ISSUE TITLE
[FEATURE] <Ask for confirmation while deleting a comment>

### ISSUE THREAD

**Issue by aadityadike** [narayan954/dummygram#295]
### Ask for confirmation while deleting a comment

1. I will make a pop up that will ask user whether they want to delete the comment or not after pressing the delete button.
2. Here, The actual problem is what if the user mistakenly press the delete icon. since its not asking for confirmation the comment will get deleted. 

### Additional 
I want to work on this issue, can you please assign to me and also add the gssoc23 label.

**Comment by dhruv8433** [comment]
I would like to work on this issue
