### ISSUE TITLE
Want to improve the  New Post section [OTHER]

### ISSUE THREAD

**Issue by HimanshuNarware** [narayan954/dummygram#297]
### What would you like to share?

I want to improve the new post section  UI to improve the user experience
![Screenshot 2023-05-22 200352](https://github.com/narayan954/dummygram/assets/83147410/890940d6-4040-42d6-b122-3fe9952b8b00)

**Comment by narayan954** [comment]
you're already assigned an issue, please fix that first!

**Comment by narayan954** [comment]
what'd you change in this section?

**Comment by HimanshuNarware** [comment]
> you're already assigned an issue so you can not be assigned before completing that @HimanshuNarware .

ok

**Comment by HimanshuNarware** [comment]
> what'd you change in this section?

Want  to improve the UI of this section
