### ISSUE TITLE
Want to inhance the  color  of the background of the website [FEATURE] <description>

### ISSUE THREAD

**Issue by HimanshuNarware** [narayan954/dummygram#298]
### Description

I want to give more user-friendly colors to the background which are not ruin the user eyes, currently website color is too dark and too white, so I want to improve the background color of the  website which can improve the  user experience

### Screenshots

![color](https://github.com/narayan954/dummygram/assets/83147410/9f2de74b-dc1d-4b86-bf81-66a29b8a7104)
![colro 2](https://github.com/narayan954/dummygram/assets/83147410/133d1fdf-0e00-41ca-9c54-7fcd442cfce3)

**Comment by narayan954** [comment]
Right, try grey for dark background and cooler white(or your choice) for the light background. You can work on this
