### ISSUE TITLE
Home page is not responsive in mobile device

### ISSUE THREAD

**Issue by crocmons** [narayan954/dummygram#306]
### Description

Posts are not responsive in smaller devices we have to make it responsive ..Can you assign this issue to me under GSSOC'23?

### Steps to reproduce

make it responsive

### Screenshots

![Screenshot (329)](https://github.com/narayan954/dummygram/assets/106610322/08dae71f-eced-425d-84d7-fd1a0c985030)

**Comment by narayan954** [comment]
Yes sure you can go ahead!
