### ISSUE TITLE
In the Posts Text appear in the full screen

### ISSUE THREAD

**Issue by crocmons** [narayan954/dummygram#307]
### Description

Text appear in the screen

### Steps to reproduce

remove the text

### Screenshots

![Screenshot (330)](https://github.com/narayan954/dummygram/assets/106610322/703b8a52-18bb-4824-a175-8ec482eb1060)

**Comment by narayan954** [comment]
Thanks for raising the issue but this issue was already created and recent pr #291 solved this @crocmons 
I have to close this issue.

Regards

**Comment by crocmons** [comment]
> Thanks for raising the issue but this issue was already created and recent pr #291 solved this @crocmons I have to close this issue.
> 
> Regards

yeah, it's ok.😊
