### ISSUE TITLE
[FEATURE] Adding view post user profile

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#308]
### Description

Adding an option to view the profile of different post creators by clicking their profile picture.

### Screenshots

This feature

https://github.com/narayan954/dummygram/assets/94003231/9831d72f-fff8-435a-8d83-889cf3842981

### Additional information

@narayan954  can I create the PR?

**Comment by narayan954** [comment]
> ### Description
> Adding an option to view the profile of different post creators by clicking their profile picture.
> 
> ### Screenshots
> This feature
> 
>  Profile.Viewer.mp4 
> ### Additional information
> @narayan954 can I create the PR?

Sure go ahead @SubhamB2003 :)
