### ISSUE TITLE
[FEATURE] <description> Add a  left navbar 

### ISSUE THREAD

**Issue by arjun26122002** [narayan954/dummygram#309]
### Description

Adding a left navbar for own profile information 

### Screenshots

![profile](https://github.com/narayan954/dummygram/assets/88227330/bc86c19d-0e91-4e57-bff1-6492835172cd)

### Additional information

I am the contributor of Gssoc'23 , can you assign me for this work ?

**Comment by narayan954** [comment]
@arjun26122002 can you elaborate more about what'd you do?

**Comment by narayan954** [comment]
> "/assign"

it's /assign (without quotes) but you're trying to claim his issue and that's not fair Khushi . Isssues are claimable FCFS.

**Comment by khushi767** [comment]
> > "/assign"
> 
> it's /assign (without quotes) but you're trying to claim his issue and that's not fair Khushi . Isssues are claimable FCFS.

sure ...i wasn't aware of that before

**Comment by narayan954** [comment]
> > @arjun26122002 can you elaborate more about what'd you do?
> 
> * yes, Actually I want to make a left navbar, where I show the information of the account owner, like his/her picture, LinkedIn id, address, mail id
>   ![aRJUN12345](https://user-images.githubusercontent.com/88227330/240212507-ad1092cf-e65e-4cd8-bb46-5f20b65099dc.jpg)
> 
> like this, I want to make that the information shown in the left navbar , only shows for the profile owner.

yes you can do that, but make sure to handle the case of mobile phone displays in which it might not be feasible in left.
Also won't that affect the current position of logo?

**Comment by narayan954** [comment]
> > > "/assign"
> > 
> > 
> > it's /assign (without quotes) but you're trying to claim his issue and that's not fair Khushi . Isssues are claimable FCFS.
> 
> sure ...i wasn't aware of that before

it's okay, let the early ones take their chance :)

**Comment by arjun26122002** [comment]
@narayan954 ok ok

**Comment by sumitkr2000** [comment]
@narayan954 Please assign me this issue. I can work on it. I want to make the left navbar similar to Instagram but with a different design(matching the UI of dummygram).

Screenshot:- 

![Screenshot (836)](https://github.com/narayan954/dummygram/assets/100675296/c285622f-c5ba-4b6e-8d44-26495e0f40f4)

**Comment by narayan954** [comment]
sure go ahead @sumitkr2000
