### ISSUE TITLE
[Feature] Dark Mode

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#31]
### Description

Implement Dark mode for the application to give it a better look.

### Additional information

We can have a toggle at the side for dark mode

**Comment by arthurmatthew** [comment]
Hi, I think I could work on this. Could you assign me?

**Comment by narayan954** [comment]
Sure!

**Comment by arthurmatthew** [comment]
Hey, could you link me to instructions on how to get Firebase working locally? The posts are not loading when I run my fork of the project on my computer. I am getting this error: `@firebase/firestore: Firestore (9.10.0): Uncaught Error in snapshot listener: {"code":"resource-exhausted","name":"FirebaseError"}`. Any tips?

**Comment by narayan954** [comment]
Actually we made way too many requests to firebase due to so many changes and testing etc and actually exhausted the free limit for today, so this error occured .  Don't worry , it should refresh in some hours

**Comment by arthurmatthew** [comment]
Sounds good- I'll get to work when it's back up.

**Comment by narayan954** [comment]
It should be back up by PDT 00:00hrs

**Comment by arthurmatthew** [comment]
Hi, unfortunately something came up and I will be unable to work on this project for the next couple of days. I think it's best if somebody else gets this issue assigned to them.

**Comment by narayan954** [comment]
It's Okay

**Comment by Kritika30032002** [comment]
is this still available?
May I contribute to this?

**Comment by narayan954** [comment]
> is this still available?
> May I contribute to this?

yes it's available :) , feel free to work on this!

**Comment by Kritika30032002** [comment]
> > is this still available?
> > May I contribute to this?
> 
> yes it's available :) , feel free to contribute to this!

you can assign me this

**Comment by iamwicked** [comment]
I can also work on it. Could you assign it to me?

**Comment by narayan954** [comment]
> I can also work on it. Could you assign it to me?

sorry bud, it was claimed before you :)

**Comment by narayan954** [comment]
closed in #85
