### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by shraddha761** [narayan954/dummygram#312]
### Description

Adding badges to readme makes it more attractive 

### Screenshots

![Screenshot 2023-05-21 160801](https://github.com/narayan954/dummygram/assets/106100728/5714e380-48e9-42cb-afb0-d54c66217968)

### Additional information

assign me this issue under GSSOC'23

**Comment by narayan954** [comment]
> ### Description
> Adding badges to readme makes it more attractive
> 
> ### Screenshots
> ![Screenshot 2023-05-21 160801](https://user-images.githubusercontent.com/106100728/240232547-5714e380-48e9-42cb-afb0-d54c66217968.png)
> 
> ### Additional information
> assign me this issue under GSSOC'23

Yeah they look nice and bright!
Go ahead!

Regards
