### ISSUE TITLE
[FEATURE] Changes in Profile and Create Post tab.

### ISSUE THREAD

**Issue by kriti-002** [narayan954/dummygram#313]
### Description

I think the User Profile page can be improved as far as UI is concerned. There should be an option for editing the username of the user in the User Profile page. Also, all the posts made by the user should be shown up in the Profile page.

For create post, I think a different route should be created for this purpose. Previewing the image before posting is also a good option for its improvement.

@narayan954 kindly assign this issue to me under GSSOC'23. I am pretty sure that I could work on them efficiently.

**Comment by kriti-002** [comment]
Ye

> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Yeah I want this issue to be assigned to me.

**Comment by narayan954** [comment]
> ### Description
> I think the User Profile page can be improved as far as UI is concerned. There should be an option for editing the username of the user in the User Profile page. Also, all the posts made by the user should be shown up in the Profile page.
> 
> For create post, I think a different route should be created for this purpose. Previewing the image before posting is also a good option for its improvement.
> 
> @narayan954 kindly assign this issue to me under GSSOC'23. I am pretty sure that I could work on them efficiently.

Hi Kriti, thanks for finding and raising these many issues but would you be able to work on all of these together or would you like to take them as a step, one by one? It's your call. I'm assigning you.

Thank you!

**Comment by Palakkgoyal** [comment]
Hey @kriti-002 are you working on this issue?

**Comment by Palakkgoyal** [comment]
@narayan954 I think she is busy can you please assign this to me?

**Comment by narayan954** [comment]
> @narayan954 I think she is busy can you please assign this to me?

sure

**Comment by narayan954** [comment]
> I think I should work on editing name and previewing the image before posting.

Yes you can work on editing the name or other stuff, but for previewing the image before posting, I think @Gurmeet-Singh657  is working on that in his own issue.

**Comment by Gurmeet-Singh657** [comment]
Right I am already working on this !!

**Comment by narayan954** [comment]
> Right I am already working on this !!

Thanks for confirming :)

**Comment by Palakkgoyal** [comment]
Okay. Got it.
