### ISSUE TITLE
[FEATURE] Adding gradient effect to "Upload picture" button

### ISSUE THREAD

**Issue by mukul314** [narayan954/dummygram#314]
### Description

Since the majority of the buttons on the website like the New post button, and logout button change the gradient when hovered upon, I noticed that the "Upload picture" button should also do so. So I added a little bit of CSS to change its gradient when hovered upon!!

### Screenshots

Watch the below videos for reference:

Before:

https://github.com/narayan954/dummygram/assets/76463001/d8ce8474-ef32-4408-833c-c8344145821e

Notice that no change occurs when hovered upon.

After:

https://github.com/narayan954/dummygram/assets/76463001/cce79b50-f600-43e2-91a8-6858233eec53

Now the gradient of the button is changing due to hovering.

### Additional information

@narayansoni , I'd like to work on this issue if you approve!!

**Comment by narayan954** [comment]
Sure you can fix that! 

Regards

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by narayan954** [comment]
> This issue has been inactive for a long time I would like to work on this issue Please assign

Hi @sagnik-p , sure you can go ahead. By the way heads up, a live pr is also based on improving upload post section. So keep your code updated to avoid conflicts.

**Comment by sagnik-p** [comment]
Sorry to keep you waiting.
I had my college exams
Should I proceed with this issue?
Thanks !

**Comment by narayan954** [comment]
> Sorry to keep you waiting.
> I had my college exams
> Should I proceed with this issue?
> Thanks ! 

Hi @mukul314 let's leave the issue, we'd be redesigning those parts
