### ISSUE TITLE
Clicking on logo redirects to an empty blank homescreen

### ISSUE THREAD

**Issue by Lakshyyaa** [narayan954/dummygram#316]
### Description

Once the logo is clicked when I first open the website, it redirects to the same home page but this time it is blank, the login/signup popus is not there. I request you to assign this to me under GSSOC'23 with the changes you'd like

### Steps to reproduce

 Either we can add something for the homepage to redirect to have the login popup again.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/99789174/db7f4fbd-35c5-495f-946f-f1c429e713b7)

**Comment by Lakshyyaa** [comment]
Thank you for considering my contribution! I would be happy to work on this issue. Please assign it to me, and I'll start working on a solution.

**Comment by narayan954** [comment]
Sure go ahead @Lakshyyaa  :)

regards
