### ISSUE TITLE
Clicking on Profile Icon and after that clicking on page , profile and logout bar remains as it is

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [narayan954/dummygram#318]
### Description

Hye
I found a issue Like whenever I am clicking on the profile icon and clicking anything keeps the profile and logout page remains opened like this 
Plz assign me this issue as GSSOC'23 Contributor.

![image](https://github.com/narayan954/dummygram/assets/83361657/66ee3e69-5e40-466a-8d11-a852735c4a91)

### Steps to reproduce

* Using the EventHandling Concept that whenever I click on the page anyside , it should disappear it !!

### Desktop (please complete the following information)

Windows
Chrome

**Comment by narayan954** [comment]
Yeah sure, go ahead Gurmeet! :)

Regards
