### ISSUE TITLE
Emojis box not collapsing on clicking outside the post

### ISSUE THREAD

**Issue by divyansh2212** [narayan954/dummygram#319]
### Description

Emojis box not closing on clicking outside of the post.
I want to add the feature so that **Emojis box** can collapse on clicking outside of it.

Please assign me this issue as GSSoC 2023 contributor.

### Steps to reproduce

Emoji Box is only collapsing on clicking the emoji icon. It should collapse on every click outside of it.

### Screenshots

Here is the related screenshot:
![image](https://github.com/narayan954/dummygram/assets/90034292/b64cd619-fe6a-45b6-9486-6b01f189913d)

**Comment by divyansh2212** [comment]
> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

I would like to work on this issue.

**Comment by narayan954** [comment]
great go ahead!
