### ISSUE TITLE
[FEATURE] <To add back button>

### ISSUE THREAD

**Issue by AK4266** [narayan954/dummygram#324]
### Idea
When we are on the user profile age we don't have any back button to go back to the home again

### Expected Behaviour
When clicked on the back button on the profile page, it should map back to the home page

### Additional information

I wish to work on this issue

**Comment by narayan954** [comment]
go ahead!

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by AK4266** [comment]
@bhoomikhurana this issue is already assigned. Look for other issues
