### ISSUE TITLE
[DOCS] Fix Grammar in README

### ISSUE THREAD

**Issue by Sriparno08** [narayan954/dummygram#327]
### Description

I have noticed some grammatical errors in README.

Fixes:

- `run down` -> `rundown`
- `let's` -> `lets` (In Git and GitHub description)
- `loses` -> `loss`
- Punctuation Mistakes

### Screenshots

![Screenshot 2023-05-24 155514](https://github.com/narayan954/dummygram/assets/89148144/41a7f773-d20e-4346-9d7e-689d07cc725f)

### Additional information

I would like to work on this as part of GSSoC'23.

**Comment by narayan954** [comment]
sure go ahead!
