### ISSUE TITLE
Improve UI - for cards

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#33]
### Description

Cards for post look really dull or I should say simple. We can design them better with some border/border radius etc. Align the contents to the left similar to a Instagram post

### Screenshots

<p align="center">
  <img alt="Current" src="https://user-images.githubusercontent.com/77617189/193441254-c03a0326-737a-4bce-8843-552973c8cae5.png" width="45%" height="500">
&nbsp; &nbsp; &nbsp; &nbsp;
  <img alt="Reference" src="https://user-images.githubusercontent.com/77617189/193441350-9ed741c5-f225-4d2b-80cd-14fa28b87d2d.png" width="45%" height="500">
</p>

**Comment by najeebkp** [comment]
hi @narayan954  i can take this up. please assign me

**Comment by narayan954** [comment]
sure @najeebkp
