### ISSUE TITLE
[FEATURE] Centralise the Caption , Variable Size Post Shifting Fixing , Name for Caption Should not be repeated

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [narayan954/dummygram#330]
### Description

I want to add this condition whenever user wants to add a post so he / she needs at least one image to do that.
If he/she wants to add many images, I want to implement the sliding functionality !!
Please assign me this issue as GSSOC'23 Contributor

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/83361657/6fd9de08-d813-400c-b7f5-47c22797a96f)

**Comment by Navjot4** [comment]
I also want to work with @Gurmeet-Singh657 in this issue.

**Comment by Gurmeet-Singh657** [comment]
One thing I noticed that post is shifting above whenever I upload two variable size images -> I want to fix that 
Another thing is Caption and Gradient. 
I want to fix these two things !!
Please assign me this issue as GSSOC'23 Contributor

**Comment by narayan954** [comment]
You're right @Gurmeet-Singh657 , you can work on this :)

**Comment by Gurmeet-Singh657** [comment]
Thank you so much for assigning me this issue !!

**Comment by narayan954** [comment]
> I also want to work with @Gurmeet-Singh657 in this issue.

@Gurmeet-Singh657 you may collaborate if you want. Although you both would need different prs to get the points in the leaderboard

**Comment by Gurmeet-Singh657** [comment]
Okk No Problem I will create 2 different PRs

**Comment by narayan954** [comment]
> Okk No Problem I will create 2 different PRs

I mean , if you're collaborating, then one should create pr for his contribution and other for his contribution. You don't need to create 2 prs alone, only 1 per person per issue

**Comment by narayan954** [comment]
> > Okk No Problem I will create 2 different PRs
> 
> I mean , if you're collaborating, then one should create pr for his contribution and other for his contribution. You don't need to create 2 prs alone, only 1 per person per issue

mention @Navjot4 for this info

**Comment by Gurmeet-Singh657** [comment]
I want to contribute alone @narayan954 for this issue !!

**Comment by narayan954** [comment]
> I want to contribute alone @narayan954 for this issue !!

it's okay then.
