### ISSUE TITLE
like and other buttons not visible if there's no comment

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#332]
### Description

In posts without a comment, the bottom elements are not rendered. This should not be the case. We should fix those rendering conditions.

### Steps to reproduce

comment on posts without comments, you'll see the bottom bar with likes ,comments and share  back.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77617189/c0d91967-812e-4248-a776-cd0668e9b76b)

**Comment by Gurmeet-Singh657** [comment]
I want to fix this issue . Please Assign me this issue as a GSSOC'23 Contributor

**Comment by narayan954** [comment]
> I want to fix this issue . Please Assign me this issue as a GSSOC'23 Contributor

Aren't you already working on another issue?

**Comment by Gurmeet-Singh657** [comment]
I can work on this issue as well !!

**Comment by divyansh2212** [comment]
I can work on this issue. I am done with my previous issue #319 . I am waiting for the approval of previous issue.
