### ISSUE TITLE
[Bug] When the upload button is clicked without selecting any image

### ISSUE THREAD

**Issue by Bhavik-ag** [narayan954/dummygram#34]
### Description

When the upload is clicked without selecting any image the loading continues forever. So this should be handled beforehand.

### Steps to reproduce

1) Do not select any image and just directly press the upload button.

### Screenshots

![image](https://user-images.githubusercontent.com/73033511/193441761-66ec90de-1b17-4fee-8279-caae9f343892.png)
![image](https://user-images.githubusercontent.com/73033511/193441792-2efe8f62-9400-486c-9643-b892212cd780.png)

**Comment by Bhavik-ag** [comment]
I have fixed this issue please this issue to me so that I can submit the PR.

**Comment by narayan954** [comment]
sure

**Comment by narayan954** [comment]
@Bhavik-ag pr #27 fixes this , I think this issue can be linked to that pr only.

**Comment by Bhavik-ag** [comment]
Okay 
I made the pull request so you can close it then.

**Comment by narayan954** [comment]
@Bhavik-ag You can implement this solution for the post without image feature

**Comment by narayan954** [comment]
Currently when posting with image, the upload button keeps on reloading

**Comment by Bhavik-ag** [comment]
Okay, I am working on this.

**Comment by narayan954** [comment]
thanks

**Comment by mathiasayivor** [comment]
I think #26 already addresses this issue...

**Comment by narayan954** [comment]
Ohh , It's been fixed tho :/
