### ISSUE TITLE
[FEATURE] Short post message show

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#345]
### Description

Hey, I want to add this feature.

If the post content is too long then it shows "see more..." text.

![image](https://github.com/narayan954/dummygram/assets/94003231/9d8611d4-4c52-4123-b9ca-fbd69ce47f5e)
 
After clicking see more it so whole content like this

![image](https://github.com/narayan954/dummygram/assets/94003231/876b225a-3b0c-4a7d-a6fe-d97c0349b25d)

### Additional information

Please assign it to me and another thing someone is removing the feature post user profile view that I have previously added.

![image](https://github.com/narayan954/dummygram/assets/94003231/0c1688fb-d35d-4b00-ac3d-2bce619554bb)

Removes it

![image](https://github.com/narayan954/dummygram/assets/94003231/9e8ea1d4-75eb-43b8-87c5-16ddd988163d)

**Comment by narayan954** [comment]
Hi, Shubham, doesn't that feature exist already? Please confirm. Might be because it was added recently.

**Comment by SubhamB2003** [comment]
> Hi, Shubham, doesn't that feature exist already? Please confirm. Might be because it was added recently.

Yeah, I checked it now the "read more" feature has been added.

**Comment by narayan954** [comment]
okay Shubham, thanks for raising the issue but it has been solved so I'm closing this issue
