### ISSUE TITLE
[FEATURE] UI updation of Landing Page

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [narayan954/dummygram#346]
### Description

Issue - 
1. At landing page, after just navbar the card is not having any gap(space).
2. The UI is not matching with sign up or sign in button.
3. There should be a hover effect on the Card that is present landing page.

Please assign me this issue under GSSoC '23 as a contributor. 

### Screenshots

<img width="956" alt="image" src="https://github.com/narayan954/dummygram/assets/94108574/d8604012-c175-48a9-a03d-bd4b151aa14e">
Initially, it was 

<img width="977" alt="image" src="https://github.com/narayan954/dummygram/assets/94108574/e27179d8-3c18-42d6-958f-6b3adca1b52f">
The issue are ....

### Additional information

Please assign me this issue under GSSoC '23 as a contributor.

**Comment by Rupantar-Borphukan** [comment]
> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Yes, I am interested and I want to work on the issue. Please assign me this issue

**Comment by narayan954** [comment]
right, also perhaps those sign in, sign up button at navbar don't need to exist at all, app.js have them, if you think that's correct you may remove them. that'd clean app.js a bit
