### ISSUE TITLE
[FEATURE] Text Entered by User Should be Line breaked as it is he entered 

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [narayan954/dummygram#348]
### Description

I observed that text entered by user is not coming as it is rather it is compressing . It's a backend and frontend Work that is taking the user data with line break and then sending it while fetching should be taken as it is.
I want to fix this issue.
Please assign me this issue as a GSSOC'23 Contributor.
![image](https://github.com/narayan954/dummygram/assets/83361657/b4f0838c-60aa-402b-b5d8-c6089e5a0bc4)

**Comment by Gurmeet-Singh657** [comment]
@narayan954 Waiting for this issue to be assigned to me !!

**Comment by narayan954** [comment]
goo ahead!
