### ISSUE TITLE
[FEATURE] Implement "Page Not Found" page for Incorrect URLs 

### ISSUE THREAD

**Issue by Saurav-Pant** [narayan954/dummygram#350]
### Description

when a user enters an incorrect URL, the website does not display a "Page Not Found" error page. As a GSSOC'23 contributor, I propose to create and implement the necessary error handling mechanism to ensure users are presented with a clear and informative "Page Not Found" page when encountering invalid URLs, assign it to me @narayan954.

Assigned To: @Saurav-Pant 
Labels: GSSOC'23

### Screenshots

https://github.com/narayan954/dummygram/assets/103263909/872a9744-14cd-491c-9362-500f96439a29

**Comment by narayan954** [comment]
> ### Description
> when a user enters an incorrect URL, the website does not display a "Page Not Found" error page. As a GSSOC'23 contributor, I propose to create and implement the necessary error handling mechanism to ensure users are presented with a clear and informative "Page Not Found" page when encountering invalid URLs, assign it to me @narayan954.
> 
> Assigned To: @Saurav-Pant Labels: GSSOC'23
> 
> ### Screenshots
>  DummyGram.PNF.mp4 
> ### Additional information
> _No response_

Hi @Saurav-Pant  actually the error page exists and it works but with a bug. If you enter a wrong url, you'll get to the error page but suddenly get redirected to the home page. It's due to some logic error I couldn't check. You can work on fixing this.

**Comment by Saurav-Pant** [comment]
Ok assign me , i will work on that

**Comment by narayan954** [comment]
> Ok assign me , i will work on that

right, i forgot
