### ISSUE TITLE
Improving the footer of the post.

### ISSUE THREAD

**Issue by Krishnakalani111** [narayan954/dummygram#354]
### Description

Here in the post where we can comment, it takes most of the space and the white box doesn't look good , I would like to change it and make it a simple underline where the placeholder value will be add a comment. 
I would also like to add alignment to the emoji icon , comment and Post button
@narayansoni could i work on this UI enhancement? under the gssoc.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/88764668/36d4c2e7-eaf1-43a1-9cea-d01a1128c73b)

**Comment by Krishnakalani111** [comment]
Yes I wish to work on this issue @narayan954

**Comment by narayan954** [comment]
great go ahead !

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by narayan954** [comment]
> I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

Hi @bhoomikhurana it's already assigned, you may check other issues for now or come back if it remains unsolved after 1 week

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by narayan954** [comment]
> This issue has been inactive for a long time
> I would like to work on this issue
> Please assign

yes please go ahead and I'd like to update the issue a bit... save/favorites button could be on the right.
