### ISSUE TITLE
Chat UI 

### ISSUE THREAD

**Issue by aasthaaaa7** [narayan954/dummygram#363]
### Description

I'd like to design the chat ui in figma which can be used in dummygram

**Comment by aasthaaaa7** [comment]
i wish to work on this issue

**Comment by narayan954** [comment]
Okay, you may place the Ui in assets folder under figma design or whatever you think is good :) and create a pr. 
Also, for now which chat approach do you intend to follow, would something like linkedin's chat ui work ?

**Comment by aasthaaaa7** [comment]
it would be better if we use a goofy ui ( like that of insta  ) since it's a social media app (?)

**Comment by narayan954** [comment]
> it would be better if we use a goofy ui ( like that of insta ) since it's a social media app (?)

okay makes sense.

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.I have a good knowledge of UI as well

**Comment by aasthaaaa7** [comment]
@bhoomikhurana i am working on this issue

**Comment by narayan954** [comment]
> @bhoomikhurana i am working on this issue

I think no one is :/ ,closing temporarily , will reopen if needed
