### ISSUE TITLE
Adding Profile pic

### ISSUE THREAD

**Issue by SasiVardhan247** [narayan954/dummygram#364]
### Description

As it is a Social Media Account I want to add a feature like making the user edit his profile pic.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/83742554/7da8f97a-690f-4d6e-8211-e4df60fa8d7e)

### Additional information

Having profile pic will be useful.

**Comment by SasiVardhan247** [comment]
can you assign this issue to me @narayan954 , I'm in GSSOC'23

**Comment by narayan954** [comment]
go ahead! :)
