### ISSUE TITLE
Profile button slightly out of page

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#366]
### Description

The profile button is slightly out of pages width.
![Screenshot_2023-05-27-16-07-15-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/narayan954/dummygram/assets/92094765/1d2babb9-0162-40bc-a67d-bc8ad75b05c2)

### Steps to reproduce

First login then click on profile button

**Comment by Soulpurr** [comment]
Pls assign this to me under gssoc23

**Comment by narayan954** [comment]
Go ahead!

**Comment by Soulpurr** [comment]
@narayan954 the profile button is no longer out of page as of now that's why I m not working on this🥲

**Comment by narayan954** [comment]
> @narayan954 the profile button is no longer out of page as of now that's why I m not working on thissmiling_face_with_tear

Oh alright, sorry then, it wasn't closed. Closing this
