### ISSUE TITLE
Close button missing on create new post

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#367]
### Description

After clicking create New post if we want to back there is no close button 
Pls assign this to me under gssoc23

### Steps to reproduce

Create new post 

### Screenshots

![Screenshot_2023-05-27-16-07-21-61_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/narayan954/dummygram/assets/92094765/d4b53ab9-33c1-495b-8e0b-6885dd9413c4)

**Comment by narayan954** [comment]
Yes @Soulpurr can you add a "X" close button at the top right corner?

**Comment by Soulpurr** [comment]
Ok I will add it.
Assign this to me under gssoc'23
