### ISSUE TITLE
The like button is not working properly if Someone can like post multiple times 

### ISSUE THREAD

**Issue by tajmalnas** [narayan954/dummygram#369]
### What would you like to share?

Once can like their or others post infinte times so that like feature is not making sense 
I can solve it under gssoc 23

**Comment by tajmalnas** [comment]
I want to work on this issue

**Comment by narayan954** [comment]
Hi can you elaborate the condition or steps to reproduce this issue?

**Comment by tajmalnas** [comment]
@narayan954  I can solve this issue would you please assign me this issue

**Comment by narayan954** [comment]
> @narayan954 I can solve this issue would you please assign me this issue

Show me a proof where this issue exists, I can find this issue

**Comment by tajmalnas** [comment]
Oh now it is fixed i will close my request
