### ISSUE TITLE
[FEATURE Enhancement]  Show number of comments

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#371]
### Description

- instead of `view all comments`, show something like `view all 123 comments` or `view 1 comment` in case of comments.
- in case without comment, disable the button and show something like `no comments yet`.
- in case without comment show something like `be the first one to comment` placeholder on input fields of comment.

### Additional information

Implementing all of these can get you level 3 points! (Ps: ask to update label)

**Comment by VijayalakshmiGanesh** [comment]
Hi, I would like to work on this issue. Could you please assign me this issue under GSSoC'23 label

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by narayan954** [comment]
> Hi, I would like to work on this issue. Could you please assign me this issue under GSSoC'23 label

Go ahead! :)

**Comment by narayan954** [comment]
> I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

It's already assigned, sorry

**Comment by VijayalakshmiGanesh** [comment]
Created PR https://github.com/narayan954/dummygram/pull/384. Kindly review @narayan954

**Comment by narayan954** [comment]
> Created PR #384. Kindly review @narayan954 . Also update the issue label to level-3 please

okay looking into it! Got it
