### ISSUE TITLE
SignUp form is not validated

### ISSUE THREAD

**Issue by raghavawasthi24** [narayan954/dummygram#372]
### Description

I am able to signup with the invalid email and blank username.
This will only unreal users to access your website.

### Steps to reproduce

This bug can be resolved by-
adding regex in all fields of signup page which will accept only valid entries.

### Screenshots

![Screenshot (103)](https://github.com/narayan954/dummygram/assets/113261155/57bd4604-403f-4bc4-821d-c7da0bacbc39)
![Screenshot (104)](https://github.com/narayan954/dummygram/assets/113261155/1ae43876-5267-42d2-a4ac-34c7af26d66c)

### Desktop (please complete the following information)

Windows, Crome

**Comment by raghavawasthi24** [comment]
I request you to assign me this issue in order to resolve it

**Comment by narayan954** [comment]
this is duplicate issue, closing it
