### ISSUE TITLE
[GSSoC'23] Enhancing the design of post cards.

### ISSUE THREAD

**Issue by parag477** [narayan954/dummygram#375]
### Description

I had noticed that the cards that contain the posts are not looking that much good and they are also of basic design. So I wanted to improve the styling of the cards to make them look more attractive and beautiful.

Please assign me this issue under GSSoC-2023

### Steps to reproduce

I will make a better card for the project and replace existing card from the one I will make.

### Desktop (please complete the following information)

Windows 10, Chrome

### Smartphone (please complete the following information)

Redmi Note 7 pro, Android 10

**Comment by narayan954** [comment]
@parag477 You can work on this! UI really matters! :)
