### ISSUE TITLE
[FEATURE Enhancement] Upload Camera Pics

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#376]
### Description

Users should have a option to upload pictures by camera of the device.

### Additional information

I am not sure if web and mobile version both would work! I have heard of react-webcam library, will confirm...

**Comment by khadesamrudhi** [comment]
please assign me this project.

**Comment by narayan954** [comment]
> please assign me this project.

Sure, go ahead!

**Comment by khadesamrudhi** [comment]
@narayan954 can you please review this PR?

**Comment by narayan954** [comment]
> @narayan954 can you please review this PR?

yes sure, on it
