### ISSUE TITLE
Button Updation

### ISSUE THREAD

**Issue by shraddha761** [narayan954/dummygram#377]
### Description

Delete button of comment section should be of different colour we can not easily identified the delete button easily 

### Steps to reproduce

Simply change the color of delete button

### Additional information
Assign me this issue under GSSOC'23 
_No response_

**Comment by khadesamrudhi** [comment]
Assign me this issue under GSSOC'23.

**Comment by narayan954** [comment]
> ### Description
> Delete button of comment section should be of different colour we can not easily identified the delete button easily
> 
> ### Steps to reproduce
> Simply change the color of delete button
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> Assign me this issue under GSSOC'23 _No response_

go ahead!

**Comment by narayan954** [comment]
> Assign me this issue under GSSOC'23.

claimed already :/
