### ISSUE TITLE
[FEATURE] Add status option for users

### ISSUE THREAD

**Issue by binbard** [narayan954/dummygram#379]
### Description

Every user should be able to set their status under the profile page

### Screenshots

![chrome_zqCcMUvQSK](https://github.com/narayan954/dummygram/assets/28684962/cb28bf6e-145e-4d46-8bce-0c10c3d05d49)

**Comment by narayan954** [comment]
Hi @binbard issue #351 addresses this and is in progress. So I have to close this one
