### ISSUE TITLE
[FEATURE] Improve preloader 

### ISSUE THREAD

**Issue by binbard** [narayan954/dummygram#380]
### Description

The currently used preloader for the website is not clean.
Make it elegant

### Screenshots

![chrome_nepIaeXkzI](https://github.com/narayan954/dummygram/assets/28684962/9f52ff21-94a9-4503-a689-4ff8994b2e80)

**Comment by narayan954** [comment]
Right!, go ahead!

**Comment by narayan954** [comment]
How'd you like to improve it?, also loader and this preloader have a collision
