### ISSUE TITLE
[FEATURE] Want to Completely Change the New Post Feature

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [narayan954/dummygram#383]
### Description

📌 In the New Post, I want to change the UI First where in upload post will be shown on left hand side and caption addition will be shown on right hand side
📌I want to add a Location Feature where user can add his/her Location so, whatever Location he will add will be display along with post
📌User can enable/disable commenting on his post 

Please Assign me this issue as a GSSOC'23 Contributor.

**Comment by narayan954** [comment]
- having two buttons like that won't be a good ux imo @Gurmeet-Singh657 , instead we can make the upload post button dynamic (it can be something like upload text post by default and once a user uploads a pic it can change to upload post, changes in this approach are welcomed)
- Currently we can't flood the post with too much data, it's supposed to be clean. Location doesn't seem necessary atm.
- Disabling/Enabling shall require db operations, also you'll have to handle old posts as well somehow, you are aware of this, right?

**Comment by narayan954** [comment]
> * having two buttons like that won't be a good ux imo @Gurmeet-Singh657 , instead we can make the upload post button dynamic (it can be something like upload text post by default and once a user uploads a pic it can change to upload post, changes in this approach are welcomed)
> * Currently we can't flood the post with too much data, it's supposed to be clean. Location doesn't seem necessary atm.
> * Disabling/Enabling shall require db operations, also you'll have to handle old posts as well somehow, you are aware of this, right?

We'll need to discuss the 1st point

**Comment by Gurmeet-Singh657** [comment]
For First Point, 
Case 1: When user wants to add image
Case 2: When user wants to add caption
Case 3: When user wants to add Image And Caption

I think we can provide below UI for all of these Cases & it looks really good !! 

![image](https://github.com/narayan954/dummygram/assets/83361657/85fd9620-5150-4932-b02b-212b3123f4f5)

**Comment by narayan954** [comment]
> For First Point, Case 1: When user wants to add image Case 2: When user wants to add caption Case 3: When user wants to add Image And Caption
> 
> I think we can provide below UI for all of these Cases & it looks really good !!
> 
> ![image](https://user-images.githubusercontent.com/83361657/241748251-85fd9620-5150-4932-b02b-212b3123f4f5.png)

that works, you're right!

**Comment by Gurmeet-Singh657** [comment]
Please Assign me this issue @narayan954 As a GSSOC'23 Contributor.

**Comment by narayan954** [comment]
> Amazing firePlease Assign me this issue @narayan954 As a GSSOC'23 Contributor.

Go ahead!
