### ISSUE TITLE
improve the UI of Profile section of the User

### ISSUE THREAD

**Issue by shruti8302** [narayan954/dummygram#385]
### What would you like to share?

@narayan954  As a part of GSSOC'23, I would like to improve the UI of Profile section of the User. Kindly assign this issue to me.

**Comment by narayan954** [comment]
Sure, go ahead! :)

**Comment by shruti8302** [comment]
@narayan954 Thanks

**Comment by narayan954** [comment]
it's not yet merged, don't close it. I'll link the pull request and it'll auto close

**Comment by shruti8302** [comment]
@narayan954 Okay

**Comment by narayan954** [comment]
I've labelled this issue as level 2
