### ISSUE TITLE
[OTHER] Image taking time to load

### ISSUE THREAD

**Issue by Prakriti2003** [narayan954/dummygram#386]
### What would you like to share?

The images on the website are taking time to load as they are in jpeg format. I can convert the images to webp which will take less loading time.

Kindly assign me this issue under GSSOC'23.

**Comment by Prakriti2003** [comment]
Yes kindly assign me the issue under GSSOC'23.

**Comment by narayan954** [comment]
> ### What would you like to share?
> The images on the website are taking time to load as they are in jpeg format. I can convert the images to webp which will take less loading time.
> 
> Kindly assign me this issue under GSSOC'23.
> 
> ### Additional information
> _No response_

Hi Prakreeti, how'd you approach that? Are you going to convert the existing images to webp as well??

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by narayan954** [comment]
> Please assign me this issue so that I can work on this issue under **GSSOC'23**.

go ahead!
