### ISSUE TITLE
[FEATURE] Give option to upload profile picture to users.

### ISSUE THREAD

**Issue by Prakriti2003** [narayan954/dummygram#387]
### Description

I want to add this new feature to give user option to add profile pic. 
This can be done either from:
->direct camera
->gallery
->select avatars

Please assign me this issue under GSSOC'23.

### Additional information

Also I would like to improve the overall UI of the profile section and add option to add BIO for the users.

**Comment by narayan954** [comment]
Hi @Prakriti2003  most of these issues have been raised already, I'd have to confirm profile pic edit option, but bio and Ui of profile section is under progress.

**Comment by Prakriti2003** [comment]
Ok kindly confirm and assign it to me if anyone else is not working on it. @narayan954

**Comment by narayan954** [comment]
this whole issue exists already @Prakriti2003 , the profile picture issue number is #364 .
I'd have to close this as well.

Please check the existing issues before creating a new issue next time
