### ISSUE TITLE
adding an option to download the image or view profile by clicking the three dots

### ISSUE THREAD

**Issue by Prakriti2003** [narayan954/dummygram#389]
### Description

Clicking on the three dots on others post has no action.

### Steps to reproduce

click on the three dots available on the top right corner of each posts.

### Desktop (please complete the following information)

OS - window, Linux
Browser - Firefox, Chrome, Edge, Brave

### Additional information

I can fix this bug by adding an option to download the image by clicking the three dots. Another option can be viewing the image in full screen. A third option can be to visit the person's profile who posted the image.

**Comment by narayan954** [comment]
Yes right, thanks for raising the issue.... add the option to download and visit the profile of the user. In doing so, add something like 'download image' option and an option named 'view profile' in the menu. There you can copy the current implementation of viewing the profile by clicking the profile icon (dont remove it from there tho)

**Comment by Prakriti2003** [comment]
I need access to the project on firebase to add cors.json file to it to implement the download functionality.
Please provide the acess. @narayan954

**Comment by Prakriti2003** [comment]
I  have already tried the process on the database set up on local machine and it is successfully executed.

**Comment by narayan954** [comment]
> I need access to the project on firebase to add cors.json file to it to implement the download functionality. Please provide the acess. @narayan954

sure @Prakriti2003 , share your email address

**Comment by Prakriti2003** [comment]
prakritichatterjee00@gmail.com
@narayan954

**Comment by narayan954** [comment]
> [prakritichatterjee00@gmail.com](mailto:prakritichatterjee00@gmail.com) @narayan954

I've provided editor access.
