### ISSUE TITLE
Issue with cards

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#39]
### Description

Newly implemented cards work for posts with images , but don't for post without images.

### Steps to reproduce

Make any post without images and you'll face this issue ,, where there's a default placeholder image and the actual caption might be lost.

### Screenshots

![image](https://user-images.githubusercontent.com/77617189/193444643-50ae5400-3209-4a66-864f-8cea36b5fd4f.png)

**Comment by narayan954** [comment]
@najeebkp you wanted to work on it, am I correct?

**Comment by najeebkp** [comment]
Yes. Please Assign me.
