### ISSUE TITLE
[FEATURE] - ADD CURSOR POINTER FOR EMOJI BUTTON WHILE HOVER

### ISSUE THREAD

**Issue by 0xabdulkhalid** [narayan954/dummygram#395]
### Description

- This issue is about adding `cursor: pointer` for the emoji button where the user can choose their reaction
- Without the pointer the  user can't confirm that the button is interactive
- So kindly assign me this issue under `gssoc23` for further developement

**Comment by narayan954** [comment]
go ahead! :)
