### ISSUE TITLE
[DOCS] Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [narayan954/dummygram#396]
### Description

This sentence in README:

> Yes, you might be getting the point, this application is basically a clone of the original Instagram and tends to add features like instagram or in fact the features that could not have been added in the instagram.

can be changed to:

> Yes, you might be getting the point; this application is basically a clone of the original Instagram and tends to add features that Instagram offers as well as features that are not part of this social media app.

### Screenshots

![Screenshot 2023-05-30 191212](https://github.com/narayan954/dummygram/assets/89148144/961da5c3-8e22-4e65-9a4e-8b0cd665e89c)

### Additional information

I would like to contribute as part of GSSoC'23.

**Comment by narayan954** [comment]
you can go ahead @Sriparno08 :)
