### ISSUE TITLE
i want to replace dummygram logo with new neon color logo.

### ISSUE THREAD

**Issue by mohitparmar1** [narayan954/dummygram#398]
### Description

dummygram logo rn is not looking good according to the gradient color button that we have on our website so if we add a new logo that has 
![Screenshot (60)](https://github.com/narayan954/dummygram/assets/100152343/9220f7fa-8fb8-4555-a372-aba0f8567545)
neon color.

### Screenshots

the new logo that I
![DummyGram](https://github.com/narayan954/dummygram/assets/100152343/4a3b2da6-47c7-454d-9243-ce3e4742355f)
 want to place.

**Comment by narayan954** [comment]
What do you think about light mode? would it work for light mode as well?

**Comment by mohitparmar1** [comment]
yeah! absolutely

**Comment by narayan954** [comment]
great! you may proceed :)

**Comment by Palakkgoyal** [comment]
Hey @mohitparmar1 are you working on this issue? If not then, can I take this up?

**Comment by narayan954** [comment]
> Hey @mohitparmar1 are you working on this issue? If not then, can I take this up?

You may go ahead

**Comment by mohitparmar1** [comment]
Sorry,I was busy. @Palakkgoyal you can work on this issue!

**Comment by Palakkgoyal** [comment]
Okay. Thanks @mohitparmar1

**Comment by Palakkgoyal** [comment]
![Screenshot (563)](https://github.com/narayan954/dummygram/assets/116902573/0eec6cac-387a-469d-a746-91c20329887c)
![Screenshot (564)](https://github.com/narayan954/dummygram/assets/116902573/7a5f7e09-46c1-4d59-99d4-3b7ca14ff3b9)

**Comment by Palakkgoyal** [comment]
Do you think any other changes could be done or required? @narayan954

**Comment by narayan954** [comment]
> Do you think any other changes could be done or required? @narayan954 

that looks good already! :)
