### ISSUE TITLE
[UI improvment signup and log in page]

### ISSUE THREAD

**Issue by Aliza30** [narayan954/dummygram#401]
### What would you like to share?

i want to revamp the ui of signup and login page of dummygram to make it more dynamic and responsive across all the devices

**Comment by narayan954** [comment]
Hi @Aliza30 , this issue already exists, issue #265 ... Please don't open duplicate issues. You can claim that issue if that's not worked upon.

**Comment by narayan954** [comment]
I'd have to close this one as duplicate, sorry
