### ISSUE TITLE
[FEATURE] Post Like Feature

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#41]
### Description

Can we implement a like feature for the post and see live like counts! 
It'd be great!

### Additional information

We already have the button for likes in posts , we just have to implement them!

**Comment by prateek565** [comment]
I'd like to work on it .assign it to me

**Comment by narayan954** [comment]
Sure go ahead!

**Comment by prateek565** [comment]
According to me to implement like function we have to change the db collection on firebase and add a variable likes there. ehich i cant do so if you can pls do it.

**Comment by narayan954** [comment]
You can yourself directly add a new field like caption, imageurl , i.e likecount for each new post. For older posts , yes only I can do :') . I have some cleanup to do i guess. Or you can have a condition for older post where post without likecount field wont be bothered while displaying likes

**Comment by prateek565** [comment]
hi @narayan954 i have implemented like for new posts but for old ones i cant do anything so you can delete them if you want otherwise like function doesnt work on them

**Comment by prateek565** [comment]
hi can you make this issue hacktoberfest label

**Comment by narayan954** [comment]
Yeah sure!, btw the whole repo is labelled with hacktoberfest, issue label don't matter

**Comment by narayan954** [comment]
> hi @narayan954 i have implemented like for new posts but for old ones i cant do anything so you can delete them if you want otherwise like function doesnt work on them

Yeah, I understand that, and its ok... I am planning on separating development website and production website with separate firebase projects
