### ISSUE TITLE
shift the new post button at the center position

### ISSUE THREAD

**Issue by vk20july** [narayan954/dummygram#411]
### Description

No response

### Steps to reproduce

No response

### Screenshots

![Screenshot (205)](https://github.com/narayan954/dummygram/assets/71543332/1a9ed3d0-80d8-4181-ba4e-e686d1b4cb52)

### Desktop (please complete the following information)

OS Name: Microsoft Windows 10 Home Single Language
Version: 10.0.19045 Build 19045
Browser: Opera

### Smartphone (please complete the following information)

No response

### Additional information

No response

**Comment by vk20july** [comment]
please assign me this

**Comment by narayan954** [comment]
Sure, you can go ahead. Please check for responsiveness as well... :)

Regards

**Comment by vk20july** [comment]
> Sure, you can go ahead. Please check for responsiveness as well... :)
> 
> Regards

ok sir
