### ISSUE TITLE
[FEATURE] 404 Error Page 

### ISSUE THREAD

**Issue by PatilHarshh** [narayan954/dummygram#412]
### Description

This website not contain the 404 error page please assign it to me @narayan954 @narayansoni 

### Screenshots

![Screenshot (77)](https://github.com/narayan954/dummygram/assets/120102234/7ebc403a-fce9-454f-be6e-beec4e854524)

**Comment by PatilHarshh** [comment]
Please assign me this issue @narayan954

**Comment by narayan954** [comment]
closing as duplicate
