### ISSUE TITLE
[FEATURE] Post items should be in row

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#414]
### Description

I think for larger devices post items should be in center as there is a lot of empty space on left and right.
![scrnli_02_06_2023_18-58-37](https://github.com/narayan954/dummygram/assets/92094765/01ffdd61-3a90-469b-a626-37cc9fd51843)

Please assign this to me under gssoc

### Additional information

We'll add a toggle to switch between row format and column format.

**Comment by Soulpurr** [comment]
@narayan954 yea post are in centre but they are in column format that good for mobile view but for larger devices they must be in row format
<img width="540" alt="5bsS2" src="https://github.com/narayan954/dummygram/assets/92094765/128c73d4-8e6f-4c54-bdd3-813b230cadc1">
Link this kind of for larger devices

**Comment by narayan954** [comment]
> @narayan954 yea post are in centre but they are in column format that good for mobile view but for larger devices they must be in row format <img alt="5bsS2" width="540" src="https://user-images.githubusercontent.com/92094765/242944894-128c73d4-8e6f-4c54-bdd3-813b230cadc1.png"> Link this kind of for larger devices

Okay you can go ahead!

**Comment by Soulpurr** [comment]
That also will be done by tomorrow
