### ISSUE TITLE
[FEATURE] Add a hover effect on post items.

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#415]
### Description

We should add a hover effect on post items as static card are not that great.
We can add a ease in or ease out kind of effect.

### Screenshots

![scrnli_02_06_2023_18-58-37](https://github.com/narayan954/dummygram/assets/92094765/c0b54378-09c1-4182-afb3-e33a2f7bce14)

**Comment by Soulpurr** [comment]
Pls assign this to me under gssoc23

**Comment by narayan954** [comment]
> ### Description
> We should add a hover effect on post items as static card are not that great. We can add a ease in or ease out kind of effect.
> 
> ### Screenshots
> ![scrnli_02_06_2023_18-58-37](https://user-images.githubusercontent.com/92094765/242897825-c0b54378-09c1-4182-afb3-e33a2f7bce14.png)
> 
> ### Additional information
> _No response_

Yes that's right, but how can I assign you if you're already assigned an issue and you're not working on that?

**Comment by Soulpurr** [comment]
@narayan954 if you are talking about #366 I am not working on that as that already been resolved by someone else I think because that profile button is not longer out of page.

**Comment by Soulpurr** [comment]
Will submit pr by tomorrow
