### ISSUE TITLE
[FEATURE] ADDING A FEEDBACK SECTION

### ISSUE THREAD

**Issue by kharshita590** [narayan954/dummygram#417]
### Description

I WANT TO ADD NEW FEED BACK SECTION, WHERE USERS CAN SHARE THEIR EXPERIENCE TO YOU, AS THERE IS NO BACKEND SO I WILL USE EMAIL JS LIBRARY TO DO SO.

### Screenshots

....

### Additional information

....

**Comment by kharshita590** [comment]
Yes I want to work

**Comment by narayan954** [comment]
> ### Description
> I WANT TO ADD NEW FEED BACK SECTION, WHERE USERS CAN SHARE THEIR EXPERIENCE TO YOU, AS THERE IS NO BACKEND SO I WILL USE EMAIL JS LIBRARY TO DO SO.
> 
> ### Screenshots
> ....
> 
> ### Additional information
> ....

You can work on this :)
Also where would that go? would that go inside the chat bot feature ??

**Comment by kharshita590** [comment]
No it will be different

**Comment by kharshita590** [comment]
@narayan954 Please provide me your email address, so i can add that on feedback section and you will receive the feedbacks

**Comment by narayan954** [comment]
> @narayan954 Please provide me your email address, so i can add that on feedback section and you will receive the feedbacks

yes, sure narayansoni954@gmail.com for the mails

**Comment by narayan954** [comment]
> No it will be different

Oh okay fine

**Comment by kharshita590** [comment]
@narayan954 PLease provide me your mail id so you will be able to get the feedbacks

**Comment by narayan954** [comment]
> @narayan954 PLease provide me your mail id so you will be able to get the feedbacks

Yes narayansoni954@gmail.com is my email id

**Comment by Palakkgoyal** [comment]
Hey @kharshita590 are you working on this? If not then, can I take this issue?

**Comment by narayan954** [comment]
> Hey @kharshita590 are you working on this? If not then, can I take this issue?

assigning, you can work on this if you want
