### ISSUE TITLE
Fixing The Profile Section 

### ISSUE THREAD

**Issue by JAYESHBATRA** [narayan954/dummygram#419]
### Description

There is no space between the navbar and the card in the profile section. Also, the text "You have nothing in favourites" is cutting the card. Screenshots attached.

Please assign me the issue under GSSOC'23 
I would like to fix the issue.

### Steps to reproduce

Step-1: Login using google
Step-2 Go to the NavBar and Select My Profile Option.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/112322302/9cf74437-970f-4509-83b2-cb398c71c5af)

**Comment by narayan954** [comment]
Hi @JAYESHBATRA , this issue already exists and profile section is being improved... Also you're viewing this page at at-least 125% scale. But still , this is an responsiveness issue. there's a pr as well for this issue. So i've to close this as duplicate
