### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by 9520prashant** [narayan954/dummygram#421]
### Description

I just Improved the navbar, I added the transparent background because user think it very cool and the profile button must be a circle. 

### Screenshots

https://github.com/narayan954/dummygram/assets/99237795/7f367756-784b-4196-a385-6d7a31fe3352

### Additional information

Hey kindly assign me this issue under gssoc

**Comment by narayan954** [comment]
Hi @9520prashant , transparent background is cool but I think the profile button is too big and looks dumb.It can be smaller or maybe we can use profile icon there instead, what do you say? circle button with profile icon?

**Comment by narayan954** [comment]
doing both would make this issue level 2
