### ISSUE TITLE
Email Validation 

### ISSUE THREAD

**Issue by programerr01** [narayan954/dummygram#424]
### Description

Email Validation is not being done on `\login` page, server does give error but would be ideal to validate on frontend too

### Steps to reproduce

- go to `/dummygram/login`
- enter details without correct email format
- click on login 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/61112300/287eff0a-4094-4578-ab8d-4eb721db23ec)

**Comment by narayan954** [comment]
Hi there, this issue already exists... please find the original issue and get yourself assigned.
I'd have to close this one as duplicate
