### ISSUE TITLE
Authenticate website 

### ISSUE THREAD

**Issue by shraddha761** [narayan954/dummygram#427]
### Description

There is need to authentication when user try to like post without login then it will direct to sign in page 

### Steps to reproduce

do authentication while liking

**Comment by narayan954** [comment]
> ### Description
> There is need to authentication when user try to like post without login then it will direct to sign in page
> 
> ### Steps to reproduce
> do authentication while liking
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

user won't even see the post, as the application is authenticated, so how'd he like a post Shraddha?

**Comment by shraddha761** [comment]
@narayan954 Ohh Sorry I just thought of authenticating website

**Comment by narayan954** [comment]
> @narayan954 Ohh Sorry I just thought of authenticating website

it's okay lol, you should've done your homework...
