### ISSUE TITLE
[BUG] Move the "scroll to top" button from the centre.

### ISSUE THREAD

**Issue by souravrjpt** [narayan954/dummygram#432]
### Description

Hey @narayan954 ,
I'm really glad to see your awesome project. but I came across a small bug, actually the 'scroll to top' button falls at the centre of the posts which is making the post looks bad and it also colliding with the post (as I'm clicking on the button, it sometime gets clicked on the post). 

Kindly allow me to fix this bug.
(I'm looking your valuable project for other issue and I'll post another issue soon.)

Thank you

### Steps to reproduce

I'll use css and change it's position. It won't take much time but will create a good effect.

### Screenshots

![Screenshot from 2023-06-05 02-30-59](https://github.com/narayan954/dummygram/assets/95532791/16cfd11a-22b6-4aa3-9e6e-b554fe27d48a)

**Comment by souravrjpt** [comment]
Yes, I really want to contribute in this issue. Kindly assign it to me.

**Comment by narayan954** [comment]
Great, you can go ahead. Also please check it for all screens

**Comment by souravrjpt** [comment]
Can you assign this task to me? I want to change it by myself and contribute under gssoc'23.

**Comment by narayan954** [comment]
> Can you assign this task to me? I want to change it by myself and contribute under gssoc'23.

sorry I missed assigning

**Comment by souravrjpt** [comment]
remote: Permission to narayan954/dummygram.git denied to souravrjpt.
fatal: unable to access 'https://github.com/narayan954/dummygram.git/': The requested URL returned error: 403


I'm getting this error, what can I do next?

**Comment by narayan954** [comment]
@souravrjpt please check the alignment according to our new UI.

**Comment by Deepanshu0703** [comment]
Can you assign  this issue to me now

**Comment by narayan954** [comment]
> Can you assign this issue to me now

Hi @Deepanshu0703 there's already a pr associated with this issue and we're looking into it. Please wait
