### ISSUE TITLE
[FEATURE] Implement lazy loading

### ISSUE THREAD

**Issue by Avinash905** [narayan954/dummygram#433]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website
- Increased SEO ranking

I would implement lazy loading on the website.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by narayan954** [comment]
Hi this is a duplicate issue, please claim the original one. Don't create duplicate issue, check from already present issues first.
