### ISSUE TITLE
Post Download Failing

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#436]
### Description

Post Download option will fail for posts without pictures. We can either disable downloads for such posts or find a workaround.

### Steps to reproduce

click download on posts without picture just caption.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77617189/6a5b9336-536a-432d-a86d-4d1d56cf101a)

### Additional information

Please clarify your approach to this problem (you'll disable the button or do something else?)

**Comment by mughalfrazk** [comment]
Hey @narayan954, can you assign me this bug, and also i am seeing a login page and trying to sign-up but firebase is giving OPERATION_NOT_ALLOWED, can you please specify the login process too?

**Comment by narayan954** [comment]
> Hey @narayan954, can you assign me this bug, and also i am seeing a login page and trying to sign-up but firebase is giving OPERATION_NOT_ALLOWED, can you please specify the login process too?

@mughalfrazk Yes you can work on this bug. About the error you're facing... I've mentioned about it in the discord channel. I've disabled it for the production version.Google OAuth and Facebook OAuth are working fine and you can login using them for now.

**Comment by narayan954** [comment]
> > @mughalfrazk Yes you can work on this bug. About the error you're facing... I've mentioned about it in the discord channel. I've disabled it for the production version.Google OAuth and Facebook OAuth are working fine and you can login using them for now.
> 
> ![image](https://user-images.githubusercontent.com/70030525/243996386-828c8b67-8bcb-4be9-bed4-270a2e1e2534.png)
> 
> @narayan954 I am getting this when i am trying facebook or google login, and i am running it on localhost:3000. I am not familiar with the discord discussion, can you add me to that channel?

Hi, are you not a participant of GSSOC 23 ? Discord discussion is exclusive to the program participants.
About the error... I dont think you should be facing that, the domain you're telling `localhost` is an authorized one. All ports are authorized as well. Did you modify something in the oauth?

**Comment by mughalfrazk** [comment]
No i am not part of GSSOC 23, do i need to?
found the issue, Apparently 127.0.0.1 is not authorized but localhose is.

**Comment by narayan954** [comment]
> No i am not part of GSSOC 23, do i need to? found the issue, Apparently 127.0.0.1 is not authorized but localhost is.

Actually this project is currently a part of GSSOC, but it's okay if you wish to contribute :)
Yes, 127.0.0.1 is not in the list... adding.....
