### ISSUE TITLE
Favorite icon change

### ISSUE THREAD

**Issue by shraddha761** [narayan954/dummygram#438]
### Description

icon which is used to add to favorite is not recognized easily it should be changed and make it reactive and align it to right side

### Steps to reproduce

change favorite icon

**Comment by narayan954** [comment]
> icon which is used to add to favorite is not recognized easily it should be changed

can you make it reactive as well, so it changes on a click/hover? Also, change it's position to be on right most side instead of left most.
Actually, as per new guidelines, issues like just changing an icon/sentence on readme/color are not permitted for points, so we've to make compound issues for such issues.

**Comment by shraddha761** [comment]
@narayan954 I'll do to suggest changes and will you please provide me some time reason being my exams are going on

**Comment by narayan954** [comment]
> @narayan954 I'll do to suggest changes and will you please provide me some time reason being my exams are going on

yes, please take your time :)

**Comment by shraddha761** [comment]
Please assign this issue so that I'll work on it

**Comment by narayan954** [comment]
> @narayan954 Please assign this issue so that I'll work on it

You can work on this, the issue is all yours :)

**Comment by shraddha761** [comment]
> > @narayan954 Please assign this issue so that I'll work on it
> 
> You can work on this, the issue is all yours :) I forgot to assign earlier

Ohh thank you

**Comment by shraddha761** [comment]
@narayan954 dummygram didn't have discord Channel ?

**Comment by narayan954** [comment]
> @narayan954 dummygram didn't have discord Channel ?

Dummygram does have it's channel in gssoc server. Are you not able to access it?

**Comment by shraddha761** [comment]
> > @narayan954 dummygram didn't have discord Channel ?
> 
> Dummygram does have it's channel in gssoc server. Are you not able to access it?

yahh

**Comment by narayan954** [comment]
> > > @narayan954 dummygram didn't have discord Channel ?
> > 
> > 
> > Dummygram does have it's channel in gssoc server. Are you not able to access it?
> 
> yahh

Did you try it from self roles?

**Comment by shraddha761** [comment]
> > > > @narayan954 dummygram didn't have discord Channel ?
> > > 
> > > 
> > > Dummygram does have it's channel in gssoc server. Are you not able to access it?
> > 
> > 
> > yahh
> 
> Did you try it from self roles?

Now get channel

**Comment by narayan954** [comment]
> > > > > @narayan954 dummygram didn't have discord Channel ?
> > > > 
> > > > 
> > > > Dummygram does have it's channel in gssoc server. Are you not able to access it?
> > > 
> > > 
> > > yahh
> > 
> > Did you try it from self roles?
> 
> Now get channel 

cool!
