### ISSUE TITLE
[FEATURE] Create a whole new PROFILE PAGE using React.js.

### ISSUE THREAD

**Issue by souravrjpt** [narayan954/dummygram#439]
### Description

Hey @narayan954 ,
I wanted to create a whole new Profile page as the current profile page is not that attractive, and also the button for "Edit Profile Pic" is not attractive that much (I'm not able to see the text when hover over it) . There is a lot of neon colours which are use in your web-app, Can we use other colour combinations? What' your opinion about it?

Kindly, assign this issue to me. i'm really excited to contribute in your project.
Thank you

### Screenshots

![Screenshot from 2023-06-05 21-21-42](https://github.com/narayan954/dummygram/assets/95532791/f61c9bc6-b762-4f5c-9087-1d9b6ea63bfd)
![Screenshot from 2023-06-05 21-30-06](https://github.com/narayan954/dummygram/assets/95532791/ad47d9f3-7437-4e46-983a-0503d5ffd61d)

**Comment by narayan954** [comment]
> ### Description
> Hey @narayan954 , I wanted to create a whole new Profile page as the current profile page is not that attractive, and also the button for "Edit Profile Pic" is not attractive that much (I'm not able to see the text when hover over it) . There is a lot of neon colours which are use in your web-app, Can we use other colour combinations? What' your opinion about it?
> 
> Kindly, assign this issue to me. i'm really excited to contribute in your project. Thank you
> 
> ### Screenshots
> ![Screenshot from 2023-06-05 21-21-42](https://user-images.githubusercontent.com/95532791/243408096-f61c9bc6-b762-4f5c-9087-1d9b6ea63bfd.png) ![Screenshot from 2023-06-05 21-30-06](https://user-images.githubusercontent.com/95532791/243408168-ad47d9f3-7437-4e46-983a-0503d5ffd61d.png)
> 
> ### Additional information
> _No response_

Hi @souravrjpt , can you please confirm if the issue already exists, because I think some parts of it exists already

**Comment by narayan954** [comment]
> I've checked all the issues related to above topic, I found that the issue is raised by someone else but my point is, is he working on it as the profile page is still looking the same?

well if the issue exists, instead of duplicating it, you can try to claim the original issue.

**Comment by souravrjpt** [comment]
ok i'll raise another issue. Thank you so much for your support.

**Comment by narayan954** [comment]
> ok i'll raise another issue. Thank you so much for your support.

Thanks for understanding :)
