### ISSUE TITLE
[Add Friend Request feature] make a friend request

### ISSUE THREAD

**Issue by linga66** [narayan954/dummygram#440]
### Description

I want to add a feature called friend request

Go to someone else's profile and make a friend request. Friend request should be given to other people

Assign this issue to me @narayan954 
I think i can do this

### Screenshots

![Screenshot (495)](https://github.com/narayan954/dummygram/assets/103192975/a70e6364-08b4-4ff8-abee-69f61dcd0d6a)

### Additional information

Assign me this issue @nara

**Comment by narayan954** [comment]
> ### Description
> I want to add a feature called friend request
> 
> Go to someone else's profile and make a friend request. Friend request should be given to other people
> 
> Assign this issue to me @narayan954 I think i can do this
> 
> ### Screenshots
> ![Screenshot (495)](https://user-images.githubusercontent.com/103192975/243430710-a70e6364-08b4-4ff8-abee-69f61dcd0d6a.png)
> 
> ### Additional information
> Assign me this issue @nara

bro I'm not @nara, I'm @narayan954 . Also, this one's a difficult one. Can you please tell your approach?

**Comment by linga66** [comment]
Sorry 😅
I will Create a APIs to handle friend request-related operations. I will create a backend inserting new friend requests into the FriendRequests table, updating the status of friend requests, and fetching pending friend requests for a user.

**Comment by narayan954** [comment]
> Sorry sweat_smile I will Create a APIs to handle friend request-related operations. I will create a backend inserting new friend requests into the FriendRequests table, updating the status of friend requests, and fetching pending friend requests for a user.

Hi, you can directly interact with firebase database , you don't need to create a separate backend for this only. I'd suggest to insert into a new collection 'users' . Users will have user entitites containing several fields which are going to be used in future issues as well. Field we'll be using for this issue could be friendlist/friends and friendRequests both as array. if a user clicks on add friend button, userid would be added to the friendRequests array of the user, which he can accept. About accepting... in profile there could be a section, accept requests where the requests shall be rendered. Finally he accepts/reject it cleaning from friendlist and moving either to friendlist or going void, respectively.... User can also view his friendlist. There are many stuffs to perform for this task so procede in sequence, first just work on till sending a friendrequest... later we can add issue to accept and add to friendlist.

**Comment by narayan954** [comment]
let the pull request close the issue
