### ISSUE TITLE
[FEATURE] Remove post from favourites

### ISSUE THREAD

**Issue by AK4266** [narayan954/dummygram#443]
### What is the issue?
If I add some post as my favourites, there isn't any button that lets you to remove that post from the favourites

![Screenshot 2023-06-06 210538](https://github.com/narayan954/dummygram/assets/99728079/3f426436-619b-4afb-86c6-d791ac0be3ee)

### Feature I want to implement
I want to implement some button. So, whenever I press that button that lets me remove the favourite post that I save earlier

### Additional information

I would like to work on this isuue assign it to me

**Comment by narayan954** [comment]
@AK4266 How about we use the favourite button itself for this purpose. Though favourite button doesn't tell if post is already in favourites or not, I think there's an issue trying to make it dynamic. So you can do your part in letting this button remove the post from favourites.

**Comment by narayan954** [comment]
Upgraded difficulty level
