### ISSUE TITLE
[FEATURE]Seperate component for navbar/header

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#444]
### Description

So the idea is to create a separate component for navbar/header so that app.js doesn't  look messy.
![scrnli_07_06_2023_13-32-14](https://github.com/narayan954/dummygram/assets/92094765/c543b837-8e6e-4e7f-a9a9-c4116ec4d4bd)

Pls assign this to me under gssoc23

**Comment by narayan954** [comment]
> ### Description
> So the idea is to create a separate component for navbar/header so that app.js doesn't look messy. ![scrnli_07_06_2023_13-32-14](https://user-images.githubusercontent.com/92094765/243971743-c543b837-8e6e-4e7f-a9a9-c4116ec4d4bd.png)
> 
> Pls assign this to me under gssoc23

Yes, refactoring is really required. I was thinking the same!

**Comment by narayan954** [comment]
also to assist you, we have a pull request on review, pr number https://github.com/narayan954/dummygram/pull/437 which intends to remove some of the sections of navbar. Can you try to work according to that so there're less conflicts

**Comment by Soulpurr** [comment]
> also to assist you, we have a pull request on review, pr number #437 which intends to remove some of the sections of navbar. Can you try to work according to that so there're less conflicts

Yea I will see

**Comment by narayan954** [comment]
> > also to assist you, we have a pull request on review, pr number #437 which intends to remove some of the sections of navbar. Can you try to work according to that so there're less conflicts
> 
> @narayan954 #437 is adding a sidebar.so can you confirm that it's making some changes in navbar as sidebar is entirely different.If it's not making any changes to navbar then I can start working on creating a seperate component for navbar.

let's wait the pull request to merge for this issue. Also, as far as I remember, I told him "not to edit navbar, first implement sidebar, then we'll clean navbar"

**Comment by narayan954** [comment]
@Soulpurr you can look at this now and we still need to make navbar a separate component

**Comment by Soulpurr** [comment]
> @Soulpurr you can look at this now and we still need to make navbar a separate component

Okk

**Comment by Soulpurr** [comment]
> @Soulpurr you can look at this now and we still need to make navbar a separate component

Pls just give me a few days I will finish this and my other issues in a few days as currently my sessional exams are going on.
