### ISSUE TITLE
[FEATURE] A separate section for favaorite posts.

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#445]
### Description

Currently we have no separate section for accessing favourite post we have to open profile section.
I think it will be better if we add a page for favorite post.

pls assign this to me under gssoc23

**Comment by narayan954** [comment]
> ### Description
> Currently we have no separate section for accessing favourite post we have to open profile section. I think it will be better if we add a page for favorite post.
> 
> pls assign this to me under gssoc23

Great, go ahead!

**Comment by Soulpurr** [comment]
> > ### Description
> > Currently we have no separate section for accessing favourite post we have to open profile section. I think it will be better if we add a page for favorite post.
> > pls assign this to me under gssoc23
> 
> Great, go ahead!, also to help you, we have a pull request on review, pr number #437 which will have the direct link for favourite section. Can you work according to that so that section can render it directly(it's blank for now)

yea ok
