### ISSUE TITLE
[Enhancement] - Fix empty uploads and show progress bar while uploading only

### ISSUE THREAD

**Issue by Bhavik-ag** [narayan954/dummygram#45]
### What would you like to share?

I want to do the following changes:- 

- Show the progress bar only while uploading
- Fix a bug - Post with no caption and no image should not be uploaded.

**Comment by Bhavik-ag** [comment]
Please assign this issue to me if you find the changes appropriate for the project so that I can submit a PR.

**Comment by narayan954** [comment]
yeah go ahead!
