### ISSUE TITLE
Make the pictures clickable

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#455]
### Description

Currently, we can see that pictures are only of small size. I want to make them such that when the user click on it the image expands, and overlap the screen in a nice way and user can easily click cross button to remove the image from covering the entire screen.

**Comment by Palakkgoyal** [comment]
I want to work on this issue. Please assign it to me and also add GSSOC label

**Comment by narayan954** [comment]
> ### Description
> Currently, we can see that pictures are only of small size. I want to make them such that when the user click on it the image expands, and overlap the screen in a nice way and user can easily click cross button to remove the image from covering the entire screen.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

which picture Palak? The one on posts? Actually I was thinking of adding double click to like on those pictures . Would double click to like be better or single click to expand? What do you think or is there a third way? btw if both are together, user might mistaken between like and zooming in right?

**Comment by Palakkgoyal** [comment]
Yes, that might be. I tried it but I think you are right.

**Comment by Palakkgoyal** [comment]
I have a suggesting that we should move the website from create react app to vite. If you agree then, can I create a new issue for it? @narayan954

**Comment by narayan954** [comment]
> Yes, that might be. I tried it but I think you are right.

so what do we do?

**Comment by Palakkgoyal** [comment]
Double click to like the post would be more good and will look and feel great.

**Comment by narayan954** [comment]
> Double click to like the post would be more good and will look and feel great. So, I think it would be better to apply the double click functionality.

Would you like to work on that? if so please update the issue to mention this, else you may close this issue.

**Comment by narayan954** [comment]
> > Double click to like the post would be more good and will look and feel great. So, I think it would be better to apply the double click functionality.
> 
> Would you like to work on that? if so please update the issue to mention this, else you may close this issue.

Ohh you already created an issue. Closing this :)
