### ISSUE TITLE
Change the font of profile page to Poppins

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#456]
### Description

The font of website is Poppins but it is missing in the profile section on name and email which doesn't look so good. So, please assign this issue to me under GSSOC'23 to change its font.

### Steps to reproduce

Go to profile page and see the name and email on it.

### Screenshots

![Screenshot 2023-06-11 145929](https://github.com/narayan954/dummygram/assets/116902573/bd132b31-e948-4090-96cb-14276662aba9)

**Comment by narayan954** [comment]
Yes please help maintain consistencies in fonts, it's a great UI fix. Also please check if other section also dont have the same issue
