### ISSUE TITLE
Button hover effect need improvment

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#457]
### Description

When the button on the profile page is hovered it doesn't match with its surrounding and feels odd. It needs a new beautiful gradient.

### Steps to reproduce

- Go to profile section. 
- Hover on `Edit Profile Pic`
- The gradient will show up

### Screenshots

![Screenshot 2023-06-11 150510](https://github.com/narayan954/dummygram/assets/116902573/152b77cf-bb69-45aa-9d07-85cd8260cd6e)

**Comment by Palakkgoyal** [comment]
Please assign this issue to me under GSSOC'23

**Comment by narayan954** [comment]
go ahead!
