### ISSUE TITLE
Adding Separate Section for Favourite Posts

### ISSUE THREAD

**Issue by pranavsrvstv** [narayan954/dummygram#458]
### Description

Currently , the favourite posts are shown in the profile page itself, even if the user doesnt wish to see them .
We can instead create a button for [show favourites ] in the profile page .
On clicking the button the user will get navigated to the favourites page.
Basically the favourites page can be separately implemented out of the profile section.
That would improve the UI .

### Screenshots

<img width="370" alt="fav" src="https://github.com/narayan954/dummygram/assets/120587771/8689d3bb-b6de-4068-bc6b-21ef8137bf13">

### Additional information

I am a gssoc contributor. I would be happy to work on this issue.

**Comment by pranavsrvstv** [comment]
> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Yeah , I wish to work on this issue !

**Comment by narayan954** [comment]
> ### Description
> Currently , the favourite posts are shown in the profile page itself, even if the user doesnt wish to see them . We can instead create a button for [show favourites ] in the profile page . On clicking the button the user will get navigated to the favourites page. Basically the favourites page can be separately implemented out of the profile section. That would improve the UI .
> 
> ### Screenshots
> <img alt="fav" width="370" src="https://user-images.githubusercontent.com/120587771/244945903-8689d3bb-b6de-4068-bc6b-21ef8137bf13.png">
> ### Additional information
> I am a gssoc contributor. I would be happy to work on this issue.

Hi @pranavsrvstv this is a duplicate issue and has already been resolved. So, unfortunately I'll have to close this issue. Meanwhile you can check the other issues present in our repository. You can also claim inactive ones.

Thanks for your understanding
