### ISSUE TITLE
Github Action Failing

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#46]
### Description

Every build action is failing due to npm ci not working. This isn't intended and also confuses the contributors.
Can anyone solve this issue /suggest an alternative?
Thanks

### Steps to reproduce

With every merge in the repository, GitHub action gets triggered , but it fails everytime.

**Comment by KehindeBello** [comment]
I recently learnt about continuous integration with Travis and GitHub actions and I'll love to work on this issue.

**Comment by narayan954** [comment]
great go ahead!
