### ISSUE TITLE
Messing of sidebar with posts

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#460]
### Description

The new sidebar implemented is creating problem with the 3 column layout. I want to fix this and make the UI look clean.
Please assign this issue to me under GSSOC'23

### Steps to reproduce

Go to https://narayan954.github.io/dummygram
Click on the layout switching button
The sidebar will look messing up

### Screenshots

![Screenshot 2023-06-12 153618](https://github.com/narayan954/dummygram/assets/116902573/7b348c4e-b125-46da-8329-a8ed53e24d5d)

### Desktop (please complete the following information)

- **OS** : Window
- **Browser** : Chrome
- **Version** : 114.0.5735.110 (Official Build) (64-bit)

**Comment by narayan954** [comment]
Yeah sure, go ahead!
