### ISSUE TITLE
[FEATURE] - Improve Navbar UI and Enhance Hover Effects

### ISSUE THREAD

**Issue by Amitavpanda** [narayan954/dummygram#461]
### Description

The current navbar UI lacks visual appeal and the hover effects on the navbar buttons are not engaging enough. This can lead to a suboptimal user experience and may hinder the overall usability of the website/application.

I propose to improve the navbar UI and enhance the hover effects on the navbar buttons. The goal is to create a visually appealing and interactive navigation experience for users.

The following changes should be implemented:

- Redesign the navbar to have a modern and aesthetic appearance.
- Implement smooth transitions and animations for the hover effects on the navbar buttons.
- Enhance the visual feedback when a button is in the active or focused state.

**I would like to work on this issue under GSSOC'23.**

**Comment by Amitavpanda** [comment]
@narayan954 can you assign me this task.

**Comment by narayan954** [comment]
> @narayan954 can you assign me this task.

Hi @Amitavpanda , actually this issue is already under progress. Also as the sidebar is in place now, we're cleaning the navbar. You can await on this issue for some days to further improve if you want.
