### ISSUE TITLE
[FEATURE]: Add "Forgot Password" Option in Login Page

### ISSUE THREAD

**Issue by NarendraKoya999** [narayan954/dummygram#469]
### Issue Description: Add Forgot Password Feature Option in Login Page Whenever User Forgot the Password.

> How To Design It ??
- **Go To 'https://narayan954.github.io/dummygram/login' Website.**
- **The Login Page Appears on Main Page.**
- **Observing After E-Mail, Password Sections, Forgot Password Option is Not There.That's Why I suggest New Feature.**   

### Screenshot of My Suggested Feature:
<img width="296" alt="dummygram-3" src="https://github.com/narayan954/dummygram/assets/84512164/24ddf26c-a295-4d81-a2f6-07f821d053f9">

### NOTE:
- **According To Latest Trends, Forgot Password Feature is Thoroughly Used Login and Sign-in Pages.**
- **Implementing this Feature is Very Helpful for Current and Future Perspective.**

**Comment by narayan954** [comment]
Yes, sure you can work on this, use firebase inbuilt features for forget password to breeze the process.
Also you can generate your own credentials for testing as in the production app, email login is disabled.

Additionally, we might add the email confirmation at the sign up of our application in separate issue. This will ensure, emails are authentic as well.

**Comment by NarendraKoya999** [comment]
Please Assign this Issue to Others Who can Interested to Develop this Feature.

**Comment by rudrakushwaha** [comment]
Hey @NarendraKoya999  I am interested in this issue and would love to work on it . Please assign it to me under GSSoC'23

**Comment by narayan954** [comment]
> Hey @NarendraKoya999 I am interested in this issue and would love to work on it . Please assign it to me under GSSoC'23

Sure, go ahead!

**Comment by rudrakushwaha** [comment]
Thanks for assigning me the issue.

**Comment by rudrakushwaha** [comment]
Hey @narayan954 can you provide me the credentials for testing?

**Comment by narayan954** [comment]
> Hey @narayan954 can you provide me the credentials for testing?

direct message in discord

**Comment by narayan954** [comment]
> > Hey @narayan954 can you provide me the credentials for testing?
> 
> dm me on discord

**Comment by rudrakushwaha** [comment]
@narayan954 what is your username?

**Comment by narayan954** [comment]
> @narayan954 what is your username?

are you not from gssoc? I should be present there. Username: nexxx#2047

**Comment by rudrakushwaha** [comment]
Hey @narayan954 I have added the forgot password feature and opened the pull request please review it.
