### ISSUE TITLE
[FEATURE] Adding Bio feature to the Profile section

### ISSUE THREAD

**Issue by AK4266** [narayan954/dummygram#470]
### Description

It would be great to showcase ones skills or a person short intro on their profile section. So, I would like to suggest bio to add section

![Screenshot 2023-06-13 195818](https://github.com/narayan954/dummygram/assets/99728079/866acb8c-8cc3-49f8-b78a-3c81f2285c7e)

I would like to add it right after username

### Iam willing to work on this issue, assign me.

**Comment by AK4266** [comment]
Hey @narayan954 assign me this issue

**Comment by narayan954** [comment]
@AK4266 this issue exists already, please find and claim it. After that, close this one as duplicate.
