### ISSUE TITLE
Sign up option other than with google & facebook is not working.

### ISSUE THREAD

**Issue by debsouryadatta** [narayan954/dummygram#473]
### Description

The Sign Up option other than with google & facebook is not working.

### Steps to reproduce

There is an issue in the firebase console which needs to be fixed for signing up other than with google and facebook

### Screenshots

![Screenshot (266)](https://github.com/narayan954/dummygram/assets/91617309/34176e1f-af12-4017-bd5d-6fc8b5023623)

**Comment by debsouryadatta** [comment]
Yes, I would like to work on 

> Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned

Yes, I would like to work on this issue under GSSOC'23

**Comment by narayan954** [comment]
> > Hi there, Thanks a lot for raising the issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned
> 
> Yes, I would like to work on this issue under GSSOC'23

I've commented regarding this issue in the discord channel, you may close it
