### ISSUE TITLE
Bug was found on clicking "change layout button"

### ISSUE THREAD

**Issue by Bhuvanchand26** [narayan954/dummygram#474]
### Description

After clicking a button to change the layout, we can see that it got overflowed onto the vertical navbar. we change that according to our requirements. we can do this in two ways either we push our navbar to the left side completely( only icons visible ) or we can edit the layout's padding and margin.
I'm from gssoc'23, I think I can do this, Assign me this task

Thank you!!!!!!

### Steps to reproduce

Either compress our vertical navbar to left or adjust the layout in the given space.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/131843589/f021af15-a64e-4113-ab87-bfd67f725fe2)

**Comment by narayan954** [comment]
> ### Description
> After clicking a button to change the layout, we can see that it got overflowed onto the vertical navbar. we change that according to our requirements. we can do this in two ways either we push our navbar to the left side completely( only icons visible ) or we can edit the layout's padding and margin. I'm from gssoc'23, I think I can do this, Assign me this task
> 
> Thank you!!!!!!
> 
> ### Steps to reproduce
> Either compress our vertical navbar to left or adjust the layout in the given space.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/131843589/245881632-f021af15-a64e-4113-ab87-bfd67f725fe2.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi there, this was a duplicate issue and has been resolved already. Thank you for raising/finding it though. You may claim/find other issues though. I'd have to close this one as not planned/duplicate

Thanks

**Comment by Bhuvanchand26** [comment]
okay, No problem.
