### ISSUE TITLE
bug in Dark mode

### ISSUE THREAD

**Issue by Bhuvanchand26** [narayan954/dummygram#475]
### Description

On hovering over the card, we just cannot see elements that are present in the card except the comment section.

### Steps to reproduce

Have to assign correct things to when ever dark mode option is selected.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/131843589/4bf3332e-6bbf-4379-b46a-86e3c5b47d52)

**Comment by narayan954** [comment]
Thanks for finding/raising the issue, you can work on this!

**Comment by Swapnil-Singh-99** [comment]
@narayan954 Please assign this issue to me under GSSOC'23

**Comment by narayan954** [comment]
> @narayan954 Please assign this issue to me under GSSOC'23 

go ahead!

**Comment by Swapnil-Singh-99** [comment]
Thanks
