### ISSUE TITLE
Want to make New Post UI Responsive 📱(For Small Screens) + Making New Component for New Post

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [narayan954/dummygram#476]
### What would you like to share?

@narayan954 
Here is how it looks + Making New Component for New Post(As Suggested by you in previous pull request)

The idea is to shift the image part upper and Caption part Lower. 
If you have any Idea for responsiveness , Feel free to suggest me !! I will change UI Accordingly 🙂

Please assign me this issue as a GSSOC'23 Contributor.

![image](https://github.com/narayan954/dummygram/assets/83361657/5a792449-0f99-4038-b2d2-81bab9ff7e69)

**Comment by narayan954** [comment]
> ### What would you like to share?
> @narayan954 Here is how it looks + Making New Component for New Post(As Suggested by you in previous pull request)
> 
> The idea is to shift the image part upper and Caption part Lower. If you have any Idea for responsiveness , Feel free to suggest me !! I will change UI Accordingly slightly_smiling_face
> 
> Please assign me this issue as a GSSOC'23 Contributor.
> 
> ![image](https://user-images.githubusercontent.com/83361657/245934359-5a792449-0f99-4038-b2d2-81bab9ff7e69.png)
> 
> ### Additional information
> _No response_

Yes, you can work on this! 
Also,
- The divider line is not responsive as well.
![image](https://github.com/narayan954/dummygram/assets/77617189/32682e49-09d3-4506-9b79-595d1b974e39)
- please check the font size of upload picture and take picture.
- I am not at all good at UIs , as you can see the original dummygram was too bad in UI. Feel free to experiment on your own and treat yourself as the user when testing... that'd be enough. :)

**Comment by Gurmeet-Singh657** [comment]
OK Sure 😅. Thank You so much for assigning me this issue 🤩

**Comment by narayan954** [comment]
> OK Sure sweat_smile. Thank You so much for assigning me this issue star_struck

You're welcome :), best of luck!

**Comment by crocmons** [comment]
Can I work on this issue as level 3?

**Comment by narayan954** [comment]
> @narayan954 Can I work on this issue as level 3?

level 3 is for both, issue and the refactoring of new post component. Also, perhaps @Gurmeet-Singh657 is working on it. So we should wait to confirm it.

**Comment by Gurmeet-Singh657** [comment]
Yups, I have started working. Will commit by tomorrow. Small part is left Just completing that 😅
