### ISSUE TITLE
Favourites Page is not showing multi column layout

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#479]
### Description

As the layout on the home page, when we click the button to change layout in the favourites page from single column to multi column it do not change. I want to fix this bug.
Please assign this issue to me under GSSOC.

### Steps to reproduce

Go to Favourites
Click on the layout switching button(Second button from the top right corner)
Then, the layout didn't switch

### Screenshots

![Screenshot 2023-06-15 152232](https://github.com/narayan954/dummygram/assets/116902573/cfba0b51-cef4-451c-b3b4-2b4deb46726a)

**Comment by narayan954** [comment]
Great, go ahead!

**Comment by narayan954** [comment]
Since you made use of context api, which greatly enhances the implementation, I've upgraded the issue to level 2

**Comment by Palakkgoyal** [comment]
Thanks a lot @narayan954
