### ISSUE TITLE
Editing name and email

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#480]
### Description

In the profile page there is only one option i.e to edit the image. I want to add a new feature by which user will be able to edit their name and email too.

### Screenshots

![Screenshot 2023-06-15 152838](https://github.com/narayan954/dummygram/assets/116902573/7e5a3da8-be54-46c1-a146-56f6b4aaa4a4)

### Additional information

Please assign this issue to me under GSSOC

**Comment by narayan954** [comment]
> ### Description
> In the profile page there is only one option i.e to edit the image. I want to add a new feature by which user will be able to edit their name and email too.
> 
> ### Screenshots
> ![Screenshot 2023-06-15 152838](https://user-images.githubusercontent.com/116902573/246072871-7e5a3da8-be54-46c1-a146-56f6b4aaa4a4.png)
> 
> ### Additional information
> Please assign this issue to me under GSSOC

Hi @Palakkgoyal , edit features are already being worked upon. there're 2 issues already revolving around this. I've to close this as duplicate. Though I might suggest we need a footer in the sidebar now. Also, an option to minimise sidebar by toggle can help. Also, instead of mui icon for profile in the sidebar, we can have current user's profile picture... I'm listing these here as I've to raise these issues and hopefully I don't forget again

**Comment by Palakkgoyal** [comment]
Can you please elaborate how you want to add a footer in the sidebar? I mean what should be included in it and how you want to structure it.

**Comment by narayan954** [comment]
> Can you please elaborate how you want to add a footer in the sidebar? I mean what should be included in it and how you want to structure it.

First of all this footer seems feasible only for desktop version for now. We can have dark mode toggle, logout option, github repo icon with link, some copyright text at the bottom. Whatever you think fits.

Structure can be inspired by different sites, and I'm attaching some ss as well.
![image](https://github.com/narayan954/dummygram/assets/77617189/2f6b8d4a-e36a-469b-ad29-b3f8d259921e)
![image](https://github.com/narayan954/dummygram/assets/77617189/2499caba-e9ab-42be-b3b5-61973cc08b54)
![image](https://github.com/narayan954/dummygram/assets/77617189/6f76df8d-7f3f-4534-a080-e525fcb45817)

**Comment by Palakkgoyal** [comment]
Ohkk. Understood

**Comment by narayan954** [comment]
> Ohkk. Understood

updated a bit, this footer can also work for mobile devices, but mobile devices have a different view.

**Comment by Palakkgoyal** [comment]
Ohk. First, I will do some research on how I can implement this than I will create issue.

**Comment by narayan954** [comment]
> Ohk. First, I will do some research on how I can implement this than I will create issue.

feel free to, you can come up with your own approach :)
