### ISSUE TITLE
Make all posts visible on profile

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#481]
### Description

Currently, in the profile page it shows only detail of the person but I think there must be a section for showing all the posts done by a user itself below the profile component.

### Screenshots

![Screenshot 2023-06-15 152838](https://github.com/narayan954/dummygram/assets/116902573/7cbcc357-31b6-45c5-b50e-15e04ec57cd0)

### Additional information

Please assign this issue to me under GSSOC

**Comment by narayan954** [comment]
> ### Description
> Currently, in the profile page it shows only detail of the person but I think there must be a section for showing all the posts done by a user itself below the profile component.
> 
> ### Screenshots
> ![Screenshot 2023-06-15 152838](https://user-images.githubusercontent.com/116902573/246073840-7cbcc357-31b6-45c5-b50e-15e04ec57cd0.png)
> 
> ### Additional information
> Please assign this issue to me under GSSOC

Yes!, our own user profile feed! We can later convert them into grid like display just like instagram.
