### ISSUE TITLE
[FEATURE] add cursor pointer to see next post 

### ISSUE THREAD

**Issue by Noothan-am** [narayan954/dummygram#484]
### Description

add cursor pointer to see next post instead of normal arrow

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100135382/1ce50321-ee48-4935-8706-ffa4903c1bfd)

**Comment by narayan954** [comment]
> ### Description
> add cursor pointer to see next post instead of normal arrow
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/100135382/246334980-1ce50321-ee48-4935-8706-ffa4903c1bfd.png)
> 
> ### Additional information
> _No response_

Go ahead!
