### ISSUE TITLE
[FEATURE] User Profile Page

### ISSUE THREAD

**Issue by SSHSRN** [narayan954/dummygram#49]
### Description

I want to do the following changes: -

* Create a separate route or a modal or an overlay for user settings.
* Right now, the page just shows if a user is logged in or not and a user cannot see which email or the details, he/she used to log in.
* I also want to add a **dynamic user profile picture** to a user when they sign in (as a Gravatar).

### Additional information

Information needed:
* Kindly suggest how should I make the profile page? As a separate route or as an overlay?
Kindly confirm.

**Comment by SSHSRN** [comment]
Please assign this issue to me if you find the idea appropriate for the project so that I can submit a Pull Request.

**Comment by narayan954** [comment]
User profile seems like a great idea!
In the project we already have implemented an avatar option #5 corresponding to #42 while signing up.
We can make that avatar upload feature as an optional and implement your suggestion for when users don't upload an avatar.
So yeah , it's a green light from me!

**Comment by narayan954** [comment]
@SSHSRN I'm opening this issue for KWOC 2022

**Comment by SSHSRN** [comment]
Can I work on it for KWOC?

**Comment by narayan954** [comment]
Sure, you can :)

**Comment by narayan954** [comment]
@SSHSRN are you still working on this? and please take inspiration from #107

**Comment by SSHSRN** [comment]
Yah, I am working on this, but I would need some time, please!

We got our end sem exams going now and it ends on 13th only.

**Comment by narayan954** [comment]
> Yah, I am working on this, but I would need some time, please!
> 
> We got our end sem exams going now and it ends on 13th only.

It's okay take your time and best of luck :)

**Comment by narayan954** [comment]
@SSHSRN are you working on this issue?

**Comment by thevinitgupta** [comment]
I would love to work on this.

**Comment by narayan954** [comment]
> I would love to work on this.

great, go ahead!

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
You can be assigned to only one issue at a time, finish the assigned issue first. Thank you

**Comment by Hritik1503** [comment]
Please assign me this issue currently i am completed my all so i am free for this so please assign me this issue

**Comment by sarkartanmay393** [comment]
@narayan954 I would like to work in it under JWOC, after you review #254

**Comment by narayan954** [comment]
> @narayan954 I would like to work in it under JWOC, after you review #254

okay sure

**Comment by narayan954** [comment]
> @narayan954 I would like to work in it under JWOC, after you review #254

assigned!
