### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#494]
### What would you like to share?

The codebase is not readable and decrease efficiency of other developers to develop anything. I want to restructure the codebase.

### Additional information

Please assign this issue to me under GSSOC'23

**Comment by narayan954** [comment]
Yes sure, go ahead!! Thanks a lot!

**Comment by Palakkgoyal** [comment]
Sure, I will test every change. Can you please assign it. Otherwise, it won't get counted in GSSOC

**Comment by Palakkgoyal** [comment]
Hey @narayan954 Please add gssoc and level label to PR. It is not necessary on issue but very important on PR otherwise they will not be counted. Can you also add labels and levels on merged PRs too?

**Comment by narayan954** [comment]
> Hey @narayan954 Please add gssoc and level label to PR. It is not necessary on issue but very important on PR otherwise they will not be counted. Can you also add labels and levels on merged PRs too?

@Palakkgoyal , labels are to be added to merged prs only as they confirm the point distribution. Unmerged prs don't need points, merged ones do. Also, please update your branch with master before refactoring to avoid conflicts.

**Comment by narayan954** [comment]
> Hey @narayan954 Please add gssoc and level label to PR. It is not necessary on issue but very important on PR otherwise they will not be counted. Can you also add labels and levels on merged PRs too?

in issues, labels are only needed for my side so I can confirm what labels to add in pull requests when merging the pr

**Comment by Palakkgoyal** [comment]
Oh, Ohk. Thanks for letting me know

**Comment by Palakkgoyal** [comment]
> > Hey @narayan954 Please add gssoc and level label to PR. It is not necessary on issue but very important on PR otherwise they will not be counted. Can you also add labels and levels on merged PRs too?
> 
> @Palakkgoyal , labels are to be added to merged prs only as they confirm the point distribution. Unmerged prs don't need points, merged ones do. Also, please update your branch with master before refactoring to avoid conflicts.

Sure. I will do the same before refactoring.

**Comment by narayan954** [comment]
> Oh, Ohk. Thanks for letting me know

I checked old prs and understood you're talking about the old pr I merged ... You should've mentioned that instead . Earlier I thought you're talking about current pr and issue. It's alright though.

**Comment by Palakkgoyal** [comment]
I apologize for confusion. Actually, I was just some tensed about points. But thanks for your response😄

**Comment by narayan954** [comment]
> I apologize for confusion. Actually, I was just some tensed about points. But thanks for your responsesmile

It's alright! :) I'm just here to help
