### ISSUE TITLE
profile page bug

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#496]
### Description

As we're passing the state from one component to another component (here as in from app.jsx to profile.jsx) so if we try to render the profile component separately, or if we go directly to profile route, we'd get error as there's no prop available. We can fix this by getting the current user from firebase which is similar to global context. Other components have this implementation so inspiration can be taken from them and implemented similarly. 

### Steps to reproduce

while going to profile page from app jsx works, but if you go directly to profile route, it wont work or if you refresh on profile page, it'd crash as well. Automatic refresh that happens when site is open for longer amount of time shall also crash the page.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/77617189/420b22a7-b2b0-4056-81c9-aa6a8825a0ef)

### Additional information

As a successor to this issue, we can define the parameterised route for profile that'd correct the implementation of viewing other's profiles, using their uuid.

**Comment by VijayalakshmiGanesh** [comment]
Hi @narayan954 , 

I would like to work on this issue under GSSOC'23. Can you assign this to me please.  Thank you

**Comment by narayan954** [comment]
> Hi @narayan954 ,
> 
> I would like to work on this issue under GSSOC'23. Can you assign this to me please. Thank you

Yeah sure, just a heads up, this one's updated quite a bit. I've fixed most of it. Just the part where going directly to profile route, you'll face error.

**Comment by VijayalakshmiGanesh** [comment]
https://github.com/narayan954/dummygram/pull/532 - @narayan954  raised PR. Kindly review it. For some reason, linting process is failed. Could you please explain on how to resolve it. Thank  you

**Comment by narayan954** [comment]
> https://github.com/narayan954/dummygram/pull/532 - @narayan954  raised PR. Kindly review it. For some reason, linting process is failed. Could you please explain on how to resolve it. Thank  you 

I think error is related to the action... looking into it.
