### ISSUE TITLE
[FEATURE] <Zoom in profile picture>

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#497]
### Description

Hey, I want to add the zoom-in profile picture feature. If I click the profile picture then it is zoomed in. 
 
Like this
![image](https://github.com/narayan954/dummygram/assets/94003231/93d3cf34-dd8a-4e69-bdce-ec9886667293)

Please assign it to me under GSSOC'23.

**Comment by narayan954** [comment]
Hi @SubhamB2003 where do you want to add this feature, we may view profile picture in posts as well as profile.
Though I am expecting the profile.
Why? because currently if we click on the profile picture on posts , it redirects to their profile.
I think it'd be better when user is in profile page. Anyone, should be able to zoom in on the profile picture. And for the profile owner we can add option to modify the picture as well. Last one is optional and it'd upgrade this issue to level 2(modifying feature is present already, just need to move it there.

What're you opinions and suggestions on this?

**Comment by SubhamB2003** [comment]
> Hi @SubhamB2003 where do you want to add this feature, we can view profile picture in posts as well as profile. Though I am expecting the profile. Why? because currently if we click on the profile picture on posts , it redirects to their profile. I think it'd be better when user is in profile page. Anyone, should be able to zoom in on the profile picture. And for the profile owner we can add option to modify the picture as well. Last one is optional and it'd upgrade this issue to level 2(modifying feature is present already, just need to move it there.
> 
> What're you opinions and suggestions on this?

Yeah, I add this feature to only the profile page. After clicking the profile picture it zooms in so the user can see a better view of the profile picture.

**Comment by narayan954** [comment]
> clicking

cool go ahead!

**Comment by SubhamB2003** [comment]
> Reference in new

Hey, can you elaborate more on how can we modify it you saying this "And for the profile owner we can add an option to modify the picture as well"

**Comment by narayan954** [comment]
> > Reference in new
> 
> Hey, can you elaborate more on how can we modify it you saying this "And for the profile owner we can add an option to modify the picture as well"

there's already an option for profile owners to modify their profile picture by uploading another one. if we allow users to zoom on in the picture, we can add a update profile picture option in that popup/modal. Implementation can be copied almost

**Comment by SubhamB2003** [comment]
> > > Reference in new
> > 
> > 
> > Hey, can you elaborate more on how can we modify it you saying this "And for the profile owner we can add an option to modify the picture as well"
> 
> there's already an option for profile owners to modify their profile picture by uploading another one. if we allow users to zoom on in the picture, we can add a update profile picture option in that popup/modal. Implementation can be copied almost

Yeah, okk

**Comment by SubhamB2003** [comment]
> > > Reference in new
> > 
> > 
> > Hey, can you elaborate more on how can we modify it you saying this "And for the profile owner we can add an option to modify the picture as well"
> 
> there's already an option for profile owners to modify their profile picture by uploading another one. if we allow users to zoom on in the picture, we can add a update profile picture option in that popup/modal. Implementation can be copied almost

Hey, in update profile picture option after I choose the image the new image is not visible if I click save then after some time it is visible.

You can see here
Uploading profile.mp4…

I want to add a feature where after choose the new image it is visible instantly. Can I also add this feature ?
