### ISSUE TITLE
[FEATURE] :  Enhance Post Display in Feed for Larger Screens and Introduce Improved Post View Design

### ISSUE THREAD

**Issue by Kalyan-velu** [narayan954/dummygram#499]
### Description

Currently, when a user clicks on a post in the feed, the post is displayed in the same format as it appears in the feed. While this works well for smaller screens (less than 600px), it doesn't provide an optimal user experience on larger screens. The current design results in a cramped layout, making it difficult for users to read and interact with the content effectively.

In addition, there is an option to view comments, which opens a dialog component showing the post content and comments. However, I believe it would be more user-friendly to have a default view that showcases the post content along with the comments. This approach allows for a more immersive and engaging experience for users, particularly on larger screens.

## Proposed Solution:
To address these issues, I suggest implementing the following enhancements to the codebase:

 - Improved Post Display: When a user clicks on a post in the feed, the post should be displayed in a redesigned layout that optimizes the available screen space. This design should feature the post image or text prominently at the top of the screen, followed by the comments section below it. This approach ensures that users can easily view and engage with both the post and the associated comments without any visual clutter.

 - Responsive Design: The post-view design should be responsive to accommodate different screen sizes. For smaller screens, the default view can prioritize displaying the comments, allowing users to expand the post component to view the full content. This adaptive design ensures that the user experience remains consistent across devices, providing an optimal viewing experience regardless of screen size.

By implementing these changes, we can significantly improve the usability and visual appeal of the post view in the feed, catering to users on both small and large screens.

**Comment by narayan954** [comment]
> @narayan954 I would like to work on this if possible

yeah sure, looking into it

**Comment by Kalyan-velu** [comment]
Give it whatever level you think suitable. and also, It might take some time to finish it.

**Comment by narayan954** [comment]
> Give it whatever level you think suitable. and also, It might take some time to finish it.

alright, go ahead!
