### ISSUE TITLE
Add logo to profiles

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#5]
Add logo uploading option while signing up for profiles through firebase, so that each profile can have its own profile picture as logo.

**Comment by Ujjawal3** [comment]
HI @narayan954 can you assign me this task as a part of hacktoberfest?

**Comment by narayan954** [comment]
yeah sure @Ujjawal3

**Comment by narayan954** [comment]
are you working on this @Ujjawal3 ?

**Comment by Ujjawal3** [comment]
Ya @narayan954 will make pr by evening

**Comment by narayan954** [comment]
okayy take your time :)

**Comment by narayan954** [comment]
@Ujjawal3 with that feature added I am facing issues , please look into this

**Comment by narayan954** [comment]
![image](https://user-images.githubusercontent.com/77617189/193443785-6d2a843a-6445-4733-9934-c97c6e992256.png)

I signed up a new account and tried posting but neither my profile logo/avatar came nor the name,After that I logged out and sigined in again and posted , this time I have the username but still no logo/avatar :(. 
I am reverting the pr for now , please look into it
