### ISSUE TITLE
Darkmode not applicable on sidebar

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#502]
### Description

Darkmode is not working for sidebar
![Screenshot_2023-06-20-12-36-44-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/narayan954/dummygram/assets/92094765/b27ee12d-d886-417a-8aad-5b820512e46b)
Pls assign this to me under gssoc23

### Steps to reproduce

Open side bar

**Comment by narayan954** [comment]
Correct!, you can work on that!

**Comment by narayan954** [comment]
@Soulpurr  you can stop working on this, it's been resolved

**Comment by Soulpurr** [comment]
> @Soulpurr you can stop working on this, it's been resolved

Ok

**Comment by narayan954** [comment]
> > @Soulpurr you can stop working on this, it's been resolved
> 
> Ok

thanks for understanding
