### ISSUE TITLE
ISSUE: Different text size for buttons

### ISSUE THREAD

**Issue by DivyanshiNarang** [narayan954/dummygram#503]
### Description

The text size in buttons is different.

### Steps to reproduce

Making text size equal to maintain the consistency of the page.

### Screenshots

<img width="227" alt="Screenshot 2023-06-20 134313" src="https://github.com/narayan954/dummygram/assets/74779601/4aeff2c0-11d4-4709-889a-d2d2142bfd5b">

### Additional information

@*Please assign this issue to me under GSSoC'23*

**Comment by narayan954** [comment]
> ### Description
> The text size in buttons is different.
> 
> ### Steps to reproduce
> Making text size equal to maintain the consistency of the page.
> 
> ### Screenshots
> <img alt="Screenshot 2023-06-20 134313" width="227" src="https://user-images.githubusercontent.com/74779601/247050896-4aeff2c0-11d4-4709-889a-d2d2142bfd5b.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> @_Please assign this issue to me under GSSoC'23_

Go ahead!
