### ISSUE TITLE
[FEATURE] <UI Improvement>

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#504]
### Description

Hey, I want to improve the below portion ui
![image](https://github.com/narayan954/dummygram/assets/94003231/a8ceb017-0553-427c-95bc-fd539e63b44d)

And also I add the read more button yeah I know it's already added but it's not working properly.
![image](https://github.com/narayan954/dummygram/assets/94003231/70ded406-5c59-477d-99ae-cafd98f9106d)

Can you please assign it to me under the GSSOC'23?

**Comment by narayan954** [comment]
> ### Description
> Hey, I want to improve the below portion ui ![image](https://user-images.githubusercontent.com/94003231/247051779-a8ceb017-0553-427c-95bc-fd539e63b44d.png)
> 
> And also I add the read more button yeah I know it's already added but it's not working properly. ![image](https://user-images.githubusercontent.com/94003231/247052313-70ded406-5c59-477d-99ae-cafd98f9106d.png)
> 
> Can you please assign it to me under the GSSOC'23?
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

But why is the background picture not showing up on my end ;-;
![image](https://github.com/narayan954/dummygram/assets/77617189/87c74d9f-1c3d-4890-a14d-1cb6c50328df)

**Comment by narayan954** [comment]
> ### Description
> Hey, I want to improve the below portion ui ![image](https://user-images.githubusercontent.com/94003231/247051779-a8ceb017-0553-427c-95bc-fd539e63b44d.png)
> 
> And also I add the read more button yeah I know it's already added but it's not working properly. ![image](https://user-images.githubusercontent.com/94003231/247052313-70ded406-5c59-477d-99ae-cafd98f9106d.png)
> 
> Can you please assign it to me under the GSSOC'23?
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

You can go ahead on this!

**Comment by SubhamB2003** [comment]
> > ### Description
> > Hey, I want to improve the below portion ui ![image](https://user-images.githubusercontent.com/94003231/247051779-a8ceb017-0553-427c-95bc-fd539e63b44d.png)
> > And also I add the read more button yeah I know it's already added but it's not working properly. ![image](https://user-images.githubusercontent.com/94003231/247052313-70ded406-5c59-477d-99ae-cafd98f9106d.png)
> > Can you please assign it to me under the GSSOC'23?
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> You can go ahead on this!

thanks
