### ISSUE TITLE
ISSUE: Different font style

### ISSUE THREAD

**Issue by DivyanshiNarang** [narayan954/dummygram#505]
### Description

Different font styles making inconsistency on the page.

### Steps to reproduce

We can change the font to only one font style.

### Screenshots

<img width="113" alt="Screenshot 2023-06-20 134830" src="https://github.com/narayan954/dummygram/assets/74779601/e1851641-d61f-4451-ba9f-baa9d66c9ca0">

**Comment by narayan954** [comment]
> ### Description
> Different font styles making inconsistency on the page.
> 
> ### Steps to reproduce
> We can change the font to only one font style.
> 
> ### Screenshots
> <img alt="Screenshot 2023-06-20 134830" width="113" src="https://user-images.githubusercontent.com/74779601/247052135-e1851641-d61f-4451-ba9f-baa9d66c9ca0.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

sure you can fix that!
