### ISSUE TITLE
Sign Up page : Sign up form is not aligned properly

### ISSUE THREAD

**Issue by rishuraj1** [narayan954/dummygram#507]
### Description

In signup page, form is not aligned properly and ui looks simple and plain.
The profile picture section gets hidden.

### Steps to reproduce

Open the website of the project and click on sign up option on the sign in form. You will be directed to the signup page.

### Screenshots

Previous : 

<img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/47839626/445d1285-c16f-4d3b-9495-af22998de3b2">

proposed changes:

![image](https://github.com/narayan954/dummygram/assets/47839626/4c824790-67bb-411a-9618-019c13b2c351)

### Desktop (please complete the following information)

OS : Windows 11
Browser: Brave

### Additional information

I want to contribute to this project by fixing this issue. Can you please assign me to this issue under GSSoC '23.
Thank You!

**Comment by narayan954** [comment]
> ### Description
> In signup page, form is not aligned properly and ui looks simple and plain. The profile picture section gets hidden.
> 
> ### Steps to reproduce
> Open the website of the project and click on sign up option on the sign in form. You will be directed to the signup page.
> 
> ### Screenshots
> Previous :
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/47839626/247188143-445d1285-c16f-4d3b-9495-af22998de3b2.png">
> proposed changes:
> 
> ![image](https://user-images.githubusercontent.com/47839626/247188289-4c824790-67bb-411a-9618-019c13b2c351.png)
> 
> ### Desktop (please complete the following information)
> OS : Windows 11 Browser: Brave
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> I want to contribute to this project by fixing this issue. Can you please assign me to this issue under GSSoC '23. Thank You!

you can fix that!, thank you !
