### ISSUE TITLE
[FEATURE] <Change the All comments show modal>

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#508]
### Description

@narayan954 Hey, I want to change all comments' modal UI. I want to redesign it.

Can you assign it to me under GSSOC'23?

**Comment by narayan954** [comment]
sure go ahead!

**Comment by narayan954** [comment]
please use a materialistic approach and you'll get higher points

**Comment by SubhamB2003** [comment]
> please use a materialistic approach and you'll get higher points

The design should be like this first the profile pic of the commented user then the name below that time of creation and under all of that the comment text. But can you tell me how can I fetch the commented user profile pic bcz I don't have any IDs of that user

![image](https://github.com/narayan954/dummygram/assets/94003231/98d9cbc2-ce7c-42e4-a7f7-b32b8be72a47)

**Comment by narayan954** [comment]
> > please use a materialistic approach and you'll get higher points
> 
> The design should be like this first the profile pic of the commented user then the name below that time of creation and under all of that the comment text. But can you tell me how can I fetch the commented user profile pic bcz I don't have any IDs of that user
> 
> ![image](https://user-images.githubusercontent.com/94003231/247464930-98d9cbc2-ce7c-42e4-a7f7-b32b8be72a47.png)

See, as in the picture, comments is a nested collection and you can get these fields from this collection's documents
![image](https://github.com/narayan954/dummygram/assets/77617189/b9a78599-145b-4a69-be59-50a6b1674f45)

**Comment by narayan954** [comment]
> > please use a materialistic approach and you'll get higher points
> 
> The design should be like this first the profile pic of the commented user then the name below that time of creation and under all of that the comment text. But can you tell me how can I fetch the commented user profile pic bcz I don't have any IDs of that user
> 
> ![image](https://user-images.githubusercontent.com/94003231/247464930-98d9cbc2-ce7c-42e4-a7f7-b32b8be72a47.png)

okay you can work on this!

**Comment by SubhamB2003** [comment]
@narayan954 Hey, this is the new UI of the comment section I try to add the date but I can't

https://github.com/narayan954/dummygram/assets/94003231/31109b08-3f13-4fe9-9786-138f90a2597e

**Comment by narayan954** [comment]
> @narayan954 Hey, this is the new UI of the comment section I try to add the date but I can't If it's ok then I create the PR
> 
>  Untitled.mp4

Hi @SubhamB2003 , doesn't this look odd, check other social medias, comments are preferred to be on same line with username.. at the end you can put time.. I suppose comments might not have a timestamp that's why you're having problem with that.Will look into that. You can work on making this better and for the original show all comments modal, put that as a single click action on post.

**Comment by SubhamB2003** [comment]
@narayan954 Hey, Is it oke can you please check

https://github.com/narayan954/dummygram/assets/94003231/f46bb220-f824-45e7-b12b-e7fd8aa4eeae

**Comment by narayan954** [comment]
> @narayan954 Hey, Is it oke? Can you please check
> 
>  dummaygramCmt.mp4

this looks nice!!

**Comment by SubhamB2003** [comment]
> > @narayan954 Hey, Is it oke? Can you please check
> > dummaygramCmt.mp4
> 
> this looks nice!!

@narayan954 Hey, can I add read more button also in the comment bcz if someone is writing so many things then we should use the read more button. What did you say?

**Comment by narayan954** [comment]
> > > @narayan954 Hey, Is it oke? Can you please check
> > > dummaygramCmt.mp4
> > 
> > 
> > this looks nice!!
> 
> @narayan954 Hey, can I add a read more button also in the comment bcz if someone is writing so many things then we should use the read more button. What did you say? can I create PR? Just asking If I add this can you increase the level?

Yeah sure, you can add this!! and also, yes I'll increase the points if you test them as well on your end.

**Comment by SubhamB2003** [comment]
@narayan954 There are two examples which one I can select

https://github.com/narayan954/dummygram/assets/94003231/950103fc-ae00-4f2f-bd35-33b1d9e35401

https://github.com/narayan954/dummygram/assets/94003231/77b9b5ec-5765-40ee-8be6-a1c861589470

**Comment by narayan954** [comment]
> @narayan954 There are two examples which one I can select ?
> 
> https://github.com/narayan954/dummygram/assets/94003231/950103fc-ae00-4f2f-bd35-33b1d9e35401
> 
> https://github.com/narayan954/dummygram/assets/94003231/77b9b5ec-5765-40ee-8be6-a1c861589470
> 

first one's alright!
