### ISSUE TITLE
Add the prettier linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [narayan954/dummygram#509]
### Description

Add the prettier linter to ensure proper and uniform linting of the codebase. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

I would like to work on this as a part of GSSoC 23.

**Comment by narayan954** [comment]
> ### Description
> Add the prettier linter to ensure proper and uniform linting of the codebase. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.
> 
> I would like to work on this as a part of GSSoC 23.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi, there's already prettier action for this project, but it's not fixing contributors code. It's working if owner commits or something's off in the main repo. Can you try to fix that?

**Comment by metabiswadeep** [comment]
@narayan954 The prettier that you are talking about is implemented using deepsource which cannot perform autofix if the base branch of the PR and the current repo state dont match. So, a better way would be to implement prettier using GitHub actions as it would run on every push, commit and pull request.

**Comment by narayan954** [comment]
> @narayan954 The prettier that you are talking about is implemented using deepsource which cannot perform autofix if the base branch of the PR and the current repo state dont match. So, a better way would be to implement prettier using GitHub actions as it would run on every push, commit and pull request.

You're correct! you can work on this!

**Comment by narayan954** [comment]
> > @narayan954 The prettier that you are talking about is implemented using deepsource which cannot perform autofix if the base branch of the PR and the current repo state dont match. So, a better way would be to implement prettier using GitHub actions as it would run on every push, commit and pull request.
> 
> You're correct! you can work on this!

ensure/test for working as well.
