### ISSUE TITLE
[FEATURE] UI(Thread): Use MUI Alerts

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#51]
### Description

Currently, we're only using native browser alerts for notifications. It'd be a great improvement to use MUI alerts/dialogs to create a consistent UI.

**Comment by narayan954** [comment]
Indeed it would be a good improvement!

**Comment by warmachine028** [comment]
I would be happy to add the MUI alerts.

**Comment by narayan954** [comment]
Sure go ahead! 
Ps. Project is currently down for some hours, so you might face some issues for now.
