### ISSUE TITLE
[FEATURE] < Search Bar 

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#510]
### Description

As all the user most of time search for the friend I want to add search bar in this #dummygram project to make easy use.

**Comment by narayan954** [comment]
> ### Description
> As all the user most of time search for the friend I want to add search bar in this #dummygram project to make easy use.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @BhartiNagpure you can work on this!

**Comment by BhartiNagpure** [comment]
@narayan954  project webage show unresponsive when open in browser.

**Comment by narayan954** [comment]
> @narayan954 project webage show unresponsive when open in browser.

can you please show the error?

**Comment by BhartiNagpure** [comment]
![2023-06-23 (1)](https://github.com/narayan954/dummygram/assets/104631882/bc908311-d842-404d-a5e1-2f26f08c0568)

**Comment by narayan954** [comment]
> ![2023-06-23 (1)](https://user-images.githubusercontent.com/104631882/248240977-bc908311-d842-404d-a5e1-2f26f08c0568.png)

can you try another browser?

**Comment by BhartiNagpure** [comment]
yes 
![2023-06-23 (2)](https://github.com/narayan954/dummygram/assets/104631882/96cf4b11-478d-4ac7-95bb-3df9047cd06f)

**Comment by narayan954** [comment]
> yes ![2023-06-23 (2)](https://user-images.githubusercontent.com/104631882/248246647-96cf4b11-478d-4ac7-95bb-3df9047cd06f.png)

Okay so, 
First of all update your fork using git commands. You fork is behind our current branch and if some features have been changed and are critical, they'd be breaking your version. 
If this doesn't solve, try opening the console and if there're errors, show them in a screenshot.

Also check to reinstall the modules after deleting old ones (remove the node modules folder and then `npm i -f` )

**Comment by BhartiNagpure** [comment]
still it not showing webpage

**Comment by narayan954** [comment]
> still it not showing webpage

Ohh, I faced this error on my browser with this pr as well, your implementation has some resource heavy implementation I believe. I'm looking into it as well

**Comment by narayan954** [comment]
> > still it not showing webpage
> 
> Ohh, I faced this error on my browser with this pr as well, your implementation has some resource heavy bug I believe. I'm looking into it as well

I fixed it, you mistakenly put a duplicate search component at the wrong place and it was trying to render in the bg all the time

**Comment by BhartiNagpure** [comment]
Where ?

**Comment by BhartiNagpure** [comment]
> > > still it not showing webpage
> > 
> > 
> > Ohh, I faced this error on my browser with this pr as well, your implementation has some resource heavy bug I believe. I'm looking into it as well
> 
> I fixed it, you mistakenly put a duplicate search component at the wrong place and it was trying to render in the bg all the time

Thanku for fixing error
