### ISSUE TITLE
I will be improving hover effect of the posts

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [narayan954/dummygram#515]
### Description

When we hover the post the font dissapears from it

### Steps to reproduce

When we hover the post

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/85278243/d46960fd-9e7a-4df1-bce3-24fdc71e79f9)
![image](https://github.com/narayan954/dummygram/assets/85278243/8ba85a06-42a6-44ce-a4fe-c912b1d33867)

### Additional information

Please assign me this issue under GSSOC'23

**Comment by narayan954** [comment]
> ### Description
> When we hover the post the font dissapears from it
> 
> ### Steps to reproduce
> When we hover the post
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/85278243/247503667-d46960fd-9e7a-4df1-bce3-24fdc71e79f9.png) ![image](https://user-images.githubusercontent.com/85278243/247503710-8ba85a06-42a6-44ce-a4fe-c912b1d33867.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> Please assign me this issue under GSSOC'23

I think this issue has already been raised and assigned, can you confirm that. If issue has been assigned over a week, you can claim the issue

**Comment by narayan954** [comment]
> @narayan954 It has been 7 days since the issue has been raised
> Please assign it to me if possible
> I will be working on it
> 
> Issue : https://github.com/narayan954/dummygram/issues/475

comment there so I can assign you
