### ISSUE TITLE
[FEATURE] Add CodeQL Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [narayan954/dummygram#518]
### Description

Although the repository has javascript code, it lacks workflow for code inspection.

The codeql.yml workflow file will be added by me to automate security checks.

CodeQL is a code analysis tool, to find vulnerabilities in programs. The code will be examined, and the results will be presented as code scanning alerts. Every push, commit, and pull request that uses GitHub actions will have it enabled.

### Additional information

I want to work on this issue under GSSoC'23

**Comment by narayan954** [comment]
> ### Description
> 
> Although the repository has javascript code, it lacks workflow for code inspection.
> 
> The codeql.yml workflow file will be added by me to automate security checks.
> 
> CodeQL is a code analysis tool, to find vulnerabilities in programs. The code will be examined, and the results will be presented as code scanning alerts. Every push, commit, and pull request that uses GitHub actions will have it enabled.
> ### Screenshots
> 
> _No response_
> ### Additional information
> 
> I want to work on this issue under GSSoC'23

Hi @abhinav-m22  codeql workflow exists already as you can see.
![image](https://github.com/narayan954/dummygram/assets/77617189/c519cdac-f60f-41e3-924f-27d40d0c90fe)

**Comment by narayan954** [comment]
> @narayan954 Yes but there is no yml script in the repository. I think adding that particular file will make the codebase standard and other people can understand about the working of codeql and it's properties.
> 
> That's the reason I created the issue. Please give a think and let me know!

Agreed, you can fix this!
