### ISSUE TITLE
[Add Guest signin] 

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#521]
### Description

Allow guests to enter our application and test it without needing to sign up. This would be really useful to show the app to anyone.

You can use the resource mentioned in the comments to implement this functionality

**Comment by narayan954** [comment]
[Resource](https://itnext.io/firebase-guest-access-38775cde50b3) for more info on this

**Comment by narayan954** [comment]
![image](https://github.com/narayan954/dummygram/assets/77617189/d8430ff0-4d32-429e-9191-84feb334378d)
I've also enabled anonymouse sign in

**Comment by VijayalakshmiGanesh** [comment]
I would like to work on this issue under GSSOC'23 label.

**Comment by narayan954** [comment]
> I would like to work on this issue under GSSOC'23 label.

sure you can go ahead!

**Comment by Palakkgoyal** [comment]
Hey @narayan954 Can I work on this?

**Comment by VijayalakshmiGanesh** [comment]
> Hey @narayan954 Can I work on this?

Hey, you can work on it. I am not getting time.

**Comment by Palakkgoyal** [comment]
@narayan954 to create the guest sign in I need you to go to firebase then to authentication and in authentication go to signin methods and enable anonymous.
Besides enabling Anonymous Sign-In method , make sure to check Enable create (sign-up) in the User actions section of the Authentication Settings of the Firebase console.
![72Txg](https://github.com/narayan954/dummygram/assets/116902573/ffbc9c24-9c07-4b77-bf30-2985a3583328)

**Comment by narayan954** [comment]
> @narayan954 to create the guest sign in I need you to go to firebase then to authentication and in authentication go to signin methods and enable anonymous.
> Besides enabling Anonymous Sign-In method , make sure to check Enable create (sign-up) in the User actions section of the Authentication Settings of the Firebase console.
> ![72Txg](https://github.com/narayan954/dummygram/assets/116902573/ffbc9c24-9c07-4b77-bf30-2985a3583328)
> 

that's a paid service :/ 
![IMG_20230718_201825.jpg](https://github.com/narayan954/dummygram/assets/77617189/95c36a1c-bf84-49f4-84b9-2640a783544a)

won't this work? I think this'dve worked 
according to [this  tutorial](https://firebase.google.com/docs/auth/web/anonymous-auth)

**Comment by narayan954** [comment]
> enabled!!

understood, this'd enable those guest account to convert to real accounts nah?

**Comment by Palakkgoyal** [comment]
> > enabled!!
> 
> understood, this'd enable those guest account to convert to real accounts nah?

Yes, exactly you are right. By this we will be able to let the user sign up in their guest account
