### ISSUE TITLE
Download Option bug for Text posts

### ISSUE THREAD

**Issue by Deepanshu0703** [narayan954/dummygram#523]
### Description

If you click on download in text based project it will not download anything and there is no meaning of downloading a text based post so i think download option should not be there for text posts

### Steps to reproduce

I will simply filter post having images aor other multimedia or not and implement whether to download or not.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/114489502/5625f030-ffec-40d0-aac0-5ae658027ee4)

### Desktop (please complete the following information)

OS- Windows
Browser -Chrome
version -Latest

**Comment by narayan954** [comment]
you can go ahead!
