### ISSUE TITLE
Alignment of scroll to Top button in profile page

### ISSUE THREAD

**Issue by Deepanshu0703** [narayan954/dummygram#525]
### Description

Alignment of scroll to Top button in profile page is not in proper . It is cutting the posts

### Steps to reproduce

I will change the css of it to make it look better. I will make in right side.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/114489502/ac1c1df1-7646-46b6-9aa6-268ed4192c5f)

**Comment by narayan954** [comment]
Yes, you can fix that!

**Comment by Deepanshu0703** [comment]
Can you confirm it is ok or not  then i will make the PR @narayan954 

## Profile page

![image](https://github.com/narayan954/dummygram/assets/114489502/ddd0b1ad-ab5f-4b82-bc3e-61ab2717635a)

![image](https://github.com/narayan954/dummygram/assets/114489502/b7a08bda-9b93-4c7b-a26f-e77daff90745)


## Home page
![image](https://github.com/narayan954/dummygram/assets/114489502/499ef855-86f9-4b87-bb75-7a825aabceb1)

![image](https://github.com/narayan954/dummygram/assets/114489502/3f6a580b-e717-46b9-823f-fb75b88c94e0)

**Comment by narayan954** [comment]
> Can you confirm it is ok or not then i will make the PR @narayan954
> 
> ## Profile page
> ![image](https://user-images.githubusercontent.com/114489502/247898690-ddd0b1ad-ab5f-4b82-bc3e-61ab2717635a.png)
> 
> ![image](https://user-images.githubusercontent.com/114489502/247899188-b7a08bda-9b93-4c7b-a26f-e77daff90745.png)
> 
> ## Home page
> ![image](https://user-images.githubusercontent.com/114489502/247898876-499ef855-86f9-4b87-bb75-7a825aabceb1.png)
> 
> ![image](https://user-images.githubusercontent.com/114489502/247899058-3f6a580b-e717-46b9-823f-fb75b88c94e0.png)

Can you try to make it at the center of the post feed when in column mode, and let it be like this when in row mode? Else it's fine

**Comment by Deepanshu0703** [comment]
posts are always in column mode in postView and posts are in coloumn mode and row mode  (according to screen size ) in profile feed. So i will make the scroll to top button in left in row mode and in centre for column  mode for profile feed and in post feed making it always in centre as it was earlier. Is that okay.

**Comment by narayan954** [comment]
> posts are always in column mode in postView and posts are in coloumn mode and row mode (according to screen size ) in profile feed. So i will make the scroll to top button in left in row mode and in centre for column mode for profile feed and in post feed making it always in centre as it was earlier. Is that okay.

yeah that'd be fine!
