### ISSUE TITLE
Add Bio feature on profile

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#527]
### Description

Currently, the profile only contain name, email and DP. I want to add a new feature of bio which user can display and edit anytime according to his/her need.

**Comment by narayan954** [comment]
> ### Description
> Currently, the profile only contain name, email and DP. I want to add a new feature of bio which user can display and edit anytime according to his/her need.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @Palakkgoyal this issue already exists, please either claim the original issue or wait for it to be inactive and close this as duplicate issue.

Thanks
