### ISSUE TITLE
Update the UI of Profile page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#528]
### What would you like to share?

Currently, the UI of profile page doesn't look attractive. I want to update the UI
![Screenshot 2023-06-22 160237](https://github.com/narayan954/dummygram/assets/116902573/e523809d-a48b-46fe-926b-ef2048478064)

**Comment by narayan954** [comment]
> ### What would you like to share?
> Currently, the UI of profile page doesn't look attractive. I want to update the UI ![Screenshot 2023-06-22 160237](https://user-images.githubusercontent.com/116902573/247904085-e523809d-a48b-46fe-926b-ef2048478064.png)
> 
> ### Additional information
> _No response_

this issue exists as well, please check
