### ISSUE TITLE
Dark Mode makes text unreadable on hover

### ISSUE THREAD

**Issue by ManavMalhotra** [narayan954/dummygram#534]
### Description

When using Dark Mode, hovering over text causes it to become unreadable. This issue affects the user experience and needs to be addressed.

### Steps to reproduce

Use Dark Mode and Hover on the post

### Screenshots

https://github.com/narayan954/dummygram/assets/64147782/ef7db403-3dc6-4cfb-95ce-1e8a786506c2

**Comment by ManavMalhotra** [comment]
Please assign this task to me under GSSOC'23 , I can fix this issue

**Comment by narayan954** [comment]
@ManavMalhotra  this issue already exists, can you check that?
