### ISSUE TITLE
Add cursor pointer for "Read More" and "Show Less" in post content

### ISSUE THREAD

**Issue by ManavMalhotra** [narayan954/dummygram#535]
### Description

The "Read More" and "Show Less" options in the content of a post should have a cursor pointer when hovered over to indicate that they are clickable. This will improve the user experience and make it more intuitive to interact with the post.

### Steps to reproduce

Click on the read more in the content 

### Screenshots

https://github.com/narayan954/dummygram/assets/64147782/83f61a8f-53ef-4e6c-8975-691a36464d31

**Comment by narayan954** [comment]
you can go ahead!

**Comment by ManavMalhotra** [comment]
#546 Please check 


https://github.com/narayan954/dummygram/assets/64147782/250b8b90-ce83-4417-b1a3-859286d13fd2
