### ISSUE TITLE
[FEATURE] Add toggle functionality to Save Post

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [narayan954/dummygram#536]
### Description

I would like to add toggle functionality to Save button.  If the post is already in your saved list, on clicking it should remove and vice versa.

Also, add a color to the Save icon when the post is already in your Favorites list so that the end user knows the post is already saved.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104077094/ab53e7ba-e169-4082-ac30-5d413ca26110)

**Comment by narayan954** [comment]
> ### Description
> I would like to add toggle functionality to Save button. If the post is already in your saved list, on clicking it should remove and vice versa.
> 
> Also, add a color to the Save icon when the post is already in your Favorites list so that the end user knows the post is already saved.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/104077094/247989460-ab53e7ba-e169-4082-ac30-5d413ca26110.png)
> 
> ### Additional information
> _No response_

you can go ahead!

**Comment by VijayalakshmiGanesh** [comment]
@narayan954, created PR. Kindly check.
