### ISSUE TITLE
Responsive: Dark/light mode btn is not fully visible 

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [narayan954/dummygram#537]
### Description

In smaller screens, Dark/light mode button is not fully visible 

### Steps to reproduce

When scrolling down, theme button goes behind the navBar

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104077094/f33ec494-9239-4a64-99f3-a30fcc1e56a6)

### Smartphone (please complete the following information)

![image](https://github.com/narayan954/dummygram/assets/104077094/5652ced2-029c-4e8e-ba91-1afc0a92e51f)

**Comment by VijayalakshmiGanesh** [comment]
I would like to work on this issue GSSOC'23 label

**Comment by narayan954** [comment]
> ### Description
> In smaller screens, Dark/light mode button is not fully visible
> 
> ### Steps to reproduce
> When scrolling down, theme button goes behind the navBar
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/104077094/247990611-f33ec494-9239-4a64-99f3-a30fcc1e56a6.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> ![image](https://user-images.githubusercontent.com/104077094/247994653-5652ced2-029c-4e8e-ba91-1afc0a92e51f.png)
> 
> ### Additional information
> _No response_

Yes, can you add the theme switch at the sidebar for big screens and at navbar in smaller screens?
