### ISSUE TITLE
[FEATURE] would like add a chat bot in form of chatgpt

### ISSUE THREAD

**Issue by Soulpurr** [narayan954/dummygram#538]
### Description

I would like to add a chat bot to which users can talk.
Pls assign this to me under gssoc 23

**Comment by narayan954** [comment]
> ### Description
> I would like to add a chat bot to which users can talk. Pls assign this to me under gssoc 23
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

this issue already exists, please claim that, closing this as duplicate
