### ISSUE TITLE
Dark mode is not implemented properly

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#541]
### Description

Currently, the dark mode is just inverting the gray scale of all the colors which makes the UI of website less attractive. 
For example: The like, comment, share icons on the post disappear and when we hover the post their text also disappear.
There doesn't seem to be any hover effect on the sidebar in dark mode etc.
I want to rewrite the whole dark mode feature and implement it on the basis of each and every color of the whole  website. 

### Steps to reproduce

Click on dark mode button

### Screenshots

![Screenshot (557)](https://github.com/narayan954/dummygram/assets/116902573/ed4bf9b6-73fe-4225-8d63-831b1e73ee6c)

**Comment by narayan954** [comment]
> ### Description
> Currently, the dark mode is just inverting the gray scale of all the colors which makes the UI of website less attractive. For example: The like, comment, share icons on the post disappear and when we hover the post their text also disappear. There doesn't seem to be any hover effect on the sidebar in dark mode etc. I want to rewrite the whole dark mode feature and implement it on the basis of each and every color of the whole website.
> 
> ### Steps to reproduce
> Click on dark mode button
> 
> ### Screenshots
> ![Screenshot (557)](https://user-images.githubusercontent.com/116902573/248125855-ed4bf9b6-73fe-4225-8d63-831b1e73ee6c.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

you can work on this, after I merge the refactoring pr, so no conflicts arise.

**Comment by Palakkgoyal** [comment]
Can I work on this now?

**Comment by narayan954** [comment]
> Can I work on this now?

yes sure, if you're free. You've taken up many issues, so just so you don't get overwhelmed, try solving one at a time. 
Best of luck!
