### ISSUE TITLE
[FEATURE] Implement a footer in the sidebar

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#542]
### Description

As you before told me that you want a footer to be implemented in the sidebar. I want to add that. 
Can you please resend the screenshots you sent before or can you please tell what you might want to be included in the footer.

**Comment by narayan954** [comment]
> ### Description
> As you before told me that you want a footer to be implemented in the sidebar. I want to add that. Can you please resend the screenshots you sent before or can you please tell what you might want to be included in the footer.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

you can go ahead, I'll be adding them in some time. Meanwhile for an initial footer, any idea should do and refer to the comment where I said these things, it should be one of the issues I believe.

**Comment by narayan954** [comment]
sorry I didn't provide any resources, but we just needed a simple footer to start, so any design should do
