### ISSUE TITLE
[FEATURE] Have a unique username

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#544]
### Description

The website just have name and email. I want to give every user a unique username which will make it easy to identify any user with the help of their username rather than their email. As the names could be duplicated but username can't which in turn will help in easy implementation of following and followers list on dummygram.

**Comment by narayan954** [comment]
> ### Description
> The website just have name and email. I want to give every user a unique username which will make it easy to identify any user with the help of their username rather than their email. As the names could be duplicated but username can't which in turn will help in easy implementation of following and followers list on dummygram.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Correct.. Also when signing up through oauth, username is added by default and same as display name.You may make that email id...this'd help I believe in making them unique.
