### ISSUE TITLE
Refactoring the Codebase

### ISSUE THREAD

**Issue by Kalyan-velu** [narayan954/dummygram#545]
### Description
The codebase requires a comprehensive refactoring effort to address its current messy state. The codebase lacks a specific styling method, resulting in a mixture of SASS, CSS, inline CSS, and Material UI approaches. This inconsistency makes the code difficult to manage and maintain. Additionally, the code files are excessively large, ranging from 300 lines to 700 or 800 lines, which hinders debugging and introduces complexity when adding new features.

To address these issues and improve the codebase, the following actions are proposed:

1. Centralize Common Components and Styles: Establish a dedicated folder or directory to store common components and styles. This centralization will promote code reuse, enhance consistency, and simplify maintenance.

2. Separate Complex Logic from Component Files: Extract substantial logic blocks from component files and create separate modules or files. This practice will improve code readability, enable easier debugging, and facilitate the reuse of logic across multiple components or files.

3. Incremental Refactoring: Due to the size of the codebase and the potential challenges associated with making sweeping changes, it is recommended to adopt a phased approach to refactoring. Breaking down the task into manageable parts will minimize disruptions and help identify and address issues more effectively.

4. Utilize React Suspense for Performance Improvement: Incorporate React Suspense, a feature that enables declarative handling of loading states, to enhance the performance of the application. This will ensure smoother rendering and improve user experience.

### Approach for this Issue
To address the codebase's messiness, we will follow these steps:

1. Review the entire codebase and identify the areas that require refactoring, focusing on inconsistent styling methods, large code files, and complex logic within component files.
2. Create a new folder or directory to centralize common components and styles. Move relevant components and styles to this folder and update the codebase accordingly.
3. Extract complex logic from component files and create separate modules or files. Update the affected components to import and utilize these logic modules.
4. Divide the refactoring process into manageable parts. Identify specific sections or features to refactor and proceed incrementally to minimize disruptions and potential issues.
5. Integrate React Suspense into the project, leveraging its performance benefits. Update the relevant components to implement React Suspense for handling loading states.

### Project Admins
Please review and provide your suggestions, guidance, and any specific instructions regarding the proposed codebase refactoring. Your input is vital in ensuring a successful and coordinated refactoring effort.

**Comment by Kalyan-velu** [comment]
@narayan954 I would like to work on this.

**Comment by narayan954** [comment]
refactoring is already in pr review process and issue already exists, please check

**Comment by narayan954** [comment]
@Kalyan-velu you can refactor or fix it more later

**Comment by Kalyan-velu** [comment]
> @Kalyan-velu you can refactor or fix it more later

I don't quite understand what you meant by that.

**Comment by narayan954** [comment]
> > @Kalyan-velu you can refactor or fix it more later
> 
> I don't quite understand what you meant by that.

after refactoring, if something is left, you can work on that!
