### ISSUE TITLE
[FEATURE] Add a bell sound whenever an event occurs

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#551]
### Description

I want to add different sounds for different events. For example 
- when the user sign up successfully then, with the snackbar there is also a bell sound
- if sign up unsuccessfull then an error kind of sound
- post sent successfully
- image edited successfully
- Logged out
- Pressed back
Further in new issues I would like to create a settings page in which user can select whether they want to turn off the sound.

**Comment by narayan954** [comment]
> ### Description
> I want to add different sounds for different events. For example
> 
> * when the user sign up successfully then, with the snackbar there is also a bell sound
> * if sign up unsuccessfull then an error kind of sound
> * post sent successfully
> * image edited successfully
> * Logged out
> * Pressed back
>   Further in new issues I would like to create a settings page in which user can select whether they want to turn off the sound.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

That's really an awesome feature. You can work on this!
