### ISSUE TITLE
[FEATURE] Create about page for dummygram

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#552]
### Description

There is no about page for dummygram. I want to create a clean looking yet modern about page. 

### Additional information

I think the link of this page must not be in the navbar rather it should be included in the footer sidebar.

**Comment by narayan954** [comment]
> ### Description
> There is no about page for dummygram. I want to create a clean looking yet modern about page.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> I think the link of this page must not be in the navbar rather it should be included in the footer sidebar.

yes we may have that!
