### ISSUE TITLE
[Add hover effect on Profile, Favourites, Log out]

### ISSUE THREAD

**Issue by akshaysoni10** [narayan954/dummygram#553]
### Description

Under user logo I want to add hover effect on Profile, Favourites and Log Out to make it more attractive. Please assign me this task under **GSSoC'23**.

**Comment by Riyazul555** [comment]
Hey @narayan954 I want to handle this issue.... please assign me this

**Comment by narayan954** [comment]
> ### Description
> Under user logo I want to add hover effect on Profile, Favourites and Log Out to make it more attractive. Please assign me this task under **GSSoC'23**.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @akshaysoni10 actually we're removing that option and moving completely to sidebar, so it's not much needed. But thanks for raising the issue

**Comment by narayan954** [comment]
I'm closing this as not required right now
