### ISSUE TITLE
[FEATURE] Create a guidelines page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#555]
### Description

The guideline page will include how to contribute to the project. Its somewhat like the README but if we add this as a new page to the website with a nice UI it will look more good.

**Comment by narayan954** [comment]
> ### Description
> The guideline page will include how to contribute to the project. Its somewhat like the README but if we add this as a new page to the website with a nice UI it will look more good.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

will need to discuss more on this. This requires a lot of hard work so need to understand if this is actually needed.

**Comment by Palakkgoyal** [comment]
I think we should have it but not like README, instead it should be like real guidelines page which will include user conduct, safety and security, how they should behave otherwise they would be banned. etc.
What do you think?

**Comment by narayan954** [comment]
> I think we should have it but not like README, instead it should be like real guidelines page which will include user conduct, safety and security, how they should behave otherwise they would be banned. etc. What do you think?

Yes, that'd be great. You can work on this! :)
