### ISSUE TITLE
Image is not updated in old posts

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#556]
### Description

If we edit the image then, in the old posts the old image is shown and not the new one.

### Steps to reproduce

- Create a post
- Edit your profile image
- Create a new post

In both the posts the profile picture will be different.

**Comment by Palakkgoyal** [comment]
![Screenshot 2023-06-24 160435](https://github.com/narayan954/dummygram/assets/116902573/a17ab859-7af7-41ba-b2ed-5cb10f0432b9)

**Comment by narayan954** [comment]
> ### Description
> If we edit the image then, in the old posts the old image is shown and not the new one.
> 
> ### Steps to reproduce
> * Create a post
> * Edit your profile image
> * Create a new post
> 
> In both the posts the profile picture will be different.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

glad you noticed! this needs to be fixed. Also it's permanent for a post.

**Comment by Palakkgoyal** [comment]
Yes, and if we let the user to change their display name then the same problem will occur with names too.

**Comment by narayan954** [comment]
> Yes, and if we let the user to change their display name then the same problem will occur with names too.

It's because, avatar and username are hard code into the posts as in the picture
![image](https://github.com/narayan954/dummygram/assets/77617189/4491dbea-f776-4546-ac01-9d5d7dc44fb6)
we can instead store user ref I believe and post header are loaded from user collection.
Is the solution, ok? or what should we do?

**Comment by Palakkgoyal** [comment]
Yes, I think this solution would be ok.

**Comment by Palakkgoyal** [comment]
Hey @narayan954 I know the signup and signin page UI is changed a lot of time but, do you really think this one looks good or the previous was better. If you think so, can I create a new issue for its UI and its is also not compatible with dark mode. I mean image background is still white and the input placeholder text become invisible.
![Screenshot (601)](https://github.com/narayan954/dummygram/assets/116902573/e46f61bb-47dd-4df2-b1c7-97a429972d2a)

**Comment by narayan954** [comment]
> Hey @narayan954 I know the signup and signin page UI is changed a lot of time but, do you really think this one looks good or the previous was better. If you think so, can I create a new issue for its UI and its is also not compatible with dark mode. I mean image background is still white and the input placeholder text become invisible. ![Screenshot (601)](https://user-images.githubusercontent.com/116902573/253806892-e46f61bb-47dd-4df2-b1c7-97a429972d2a.png)

That image is the root of all evil I believe now XD. Actually sign up page UI improvement (yet again) is already in progress.
I'm hoping to get the signup page in sync with login page, and for the overflow, scroll could be an option for the form area. What  do you think about this?
Also, about dark mode, yeah you're correct this image is not compatible at all. I think we might need to find an SVG for the these login/signup page.

**Comment by Palakkgoyal** [comment]
I think we even don't need an image. Instead we can give a minimalistic look by adding logo and a line about dummygram. 
![Screenshot (603)](https://github.com/narayan954/dummygram/assets/116902573/3b0501fe-c72b-4c5b-be46-66f5b3c29cab)
![Screenshot (604)](https://github.com/narayan954/dummygram/assets/116902573/94fa917d-050b-4b40-8f3e-3c65d1b0e322)
![Screenshot (605)](https://github.com/narayan954/dummygram/assets/116902573/c39ede8c-534b-4ba0-9509-11475868457c)
![Screenshot (606)](https://github.com/narayan954/dummygram/assets/116902573/8cbd4280-67cc-41fd-bbb6-a2edca6c7895)
![Screenshot (607)](https://github.com/narayan954/dummygram/assets/116902573/b978d938-5ad3-474e-809f-8627b1239460)

**Comment by narayan954** [comment]
> I think we even don't need an image. Instead we can give a minimalistic look by adding logo and a line about dummygram. ![Screenshot (603)](https://user-images.githubusercontent.com/116902573/253853363-3b0501fe-c72b-4c5b-be46-66f5b3c29cab.png) ![Screenshot (604)](https://user-images.githubusercontent.com/116902573/253853413-94fa917d-050b-4b40-8f3e-3c65d1b0e322.png) ![Screenshot (605)](https://user-images.githubusercontent.com/116902573/253853417-c39ede8c-534b-4ba0-9509-11475868457c.png) ![Screenshot (606)](https://user-images.githubusercontent.com/116902573/253853423-8cbd4280-67cc-41fd-bbb6-a2edca6c7895.png) ![Screenshot (607)](https://user-images.githubusercontent.com/116902573/253853429-b978d938-5ad3-474e-809f-8627b1239460.png)

indeed, that'd look amazing but I've assigned someone an issue regarding designing a new image for this page :'')

**Comment by Palakkgoyal** [comment]
Yes, I think that would look good and you should discuss with them regarding this. It would not look bad if the image is compatible with the look but I think without image it would look more nice.

**Comment by narayan954** [comment]
> Yes, I think that would look good and you should discuss with them regarding this. It would not look bad if the image is compatible with the look but I think without image it would look more nice.

yes, earlier it was without any image, but everyone was raising issue to improve it, so I let them at last, and here we are. Some people here be rearranging elements and calling it redesigning ;-;
