### ISSUE TITLE
Creating users collections.

### ISSUE THREAD

**Issue by gitpugal** [narayan954/dummygram#560]
### Description

I think we need to create an users collection when the users signup, so that we can do many of the tasks like users search, friend requests, favorites into one organized document for each user.

**Comment by gitpugal** [comment]
yes I can work on this issue and can I know the schema for the users collection.

**Comment by narayan954** [comment]
> ### Description
> I think we need to create an users collection when the users signup, so that we can do many of the tasks like users search, friend requests, favourites into one organised document for each user.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

So, are you suggesting, we use db to authenticate instead of Firebase authentication? Well, you don't seem wrong... it's just that we're using it everywhere and it'd be hard to migrate. What're your opinions on this?

**Comment by gitpugal** [comment]
No, we can stick to Firebase authentication for authenticating the users and store the other profile details in the user schema
so that we scale up to more functionalities and reduce the number of requests as we will get all the generic information about the user and their connections through minimal requests.

**Comment by narayan954** [comment]
> No, we can stick to Firebase authentication for authenticating the users and store the other profile details in the user schema so that we scale up to more functionalities and reduce the number of requests as we will get all the generic information about the user and their connections through minimal requests.

That's a win win, you can work on this!

**Comment by gitpugal** [comment]
<img width="420" alt="dgSchema" src="https://github.com/narayan954/dummygram/assets/45727933/f93260ea-1ee7-432f-b56d-7360f7e3c239">


Is this Schema ok for the schema migration?

**Comment by narayan954** [comment]
> <img alt="dgSchema" width="420" src="https://user-images.githubusercontent.com/45727933/250175740-f93260ea-1ee7-432f-b56d-7360f7e3c239.png">
> Is this Schema ok for the schema migration?

yes it looks great @gitpugal , by the way, post array should be a ref to the post collection, right?. This'd really help in maintaining feed with timestamps, right?

**Comment by gitpugal** [comment]
Sorry I've made a mistake, the post array in users collection will only contain post ID Ref's of that user's posts.
So We can retain the Previous posts collection we've already had and only include the post ID of that user in their posts array in their user document.

**Comment by gitpugal** [comment]
<img width="275" alt="Screenshot (336)" src="https://github.com/narayan954/dummygram/assets/45727933/74d279c7-3ba4-4ebb-90d4-e6a4b97393ae">


I think this schema is fine?

**Comment by gitpugal** [comment]
<img width="282" alt="Screenshot (337)" src="https://github.com/narayan954/dummygram/assets/45727933/6bc621d0-a4f3-4bbc-a532-95490e4071ae">

Is this Schema fine?

**Comment by narayan954** [comment]
> <img alt="Screenshot (337)" width="282" src="https://user-images.githubusercontent.com/45727933/250273454-6bc621d0-a4f3-4bbc-a532-95490e4071ae.png">
> Is this Schema fine?

Yes it's fine

**Comment by narayan954** [comment]
> Sorry I've made a mistake, the post array in users collection will only contain post ID Ref's of that user's posts. So We can retain the Previous posts collection we've already had and only include the post ID of that user in their posts array in their user document.

it's alright

**Comment by gitpugal** [comment]
Is it ok if we use nested collections inside users collections for Friendrequests, Notifications and Friends instead of array as I mentioned earlier

**Comment by narayan954** [comment]
> Is it ok if we use nested collections inside users collections for Friendrequests, Notifications and Friends instead of array as I mentioned earlier

if by design the amount of sub-data you want to store is limited and very low, you should use arrays, since you reduce the number of document reads, which means lower costs.

**Comment by narayan954** [comment]
> Is it ok if we use nested collections inside users collections for Friendrequests, Notifications and Friends instead of array as I mentioned earlier

both are ok.

**Comment by gitpugal** [comment]
I think we can proceed with subcollections  approach because with arrays we are having some downsides with accessing which is not efficient,
but with subcollections we can do reads and writes faster than arrays with Doc-Id and also it brings all the data under one hood and we can also reduce the reads by only querying the subcollections we need.

**Comment by narayan954** [comment]
> I think we can proceed with subcollections approach because with arrays we are having some downsides with accessing which is not efficient, but with subcollections we can do reads and writes faster than arrays with Doc-Id and also it brings all the data under one hood and we can also reduce the reads by only querying the subcollections we need.

yes that works @gitpugal , you can go ahead! :)

**Comment by gitpugal** [comment]
Yeah, I am working on it @narayan954 .
