### ISSUE TITLE
Set a loader on favorite page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#562]
### Description

When we have some posts as favorite but, when we go to the favorite page it seems empty initially as if there are no favorites which leads to bad user experience.
I want to fix this bug.

### Steps to reproduce

Add a post to favorite
Go to favorite page
It is empty until the data is loaded

### Screenshots

![Screenshot 2023-06-24 232112](https://github.com/narayan954/dummygram/assets/116902573/1b8e6872-6b71-4638-a307-dd6484312dcb)

**Comment by narayan954** [comment]
> ### Description
> When we have some posts as favorite but, when we go to the favorite page it seems empty initially as if there are no favorites which leads to bad user experience. I want to fix this bug.
> 
> ### Steps to reproduce
> Add a post to favorite Go to favorite page It is empty until the data is loaded
> 
> ### Screenshots
> ![Screenshot 2023-06-24 232112](https://user-images.githubusercontent.com/116902573/248504677-1b8e6872-6b71-4638-a307-dd6484312dcb.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

you're right and you can work on this!
