### ISSUE TITLE
Long posts mess with other posts

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#563]
### Description

When a post has so much written into it and if the layout is multi-column then, it mess the UI of other posts by stretching them.

### Steps to reproduce

Find a long post
Switch to multi column layout
click on read more 
The shorter post will stretch to fill the space

### Screenshots

![Screenshot (558)](https://github.com/narayan954/dummygram/assets/116902573/88cbb01a-1813-4ce8-baa9-77e8da94bed8)

**Comment by narayan954** [comment]
> ### Description
> When a post has so much written into it and if the layout is multi-column then, it mess the UI of other posts by stretching them.
> 
> ### Steps to reproduce
> Find a long post Switch to multi column layout click on read more The shorter post will stretch to fill the space
> 
> ### Screenshots
> ![Screenshot (558)](https://user-images.githubusercontent.com/116902573/248504844-88cbb01a-1813-4ce8-baa9-77e8da94bed8.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

What do you think for solving this?? I think on clicking readmore, the post should be open like view all comments modal we have or you can say, comments modal.There we get the full post on demand. Any other solution in mind?

**Comment by Palakkgoyal** [comment]
Yes, we can do this or I think we can redirect the user to the postview of that post. I also think that user must not be allowed to write such long captions. There must be some limit. What do you think?

**Comment by narayan954** [comment]
> Yes, we can do this or I think we can redirect the user to the postview of that post. I also think that user must not be allowed to write such long captions. There must be some limit. What do you think?

Yes, any option shall do, but redirecting user in this case would affect UX right? He would've to click back this way and thus he'd refrain from clicking readmore unless there's something interesting enough to read. Also,you're right, the captions and other text fields must have their own text limits.

**Comment by Palakkgoyal** [comment]
No, I don't think so. If we redirect user than he/she has to just do one click to go back and it's the same for showing a modal. There also user has to do a click to close the modal. For example if we click on a long twitter post it also redirect us to that post. And if the user click read more than it means they are interested in that post and might love to see other people's engagement through comments which would be easy through redirecting.

**Comment by narayan954** [comment]
> No, I don't think so. If we redirect user than he/she has to just do one click to go back and it's the same for showing a modal. There also user has to do a click to close the modal. For example if we click on a long twitter post it also redirect us to that post. And if the user click read more than it means they are interested in that post and might love to see other people's engagement through comments which would be easy through redirecting.

agreed on this! :) Thanks for explaining
