### ISSUE TITLE
Button hover effect needed 

### ISSUE THREAD

**Issue by Rancho2002** [narayan954/dummygram#572]
### Description

There must be a full length hover effect in the button where user click on share. Also, the lines are looking very simple. Need to design a bit
![image](https://github.com/narayan954/dummygram/assets/92109154/21c9502d-2f91-4be7-b861-b103a8205cf6)

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/92109154/25625ad4-9b7c-4c6c-a973-534736d60344)

### Additional information

This feature make dummygram more interactive

**Comment by Rancho2002** [comment]
@narayan954 can you assign the issue, so that I can work on it?

**Comment by narayan954** [comment]
> @narayan954 can you assign the issue, so that I can work on it?

hii @Rancho2002 this section is already being changed/enhanced/revamped, so we can't work on this issue right now.

Thanks for raising this issue though!
