### ISSUE TITLE
Add username for old users

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#574]
### Description

Currently the username is for those who have created their account using signup(rather that using Google or facebook auth provider) and are also new users. So, the username for old users is not available.

I have a question:
- Can I make it such that when the old user open dummygram they will get a popup to select a username and until they don't select they will not be able to use dummygram. The same goes for the users who created their account using google or fb provider.

### Steps to reproduce

Create account using google or fb
Go to profile
Username will not be available

**Comment by narayan954** [comment]
> ### Description
> Currently the username is for those who have created their account using signup(rather that using Google or facebook auth provider) and are also new users. So, the username for old users is not available.
> 
> I have a question:
> 
> * Can I make it such that when the old user open dummygram they will get a popup to select a username and until they don't select they will not be able to use dummygram. The same goes for the users who created their account using google or fb provider.
> 
> ### Steps to reproduce
> Create account using google or fb Go to profile Username will not be available
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Yes you're correct about this, also, after signup using oauth, there're two options: a default username like a randomly generated available username or email address should be set. And we can update the username like everyone. 
Second option, we explicitly make the user set his username which could work as well. What's your opinion on this as UX matters... as well as DX.

**Comment by narayan954** [comment]
> > ### Description
> > Currently the username is for those who have created their account using signup(rather that using Google or facebook auth provider) and are also new users. So, the username for old users is not available.
> > I have a question:
> > 
> > * Can I make it such that when the old user open dummygram they will get a popup to select a username and until they don't select they will not be able to use dummygram. The same goes for the users who created their account using google or fb provider.
> > 
> > ### Steps to reproduce
> > Create account using google or fb Go to profile Username will not be available
> > ### Screenshots
> > _No response_
> > ### Desktop (please complete the following information)
> > _No response_
> > ### Smartphone (please complete the following information)
> > _No response_
> > ### Additional information
> > _No response_
> 
> Yes you're correct about this, also, after signup using oauth, there're two options: a default username like a randomly generated available username or email address should be set. And we can update the username like everyone. Second option, we explicitly make the user set his username which could work as well. What's your opinion on this as UX matters... as well as DX.

For old users without usernames, I think their quantity is negligible and they're in testing db only. In the production db, we wont' have them, so we don't need to worry about them, right? Also, there already are users with duplicate usernames as well, and we can't run a cleanup easily.

**Comment by narayan954** [comment]
Also, (this might be unrelated to this issue but) we need to think about the db usage. Every db call is now crucial as we're running out of daily limits. Earlier in search functionality(it's currently an open pr) She was querying the whole db for posts collection and then filtering the correct posts from them. But that causes thousands of read operations as that collection has lot of sub data such as likes,comments,picture,etc and hence crossed the daily limit of 50k read operations. We need to think of solutions for future problems which are not hard to the db.

**Comment by Palakkgoyal** [comment]
Yes, you are right and I was also thinking about the same thing that it might cost extra requests. I think I should implement the whole username setup to the user data. I mean where his/her display name, email are available, there I should create a new field in which username will be available and if it is unavailable then we can ask to add there.

**Comment by narayan954** [comment]
> Yes, you are right and I was also thinking about the same thing that it might cost extra requests. I think I should implement the whole username setup to the user data. I mean where his/her display name, email are available, there I should create a new field in which username will be available and if it is unavailable then we can ask to add there.

First we need to think what can we access from firebase, how it stores users after authentication. The application uses firebase authentication and user is created by that only. We can add username there, but how'd we check other usernames there for uniqueness, also how'd we get users by username instead of uuids. We'll update likes feature to store usernames instead(and we need this unique username for identification). What do we do? My guess is firebase documentation and some research.

**Comment by narayan954** [comment]
Also please provide me your email somewhere (dm preferrably for privacy reasons) so I can add you to the main project in firebase, so you can see for yourself.

**Comment by Palakkgoyal** [comment]
Hey @narayan954, Is the work on user collection completed. I checked but, I can't find the issue and I checked the commit history too. There were no commits regarding this(If there is then, can you please send me the link).

**Comment by narayan954** [comment]
> Hey @narayan954, Is the work on user collection completed. I checked but, I can't find the issue and I checked the commit history too. There were no commits regarding this(If there is then, can you please send me the hash).

it's been merged

**Comment by narayan954** [comment]
> Hey @narayan954, Is the work on user collection completed. I checked but, I can't find the issue and I checked the commit history too. There were no commits regarding this(If there is then, can you please send me the hash).

you can check #613

**Comment by Palakkgoyal** [comment]
Yes, I checked it. Thanks.
