### ISSUE TITLE
Create New Post is not responsive for mobile device

### ISSUE THREAD

**Issue by crocmons** [narayan954/dummygram#575]
### Description

I want to make it responsive the create new post popup for all devices..Please assign this issue to me as GSSOC23 contributor.
![Screenshot (449)](https://github.com/narayan954/dummygram/assets/106610322/e4c4d4d5-49cb-4148-9979-436b082de120)

**Comment by narayan954** [comment]
> ### Description
> I want to make it responsive the create new post popup for all devices..Please assign this issue to me as GSSOC23 contributor. ![Screenshot (449)](https://user-images.githubusercontent.com/106610322/248738627-e4c4d4d5-49cb-4148-9979-436b082de120.png)

Hello @crocmons , thanks for raising the issue, but unfortunately this issue exists already. Can you try claiming that instead. Issue number #476

**Comment by narayan954** [comment]
I've to close this as duplicate, sorry
