### ISSUE TITLE
[Bug]: Displays incorrect email

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [narayan954/dummygram#578]
### Description

Displays current user's email in other user's profile page. 

### Steps to reproduce

If the current user has an email and the other person doesnt , then current user's email address is displayed in other user's profile.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104077094/0c18541d-1479-4d0d-8cfd-818335053030)

**Comment by addymistrel** [comment]
Hey DummyGram Officials. It seems that this issue requires some use effect call to maintain synchronization. So I would like to handle this issue as my first contribution alongside GSSOC'23.

**Comment by narayan954** [comment]
> Hey DummyGram Officials. It seems that this issue requires some use effect call to maintain synchronization. So I would like to handle this issue as my first contribution alongside GSSOC'23.

Hi @addymistrel thanks for asking but @VijayalakshmiGanesh claimed the issue before you, in fact she raised the issue. Also I don't see how useeffect would help here. We need to be careful in using hooks as they can cause performance issues as well. 
One of the ways to solve this would be a parameterised route with uuid of user so that the profile page loads profile properly.
Thanks for trying though, or correct me if I am wrong

**Comment by narayan954** [comment]
> ### Description
> Displays current user's email in other user's profile page.
> 
> ### Steps to reproduce
> If the current user has an email and the other person doesnt , then current user's email address is displayed in other user's profile.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/104077094/248783790-0c18541d-1479-4d0d-8cfd-818335053030.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Thanks for raising the issue, you may work on this!

**Comment by narayan954** [comment]
Also @VijayalakshmiGanesh , I just thought, do we really need to show email at all? As email cause privacy concerns, it's better not to show them. We may have setting option for public emails in the future but I doubt we should show email at all for other's profile

**Comment by VijayalakshmiGanesh** [comment]
> Also @VijayalakshmiGanesh , I just thought, do we really need to show email at all? As email cause privacy concerns, it's better not to show them. We may have setting option for public emails in the future but I doubt we should show email at all for other's profile

Okay then, I will make the email to be displayed only for the current user and he/she cannot view other user's email address in profile?

**Comment by narayan954** [comment]
> > Also @VijayalakshmiGanesh , I just thought, do we really need to show email at all? As email cause privacy concerns, it's better not to show them. We may have setting option for public emails in the future but I doubt we should show email at all for other's profile
> 
> Okay then, I will make the email to be displayed only when it's current user profile page and he/she cannot view other user's email address in profile page?

yes correct then

**Comment by VijayalakshmiGanesh** [comment]
i will complete and close this today.

**Comment by VijayalakshmiGanesh** [comment]
@narayan954  I have created PR. 

Blocker: unable to check in local as my local account doesn't have an email.

I think this PR should also fix this issue : [https://www.loom.com/share/18d3c9caca1543efb693cf68b6ceefde?sid=a74cd4b6-5422-478c-8c22-74198b86b81b](Video)

**Comment by narayan954** [comment]
> @narayan954 I have created PR.
> 
> Blocker: unable to check in local as my local account doesn't have an email.
> 
> I think this PR should also fix this issue : [Video](https://www.loom.com/share/18d3c9caca1543efb693cf68b6ceefde?sid=a74cd4b6-5422-478c-8c22-74198b86b81b)

Thank you! :)
