### ISSUE TITLE
[FEATURE] Make the navbar vertical and to the bottom of the page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [narayan954/dummygram#582]
### Description

![image](https://github.com/narayan954/dummygram/assets/133862694/327f480e-067f-4a05-bfe6-32f7f5d76169)

Currentlty the navbar looks odd, above some height in the left. I want to fix it so that it becomes vertically aligned and to the bottom of the page, and add styling according to the UI of the page

**Comment by PoulavBhowmick03** [comment]
I would like to work on this issue I created. @narayan954

**Comment by narayan954** [comment]
> I would like to work on this issue I created. @narayan954

Sure, you can work on this! :)
