### ISSUE TITLE
[FEATURE] Profile Page Enhancement

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#586]
### Description

I would like to display more information of the user like email id, and number of posts in the profile page.

**Comment by narayan954** [comment]
> ### Description
> I would like to display more information of the user like email id, and number of posts in the profile page.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

email id could raise a privacy concern, we can add number of posts

**Comment by anamika7153** [comment]
> > ### Description
> > I would like to display more information of the user like email id, and number of posts in the profile page.
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> email id could raise a privacy concern, we can add number of posts

okay, that can be added. Assign me this issue. Or if do you have something in mind, we can discuss that too.

**Comment by narayan954** [comment]
> > > ### Description
> > > I would like to display more information of the user like email id, and number of posts in the profile page.
> > > ### Screenshots
> > > _No response_
> > > ### Additional information
> > > _No response_
> > 
> > 
> > email id could raise a privacy concern, we can add number of posts
> 
> okay, that can be added. Assign me this issue. Or if do you have something in mind, we can discuss that too.

you can go ahead, I forgot to assign :) thank u
