### ISSUE TITLE
[BUG]: Other users profile pic bug

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#587]
### Description

On the profile page of other users, my (logged-in user) profile is displayed instead of that other user's profile pic.

### Steps to reproduce

Rendering the profile pics of that particular user and not the logged-in user only

###  My Pofile

<img width = "400" src="https://github.com/narayan954/dummygram/assets/66116440/43daef31-2f31-4f02-81bf-1b54881b7816">

### Other User
<img width = "350" src="https://github.com/narayan954/dummygram/assets/66116440/4e369ab0-3dd8-4e03-9073-ef0cb76e5d69">
<img width = "350" src="https://github.com/narayan954/dummygram/assets/66116440/34bc4d86-58bb-4d85-ad67-f0d4545f052b">

**Comment by narayan954** [comment]
559 Hi @anamika7153 thanks a lot for finding and raising the issue, but fortunately it's been already raised and assigned. Issue #559 . You can wait or work on other issues as well. Thanks and i'm closing this as duplicate
