### ISSUE TITLE
[FEATURE] Adding my friends page

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#588]
### Description

- I would like to add a 'my friends' link in the profile page which will be linked to a page to display all the friends that a user has and is connected to.
- That page will have friend's pic, name and an unfollow button.

**Comment by anamika7153** [comment]
> ### Description
> I would like to add a 'my friends' link in the profile page which will be linked to a page to display all the friends that a user has and is connected to.
> That page will have friend's pic, name and an unfollow button.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

**Comment by narayan954** [comment]
@anamika7153 we have a little issue in this for the current implementation. We don't have a users collections, instead we're getting users from firebase authentication. So we need to study if such can be implemented at all. We've added a send friend request feature and notfication bar for this feature, but need to confirm about this. There's a workaround I can think of, but it's kinda expensive, so I am thinking of the correct solution. If you have ideas, please shoot up.

Thank you
