### ISSUE TITLE
[FEATURE] <add hover effect>

### ISSUE THREAD

**Issue by dheeraj1129** [narayan954/dummygram#589]
### Description

Add Some hover Effect on the nav Element and add some color in the background

**Comment by narayan954** [comment]
> ### Description
> Add Some hover Effect on the nav Element and add some color in the background
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @dheeraj1129 there already exists issue #553 addressing this. About background colour, I doubt we need a background colour right now as it will make the application way too colorful, I want the theme to be simplistic like [this site](https://narayan-soni.web.app/) only
