### ISSUE TITLE
[FEATURE] Real time validation in login and signup

### ISSUE THREAD

**Issue by AlfiyaSiddique** [narayan954/dummygram#590]
## Current Feature
Currently, the user gets an error message after the user clicks on the submit (login/ sign up) button. 

<img width="591" alt="4" src="https://github.com/narayan954/dummygram/assets/86224794/ad5ef147-4142-44a8-ab27-7ba84c0f6432">

## New feature

I want to implement real-time validation so that the user gets a validation message as he/she enters the data, And as soon as the valid data is entered the messages disappear. A sample video is given in the screenshot section.

## Sample Video.

I want to implement functionality similar to the one below in the login and signup form.

https://github.com/agamjotsingh18/pollitup/assets/86224794/b3d8c27f-da3b-4b82-9ea2-e4db3c710923

## Request
**Please assign me this issue under gssoc'23 label.**

**Comment by addymistrel** [comment]
Hello there! I have gone through the issue and I would like to work on this issue So I request you to assign this issue to me on behalf of GSSOC'23

**Comment by narayan954** [comment]
> ### Description
> ## Current Feature
> Currently, the user gets an error message after the user clicks on the submit (login/ sign up) button.
> 
> <img alt="4" width="591" src="https://user-images.githubusercontent.com/86224794/249477675-ad5ef147-4142-44a8-ab27-7ba84c0f6432.png">
> ## New feature
> I want to implement real-time validation so that the user gets a validation message as he/she enters the data, And as soon as the valid data is entered the messages disappear. A sample video is given in the screenshot section.
> 
> ### Screenshots
> ## Sample Video.
> I want to implement functionality similar to the one below in the login and signup form.
> 
>  sample.mp4 
> ## Request
> **Please assign me this issue under gssoc'23 label.**
> 
> ### Additional information
> _No response_

You can work on this! :)

**Comment by narayan954** [comment]
> Hello there! I have gone through the issue and I would like to work on this issue So I request you to assign this issue to me on behalf of GSSOC'23

@addymistrel This issues has been claimed, please find another issue :)
