### ISSUE TITLE
 404 page Back to Home button is not working.

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#591]
### Description

about help-center Guidelines policy this page is redirected to the 404 page and the 404 page Bach to Home is not working.
Can you please assign the issue to me?

### Steps to reproduce

![image](https://github.com/narayan954/dummygram/assets/94003231/cd3c39ec-b8b5-4978-a8fb-f35a73ff6f93)

**Comment by narayan954** [comment]
> ### Description
> about help-center Guidelines policy this page is redirected to the 404 page and the 404 page Bach to Home is not working. Can you please assign the issue to me?
> 
> ### Steps to reproduce
> ![image](https://user-images.githubusercontent.com/94003231/250013335-cd3c39ec-b8b5-4978-a8fb-f35a73ff6f93.png)
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi thanks for raising the issue, but I can't allow this issue for points as it's a one line fix. Apologies for that please but that's the guideline for this program. If you have more issues you can add to this, please proceed.

**Comment by SubhamB2003** [comment]
> > ### Description
> > about help-center Guidelines policy this page is redirected to the 404 page and the 404 page Bach to Home is not working. Can you please assign the issue to me?
> > ### Steps to reproduce
> > ![image](https://user-images.githubusercontent.com/94003231/250013335-cd3c39ec-b8b5-4978-a8fb-f35a73ff6f93.png)
> > ### Screenshots
> > _No response_
> > ### Desktop (please complete the following information)
> > _No response_
> > ### Smartphone (please complete the following information)
> > _No response_
> > ### Additional information
> > _No response_
> 
> Hi thanks for raising the issue, but I can't allow this issue for points as it's a one line fix. Apologies for that please but that's the guideline for this program. If you have more issues you can add to this, please proceed.

@narayan954 Ok I search for another issue. 
And another thing can you please check my pr https://github.com/narayan954/dummygram/pull/573

**Comment by SubhamB2003** [comment]
@narayan954 Hey, I closed this issue I already solved it.

**Comment by narayan954** [comment]
> I closed this issue I already solved it.

thanks :)
