### ISSUE TITLE
[FEATURE] Profile page UI Enhancement

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#601]
### Description

- Currently, the profile page looks very basic and boring.

### Solution

- I am thinking of removing the profile page card that contains user information and render user information without card.
- Posts cards will be displayed below the profile details like they are currently with some stylings.

### Screenshots

Something like this. This is the website that I made.

![screencapture-projekthouse-netlify-app-profile-2023-07-01-22_38_51](https://github.com/narayan954/dummygram/assets/66116440/f3e5eb42-fd19-4852-ad5e-f84fc6c92a6f)

**Comment by narayan954** [comment]
> ### I'm in GSSoC'23
> ### Description
> * Currently, the profile page looks very basic and boring.
> 
> ### Solution
> * I am thinking of removing the profile page card that contains user information and render user information without card.
> * Posts cards will be displayed below the profile details like they are currently with some stylings.
> 
> ### Screenshots
> Something like this. This is the website that I made.
> 
> ![screencapture-projekthouse-netlify-app-profile-2023-07-01-22_38_51](https://user-images.githubusercontent.com/66116440/250295304-f3e5eb42-fd19-4852-ad5e-f84fc6c92a6f.png)
> 
> ### Additional information
> _No response_

This looks clean and nice @anamika7153 , you can work on this :)
