### ISSUE TITLE
[BUG]: PRofile image not showing after updating 

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#604]
### Description

- When I update the profile image, it's not rendering in my profile page.

### Steps to reproduce

- Rendering the image instantly after updating.

### Video

https://github.com/narayan954/dummygram/assets/66116440/5e3eaf17-58ae-4cd2-9534-aec4ec927e5d

**Comment by narayan954** [comment]
> ### I'm in GSSoC'23
> ### Description
> * When I update the profile image, it's not rendering in my profile page.
> 
> ### Steps to reproduce
> * Rendering the image instantly after updating.
> 
> ### Video
>  new_recording_-_7_1_2023._11_38_05_pm.Original.mp4 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Yes, and can you please try fixing this delay bug as well? or add loader to that
