### ISSUE TITLE
Optimize favorite page requests

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#607]
### Description

Currently, if a person has only a single post as favorite then still the function will iterate through whole posts collection which lag very much in performance and take too many requests.

### Steps to reproduce

Have a single post as favorite.
Go to favorite page.
It will take too much time to load as the function is iterating over all posts even if all favorites post are found.

**Comment by narayan954** [comment]
> ### Description
> Currently, if a person has only a single post as favorite then still the function will iterate through whole posts collection which lag very much in performance and take too many requests.
> 
> ### Steps to reproduce
> Have a single post as favorite. Go to favorite page. It will take too much time to load as the function is iterating over all posts even if all favorites post are found.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi @Palakkgoyal , how do you plan to solve that? go ahead!

**Comment by Palakkgoyal** [comment]
I optimized it somewhat as it was fetching the whole database even if the saved post list is empty to fetch nothing.
I checked that the post are added as array and not as collection docs. So, can I change their structure to collection rather than array as it would become very inefficient if there would be more posts(Currently, there are only 382 posts)

**Comment by narayan954** [comment]
> I optimized it somewhat as it was fetching the whole database even if the saved post list is empty to fetch nothing. I checked that the post are added as array and not as collection docs. So, can I change their structure to collection rather than array as it would become very inefficient if there would be more posts(Currently, there are only 382 posts)

Posts are indeed added as collections docs. I doubt they're added as arrays, please can you check again?

**Comment by narayan954** [comment]
![image](https://github.com/narayan954/dummygram/assets/77617189/d803c825-555e-470a-86e8-eaf0ce75bdaa)

**Comment by Palakkgoyal** [comment]
> > I optimized it somewhat as it was fetching the whole database even if the saved post list is empty to fetch nothing. I checked that the post are added as array and not as collection docs. So, can I change their structure to collection rather than array as it would become very inefficient if there would be more posts(Currently, there are only 382 posts)
> 
> Posts are indeed added as collections docs. I doubt they're added as arrays, please can you check again?

Yes, I checked due to fetching it differently posts were showing up as arrays

**Comment by narayan954** [comment]
> > > I optimized it somewhat as it was fetching the whole database even if the saved post list is empty to fetch nothing. I checked that the post are added as array and not as collection docs. So, can I change their structure to collection rather than array as it would become very inefficient if there would be more posts(Currently, there are only 382 posts)
> > 
> > 
> > Posts are indeed added as collections docs. I doubt they're added as arrays, please can you check again?
> 
> Yes, I checked due to fetching it differently posts were showing up as arrays

So, our problem's solved, somewhat, right?
