### ISSUE TITLE
New logo for the website

### ISSUE THREAD

**Issue by Tisha6661** [narayan954/dummygram#608]
### Description

The current logo is somewhat same as instagram, I would like to design a new logo for this website.

### Screenshots

some of the designs i have made are-
![Screenshot 2023-06-27 011300](https://github.com/narayan954/dummygram/assets/98682478/ca4aa54d-b7e9-499f-8547-5f2d12a6b4c2)
![Screenshot 2023-06-29 000158](https://github.com/narayan954/dummygram/assets/98682478/8c911d0e-b873-4667-8c06-a3177b1475f8)

### Additional information

Please assign me this task, under GSSOC'23.

**Comment by narayan954** [comment]
> ### Description
> The current logo is somewhat same as instagram, I would like to design a new logo for this website.
> 
> ### Screenshots
> some of the designs i have made are- ![Screenshot 2023-06-27 011300](https://user-images.githubusercontent.com/98682478/250300292-ca4aa54d-b7e9-499f-8547-5f2d12a6b4c2.png) ![Screenshot 2023-06-29 000158](https://user-images.githubusercontent.com/98682478/250300321-8c911d0e-b873-4667-8c06-a3177b1475f8.png)
> 
> ### Additional information
> Please assign me this task, under GSSOC'23.

Woah, your designs are awesome! @Tisha6661 , we could definitely use your magic for the logo! :)

**Comment by Tisha6661** [comment]
@narayan954 I have made a pull request regarding this issue, please verify and merge it.

**Comment by narayan954** [comment]
> @narayan954 I have made a pull request regarding this issue, please verify and merge it.

reviewed :)
