### ISSUE TITLE
[FEATURE] Create Post form

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#612]
### I'm in GSSoC'23

- Create post form doesnt look much attractive.
- It also doesn't display the whole form. User has to scroll it to see the Share button.

### Screenshots

<img width="660" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/2f1cd275-9ad8-45ec-92e8-1c3053584b29">

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * Create post form doesnt look much attractive.
> * It also doesn't display the whole form. User has to scroll it to see the Share button.
> 
> ### Screenshots
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/66116440/250310560-2f1cd275-9ad8-45ec-92e8-1c3053584b29.png">
> ### Additional information
> _No response_

Hi @anamika7153 , this issue exists already and Gurpreet is already working on it. 
Thanks for raising the issue though, I guess the second issue is related to responsiveness.
If in some days it doesn't get fixed, you can work on it :)

Thank you

**Comment by anamika7153** [comment]
> > ### Description
> > ### I'm in GSSoC'23
> > 
> > * Create post form doesnt look much attractive.
> > * It also doesn't display the whole form. User has to scroll it to see the Share button.
> > 
> > ### Screenshots
> > <img alt="image" width="660" src="https://user-images.githubusercontent.com/66116440/250310560-2f1cd275-9ad8-45ec-92e8-1c3053584b29.png">
> > ### Additional information
> > _No response_
> 
> Hi @anamika7153 , this issue exists already and Gurpreet is already working on it. Thanks for raising the issue though, I guess the second issue is related to responsiveness. If in some days it doesn't get fixed, you can work on it :)
> 
> Thank you

Okay :)
