### ISSUE TITLE
Dark mode not applied on newly added section

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#614]
### Description

Hey, @narayan954 Dark mode is not getting applied on the newly added section on the sidebar. Please assign me this issue to resolve this bug. Thank you!

### Steps to reproduce

Added dynamic colour to this section using --var() function.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100675296/76bb6bab-667a-47fc-806e-d01bc83846db)

**Comment by narayan954** [comment]
> ### Description
> Hey, @narayan954 Dark mode is not getting applied on the newly added section on the sidebar. Please assign me this issue to resolve this bug. Thank you!
> 
> ### Steps to reproduce
> Added dynamic colour to this section using --var() function.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/100675296/250335434-76bb6bab-667a-47fc-806e-d01bc83846db.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi @sumitkr2000 , this issue exists already, please claim that or wait for it to be inactive. I've to close this one as duplicate

**Comment by sumitkr2000** [comment]
Can you please tag the issue number?

**Comment by narayan954** [comment]
> Can you please tag the issue number?

actually, even I can't find the issue, I think I saw it and assigned it... Anyways you can work on this
