### ISSUE TITLE
[FEATURE] Show profile picture instead of static icon on navbar

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#615]
### Description

Hey, @narayan954 It would be good if we could show the user profile picture on the top right sides of the navbar instead of just a fixed icon. This can be done by using google photURL which Google provides in its API. Please assign me this issue. Thank you!

### Screenshots

![Screenshot (881)](https://github.com/narayan954/dummygram/assets/100675296/3fa29454-f3af-4756-b3ca-1d688d10e5ef)

**Comment by narayan954** [comment]
> ### Description
> Hey, @narayan954 It would be good if we could show the user profile picture on the top right sides of the navbar instead of just a fixed icon. This can be done by using google photURL which Google provides in its API. Please assign me this issue. Thank you!
> 
> ### Screenshots
> ![Screenshot (881)](https://user-images.githubusercontent.com/100675296/250335702-3fa29454-f3af-4756-b3ca-1d688d10e5ef.png)
> 
> ### Additional information
> _No response_

instead can you implement that in the sidebar?, we're cleaning the navbar

**Comment by sumitkr2000** [comment]
Okay then I'll implement it on the sidebar
