### ISSUE TITLE
[FEATURE] UI(Thread)+DX: Create reusable dialogs

### ISSUE THREAD

**Issue by mathiasayivor** [narayan954/dummygram#62]
### Description

Just like how notistack works, we can create reusable dialogs the provides an imperative api to easily create dialog messages, without repeating code.

**Comment by saitama2812** [comment]
![image](https://user-images.githubusercontent.com/102511217/193629520-e25445b2-56c9-45cf-be14-e1b4715b3626.png)
does this help or is it something else that you wanted?

**Comment by narayan954** [comment]
@saitama2812 I think this works as @mathiasayivor liked it, would you like to work on this?

**Comment by narayan954** [comment]
Open for KWOC

**Comment by kshitij01042002** [comment]
Assign me this I can work on it. I can create a reusable dialog box which can contain props for title and message and can be used anywhere in the applicaiton

**Comment by kshitij01042002** [comment]
You can close this issue since it has already been resolved
