### ISSUE TITLE
[FEATURE] Create a settings page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#620]
### Description

I want to create a setting page. Currently, it would just contain Sounds setting but with time as the website progress we can add more feature to it.

**Comment by narayan954** [comment]
> ### Description
> I want to create a setting page. Currently, it would just contain Sounds setting but with time as the website progress we can add more feature to it.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

You can work on this!
Also, would it be better to put it in the navbar dropdown than sidebar?

**Comment by Palakkgoyal** [comment]
Yes, I was going to implement it there only.
