### ISSUE TITLE
Bug in favorite page post nav

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#627]
### Description

When you click on the like button to like the post on the fav. page then, it just increase the like count by 1 and do not change the color of like icon to red and if you click once again on the button the like count will also increase one more time. Same happen when you try to unlike the liked post.

### Steps to reproduce

- Go to fav page.
- Click on like button 2-3 times and see the like count.

### Screenshots

https://github.com/narayan954/dummygram/assets/116902573/f0989294-15d1-409e-89bb-b6d0e4b20b5a

**Comment by narayan954** [comment]
you can work on this! :)
