### ISSUE TITLE
Improve Posts Ui

### ISSUE THREAD

**Issue by Tisha6661** [narayan954/dummygram#628]
### Description

The posts card UI is very simple and everything is congested, I would like to improve the Ui of the posts card page.

### Screenshots

![WhatsApp Image 2023-07-03 at 15 18 24](https://github.com/narayan954/dummygram/assets/98682478/246ddb6e-e8de-4d75-a51b-fa4a32036d10)

### Additional information

Under Gssoc'23 please assign me this task, I would really make an improvement.

**Comment by narayan954** [comment]
you can work on this! :)

**Comment by Tisha6661** [comment]
@narayan954 I have created a pull request regarding this task, please verify.

**Comment by narayan954** [comment]
> @narayan954 I have created a pull request regarding this task, please verify.

okay, sure I'll check
