### ISSUE TITLE
Improve the site's header

### ISSUE THREAD

**Issue by Emilance** [narayan954/dummygram#63]
### What would you like to share?

The current site's header needs a little improvement to look exactly like that of IG,  assign this to me I will get it done perfectly

**Comment by narayan954** [comment]
Go Ahead! and please share the screenshots for the change

**Comment by bhadurishayoun** [comment]
please assign me this issue @Emilance

**Comment by narayan954** [comment]
@Emilance are you working on this issue?

**Comment by narayan954** [comment]
Open for KWOC

**Comment by saurabhbakolia** [comment]
hi, @narayan954  I would like to work on it.

**Comment by narayan954** [comment]
sure, but can you please elaborate the changes you'll make?

**Comment by saurabhbakolia** [comment]
Yes, why not.
I am thinking on it. As soon as I complete, I will share the screenshot.

**Comment by saurabhbakolia** [comment]
@narayan954  Should I add home button?
and can you give me some suggestion what else  I can add?

**Comment by saurabhbakolia** [comment]
![image](https://user-images.githubusercontent.com/78996216/205261064-8fc64abe-8224-46c9-b542-49208bb463b5.png)


This is my new navbar design, I think we can add a new search bar also, to search user.

**Comment by narayan954** [comment]
> @narayan954 Should I add home button? and can you give me some suggestion what else I can add?

yes, as we might be able to implement it in the near future, we can add it.
We currently don't have many functionalities to add, but we can add buttons for them to be implemented like profile button, home button, messages button, new post button, story button etc.

**Comment by narayan954** [comment]
> ![image](https://user-images.githubusercontent.com/78996216/205261064-8fc64abe-8224-46c9-b542-49208bb463b5.png)
> 
> This is my new navbar design, I think we can add a new search bar also, to search user.

yes, that'd be great!

**Comment by saurabhbakolia** [comment]
So, for now should I go with it or should I add other button as well?

**Comment by narayan954** [comment]
> So, for now should I go with it or should I add other button as well?

Profile button should do, as profile page will be soon in development :)

**Comment by saurabhbakolia** [comment]
![image](https://user-images.githubusercontent.com/78996216/205485772-8f6d2c80-418e-443c-8e96-e05ed789bbe0.png)


@narayan954  I have finished the designed of the header. Now I am going to implement it. I think it is fine!

**Comment by saurabhbakolia** [comment]
we are using material-ui for icons right?

**Comment by narayan954** [comment]
> we are using material-ui for icons right?
> 

yes!

**Comment by saurabhbakolia** [comment]
![Double Click Functionality](https://user-images.githubusercontent.com/78996216/205490348-b150d9dc-cc9e-4b22-88d7-abeaec740162.gif)

I have added search bar , home button, post icon, and profile button which has only logout functionality till now. Please have a look.

**Comment by narayan954** [comment]
> ![Double Click Functionality](https://user-images.githubusercontent.com/78996216/205490348-b150d9dc-cc9e-4b22-88d7-abeaec740162.gif) [ ![Double Click Functionality](https://user-images.githubusercontent.com/78996216/205490348-b150d9dc-cc9e-4b22-88d7-abeaec740162.gif) ](https://user-images.githubusercontent.com/78996216/205490348-b150d9dc-cc9e-4b22-88d7-abeaec740162.gif) [ ](https://user-images.githubusercontent.com/78996216/205490348-b150d9dc-cc9e-4b22-88d7-abeaec740162.gif)
> 
> I have added search bar , home button, post icon, and profile button which has only logout functionality till now. Please have a look.

Hi there Saurabh, please let sign/signup/logout be a separate button as profile button has a different purpose. You can leave the implementation of profile button for now :)

**Comment by saurabhbakolia** [comment]
Can we add logout button under profile button and sign in button as separate. As if any user is not signed in then he/she we will be able to see only sign in button and  there will be no profile button.

**Comment by narayan954** [comment]
> Can we add logout button under profile button and sign in button as separate. As if any user is not signed in then he/she we will be able to see only sign in button and there will be no profile button.

yes sure!

**Comment by saurabhbakolia** [comment]
![Profie Menu](https://user-images.githubusercontent.com/78996216/206088532-f4911da3-8971-4a4c-95dd-ab8cbb3ff4fc.gif)

Profile Menu added. 
Can add more menu options when new functionality added. 
now doing a pull request.

**Comment by saurabhbakolia** [comment]
I think we should create a new Landing page for those user who haven't signed in yet.
As if someone is not signed in he/she can view the website. So, I think we should also add a separate landing page. To make user sign in. 
If you approve it I can create a feature request and work on that. 

LIKE THIS ONLY. 
![image](https://user-images.githubusercontent.com/78996216/206089228-830aa774-d275-49f8-b57c-39e2e82a5e4c.png)

**Comment by narayan954** [comment]
> I think we should create a new Landing page for those user who haven't signed in yet. As if someone is not signed in he/she can view the website. So, I think we should also add a separate landing page. To make user sign in. If you approve it I can create a feature request and work on that.
> 
> LIKE THIS ONLY. ![image](https://user-images.githubusercontent.com/78996216/206089228-830aa774-d275-49f8-b57c-39e2e82a5e4c.png)

it's already in develop if I'm correct in some issue named login page, will double check and let you know! :)

**Comment by saurabhbakolia** [comment]
Creating a new PR.

**Comment by SattyamSamania** [comment]
@narayan954 Can I work on this?

**Comment by narayan954** [comment]
> @narayan954 Can I work on this?

it's already a work in progress with the active PR

**Comment by codemaniac-sahil** [comment]
Hey @narayan954, I would like to work on this issue. Would you please assign this issue to me.

**Comment by narayan954** [comment]
> Hey @narayan954, I would like to work on this issue. Would you please assign this issue to me.

great go ahead

**Comment by narayan954** [comment]
Hi @codemaniac-sahil , are you still working?

**Comment by codemaniac-sahil** [comment]
Yes, I am working.

**Comment by narayan954** [comment]
@codemaniac-sahil Hi, please update with your progress

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by narayan954** [comment]
> I want to work on this issue under JWOC

sorry, but you can only work at one issue at a time

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by narayan954** [comment]
You can be assigned to only one issue at a time, finish the assigned issue first. Thank you

**Comment by Hritik1503** [comment]
Please assign me this issue currently i am completed my all so i am free for this so please assign me this issue

**Comment by narayan954** [comment]
you can go ahead, but at max 2 issues at a time as there're other contributors as well.
