### ISSUE TITLE
[BUG]: Home page UI not responsive

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#630]
### I'm in GSSoC'23

- When the user toggle the post view to display posts in grid, posts get hidden behind the header.
- In the medium screen, grid view of posts is not responsive and the posts are overlapping the sidebar.

### Steps to reproduce

- Making the home page responsive for all screen devices.
- Aligning the content properly for the grid view.

### Screenshots

https://github.com/narayan954/dummygram/assets/66116440/ad121848-ae99-4479-9db6-a44288e3665d

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * When the user toggle the post view to display posts in grid, posts get hidden behind the header.
> * In the medium screen, grid view of posts is not responsive and the posts are overlapping the sidebar.
> 
> ### Steps to reproduce
> * Making the home page responsive for all screen devices.
> * Aligning the content properly for the grid view.
> 
> ### Screenshots
>  new_recording_-_7_3_2023._4_06_33_pm.Original.mp4 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

thanks for spotting, you can work on this! :)
