### ISSUE TITLE
[BUG]: Profile avatar on click blank modal

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#632]
### I'm in GSSoC'23
- When clicking the profile avatar, blank modal pops up.

### Steps to reproduce

- Either remove it or display the profile picture in it.

## Screenshot

<img width="660" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/e2c3d22a-d391-47b6-9b6a-46577f6b3697">

## Video

https://github.com/narayan954/dummygram/assets/66116440/77b15d4c-6538-4ff1-aa1b-be63bb2b1907

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * When clicking the profile avatar, blank modal pops up.
> 
> ### Steps to reproduce
> * Either remove it or display the profile picture in it.
> 
> ### Screenshots
> ## Screenshot
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/66116440/250543087-e2c3d22a-d391-47b6-9b6a-46577f6b3697.png">
> ## Video
>  new_recording_-_7_3_2023._4_55_37_pm.Original.mp4 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

yes this is the case of no profile pic,you can just show the default image as of the profilepic
