### ISSUE TITLE
[BUG]: Profile route issue

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#633]
### I'm in GSSoC'23

- Currently, other user profile route and logged-in user profile routes are same.
- When the user is on another user's profile page and clicks on the profile link to see his profile page, the user remains on the other's profile page only rather than being redirected to his profile page.

### Steps to reproduce

- Other user profile route and logged-in user profile route should be different.
- There should be a state that maintains the state of the user and checks if the profile page requested belongs to other user or logged-in user. 
- Clicking the profile link of the sidebar and profile section (top-right) of the header should display the logged-in user profile page instantly.

### Screenshots

https://github.com/narayan954/dummygram/assets/66116440/7a0a0eb2-4971-4e06-ac2c-f103b0bd767e

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * Currently, other user profile route and logged-in user profile routes are same.
> * When the user is on another user's profile page and clicks on the profile link to see his profile page, the user remains on the other's profile page only rather than being redirected to his profile page.
> 
> ### Steps to reproduce
> * Other user profile route and logged-in user profile route should be different.
> * There should be a state that maintains the state of the user and checks if the profile page requested belongs to other user or logged-in user.
> * Clicking the profile link of the sidebar and profile section (top-right) of the header should display the logged-in user profile page instantly.
> 
> ### Screenshots
>  New_Recording_-_7_3_2023._4_59_59_PM.mp4 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Yes, there could be several solutions for this, like
- a route "dummygram/profile/me" for the user profile and plain profile route for other users(simplest)
- use of dynamic/parameterised routes that can be just like post's dynamic route.(better and proper approach and can take help of previous approach for current user's profile)
- to be researched

what are your opinions?

**Comment by anamika7153** [comment]
@narayan954  please review and merge. I have solved other issue(profile image not displaying)  and need to implement after this PR gets merged :)

**Comment by narayan954** [comment]
> @narayan954  please review and merge. I have solved other issue(profile image not displaying)  and need to implement after this PR gets merged :)

ohh, alright. sure

**Comment by narayan954** [comment]
> @narayan954 please review and merge. I have solved other issue(profile image not displaying) and need to implement after this PR gets merged :)

I am having a bit headache, I'll check around afternoon today.

**Comment by anamika7153** [comment]
> > @narayan954 please review and merge. I have solved other issue(profile image not displaying) and need to implement after this PR gets merged :)
> 
> I am having a bit headache, I'll check around afternoon today.

Sure, no problem. Get well soon :)

**Comment by narayan954** [comment]
> > > @narayan954 please review and merge. I have solved other issue(profile image not displaying) and need to implement after this PR gets merged :)
> > 
> > I am having a bit headache, I'll check around afternoon today.
> 
> Sure, no problem. Get well soon :)

thanks

**Comment by anamika7153** [comment]
> > > > @narayan954 please review and merge. I have solved other issue(profile image not displaying) and need to implement after this PR gets merged :)
> > > 
> > > 
> > > I am having a bit headache, I'll check around afternoon today.
> > 
> > 
> > Sure, no problem. Get well soon :)
> 
> thanks

@narayan954 sir, I hope you are well. Please review and merge :) My 3 issues' fix is dependent on it.

**Comment by narayan954** [comment]
> > > > > @narayan954 please review and merge. I have solved other issue(profile image not displaying) and need to implement after this PR gets merged :)
> > > > 
> > > > 
> > > > I am having a bit headache, I'll check around afternoon today.
> > > 
> > > 
> > > Sure, no problem. Get well soon :)
> > 
> > 
> > thanks
> 
> @narayan954 sir, I hope you are well. Please review and merge :) My 3 issues' fix is dependent on it.

Thanks a lot @anamika7153 , yes i reviewed and asked for some changes, I'll review quicker this time
