### ISSUE TITLE
[FEATURE]: Adding footer

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#638]
### I'm in GSSoC'23

- I would like to create a footer component and remove the bottom section from the sidebar and add it to the footer.

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * I would like to create a footer component and remove the bottom section from the sidebar and add it to the footer.
> 
> ### Additional information
> _No response_

Hi @anamika7153 there already exists a footer component located in sidebar folder. It's used as a component only in sidebar. Can you please check again?

**Comment by anamika7153** [comment]
> > ### Description
> > ### I'm in GSSoC'23
> > 
> > * I would like to create a footer component and remove the bottom section from the sidebar and add it to the footer.
> > 
> > ### Additional information
> > _No response_
> 
> Hi @anamika7153 there already exists a footer component located in sidebar folder. It's used as a component only in sidebar. Can you please check again?

Yes, it does, I didn't see. I thought of separating it from the sidebar and add it to bottom.

**Comment by narayan954** [comment]
> > > ### Description
> > > ### I'm in GSSoC'23
> > > 
> > > * I would like to create a footer component and remove the bottom section from the sidebar and add it to the footer.
> > > 
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Hi @anamika7153 there already exists a footer component located in sidebar folder. It's used as a component only in sidebar. Can you please check again?
> 
> Yes, it does, I didn't see. I thought of separating it from the sidebar and add it to bottom.

ohh, it's alright! I'm closing this as not required. :)
