### ISSUE TITLE
[BUG]: Sidebar

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#640]
### I'm in GSSoC'23

- Currently, the sidebar has some content with a background colour incompatible with the dark mode.
- Also some content (copyright) is not visible in the sidebar.

### Steps to reproduce

- I would like to make the sidebar content compatible with dark mode and also make it responsive.

### Screenshots

<img width="660" src="https://github.com/narayan954/dummygram/assets/66116440/b43e65fe-da8a-4543-a744-5f8df3425c9e">

**Comment by narayan954** [comment]
> ### Description
> ### I'm in GSSoC'23
> * Currently, the sidebar has some content with a background colour incompatible with the dark mode.
> * Also some content (copyright) is not visible in the sidebar.
> 
> ### Steps to reproduce
> * I would like to make the sidebar content compatible with dark mode and also make it responsive.
> 
> ### Screenshots
> <img alt="" width="660" src="https://user-images.githubusercontent.com/66116440/250646544-b43e65fe-da8a-4543-a744-5f8df3425c9e.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Hi @anamika7153 thanks for raising the issue, but this issue existed already and  fortunately this issue has already been fixed and merged :)
I'd have to close this as duplicate but thank you for spotting :)
