### ISSUE TITLE
[FEATURE] Improve the UI of login page

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#646]
### Description

Hey @narayansoni I want to improve the UI of the login page. The image on the right side looks distorted. I also wish to add the official colors of Google and Facebook on the login buttons. Please assign me this issue. Thank you!Google

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100675296/c545d493-75b9-4de7-b7dd-cc3aec5f25c2)

**Comment by narayan954** [comment]
> ### Description
> Hey @narayansoni I want to improve the UI of the login page. The image on the right side looks distorted. I also wish to add the official colors of Google and Facebook on the login buttons. Please assign me this issue. Thank you!Google
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/100675296/250860916-c545d493-75b9-4de7-b7dd-cc3aec5f25c2.png)
> 
> ### Additional information
> _No response_

I think icons have been added, can you fix other aspects you see fit?

**Comment by sumitkr2000** [comment]
Yeah sure @narayan954
