### ISSUE TITLE
Theme button position needs to be changed

### ISSUE THREAD

**Issue by Swapnil-2503** [narayan954/dummygram#647]
### Description

Currently theme button is on screen and we are unable to change its position, and also in mobile view it anoying.

### Steps to reproduce

We can see theme button position that needs to changed

**Comment by narayan954** [comment]
> ### Description
> Currently theme button is on screen and we are unable to change its position, and also in mobile view it anoying.
> 
> ### Steps to reproduce
> We can see theme button position that needs to changed
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

yes, can you integrate it in the sidebar?

**Comment by narayan954** [comment]
> hey @narayan954 i would like to work on this issue as i have fix the issue checkout this design <img alt="image" width="907" src="https://user-images.githubusercontent.com/68702055/252275395-4495b070-bf09-4943-83b8-12387db4567e.png">

please don't work on an issue assigned to someone else without taking his/my permission.

**Comment by biplavmz** [comment]
Hii @Swapnil-2503  can i work on this issue

**Comment by Swapnil-2503** [comment]
ok you fixed that , yes offcourse make it better
