### ISSUE TITLE
[FEATURE] Add Contributor page

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#648]
### Description

@narayan954  Hey, I want to add the contributor page to showcase all the contributors. If this page is needed please assign it to me!!

**Comment by narayan954** [comment]
Hi @SubhamB2003 , you can add that page! I am thinking it should be available from about page, would that be right?

**Comment by SubhamB2003** [comment]
> Hi @SubhamB2003 , you can add that page! I am thinking it should be available from about page, would that be right?

No, this section is not added on about page there is write the concept of dummygram.

**Comment by narayan954** [comment]
> > Hi @SubhamB2003 , you can add that page! I am thinking it should be available from about page, would that be right?
> 
> No, this section is not added on about page there is write the concept of dummygram.

right, but we can also add link inside the description in that page :)
Where do you think then, footer? It'd be fine as well. you can work on it!

**Comment by SubhamB2003** [comment]
@narayan954 Is it ok?

https://github.com/narayan954/dummygram/assets/94003231/deec4583-983a-4d92-b550-ab8925feecf7

Files
![image](https://github.com/narayan954/dummygram/assets/94003231/9abb3fa2-9b1b-4790-b43d-39a6710a1c78)

**Comment by narayan954** [comment]
> @narayan954 Is it ok?
> 
>  Contributor.mp4 
> Files ![image](https://user-images.githubusercontent.com/94003231/251142818-9abb3fa2-9b1b-4790-b43d-39a6710a1c78.png)

Hi @SubhamB2003 , this is to be included in footer, right? so place this inside footerpages folder.
Also, do follow other footer pages theme. You may copy the about/guideline component and modify it accordingly
