### ISSUE TITLE
User data lost whenever user create a post

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#649]
### Description

In the new user collection whenever user create a post then his/her data get lost from the user's collection.

### Steps to reproduce

- Create a new user
- Fetch data about the new user from the user collection
- Create a post
- Again fetch data 
The data is lost.

**Comment by narayan954** [comment]
> ### Description
> In the new user collection whenever user create a post then his/her data get lost from the user's collection.
> 
> ### Steps to reproduce
> * Create a new user
> * Fetch data about the new user from the user collection
> * Create a post
> * Again fetch data
>   The data is lost.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

Well that's critical! You can go ahead, I'll take a look at this as well, but later (really tired rn)
