### ISSUE TITLE
Text color change in Dark mode

### ISSUE THREAD

**Issue by shruuti321** [narayan954/dummygram#652]
### What would you like to share?

In the dark mode of the login page,the text is not visible sue to black color,
I would like to fix this under gssoc'23

### Additional information

![image](https://github.com/narayan954/dummygram/assets/114770273/5799e46f-3eee-4646-bd22-4a0d9dc9dd80)

**Comment by narayan954** [comment]
> ### What would you like to share?
> In the dark mode of the login page,the text is not visible sue to black color, I would like to fix this under gssoc'23
> 
> ### Additional information
> ![image](https://user-images.githubusercontent.com/114770273/250901304-5799e46f-3eee-4646-bd22-4a0d9dc9dd80.png)

Hi @shruuti321 
Thanks for raising the issue, need to change text color so this'd be a single line fix issue and these issues are actually not allowed in this program gssoc, so can you add 1 or more issues to this?, like for example, the bottom of login form containing forgot password and sign up options can be fixed/ improved further

**Comment by shruuti321** [comment]
@narayan954  kindly review and approve my pull request. I have changed the text colour in dark mode in login page

**Comment by narayan954** [comment]
> @narayan954  kindly review and approve my pull request. I have changed the text colour in dark mode in login page

as I said, please add another issue as well in this as I can't grade for a single line issue.

**Comment by shruuti321** [comment]
Sorry I just missed that message!Okay I will try to fix some further issues.
