### ISSUE TITLE
Footer is hiding 

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#659]
### Description

Due to the addition of new items in the sidebar the footer is getting hidden.

### Steps to reproduce

It might depend on screen size but with a less height device this will happen. Might be some of the important items get hide on a less height device such as notification and profile.

### Screenshots

![Screenshot 2023-07-05 002202](https://github.com/narayan954/dummygram/assets/116902573/6526a1c7-975a-4c7e-9fc9-fa506997cb45)

**Comment by narayan954** [comment]
thanks for raising the issue, you can work on this!
