### ISSUE TITLE
[FEATURE] Add a footer

### ISSUE THREAD

**Issue by abhijain2003** [narayan954/dummygram#66]
### Description

We can add a footer which navigates to different pages includes about us contact us your social media links and little about motive of this website

We have two options to implement this as in [This Solution](https://ux.stackexchange.com/questions/12234/how-can-the-classic-footer-elements-be-integrated-into-an-infinite-scrolling-lay)

Please confirm anyone of them and feel free to ask for more information

**Comment by narayan954** [comment]
We have (kind of) infinite scrolling in our application, so how would a footer help and be implemented @abhijain2003 ?

**Comment by abhijain2003** [comment]
by changing the scrolling to grid of infinite X 3 in large screen

and making the position fixed of about us will add more value to website

**Comment by narayan954** [comment]
@mathiasayivor  what do you suggest sir?

**Comment by narayan954** [comment]
okay @abhijain2003

**Comment by abhijain2003** [comment]
thanks

**Comment by Kritika30032002** [comment]
Is this still available?

**Comment by narayan954** [comment]
asking @abhijain2003 if he's working ?

**Comment by narayan954** [comment]
@Kritika30032002 yes, it's available but what improvement do you suggest?

**Comment by Kritika30032002** [comment]
Also you can assign me this ,If you want me too add this feature

**Comment by narayan954** [comment]
okay thanks! go ahead.

**Comment by narayan954** [comment]
Open for contribution in KWOC

**Comment by pranavajith** [comment]
Hey @narayan954 
Can I get this issue assigned?

**Comment by narayan954** [comment]
> Hey @narayan954 Can I get this issue assigned?

Sure, but first please tell how'd you like to implement this? 
Also please mention the program KWOC/Codepeak .
Thanks

**Comment by pranavajith** [comment]
> > Hey @narayan954 Can I get this issue assigned?
> 
> Sure, but first please tell how'd you like to implement this? Also please mention the program KWOC/Codepeak . Thanks


Was planning on using react, css, html to create the footer..

**Comment by pranavajith** [comment]
I am new to open source, and have little experience in webd.. 
I am very intrigued by this project.. would like to learn and contribute simultaneously...

**Comment by Tushar98644** [comment]
I would like to work on the issue ....
program:codepeak

**Comment by narayan954** [comment]
Sure, you can go ahead @pranavajith. It's just that I've a little doubt about how'd a footer be implemented for an app that has potentially infinite scrolling.

**Comment by narayan954** [comment]
> I would like to work on the issue .... program:codepeak

sorry @Tushar98644 but the issue is claimed already, you can some other issue for now :)

**Comment by pranavajith** [comment]
@narayan954 
Could you give me some directions on what languages to use, and how to proceed?

**Comment by narayan954** [comment]
@pranavajith My suggestion is a footer on the left bottom fixed, similar to the new Instagram desktop ui(which is on the right, but we don't have that much content for that position). What's your suggestion?
You can implement that in react.

**Comment by pranavajith** [comment]
> @pranavajith My suggestion is a footer on the left bottom fixed, similar to the new Instagram desktop ui(which is on the right, but we don't have that much content for that position). What's your suggestion? You can implement that in react.

Gotcha.. working on it as we speak.. thanks! Will get back to you with the developments!

**Comment by SattyamSamania** [comment]
Hey @narayan954 Can I work on this issue. Also tell me further how should I proceed.

**Comment by narayan954** [comment]
Yes, you can :), follow the suggestions mentioned in latest comments and please mention your program, kwoc or codepeak

**Comment by SattyamSamania** [comment]
> Yes, you can :), follow the suggestions mentioned in latest comments and please mention your program, kwoc or codepeak

I want to work under Codepeak. And can I create a new footer.jsx file in the src folder. Will it be ok?

**Comment by narayan954** [comment]
> > Yes, you can :), follow the suggestions mentioned in latest comments and please mention your program, kwoc or codepeak
> 
> I want to work under Codepeak. And can I create a new footer.jsx file in the src folder. Will it be ok?

Great and I'd suggest creating a footer component instead.

**Comment by KrunalGupta02** [comment]
Hi I would like to work on it for #jwoc

**Comment by narayan954** [comment]
sorry but coding period hasn't started for jwoc yet, please follow the guidelines.

**Comment by KrunalGupta02** [comment]
okay

**Comment by KrunalGupta02** [comment]
I want to work on this issue under JWOC

**Comment by narayan954** [comment]
Cool!, best of luck!

**Comment by narayan954** [comment]
Yeah, please add it as a component. External additions might show side effects in rendering the page.

**Comment by KrunalGupta02** [comment]
I have newer to react so i will try to add plz give me some time if possible

**Comment by narayan954** [comment]
> Actually I am newer to react so i will try to add plz give me some time if possible

Fine, take it easy and feel free to ask for help :)

**Comment by narayan954** [comment]
@KrunalGupta02 please update with your progress

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by narayan954** [comment]
great, go ahead!

**Comment by deepbeatz** [comment]
@narayan954 will get back to u asap

**Comment by deepbeatz** [comment]
@narayan954 can u guide me a little bit of wjat i need to do here???

**Comment by deepbeatz** [comment]
@narayan954 ??

**Comment by narayan954** [comment]
> My suggestion is a footer on the left bottom fixed, similar to the new Instagram desktop ui(which is on the right, but we don't have that much content for that position). What's your suggestion?
> You can implement that in react.

Yeah sure, you have to create a footer and for that you have two options as in [This Solution](https://ux.stackexchange.com/questions/12234/how-can-the-classic-footer-elements-be-integrated-into-an-infinite-scrolling-lay)
Please confirm anyone of them and feel free to ask for more information

**Comment by abcxyz31** [comment]
can i contribute to this ...

**Comment by narayan954** [comment]
> can i contribute to this ...

yes sure you can, but first please confirm your approach on this. Take your time to go through this issue and discuss how'd you solve this one. You can find details, help and context in comments above/before you

**Comment by abcxyz31** [comment]
we can keep footer as fixed at bottom but again it would not look good else we can add more option at bottom

**Comment by abcxyz31** [comment]
otherwise sticky footer

**Comment by narayan954** [comment]
> we can keep footer as fixed at bottom but again it would not look good else we can add more option at bottom

Yes exactly, that's why I am in doubt as well, we may look at other similar social medias and how they dealt with this.

**Comment by narayan954** [comment]
@abcxyz31  are you working on this?

**Comment by vk20july** [comment]
I want to work on this issue under GSSOC'23

**Comment by narayan954** [comment]
> @narayan954 sir I want to work on this issue under GSSOC'23

Sure, go ahead, but what's your approach

**Comment by vk20july** [comment]
sorry sir I cant do this task for some reason
sorry for inconvenience

**Comment by narayan954** [comment]
> sorry sir I cant do this task for some reason
> sorry for inconvenience
> 

it's alright
