### ISSUE TITLE
Dark mode is not implemented on new pages

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#660]
### Description

On the footer pages dark is not implemented.

### Steps to reproduce

Go to any of the footer page such as about and click on darkmode button.

### Screenshots

![Screenshot (583)](https://github.com/narayan954/dummygram/assets/116902573/a46b7ede-02c6-4df9-92e0-5751e0219f2d)
![Screenshot (584)](https://github.com/narayan954/dummygram/assets/116902573/13951a3e-6407-4970-8fd6-2948acc92135)
![Screenshot (585)](https://github.com/narayan954/dummygram/assets/116902573/d51643c6-0df6-4886-b718-ad2cd3323d54)

**Comment by narayan954** [comment]
> ### Description
> On the footer pages dark is not implemented.
> 
> ### Steps to reproduce
> Go to any of the footer page such as about and click on darkmode button.
> 
> ### Screenshots
> ![Screenshot (583)](https://user-images.githubusercontent.com/116902573/250974995-a46b7ede-02c6-4df9-92e0-5751e0219f2d.png) ![Screenshot (584)](https://user-images.githubusercontent.com/116902573/250975002-13951a3e-6407-4970-8fd6-2948acc92135.png) ![Screenshot (585)](https://user-images.githubusercontent.com/116902573/250975005-d51643c6-0df6-4886-b718-ad2cd3323d54.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

you can work on this :)
level 1 is okay, right? as it's mostly related to the fonts? or there's more?

**Comment by Palakkgoyal** [comment]
Yes, definitely.
