### ISSUE TITLE
Improve UI of comment dialog box

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#661]
### Description

The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.

**Comment by narayan954** [comment]
> ### Description
> The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Yes, comment section can be made a bit more interactive. I agree with your suggestions. We can also add a link to profile from usernames in comments. 

Also, there's issue #662 which aims to separate current profile and other's profile. Current profile doesn't need much communications from the db compared to other's so I am allowing that. Profile page for everyone could be a dynamic route with their userid and we could get them and update from user's collection directly. Thus reducing need to pass states and handling state errors.

**Comment by Palakkgoyal** [comment]
> > ### Description
> > The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> Yes, comment section can be made a bit more interactive. I agree with your suggestions. We can also add a link to profile from usernames in comments.
> 
> Also, there's issue #662 which aims to separate current profile and other's profile. Current profile doesn't need much communications from the db compared to other's so I am allowing that. Profile page for everyone could be a dynamic route with their userid and we could get them and update from user's collection directly. Thus reducing need to pass states and handling state errors.

Yes, it would be good to seperate current profile and other user's profile. And we can give a somewhat different UI for other people's profile to create a distinction between both.

**Comment by narayan954** [comment]
> > > ### Description
> > > The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.
> > > ### Screenshots
> > > _No response_
> > > ### Additional information
> > > _No response_
> > 
> > 
> > Yes, comment section can be made a bit more interactive. I agree with your suggestions. We can also add a link to profile from usernames in comments.
> > Also, there's issue #662 which aims to separate current profile and other's profile. Current profile doesn't need much communications from the db compared to other's so I am allowing that. Profile page for everyone could be a dynamic route with their userid and we could get them and update from user's collection directly. Thus reducing need to pass states and handling state errors.
> 
> Yes, it would be good to seperate current profile and other user's profile. And we can give a somewhat different UI for other people's profile to create a distinction between both.

yes exactly and some cleanup in both components as well. As we don't need state props in myprofile component and many other fixes. I'll be adding the issue after that pr is merged. 
Also, there's a blocker I'm trying to fix regarding redundant firebase db calls... let's hope it works out

**Comment by Palakkgoyal** [comment]
> > > > ### Description
> > > > The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.
> > > > ### Screenshots
> > > > _No response_
> > > > ### Additional information
> > > > _No response_
> > > 
> > > 
> > > Yes, comment section can be made a bit more interactive. I agree with your suggestions. We can also add a link to profile from usernames in comments.
> > > Also, there's issue #662 which aims to separate current profile and other's profile. Current profile doesn't need much communications from the db compared to other's so I am allowing that. Profile page for everyone could be a dynamic route with their userid and we could get them and update from user's collection directly. Thus reducing need to pass states and handling state errors.
> > 
> > 
> > Yes, it would be good to seperate current profile and other user's profile. And we can give a somewhat different UI for other people's profile to create a distinction between both.
> 
> yes exactly and some cleanup in both components as well. As we don't need state props in myprofile component and many other fixes. I'll be adding the issue after that pr is merged. Also, there's a blocker I'm trying to fix regarding redundant firebase db calls... let's hope it works out. Else, would have to revert back to a much older commit(3,4 days old commit) as final solution

Let's hope for the best as reverting back is really hard.

**Comment by narayan954** [comment]
> > > > > ### Description
> > > > > The UI of comment dialog box is good but, I think it could be better and more user-friendly. For example, when the user hover over delete icon, the cursor doesn't change into pointer and there are also no hover effects. The send icon is also not visible in dark mode and also some other changes could be done such as we can also show the image of person who did the comment.
> > > > > ### Screenshots
> > > > > _No response_
> > > > > ### Additional information
> > > > > _No response_
> > > > 
> > > > 
> > > > Yes, comment section can be made a bit more interactive. I agree with your suggestions. We can also add a link to profile from usernames in comments.
> > > > Also, there's issue #662 which aims to separate current profile and other's profile. Current profile doesn't need much communications from the db compared to other's so I am allowing that. Profile page for everyone could be a dynamic route with their userid and we could get them and update from user's collection directly. Thus reducing need to pass states and handling state errors.
> > > 
> > > 
> > > Yes, it would be good to seperate current profile and other user's profile. And we can give a somewhat different UI for other people's profile to create a distinction between both.
> > 
> > 
> > yes exactly and some cleanup in both components as well. As we don't need state props in myprofile component and many other fixes. I'll be adding the issue after that pr is merged. Also, there's a blocker I'm trying to fix regarding redundant firebase db calls... let's hope it works out. Else, would have to revert back to a much older commit(3,4 days old commit) as final solution
> 
> Let's hope for the best as reverting back is really hard.

yup, I'll be getting some holiday from college trainings from today onwards! I'll work on this now. I've thought about this and we shouldn't be needing any reverting back. I'll be checking every db call now

**Comment by Palakkgoyal** [comment]
Okay. That's nice. When I first read that you're getting holidays, I get worried(thinking that you will not work on this project) but, that's great you are utilizing your holidays. 
That would be good if we didn't need to revert back. Its a hard task, best wishes.

**Comment by narayan954** [comment]
> Okay. That's nice. When I first read that you're getting holidays, I get worried(thinking that you will not work on this project) but, that's great you are utilizing your holidays. That would be good if we didn't need to revert back. Its a hard task, best wishes.

Thanks :)
