### ISSUE TITLE
Improve UI of comment dialog box.

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#663]
### Description

Its currently good but it could be better.
There are also some shortcomings such as the delete icon don't have any hover effect on it which leads to bad UX.
The send button is not visible in dark mode and other things could be done as well to make it look good.

### Screenshots

![Screenshot (586)](https://github.com/narayan954/dummygram/assets/116902573/db0394b4-3db9-4e13-a209-6dc225848e2b)

**Comment by Palakkgoyal** [comment]
![Screenshot (587)](https://github.com/narayan954/dummygram/assets/116902573/0d9126c8-0cc6-410e-a2a0-d9ecfdfb0dfa)

**Comment by narayan954** [comment]
> I thought the previous one was not create due to network disconnection.

Yes, github is having these hiccups for fake as well nowadays.

**Comment by Palakkgoyal** [comment]
Yups, that's true
