### ISSUE TITLE
[Bug] Null Username signup

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#67]
### Description

We can just signup without putting a username, it will show some error, but logs the user in, leading to existence of null users, with ghost posts!!

### Steps to reproduce

While signing up don't use a username. 

### Screenshots

![image](https://user-images.githubusercontent.com/77617189/193799372-4f3d6381-2f8b-4aba-a4f3-4f75aa7badba.png)
![image](https://user-images.githubusercontent.com/77617189/193799484-0087df54-53a8-4550-96ec-542354fce5f7.png)

### Additional information

We should implement validation in the sign up modal.

**Comment by EdkoPitonak** [comment]
Hi i would like to work on this if possible

**Comment by narayan954** [comment]
Sure, Go ahead

**Comment by EdkoPitonak** [comment]
Hi i have it fixed , will try to do some testing and if all goes well will try to make pull request

**Comment by narayan954** [comment]
Sure, Thank you!
