### ISSUE TITLE
Navbar profile button scroll down enhancement

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#673]
### Description

I'm in Gssoc'23

When we click the rightmost profile button on the navbar, the scroll-down option shows 4 options in white boxes with very large padding.
We can change its color to align with the background color in both dark and light mode and change the size and font size of boxes to make them look even better.
Further, if the scroll down appears below the profile button taking less space on the ui.

**Comment by NandiniGera** [comment]
can i work on this issue?

**Comment by narayan954** [comment]
Hi @NandiniGera , actually we're removing the profile button from navbar as the sidebar is a better option. Also an issue regarding this is also in progress. So I don't think we need to work on that. 
You may work on other issues and claim some old stalled issues :)

Thanks

**Comment by narayan954** [comment]
closing this as not planned
