### ISSUE TITLE
Uncontrolled requests bug

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#676]
### Description

Currently somethings off with our website,that's why it's down.... too many requests are being made automatically causing the daily limit to exceed in matter of minutes. I saw around 50k requests in some minutes till the limit exceeded.
Earlier build shouldn't have caused this error as our app was working fine till morning today, perhaps.
More info: due to an error in pr #635 (that was only visible in production build) , the application was unable to build and hence we didn't have any new production deployments for 20 hours.  I pushed the fix in latest [commit](https://github.com/narayan954/dummygram/commit/18335612ee192bf2ff722497b1928dcf507be9e2), but this shouldn't be the reason.
Problem could be from a merge commit from commits earlier than pr 635, or one of the testers of our applications got this error. 
if it's the former, it should be fairly easy to solve as we have to look at previous commits only. If it's latter, it'd be really difficult.

Another clue. I was testing the pr #657 and there I noticed , favourites page seems to be misbehaving, it was repeatedly showing post not found snackbar. So I believed it  could be related to promises in there. I tried different fixes on that method, but the requests were not stopping, I even commented that useeffect but in vain :/ . I tested in test db with credentials only 1 contributor knew so chances are extremely low that his commit would've caused this.

I'll be trying another approach, basically to monitor the network tabs and try to find a solution. 
Anyone can also try fixing the errors

### Steps to reproduce

you can generate your own credentials and test as well yourself

**Comment by Kalyan-velu** [comment]
@narayan954 I would like to help.

**Comment by narayan954** [comment]
> @narayan954 I would like to help.

Thank you! I'm going to walk through the commits earlier than 635, I hope this works out

**Comment by Kalyan-velu** [comment]
> > @narayan954 I would like to help.
> 
> Thank you! I'm going to walk through the commits earlier than 635, I hope this works out

ok
