### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#677]
### Description

In setting page there is no close button option to close the setting form.
If any user just want to see that setting page and want to leave without doing changes for that user check close button to back to home page or leave to that page.

### Steps to reproduce

I would like to add cancle button  on right top of that setting page to close that page .

### Screenshots

![Screenshot 2023-07-05 214601](https://github.com/narayan954/dummygram/assets/104631882/7d8d76d8-379c-495d-b6ae-6440e9f996ed)

**Comment by narayan954** [comment]
> ### Description
> In setting page there is no close button option to close the setting form. If any user just want to see that setting page and want to leave without doing changes for that user check close button to back to home page or leave to that page.
> 
> ### Steps to reproduce
> I would like to add cancle button on right top of that setting page to close that page .
> 
> ### Screenshots
> ![Screenshot 2023-07-05 214601](https://user-images.githubusercontent.com/104631882/251215502-7d8d76d8-379c-495d-b6ae-6440e9f996ed.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_

thanks for raising the issue, you can work on this! :)
