### ISSUE TITLE
[FEATURE]: Icon in sidebar

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#685]
### Description

In the settings page sidebar, there is no icon. Without icons, our sidebar appears incomplete, which affects its professional appearance.
Also in dark mode sidebar is not appear so that I would like to solve this issue.

### Screenshots

![Screenshot 2023-07-06 142954](https://github.com/narayan954/dummygram/assets/104631882/40107d86-5583-4fff-92cf-619db86fb615)

### Additional information
![Screenshot 2023-07-06 144926](https://github.com/narayan954/dummygram/assets/104631882/2217e591-843d-40cc-9a3d-c153bec34b4f)

_No response_

**Comment by narayan954** [comment]
> ### Description
> In the settings page sidebar, there is no icon. Without icons, our sidebar appears incomplete, which affects its professional appearance. Also in dark mode sidebar is not appear so that I would like to solve this issue.
> 
> ### Screenshots
> ![Screenshot 2023-07-06 142954](https://user-images.githubusercontent.com/104631882/251403157-40107d86-5583-4fff-92cf-619db86fb615.png)
> 
> ### Additional information
> ![Screenshot 2023-07-06 144926](https://user-images.githubusercontent.com/104631882/251405755-2217e591-843d-40cc-9a3d-c153bec34b4f.png)
> 
> _No response_

we've fixed the font issue. You can add the icons for the sections in settings sidebar
