### ISSUE TITLE
Copy url button for sharing posts

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#690]
### Description

I'm a Gssoc'23 contributor.
To share a post, when we click on share icon, url of the post appears at the placeholder, we can add a copy button beside it which on pressing directly copies url for sharing. User will not have to copy it manually from the placeholder. 

I want to fix this, @narayan954  please assign me this issue!

### Steps to reproduce

We can use the Clipboard API to implement this.

**Comment by narayan954** [comment]
you can go ahead! :)

**Comment by NandiniGera** [comment]
> you can go ahead! :)

Homepage of the project isn't loading since yesterday, thats why i'm unable to check and confirm the changes i've added in the new branch of my cloned repo, is there any server issue?

**Comment by narayan954** [comment]
> > you can go ahead! :)
> 
> Homepage of the project isn't loading since yesterday, thats why i'm unable to check and confirm the changes i've added in the new branch of my cloned repo, is there any server issue?

more like client issue, client's basically sending too many requests and overloading the server, causing it's quota limit to exceed . I'm trying to find exactly which component is causing this error. Will fix this, and server should be up and running. Also you can generate your own credentials and test it. you can also ask me for the temporary credentials to replace in the .env file present in the repo.
