### ISSUE TITLE
[OTHER] Adding profile pic at dropdown

### ISSUE THREAD

**Issue by krutikajichkar** [narayan954/dummygram#691]
### What would you like to share?

Right now the profile dropdown is showing a default user image , i want to replace it with the user profile image , please assign me this under gssoc'23

**Comment by narayan954** [comment]
Hi @krutikajichkar , do you mean the one on navbar? (top right) 
Actually we're removing that whole element from navbar and implementing in the sidebar, so this won't be needed.
Hope you understand.

Thank you!

**Comment by krutikajichkar** [comment]
@narayan954  can I move that on sidebar?
