### ISSUE TITLE
[FEATURE] Improve Sign up page ui

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#695]
### Description

Hey, I want to improve the signup. The sign-in page is looking good but the sign-up page is not.  Can you please assign it to me?

**Comment by narayan954** [comment]
> ### Description
> Hey, I want to improve the signup. The sign-in page is looking good but the sign-up page is not. Can you please assign it to me?
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Hi @SubhamB2003 sign up page is already in progress and issue is created/assigned as well.
I hope to merge it by tonight. If you think there's an issue in the page afterwards, you can ping me in this issue! 

Thank you

**Comment by SubhamB2003** [comment]
> > ### Description
> > Hey, I want to improve the signup. The sign-in page is looking good but the sign-up page is not. Can you please assign it to me?
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> Hi @SubhamB2003 sign up page is already in progress and issue is created/assigned as well. I hope to merge it by tonight. If you think there's an issue in the page afterwards, you can ping me in this issue!
> 
> Thank you

Ok

**Comment by SubhamB2003** [comment]
@narayan954 Hey, is this issue solved? if not then can you please assign it to me

**Comment by narayan954** [comment]
> @narayan954 Hey, is this issue solved? if not then can you please assign it to me

please take a look at the page now and suggest what could be done? Also the image being stretched like that makes it ugly. I was thinking, maybe we can fix it on viewport and let only form be scrollable. Would that work?

**Comment by SubhamB2003** [comment]
> > @narayan954 Hey, is this issue solved? if not then can you please assign it to me
> 
> please take a look at the page now and suggest what could be done? Also the image being stretched like that makes it ugly. I was thinking, maybe we can fix it on viewport and let only form be scrollable. Would that work?

Yeah, definitely Can you assign it to me?
Also, the confirm password is not showing the validator message I mean the password rule
![image](https://github.com/narayan954/dummygram/assets/94003231/8ca3370f-6b06-44a3-97b8-e0bb54d0e7de)

**Comment by narayan954** [comment]
> > > @narayan954 Hey, is this issue solved? if not then can you please assign it to me
> > 
> > please take a look at the page now and suggest what could be done? Also the image being stretched like that makes it ugly. I was thinking, maybe we can fix it on viewport and let only form be scrollable. Would that work?
> 
> Yeah, definitely Can you assign it to me?
> Also, the confirm password is not showing the validator message I mean the password rule
> ![image](https://github.com/narayan954/dummygram/assets/94003231/8ca3370f-6b06-44a3-97b8-e0bb54d0e7de)
> 

sure, go captain! btw I doubt we need any other validator than password not matching for the confirm password field? There alignment needs to be fixed though.

**Comment by SubhamB2003** [comment]
> 
Your my captain bro. You literally told me many things about GitHub🫡

no, we don't need any other validator I was checking by if else condition

**Comment by narayan954** [comment]
> > 
> 
> Your my captain bro. You literally told me many things about GitHub🫡
> 
> no, we don't need any other validator I was checking by if else condition

hehe thanks,

Ohh alright, understood.You can do that!
