### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Deepanshu0703** [narayan954/dummygram#701]
### Description

There is only @gmail.com is allowed in mail but there are more othe mail id domain so i thing that should be improved.

### Steps to reproduce

removing only matching gmail.com and checking all domain type mail id.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/114489502/c616dc33-f098-4ded-aab6-dfc7f07ac23e)

**Comment by fiskryeziu** [comment]
why not use something more general regex like
```regex
/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i;
```

**Comment by narayan954** [comment]
> why not use something more general regex like
> 
> ```regexp
> /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i;
> ```

exactly, it involves just changing this regex

**Comment by Deepanshu0703** [comment]
So that is a bug that is why I raised the issue .

**Comment by narayan954** [comment]
> So that is a bug that is why I raised the issue .

right, you can work on this! and do test your regex! :)
