### ISSUE TITLE
Search bar page sidebar

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#702]
### Description

On search bar page sidebar shows half sidebar only from searchicon,
also profile page shows horizontal line.

### Steps to reproduce

want to add above sidebar menu.

### Screenshots

![Screenshot 2023-07-07 180842](https://github.com/narayan954/dummygram/assets/104631882/8f2f0eec-ea00-42d0-bd08-58d7509b5ea1)
![Screenshot 2023-07-07 181717](https://github.com/narayan954/dummygram/assets/104631882/872bb3eb-fbab-4099-a599-a2ce853ba9bd)

**Comment by narayan954** [comment]
thanks for spotting this bug! you can work on fixing this! :)
