### ISSUE TITLE
[OTHER] : Adding Important Checkboxes

### ISSUE THREAD

**Issue by parasss19** [narayan954/dummygram#706]
### What would you like to share?

- There are no checkboxes present in the issue template
- Which is very important for contributing (like GSSOC"23 , code of conduct etc)
- Many times contributor forget to add gssoc'23 label on issues and its difficult to project admin to mark the gssoc label on issues

### Additional information

- I will add important checkboxes
- Also there are no drop down menu in issues template like on which browser you see problems so i will also add drop down feature in issues template

## Sample

<img width="942" alt="Screenshot 2023-06-25 183208" src="https://github.com/narayan954/dummygram/assets/101205226/71e07a58-ba55-42e2-989b-0350f122e583">

**Comment by narayan954** [comment]
you can go ahead! :)
