### ISSUE TITLE
unhandled promise

### ISSUE THREAD

**Issue by debankanmitra** [narayan954/dummygram#714]
### Description

PromiseNotCaughtGeneral: No catch method for promise , This may result in an unhandled promise rejection.

### Steps to reproduce

![Screenshot from 2023-07-08 18-35-58](https://github.com/narayan954/dummygram/assets/41522827/a6cf4328-8233-49d2-a543-edd76f061631)

### Desktop (please complete the following information)

OS - fedora 38
 Browser - firefox,chromium
 Version - latest

### Additional information

I can fix the error can i go with it?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> PromiseNotCaughtGeneral: No catch method for promise , This may result in an unhandled promise rejection.
> 
> ### Steps to reproduce
> ![Screenshot from 2023-07-08 18-35-58](https://user-images.githubusercontent.com/41522827/251973865-a6cf4328-8233-49d2-a543-edd76f061631.png)
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> OS - fedora 38 Browser - firefox,chromium Version - latest
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> I can fix the error can i go with it?
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

right, you can fix this!
