### ISSUE TITLE
Error: Uncaught TypeError when accessing 'photoURL' property due to missing user

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#715]
### Description

I encountered an error in the codebase that results in an "Uncaught TypeError: Cannot read properties of null (reading 'photoURL')" message. The error occurs when navigating to the favorites and notification routes and then reloading the page. It seems to be related to the absence of a user object.

### Steps to reproduce

1. Navigate to the favorites route.
2. Navigate to the notification route.
3. Reload the page.
4. See the error message in the console or on the page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I encountered an error in the codebase that results in an "Uncaught TypeError: Cannot read properties of null (reading 'photoURL')" message. The error occurs when navigating to the favorites and notification routes and then reloading the page. It seems to be related to the absence of a user object.
> 
> ### Steps to reproduce
> 1. Navigate to the favorites route.
> 2. Navigate to the notification route.
> 3. Reload the page.
> 4. See the error message in the console or on the page.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Thanks for spotting the bug, would you like to work on this?

**Comment by fiskryeziu** [comment]
I would love to work on this

**Comment by narayan954** [comment]
> I would love to work on this

thank you! go ahead!
