### ISSUE TITLE
Error: Cannot read properties of null 

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#725]
### Description

When reloading the page  it gives an error  cannot read properties of null (reading displayName) also when fixing displayName property it shows another error cannot read properties of null this time the property uid from auth.currentUser.uid

### Steps to reproduce

1. Navigate to the profile  route.
2. Reload the page.
3. See the error message in the console or on the page.

### Additional information

The fix should be same as the #715 and some condition checks in useEffect to be sure we getting the user object 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> When reloading the page it gives an error cannot read properties of null (reading displayName) also when fixing displayName property it shows another error cannot read properties of null this time the property uid from auth.currentUser.uid
> 
> ### Steps to reproduce
> 1. Navigate to the profile  route.
> 2. Reload the page.
> 3. See the error message in the console or on the page.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> The fix should be same as the #715 and some condition checks in useEffect to be sure we getting the user object
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Right, thanks for raising the issue! I think it's perhaps due to the implementation of profile page where on refresh the element loses the props and hence everything crashes. What do you think???
You can work on this! Thanks a lot!

**Comment by narayan954** [comment]
> > ### Description
> > When reloading the page it gives an error cannot read properties of null (reading displayName) also when fixing displayName property it shows another error cannot read properties of null this time the property uid from auth.currentUser.uid
> > ### Steps to reproduce
> > 
> > 1. Navigate to the profile  route.
> > 2. Reload the page.
> > 3. See the error message in the console or on the page.
> > 
> > ### Screenshots
> > _No response_
> > ### Desktop (please complete the following information)
> > _No response_
> > ### Smartphone (please complete the following information)
> > _No response_
> > ### Additional information
> > The fix should be same as the #715 and some condition checks in useEffect to be sure we getting the user object
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [ ]   I have checked the existing issues
> > * [ ]   I'm a GSSoC'23 contributor
> > * [x]   I want to work on this issue
> 
> Right, thanks for raising the issue! I think it's perhaps due to the implementation of profile page where on refresh the element loses the props and hence everything crashes. What do you think??? You can work on this! Thanks a lot!

i think we should make profile a dynamic route with uid as parameter and then render the profile page independently.... or what's your proposal?

**Comment by fiskryeziu** [comment]
yeah that'll work besides that I tried and it fixed the problem adding a condition in this case for e.g : 
```javascript 
  useEffect(() => {
    if (auth.currentUser) {
      const checkFriendRequestSent = async () => {
        const currentUserUid = auth.currentUser.uid;
        const targetUserUid = uid;
        const friendRequestsRef = db
          .collection("users")
          .doc(targetUserUid)
          .collection("friendRequests");
        const query = friendRequestsRef
          .where("sender", "==", currentUserUid)
          .where("recipient", "==", targetUserUid)
          .limit(1);

        const snapshot = await query.get();
        if (!snapshot.empty) {
          setFriendRequestSent(true);
        }
      };
      checkFriendRequestSent();
    }
  }, []);
```
Your proposal also sounds great, with that we don't need condition check because we get the uid from the param if I'm not wrong.

**Comment by narayan954** [comment]
> 

Yes and you're correct as well. We'll implement the functionality later. I'll add that as a TODO issue. Your current fix should fix the problem, will review that asap!
