### ISSUE TITLE
logo is not properly align 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#731]
### Description

In Logout card section logo is not properly align 

### Steps to reproduce

go to website and click on profile logo avatar  and click on logout.

### Screenshots

<img width="346" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/cf81e2cd-f413-4706-bf3b-1880d0eb88ae">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @biplavmz can you please combine this issue with #724 , as per the guidelines to be scored. I've been asked by gssoc team regarding this.

Thank you!

**Comment by biplavmz** [comment]
OK @narayan954
