### ISSUE TITLE
Emojiy button is not working in the comment popup model

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#737]
### Description

Emoji button is not working.

### Steps to reproduce

click on comment in the post one popup model will open than click on emoji it is not working.  

### Screenshots

<img width="437" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/aa463b67-f87f-4c97-8e04-0d898b9a0c14">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can work on this!

**Comment by biplavmz** [comment]
ok Thanks @narayan954
