### ISSUE TITLE
Content Overflows in Posts page

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [narayan954/dummygram#739]
### Description

When the post content is more, it overflows and half of the text content gets cut. 

### Steps to reproduce

Create a post with long content and Click read more. 

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104077094/82445ec7-66dc-4a43-9e46-06881a156b5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> When the post content is more, it overflows and half of the text content gets cut.
> 
> ### Steps to reproduce
> Create a post with long content and Click read more.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/104077094/252331008-82445ec7-66dc-4a43-9e46-06881a156b5a.png)
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Thanks for raising the issue! you can work on this!

Also what do you think about that refresh icon on the right hand side? What's that button doing or how's that even existing instead of name, will need to look into the code....

**Comment by VijayalakshmiGanesh** [comment]
> Also what do you think about that refresh icon on the right hand side? What's that button doing or how's that even existing instead of name, will need to look into the code....

Onclick of the refresh button, resetErrorBoundary function is getting called. This function is coming from react-error-boundary package. 
![image](https://github.com/narayan954/dummygram/assets/104077094/8fd79f67-796b-4ad8-92b1-a86942b18b5d)

**Comment by VijayalakshmiGanesh** [comment]
@narayan954  For now i have fixed content overflow issue. Please let me know what has to be done with the refresh button

**Comment by narayan954** [comment]
> > Also what do you think about that refresh icon on the right hand side? What's that button doing or how's that even existing instead of name, will need to look into the code....
> 
> Onclick of the refresh button, resetErrorBoundary function is getting called. This function is coming from react-error-boundary package. ![image](https://user-images.githubusercontent.com/104077094/252872982-8fd79f67-796b-4ad8-92b1-a86942b18b5d.png)

ohh understood! Thank you!

**Comment by narayan954** [comment]
> @narayan954 For now i have fixed content overflow issue. Please let me know what has to be done with the refresh button

lets raise an issue?

**Comment by VijayalakshmiGanesh** [comment]
> > @narayan954 For now i have fixed content overflow issue. Please let me know what has to be done with the refresh button
> 
> lets raise an issue and solve it?

Yes...
