### ISSUE TITLE
Validation is required for comments

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [narayan954/dummygram#740]
### Description

An empty comment with just a blank space is accepted.

### Steps to reproduce

Enter a comment with just spaces and click post.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/104077094/978ae21e-c910-46a7-90aa-4991a699f046)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Thanks for finding the error :) Can you please add a min and max limit for comment as part of the validation??
