### ISSUE TITLE
add a contributor page

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#741]
### Description

Hey, there is no option to show the contributors. I want to add a contributor page where we showcase all the contributors.
Can you please assign it to me under GSSOC'23?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Hey, there is no option to show the contributors. I want to add a contributor page where we showcase all the contributors. Can you please assign it to me under GSSOC'23?
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @biplavmz there already exists a contrbutor page in footer, please have a look at it again. I'm closing this issue as not planned
