### ISSUE TITLE
Position the loading spinner to center of the page

### ISSUE THREAD

**Issue by Avinash905** [narayan954/dummygram#742]
### Description

Currently the loading spinner is present at the top of the page instead of center of the page.

### Steps to reproduce

Add height of the page to 100 vh so that the loader comes to the center of the page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Avinash905** [comment]
Currently the loader is at the top of the page instead of center.


https://github.com/narayan954/dummygram/assets/56786344/c334cfd1-f0b8-40b6-a86a-042f16581bc4

**Comment by narayan954** [comment]
> 

aight! you can work on this :)
