### ISSUE TITLE
Refactor the sign up and login page

### ISSUE THREAD

**Issue by Walexz01** [narayan954/dummygram#745]
### Description

I will like to refactor the sign up and login page by breaking then into reuseable components

### Steps to reproduce

create a reuseable components

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead! :)

**Comment by biplavmz** [comment]
Hii @Walexz01 If you are not working on It can i work on it.

**Comment by Walexz01** [comment]
@biplavmz am I working on it sir
