### ISSUE TITLE
Active Tabs are not showing

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#750]
### Description

Active Tabs are not showing on the side bar
Can you please assign it to me under GSSOC'23?

### Steps to reproduce

go to website and click on the search or home

### Screenshots

<img width="204" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/b4f022c7-c299-4869-a619-da57ab350c0c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
yes you can go ahead!
