### ISSUE TITLE
favourites is showing Empty

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#751]
### Description

when we click on like button than favourites post should be show on favourites page.

### Steps to reproduce

go to website and click on favourites Tab.

### Screenshots

<img width="383" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/94426963-85a6-49f5-bb5f-811dfb7a181c">

<img width="492" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/a597909b-bf96-49ad-89e2-c8f5facac215">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> when we click on like button than favourites post should be show on favourites page.
> 
> ### Steps to reproduce
> go to website and click on favourites Tab.
> 
> ### Screenshots
> <img alt="image" width="383" src="https://user-images.githubusercontent.com/68702055/252642191-94426963-85a6-49f5-bb5f-811dfb7a181c.png"> <img alt="image" width="492" src="https://user-images.githubusercontent.com/68702055/252642244-a597909b-bf96-49ad-89e2-c8f5facac215.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

well, favourites page is for the saved posts right now and I think it's okay for now.
Thanks for suggesting this tho :)
