### ISSUE TITLE
[BUG]: Dark mode compatibility

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#753]
### Description

- Post content is not visible in dark mode which has default background in home page.
- Post content on Post page is not visible in dark mode.
- Search page and create post form is also not compatible with dark mode.

### Steps to reproduce

- Making sure website is dark mode compatible (posts, content, headings,etc should be styled according to light and dark mode both).

### Home Page
<img width="600" src="https://github.com/narayan954/dummygram/assets/66116440/3607aac3-d651-4c53-8523-50f6022bd7aa">

### Post page

<img width ="600" src="https://github.com/narayan954/dummygram/assets/66116440/9a47f7f4-6e7c-4f3c-a21f-68985fee17ff">

### Search page
<img width ="600" src="https://github.com/narayan954/dummygram/assets/66116440/56687963-b68e-4678-affa-832ff06bd5d4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by biplavmz** [comment]
Hii @anamika7153 I would like to work on this bug.

**Comment by biplavmz** [comment]
hii @narayansoni can you assign it to me under GSSOC'23?

**Comment by narayan954** [comment]
You can work on this @anamika7153

**Comment by narayan954** [comment]
> You can work on this @anamika7153

please make sure to test everything

**Comment by anamika7153** [comment]
> > You can work on this @anamika7153
> 
> please make sure to test everything

Sure :)
