### ISSUE TITLE
unable to see post text 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#754]
### Description

unable to see post text while writing on the Create new post.
Can you please assign it to me under GSSOC'23?

### Steps to reproduce

go to website and click on the new post 

### Screenshots

<img width="497" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/69859caa-dad8-4dc7-b21b-f4e916414ed1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by anamika7153** [comment]
@narayan954 I have already raised this issue #753

**Comment by narayan954** [comment]
> @narayan954 I have already raised this issue #753

right! closing as duplicate!
