### ISSUE TITLE
[BUG]: Search operation is case sensitive and inefficient

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#755]
### Description

- Searching is case-sensitive. 
- Also it's not working efficiently, it's not providing search result .
- Also it should provide clear information as to what it searches (user or some post). There should be a heading like "Search users".

### Steps to reproduce

Go to website and search users

## Case sensitive issue:

|     |                   |
|-----|---------------------------------|
| **There is a user: "viju g"** | <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/fbb3238e-396d-419d-9b4c-b9455d694438"> |
|  **When i write "vij" (in lowercase), it gives result:** | <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/1cbb3696-cf02-43f8-8c0b-cf4992c35d42"> |
| **When i write "Vij" (in upper-case), it doesn't give result** | <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/1c47a07e-22ca-4849-b140-8bd62fbb1012"> |

## Inefficiency:

|     |                   |
|-----|---------------------------------|
| **There are users "Narayan" and "Tisha Garg"** | <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/40675022-626f-4537-993e-6f250b180de6"> |
|  **When I search for them , doesn't give results:** |  |
| <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/70dbaa5c-d3be-461b-96a3-8c5810d048ed"> | <img width="500" src="https://github.com/narayan954/dummygram/assets/66116440/dd104f0d-0443-46d0-939d-b031afda9cbe"> |

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> * Searching is case-sensitive.
> * Also it's not working efficiently, it's not providing search result .
> * Also it should provide clear information as to what it searches (user or some post). There should be a heading like "Search users".
> 
> ### Steps to reproduce
> Go to website and search users
> 
> ### Screenshots
> ## Case sensitive issue:
> **There is a user: "viju g"**	<img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252663701-fbb3238e-396d-419d-9b4c-b9455d694438.png">
> **When i write "vij" (in lowercase), it gives result:**	<img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252664030-1cbb3696-cf02-43f8-8c0b-cf4992c35d42.png">
> **When i write "Vij" (in upper-case), it doesn't give result**	<img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252664346-1c47a07e-22ca-4849-b140-8bd62fbb1012.png">
> ## Inefficiency:
> **There are users "Narayan" and "Tisha Garg"**	<img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252664680-40675022-626f-4537-993e-6f250b180de6.png">
> **When I search for them , doesn't give results:**	
> <img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252665093-70dbaa5c-d3be-461b-96a3-8c5810d048ed.png">	<img alt="" width="500" src="https://user-images.githubusercontent.com/66116440/252665759-dd104f0d-0443-46d0-939d-b031afda9cbe.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

correct! you can work on this and please make sure to test them :)
