### ISSUE TITLE
[FEATURE] Profile Pic Upload Cancel button

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#756]
### Description

- Currently, there is no cancel button while updating profile pic.
- If the user changes his mind then there is no option to cancel it, he/she has to reload the page to cancel it.
- I will add the cancel button to cancel updating the profile pic.

### Screenshots

|  |  |
|---|--------|
| This is the current version | I am thinking of achieving something like this |
| <img width="400" src="https://github.com/narayan954/dummygram/assets/66116440/e7066dde-e3cc-4f7c-8f83-5bf407f68f11"> | <img width="508" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/ca43a3ac-d4bd-41db-a312-79357c01f456"> |

I have implemented it, I just need to be assigned and need to make a PR.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can work on this! :)
