### ISSUE TITLE
Text overflowing on single post view page

### ISSUE THREAD

**Issue by SubhamB2003** [narayan954/dummygram#757]
### Description

Hey, on the single post view page, the text is overflowing. You can check below
![image](https://github.com/narayan954/dummygram/assets/94003231/bda95e98-12cf-4965-bc99-006ed9dd6d96)

Can you please assign it to me?

### Steps to reproduce

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by VijayalakshmiGanesh** [comment]
Hi @SubhamB2003 , This issue has been raised already #739

**Comment by SubhamB2003** [comment]
>

Oh ok.
