### ISSUE TITLE
[FEATURE] New login/signup page

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#76]
### Description

When we enter site, we directly get to the posts and due to this our database needs to be exposed to public to load posts, which isn't a good practice. We can have a sign in/sign up page instead.

### Additional information

We need to implement a simple login/signup page

**Comment by tanishk-23** [comment]
@narayan954 Can you please assign this issue to me?

**Comment by narayan954** [comment]
Okay @tanishk-23

**Comment by Pranjal2870** [comment]
Please assign me this issue @narayan954

**Comment by narayan954** [comment]
> Please assign me this issue @narayan954

you need to ask @tanishk-23

**Comment by narayan954** [comment]
it's been 24hours of no response from tanishk, so @Pranjal2870 you can work on this.

**Comment by Pranjal2870** [comment]
Okay

**Comment by narayan954** [comment]
Open for KWOC

**Comment by singhkaran202** [comment]
Hello @narayan954 I'd love to work on this issue if that's OK.
Can you please assign it to me?

**Comment by narayan954** [comment]
> 

Sure @singhkaran202

**Comment by srilakshmiv123** [comment]
I'm interested to contribute this issue. Can you assign me?

**Comment by narayan954** [comment]
> I'm interested to contribute this issue. Can you assign me?

Hello @srilakshmiv123, this issue is currently assigned to @singhkaran202, you can ask him, if he permits then I can assign you or if he doesn't respond within 3 days then I will assign you. 
Hope you understand.
Thanks

**Comment by kshitij01042002** [comment]
@narayan954 it seems that no one is working on this issue can you assign me this?

**Comment by narayan954** [comment]
> @narayan954 it seems that no one is working on this issue can you assign me this?

@singhkaran202 please mention if you're working on this within 24 hours or It'll get assigned to @kshitij01042002

**Comment by singhkaran202** [comment]
Yes please, I am working on it...

**Comment by ankushj0801** [comment]
I want to work on this. Please assign me @narayan954

**Comment by narayan954** [comment]
> I want to work on this. Please assign me @narayan954

due to no progress from @singhkaran202 you can work on this

**Comment by praduman8435** [comment]
can you assign this to me @narayan954

**Comment by narayan954** [comment]
Changing difficulty to medium :)

**Comment by narayan954** [comment]
Hi, are you still working?

**Comment by Sarita-021** [comment]
hi @narayan954   I would like to work on the issue . 
Can you assign it to me. under JWOC

**Comment by parv15** [comment]
I'm interested to contribute this issue. Can you assign me?

**Comment by narayan954** [comment]
@Sarita-021 best of luck! :)

**Comment by narayan954** [comment]
> I'm interested to contribute this issue. Can you assign me?

Sorry @parv15, she claimed it first :/ as in FCFS scheduling.

**Comment by narayan954** [comment]
@Sarita-021 are you still working? please confirm

**Comment by Sarita-021** [comment]
No

**Comment by narayan954** [comment]
> No

okay

**Comment by vatan-prakash** [comment]
please assign this issue to me @narayan954

**Comment by narayan954** [comment]
> please assign this issue to me @narayan954

sure go ahead! and please confirm program, jwoc?

**Comment by vatan-prakash** [comment]
Yes

**Comment by vatan-prakash** [comment]
> > please assign this issue to me @narayan954
> 
> sure go ahead! and please confirm program, jwoc?

Yes jwoc

**Comment by narayan954** [comment]
great, best of luck!

**Comment by vatan-prakash** [comment]
@narayan954 On which branch, do I have to work? Is it master or I make another branch

**Comment by narayan954** [comment]
> @narayan954 On which branch, do I have to work? Is it master or I should make another branch

you have to create a branch for the task and create a pull request to the master branch when done

**Comment by vatan-prakash** [comment]
Ok narayan Thank you

**Comment by narayan954** [comment]
are you still working on this? please update @vatan-prakash

**Comment by vatan-prakash** [comment]
No, I am not please assign to any one else

**Comment by narayan954** [comment]
alright :)

**Comment by sarkartanmay393** [comment]
@narayan954 Assign it to me Narayan.

**Comment by narayan954** [comment]
> @narayan954 Assign it to me Narayan.

okay, you can go ahead!

**Comment by sarkartanmay393** [comment]
@narayan954  Do I need to remove the sign-in and signup modals and replace them with a page?

**Comment by narayan954** [comment]
> @narayan954 Do I need to remove the sign-in and signup modals and replace them with a page?

We may have the main/whole application authenticated by default, so I don't think we'd need those login and signup buttons and their modals as well.

**Comment by narayan954** [comment]
like instagram.com

**Comment by sarkartanmay393** [comment]
@narayan954 Raised PR #222
