### ISSUE TITLE
Buttons for Routing back

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#763]
### Description

Whenever we open Contributors Page, Guidelines, Policy and About Page, there is no button for the user to go back to the home page. We can add a BACK HOME button to enable user to route back to the home page. 

### Steps to reproduce

I'll route and add the button for the same on all the four pages on the most feasible position on the ui. 

Please assign me this issue! @narayan954 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
thanks for raising the issue! you can work on this!
