### ISSUE TITLE
[BUG]: Profile Page posts overlapping

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#766]
### Description

- Profile Page Posts are overlapping the sidebar.

### Steps to reproduce

- Post something
- Go to profile page
- Inspect and see the posts below 1000px

### Video

https://github.com/narayan954/dummygram/assets/66116440/6429ead0-9a4b-4111-809d-366f80d33f48

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
now they're worse, can you please try to fix them?

**Comment by anamika7153** [comment]
> now they're worse, can you please try to fix them?

yeah, I'll check and fix it.

**Comment by narayan954** [comment]
> > now they're worse, can you please try to fix them?
> 
> yeah, I'll check and fix it.

this issue and the other are both affected due that same pr I mentioned there I suppose. Solving in either one should fix the issue.

**Comment by anamika7153** [comment]
> > > now they're worse, can you please try to fix them?
> > 
> > 
> > yeah, I'll check and fix it.
> 
> this issue and the other are both affected due that same pr I mentioned there I suppose. Solving in either one should fix the issue.

No, padding needs to be fixed for home page posts. You can check that home page posts are still affected with the padding of your mentioned PR
