### ISSUE TITLE
[FEATURE] A new loader for dummygram

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#780]
### Description

I think the current loader is very normal and we can make it look better.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
yes, also there're two loaders, we may remove the first one saying dummygram, what do you say?
Also*3, if am correct there's already an issue regarding this, can you check that out and claim?

**Comment by Palakkgoyal** [comment]
I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.

**Comment by narayan954** [comment]
> I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.

I didn't mean three loaders, I meant "also,also,also" (also*3)

**Comment by narayan954** [comment]
> I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.

That'd be better I guess. What should we do then? Remove this dummygram na? and add the splash screen instead .

**Comment by Palakkgoyal** [comment]
> > I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.
> 
> I didn't mean three loaders, I meant "also,also,also" (also*3)

Oh okk got it.

**Comment by Palakkgoyal** [comment]
> > I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.
> 
> That'd be better I guess. What should we do then? Remove this dummygram na? and add the splash screen instead .

Yes, I think this should be removed. If you want to add a splash screen so, can I create a new issue for it?

**Comment by narayan954** [comment]
> > > I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.
> > 
> > 
> > That'd be better I guess. What should we do then? Remove this dummygram na? and add the splash screen instead .
> 
> Yes, I think this should be removed. If you want to add a splash screen so, can I create a new issue for it?

would wish to, but before that, let's wait for other duplicate issue to finish.

**Comment by narayan954** [comment]
bookmarking the issue #531

**Comment by Palakkgoyal** [comment]
> > > > I think there should be a splash screen instead of just saying Dummygram. What do you think? I have seen only two I think, one is dummygram and second of which I am asking to redesign. I don't remember the third one.
> > > 
> > > 
> > > That'd be better I guess. What should we do then? Remove this dummygram na? and add the splash screen instead .
> > 
> > 
> > Yes, I think this should be removed. If you want to add a splash screen so, can I create a new issue for it?
> 
> would wish to, but before that, let's wait for other duplicate issue to finish. He's working on this as well

Ohkk, sure.
