### ISSUE TITLE
[FEATURE] Character limit on caption

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#781]
### Description

I think there must be limit on caption so that no one will be able to abruptly put a long article in it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I think there must be limit on caption so that no one will be able to abruptly put a long article in it.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

let's put limits in various components throughout, what do you say, for example username must've a limit, so does emails,name,comments,caption,etc, Add limit to whatever you feel fits, I'll add the rest in the pr.

**Comment by Palakkgoyal** [comment]
I have already given limit to username(Do not apply on the uid part) and I'll check other too.

**Comment by narayan954** [comment]
> I have already given limit to username(Do not apply on the uid part) and I'll check other too.

alright!
