### ISSUE TITLE
[FEATURE] Improve UI of profile page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#782]
### Description

The current UI of profile is not very good. I want to work on it and make it look amazing.

### Screenshots

![Screenshot 2023-07-13 171337](https://github.com/narayan954/dummygram/assets/116902573/2a272135-c042-44a6-82b4-912418f7800d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The current UI of profile is not very good. I want to work on it and make it look amazing.
> 
> ### Screenshots
> ![Screenshot 2023-07-13 171337](https://user-images.githubusercontent.com/116902573/253267578-2a272135-c042-44a6-82b4-912418f7800d.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sure, you can work on it!
