### ISSUE TITLE
Favourite route not showing liked posts

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#788]
### Description

favourite route not displaying any liked posts.

### Steps to reproduce

1.Go to /dummygram/favourites
2.See "You have nothing in favourites"

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by fiskryeziu** [comment]
Looks like the useEffect needs some improvements to fetch the liked posts of the user.

**Comment by narayan954** [comment]
> ### Description
> favourite route not displaying any liked posts.
> 
> ### Steps to reproduce
> 1.Go to /dummygram/favourites 2.See "You have nothing in favourites"
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

right!, in fact we're unable to get past the loader

**Comment by narayan954** [comment]
> Looks like the useEffect needs some improvements to fetch the liked posts of the user.

yes, you're right, it's not implemented correctly!
