### ISSUE TITLE
[BUG]: Sidebar not showing in Post page

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#789]
### Description

- Sidebar is not displayed in Post page.

### Steps to reproduce

- go to home page, click any post.

### Screenshots

<img width="658" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/f6f35d29-1741-491e-ad8f-7d4cd88b4ac9">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can work on this!
