### ISSUE TITLE
[FEATURE] Improve UI of search bar for search page

### ISSUE THREAD

**Issue by Geeta259** [narayan954/dummygram#791]
### Description

Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Make it responsive in all devices.

here is demo
![Screenshot (540)](https://github.com/narayan954/dummygram/assets/75520947/c320018e-de64-4654-898b-98d8aaba8aa3)

### Screenshots

![Screenshot (628)](https://github.com/narayan954/dummygram/assets/75520947/7a4c0e27-cfa9-4674-b6bb-00cd06d24f03)

@narayan954 I would like to contribute on this  project under GSSOC'23 !!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Sure, you can go ahead! :)
