### ISSUE TITLE
User Profile from Comments

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#796]
### Description

When we view comments on the post and click on the user who has commented something, it should take us to user's profile, but it shows 404 Page not found

![image](https://github.com/narayan954/dummygram/assets/97438986/478ee064-8de4-43c8-93d4-914d61c6d968)
When I click on my user name here 

![image](https://github.com/narayan954/dummygram/assets/97438986/54c4a7d1-cbed-4253-90af-5539292a3c9e)
it comes here 

### Steps to reproduce

We can route user name to its profile after clicking here 

I want to fix this! @narayan954 Please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!
