### ISSUE TITLE
[FEATURE] UI Improvement like button to change after the user click like

### ISSUE THREAD

**Issue by dishant0406** [narayan954/dummygram#80]
### Description

The Like button on every card should change according to the state 
If the user has already like it should be filled

Before Liking
![image](https://user-images.githubusercontent.com/90952604/195356061-862aacf3-b48b-4183-a462-4c4d76fe6897.png)

After Liking
![image](https://user-images.githubusercontent.com/90952604/195356155-70b8a8fc-d652-43e3-ae28-99b65973c4b6.png)

**Comment by dishant0406** [comment]
I am ready to work on this issue

**Comment by narayan954** [comment]
okay great!

**Comment by dishant0406** [comment]
If possible, can you please assign labels

**Comment by bhoopesh369** [comment]
can i work on this isuue? @narayan954

**Comment by narayan954** [comment]
@bhoopesh369 ask @dishant0406 as he seems to be already working on it

**Comment by dishant0406** [comment]
You can reassign this task @narayan954 I am working on the save posts task

**Comment by narayan954** [comment]
> You can reassign this task @narayan954 I am working on the save posts task

okay

**Comment by narayan954** [comment]
> can i work on this isuue? @narayan954 

yes you can

**Comment by bhoopesh369** [comment]
Please accept the pull request @narayan954

**Comment by narayan954** [comment]
looking into it :)
