### ISSUE TITLE
Sign up form improvement 

### ISSUE THREAD

**Issue by akanksha984** [narayan954/dummygram#800]
### Description

![image](https://github.com/narayan954/dummygram/assets/97845909/3090a4b6-f088-486c-a7b3-94ba525f4ebe)
![image](https://github.com/narayan954/dummygram/assets/97845909/642cedb9-3db0-4267-9dae-47d6b5b12b45)

I want to improve the ui of the signup form. The image is much extended. Please assign it to me under gssoc'23. 

### Steps to reproduce

Improvement in ui

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> ![image](https://user-images.githubusercontent.com/97845909/253527555-3090a4b6-f088-486c-a7b3-94ba525f4ebe.png) ![image](https://user-images.githubusercontent.com/97845909/253527569-642cedb9-3db0-4267-9dae-47d6b5b12b45.png)
> 
> I want to improve the ui of the signup form. The image is much extended. Please assign it to me under gssoc'23.
> 
> ### Steps to reproduce
> Improvement in ui
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sure, you may work on this! :) 
also please check login form's image as well, images of both login and signup page should synchronise for a good UI/UX

**Comment by akanksha984** [comment]
@narayan954 please check  https://github.com/narayan954/dummygram/pull/821
