### ISSUE TITLE
[FEATURE]  change padding of sidebar links

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#802]
### Description

right now it's not looking fine like it's pressed in both sides because of padding.

### Screenshots

How it's looking

![before](https://github.com/narayan954/dummygram/assets/64495368/82df0412-3460-4a47-b4fc-f92539da5a8f)

How it should look like : 

![after](https://github.com/narayan954/dummygram/assets/64495368/6e2566d8-05ad-46de-9b1b-daa703c12144)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Thanks for raising the issue, you can work on this! :)
