### ISSUE TITLE
[FEATURE] Post Page UI

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#806]
### Description

- The current UI pof post page looks very basic and boring.
- I would like to give it an attractive look.

### Screenshots

<img width="959" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/152690f1-6419-4b9d-b795-2f4289235a76">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Yes sure, you can work on this! :)
