### ISSUE TITLE
[DOCS] Fix formatting in README

### ISSUE THREAD

**Issue by Sriparno08** [narayan954/dummygram#809]
### Description

The title of the features are not bolded. We can bold them to make them clearly visible and separate them from their descriptions.

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/89148144/36d87b7f-6f37-483f-8e3e-e3f2b79719c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> The title of the features are not bolded. We can bold them to make them clearly visible and separate them from their descriptions.
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/89148144/253605043-36d87b7f-6f37-483f-8e3e-e3f2b79719c1.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can work on this!
