### ISSUE TITLE
[FEATURE] Change theme

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#818]
### Description

I would like to change app theme color .

### Screenshots

![Screenshot 2023-07-10 155832](https://github.com/narayan954/dummygram/assets/104631882/25129101-b934-4ecf-9df9-9147b2721df7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead! :)
