### ISSUE TITLE
[OTHER] Alignment of upward arrow

### ISSUE THREAD

**Issue by krutikajichkar** [narayan954/dummygram#825]
### What would you like to share?

The upward arrow is coming at center which doesnt looks goos , i want to move it on the left , please assign me this under gssoc'23

![Screenshot (164)](https://github.com/narayan954/dummygram/assets/93243210/4dd81675-5aaf-4b62-8e27-f7a737b668bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> The upward arrow is coming at center which doesnt looks good , i want to move it on the left , please assign me this under gssoc'23

Alright, you can work on this! Also, do check for responsiveness!
