### ISSUE TITLE
[OTHER] Search Bar Alignment

### ISSUE THREAD

**Issue by krutikajichkar** [narayan954/dummygram#826]
### What would you like to share?

- Instead of making another route for search bar don't you think it should placed along with posts ? 
-  so whenever user will search something the searched posts will be filtered on top.
- If you agree with this please assign me this under gssoc'23

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### What would you like to share?
> * Instead of making another route for search bar don't you think it should placed along with posts ?
> * so whenever user will search something the searched posts will be filtered on top.
> * If you agree with this please assign me this under gssoc'23
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [ ]  I have checked the existing issues
> * [ ]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

This seems like a good idea! As we're basically searching for posts right now in that page, so this'd better be implemented in the home as well. In future when we allow searching for users, then only this search page would be feasible as a separate page.

**Comment by narayan954** [comment]
you can work on this issue! :)
