### ISSUE TITLE
[OTHER] Changes in dark theme

### ISSUE THREAD

**Issue by krutikajichkar** [narayan954/dummygram#827]
### What would you like to share?

- The cards in the dark theme has purple box shadow to indicate that they are cards doesnt seems good i want adjust those cards according to dark theme
- Also the background color of sidebar components doesnt matches the UI when they are active , i want to turn them to purple
- Also the send button on  the card needs to be purple
- The borders that you have provided to indicate different div , i will replace them also
- If you agree please assign me this under gssoc'23

This is how it is looking right now
![Screenshot (166)](https://github.com/narayan954/dummygram/assets/93243210/2abc4af3-cc61-4aa8-b3c4-12dd55f68ca8)

This is how it will turn out to be in dark theme
![Screenshot (145)](https://github.com/narayan954/dummygram/assets/93243210/6c5b2fac-4608-4eeb-9c96-88bf1719ee5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by krutikajichkar** [comment]
This theme is for cards and sidebar

**Comment by narayan954** [comment]
Hi @krutikajichkar actually we're slowly moving to a light blue theme. There're 2 issues in progress for this, one for logo theme and one for components theme of the app, so I'd suggest we wait for them to be implemented, so we can implement this dark theme for our application without any conflict. I do like this dark theme with lighter and darker colour for card and sidebar.

**Comment by krutikajichkar** [comment]
Okay @narayan954 please let me know,  if you want me to implement this

**Comment by narayan954** [comment]
> Okay @narayan954 please let me know, if you want me to implement this

yes, I'll let you know at the right time.

**Comment by narayan954** [comment]
@krutikajichkar Can you please check and confirm the work to be done? I'd suggest the sidebar theme(lighter gray like in picture you provided, and same for posts, though there's already a shade of gray there) and let's adjust the shadow and all to maintain consistency. I'd be preferring the blue shade. Will add that shade to the logo as well. Also the borders separating the content, you may enhance them, Do let me know if there's any other thing in your mind.

**Comment by krutikajichkar** [comment]
@narayan954  yes, i'll let you know

**Comment by krutikajichkar** [comment]
@narayan954 Please have a look , and let me know for thye changes

![Screenshot (197)](https://github.com/narayan954/dummygram/assets/93243210/b1b3cc66-a000-4581-ad3c-9c890237e7b1)

**Comment by narayan954** [comment]
> @narayan954 Please have a look , and let me know for thye changes
> 
> ![Screenshot (197)](https://user-images.githubusercontent.com/93243210/255380247-b1b3cc66-a000-4581-ad3c-9c890237e7b1.png)

Can you please fix the logo as well?(some blue mix) I think this should be fine,,right? Btw You tell me, I'm bad at colors :')

I think, could you try [this pallete](https://colorhunt.co/palette/35394126282b5f85db90b8f8) check with current blue and this blue both

**Comment by krutikajichkar** [comment]
Okay I am trying this pallete

**Comment by krutikajichkar** [comment]
![Screenshot (202)](https://github.com/narayan954/dummygram/assets/93243210/86d63aca-8073-4c8d-9975-4eb8f8d1e26d)
![Screenshot (203)](https://github.com/narayan954/dummygram/assets/93243210/508284a9-fa4e-4394-ac0f-381733c39891)
@narayan954 Here are the results of that pallete also i made some shade changes in logo

**Comment by narayan954** [comment]
> ![Screenshot (202)](https://user-images.githubusercontent.com/93243210/255888248-86d63aca-8073-4c8d-9975-4eb8f8d1e26d.png) ![Screenshot (203)](https://user-images.githubusercontent.com/93243210/255888267-508284a9-fa4e-4394-ac0f-381733c39891.png) @narayan954 Here are the results of that pallete also i made some shade changes in logo

this looks good nah, actually? If so, you can work on this! :)

**Comment by krutikajichkar** [comment]
@narayan954 do you need any changes? Or should I make à PR

**Comment by narayan954** [comment]
> @narayan954 do you need any changes? Or should I make à PR

it looks good to me! you can go ahead!
