### ISSUE TITLE
Comment Post Icon

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#830]
### Description

When we view the post after clicking on it, there's a post button to post the comment instead of comment post icon as it appears on the homepage.

Please assign me this issue! 

### Steps to reproduce

![image](https://github.com/narayan954/dummygram/assets/97438986/ad98c505-e5af-4702-9b7a-1e63eaf89d7c)

here on this page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can fix that! :)
