### ISSUE TITLE
Increaseing the likes count 

### ISSUE THREAD

**Issue by Malavi1** [narayan954/dummygram#839]
### Description

Currently, we are allowing the user like the post only one time.
instead, we can let the user show their like towards that particular post by increasing the likes count.

### Additional information

I am thinking the count range is only 10 but if you have any suggestions do let me know.
Thank You :)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Malavi1 with this we'd need to implement something to remove the likes as well, It's perhaps a not good UX to have two butttons for this or having to reach a threshold to remove likes in case he misses the right amount of like he wishes to give. maybe we can skip it for future.

**Comment by Malavi1** [comment]
Thanks for the feedback!
Yeah we will implement later then :)
