### ISSUE TITLE
Changing the one of the leftbar side icons 

### ISSUE THREAD

**Issue by Malavi1** [narayan954/dummygram#840]
### What would you like to share?

to store all our favourite items we are using the heart icon which is similar to the like icon in the post.
If you allow I will change the icon.

### Additional information

![Screenshot (415)](https://github.com/narayan954/dummygram/assets/112646623/c263cb93-d86f-4214-8fad-2c6dbd22df57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Sure, you can work on this! and also change the name to saved perhaps ?? what do you think, suits better? Do rename that for the components as well?

**Comment by Malavi1** [comment]
Sure I got it👍
Thanks for the assigning :)
