### ISSUE TITLE
[FEATURE] A chatroom for all

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#842]
### Description

I want to create a chatroom in which anyone can reply. I think this will increase bonding and excitement among users and developers. What do you think?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I want to create a chatroom in which anyone can reply. I think this will increase bonding and excitement among users and developers. What do you think?
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

indeed!, but where'd we host it and all?

**Comment by Palakkgoyal** [comment]
I think we can do all this using firestore by creating a new db in it.

**Comment by narayan954** [comment]
> I think we can do all this using firestore by creating a new db in it.

Ohh alright! That works

**Comment by narayan954** [comment]
I've added level 3 label as it's a completely new and significant feature

**Comment by Palakkgoyal** [comment]
Thanks a lot
