### ISSUE TITLE
Comment routing

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#853]
### Description

- When clicking on the username in the comments, it's not redirecting to the requested page.

### Steps to reproduce

- Open comments in the home page, click username.

### Screenshots

https://github.com/narayan954/dummygram/assets/66116440/cfa63bde-9891-492d-8397-da3e86e040ec

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @anamika7153 There's a pull request solving this issue, pr #835 , I'll have to close this one ;-;
