### ISSUE TITLE
Improve the UI of login and signup page

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#854]
### Description

Hey @narayan954 I want to improve the UI of the login and signup page. Please assign me this issue. Thank you!
1. The password and confirm password inputs get misaligned when the password doesn't matches.
2. The image can be contained instead of fill to look good. Currently, it is looking stretched and proving bad UI.

### Steps to reproduce

Change styling

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100675296/76e486a0-7be7-4883-a9d5-db64332e99c1)

![image](https://github.com/narayan954/dummygram/assets/100675296/c22301b6-47b1-49c6-8607-db91ab07fbe9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> @narayan954 Please assign me this issue

Hi @sumitkr2000 there's been too many issue regarding this page, I'd be holding improvement issues for some time for these page. Also, a new image design is OTW :)

**Comment by sumitkr2000** [comment]
Okay @narayan954 understood
