### ISSUE TITLE
[FEATURE] Show post likers list

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#856]
### Description

I want to show the list of post likers. I think this will create more engagement.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal  this is duplicate to an issue assigned to you can @VijayalakshmiGanesh both, please work on that :)
issue #370 
closing as duplicate

**Comment by Palakkgoyal** [comment]
Ohkk
