### ISSUE TITLE
[FEATURE] Notification page css Change

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#858]
### Description

Notification page not looking good want to redesign.
I'm a GSSoC'23 contributor please assign me under gssoc23 label

### Screenshots

<img width="664" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/a6210952-19a4-4462-9ffb-69fb5e903a8d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Notification page not looking good want to redesign. I'm a GSSoC'23 contributor please assign me under gssoc23 label
> 
> ### Screenshots
> <img alt="image" width="664" src="https://user-images.githubusercontent.com/68702055/254161694-a6210952-19a4-4462-9ffb-69fb5e903a8d.png">
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

go ahead!

**Comment by ahsan-abc** [comment]
The problem has been solved then ,why this issue is still open

**Comment by narayan954** [comment]
> The problem has been solved then ,why this issue is still open 

some mistake I guess, thanks for notifying :)
