### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by GAURAV1-ui** [narayan954/dummygram#861]
### Description

Move Switch mode from light to dark button in header part.

### Screenshots

![Screenshot 2023-07-18 120101](https://github.com/narayan954/dummygram/assets/76157604/cdc7b42f-8727-43cb-95ef-de8dc866359d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi, this is a duplicate issue, closing
