### ISSUE TITLE
Sign in Page image

### ISSUE THREAD

**Issue by NandiniGera** [narayan954/dummygram#867]
### Description

![image](https://github.com/narayan954/dummygram/assets/97438986/3d857ea0-658e-407a-8a3f-32d23195d62e)

Instead of this image, I was thinking of designing another image with a Welcome to dummygram heading followed by some good caption and a good background, will share the edits here in the issue itself before making the pr.

If you find this a good idea, Please assign me this issue :) @narayan954 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
That'd be awesome @NandiniGera , you can go ahead! :D

**Comment by NandiniGera** [comment]
how does this look? @narayan954 

![image](https://github.com/narayan954/dummygram/assets/97438986/6bd90d1a-22e9-48d4-9f37-ce0cbe22417f)
in light mode

![image](https://github.com/narayan954/dummygram/assets/97438986/22b4fc26-1d57-4d27-9a10-850adc7a3727)
in dark mode

also this is a gif not an image, the caption contains effects.
and i've changed the form and background colour in light mode too.

**Comment by NandiniGera** [comment]
> > how does this look? @narayan954
> > in light mode
> > in dark mode
> > also this is a gif not an image, the caption contains effects. and i've changed the form and background colour in light mode too.
> 
> hi @NandiniGera sorry for being late, this is a good picture,but I doubt it matches the theme of our application, we need a more minimilastic approach. For example, in facebook signup page, it's just a simple picture. ![image](https://user-images.githubusercontent.com/77617189/255219160-8a64f2d8-fd6a-4449-975f-5c657bba0a2f.png) I think something like this'd be better, what do you think?

yess this looks good! I'll try implementing similar to this:)

**Comment by narayan954** [comment]
> 

cool!, thank you!!
