### ISSUE TITLE
Improve ui of page not found

### ISSUE THREAD

**Issue by akanksha984** [narayan954/dummygram#877]
### Description

![image](https://github.com/narayan954/dummygram/assets/97845909/e4b68353-b321-466d-b5e1-62a780cebe00)

I want to improve the ui of the page not found page.

Please assign it to me under gssoc'23

### Steps to reproduce

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can go ahead! @akanksha984 :) Btw that pic should load ;-;
