### ISSUE TITLE
[FEATURE]: SOUND EFFECTS FOR THEME TOGGLE BUTTON 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [narayan954/dummygram#878]
### Description

- We need to add sound effects while the user toggles the theme.
- There will be two types of sound effects one for Light mode toggle and another one for Dark mode toggle.
- This feature will be give an active feedback to the users which improves the user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @narayan954  👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by narayan954** [comment]
> Hey there @narayan954 👋🏻
> 
> Please make sure to assign this issue to me asap to make the work done!
> 
> Thank you.

Yes, sorry for being late, had some work

**Comment by narayan954** [comment]
sound effects are already implemented for several components, you can can copy the implementation approach

**Comment by Palakkgoyal** [comment]
Can I work on this if @0xabdulkhalid is busy?

**Comment by narayan954** [comment]
@0xabdulkhalid are you busy,not working on this??? please try to tell us by tonight :)

**Comment by 0xabdulkhalid** [comment]
No, please don't assign this to another person.

I will a make a PR Tonight

**Comment by 0xabdulkhalid** [comment]
@narayan954 PR has opened!
