### ISSUE TITLE
Add delete account feature

### ISSUE THREAD

**Issue by akanksha984** [narayan954/dummygram#880]
### Description

Please assign it to me under gssoc'23

### Steps to reproduce

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
That'd be really awesome, @akanksha984 you can go ahead!

**Comment by Palakkgoyal** [comment]
Hey @akanksha984 are you working on this?

**Comment by akanksha984** [comment]
yes @Palakkgoyal

**Comment by akanksha984** [comment]
should i create pr for this @narayan954 ?

**Comment by narayan954** [comment]
> should i create pr for this @narayan954 ?

sure, go ahead! :)
