### ISSUE TITLE
[FEATURE] Search bar position

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#882]
### Description

I think the search bar would look good in the navbar rather than in the main view.

### Screenshots

![Screenshot (614)](https://github.com/narayan954/dummygram/assets/116902573/c4577388-a66c-4854-9dbb-f8d2cb9f0b3b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I think the search bar would look good in the navbar rather than in the main view.
> 
> ### Screenshots
> ![Screenshot (614)](https://user-images.githubusercontent.com/116902573/254824482-c4577388-a66c-4854-9dbb-f8d2cb9f0b3b.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

It's gone actually, I reverted the commit and will need to add it back. Navbar seems like a good idea, and we can even remove the separate page it is in, already! further reducing the sections in sidebar

**Comment by narayan954** [comment]
> > ### Description
> > I think the search bar would look good in the navbar rather than in the main view.
> > ### Screenshots
> > ![Screenshot (614)](https://user-images.githubusercontent.com/116902573/254824482-c4577388-a66c-4854-9dbb-f8d2cb9f0b3b.png)
> > ### Additional information
> > _No response_
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [x]   I have checked the existing issues
> > * [x]   I'm a GSSoC'23 contributor
> > * [x]   I want to work on this issue
> 
> It's gone actually, I reverted the commit and will need to add it back. Navbar seems like a good idea, and we can even remove the separate page it is in, already! further reducing the sections in sidebar

would you like to work on this, instead. If yes, it's a green light, and assume labels, level 2 (as the query here would require some different logic, might even need a context)

**Comment by Palakkgoyal** [comment]
Yes, I would like to work on it. Can you tell me a little bit about query like should we query to get post or the person?

**Comment by narayan954** [comment]
> Yes, I would like to work on it. Can you tell me a little bit about query like should we query to get post or the person?

I think we should make it user query as we've user profiles now!

**Comment by Palakkgoyal** [comment]
I think querying for user would be more suitable cause if someone query for post then they will still type the name of person and the post will be displayed of that person. Instead we can provide querying for user by which the person can go to user profile and access all data.

**Comment by narayan954** [comment]
absolutely correct! completely agree on this!

**Comment by anamika7153** [comment]
@narayan954 could you assign this issue to me as it is not resolved yet ?

**Comment by narayan954** [comment]
> @narayan954 could you assign this issue to me as it is not resolved yet ?

sure!
