### ISSUE TITLE
Loader did not stop on profile

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#883]
### Description

When a user is not found on the profile page the loader continuously spins that will create problem for the user that they will think that the profile is still loading. I want to fix this bug.

### Steps to reproduce

NOTE: This will not work on github hosted link try it on localhost.
- Go to url `/dummygram/`
- Add a username abruptly that do not exist `/dummygram/sjkfjerjj`
- The loader will spin endlessly.

### Screenshots

![Screenshot 2023-07-20 140636](https://github.com/narayan954/dummygram/assets/116902573/7ed4d885-9e5a-4e46-bf92-533096874a6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> * Add a username abruptly that do not exist `/dummygram/sjkfjerjj`

You can fix that definitely! :)
