### ISSUE TITLE
UI of post page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#884]
### Description

I don't know what happened but, currently the UI of post page is horrible.
I want to work on it.

### Steps to reproduce

Go to any post page you will see it.

### Screenshots

![Screenshot (615)](https://github.com/narayan954/dummygram/assets/116902573/f8d3e808-13cb-4a10-9d35-d7b7bf9d28db)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
I think it's better now after I reverted a commit. Just the post pic seems to be missing, is there anything else that's deformed now? 
Can you fix that and test for multiple/single/no image case?

**Comment by narayan954** [comment]
Hi @Palakkgoyal issue #806  addresses this and is working on this, I'd have to close this one as duplicate :/
