### ISSUE TITLE
Sidebar bug on profile page

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#885]
### Description

Hey @narayan954 There is a bug on the sidebar on the profile page. top-0 should fix it. Please assign me this issue. Thank you!

### Steps to reproduce

Add top 0 to sidebar

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100675296/c28a1244-5639-4224-a776-f3258cf9ba2f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
I think it's working fine, can you please recheck?

**Comment by sumitkr2000** [comment]
yes now its working fine

**Comment by narayan954** [comment]
closing this issue, then :)
