### ISSUE TITLE
[FEATURE] Match the background of back to top button with the theme of website 

### ISSUE THREAD

**Issue by sumitkr2000** [narayan954/dummygram#886]
### Description

Hey @narayan954 It would look nice if we change the background color od back to top button matching the theme of the website. I have attached the screenshot please have a look. Please assign me this issue. Thank you!

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/100675296/119dbf57-1f4a-4249-90a9-bca9f809329e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @sumitkr2000 can you add more small issues to this one for grading?

**Comment by sumitkr2000** [comment]
yeah sure

**Comment by sumitkr2000** [comment]
@narayan954 I have found some more issue which can be fixed. These are:

1. Since the favorites have changed to saved. Here also we need to change to favorites

![image](https://github.com/narayan954/dummygram/assets/100675296/4dc4ab6a-2fe4-400a-ae52-28a7fd059633)

3. The profile picture is too small. Its width should be unset.

![image](https://github.com/narayan954/dummygram/assets/100675296/46451d0c-40c2-4967-8f33-9f3c17684f12)

3. The posts are overlapping with the navbar in row mode. It can also be fixed.

![image](https://github.com/narayan954/dummygram/assets/100675296/478452e1-7d94-472a-a3e2-9940f932f3ec)

**Comment by narayan954** [comment]
> @narayan954 I have found some more issue which can be fixed. These are:
> 
> 1. Since the favorites have changed to saved. Here also we need to change to favorites
> 
> ![image](https://user-images.githubusercontent.com/100675296/255318748-4dc4ab6a-2fe4-400a-ae52-28a7fd059633.png)
> 
> 3. The profile picture is too small. Its width should be unset.
> 
> ![image](https://user-images.githubusercontent.com/100675296/255318772-46451d0c-40c2-4967-8f33-9f3c17684f12.png)
> 
> 3. The posts are overlapping with the navbar in row mode. It can also be fixed.
> 
> ![image](https://user-images.githubusercontent.com/100675296/255318820-478452e1-7d94-472a-a3e2-9940f932f3ec.png)

right, you can pick the first one and second while third one is raised and claimed :)
