### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#887]
### Description

In search bar page search bar only search username with small letter and also on that page necessary vertical line is appear  .
I would like to fix that bug.

### Steps to reproduce

Steps
1. Write function to search capital or small letter start username
2. Test the function.

### Screenshots
![Screenshot 2023-07-20 183257](https://github.com/narayan954/dummygram/assets/104631882/032630f2-4e3f-4dec-a5db-6e9b3418a39d)

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Sure, you can go ahead!

**Comment by anamika7153** [comment]
@narayan954 i'm already working on the similar issue #755

**Comment by narayan954** [comment]
> @narayan954 i'm already working on the similar issue #755 

ohhh alright, apologies, will correct.

**Comment by narayan954** [comment]
> ### Description
> 
> In search bar page search bar only search username with small letter and also on that page necessary vertical line is appear  .
> I would like to fix that bug.
> 
> ### Steps to reproduce
> 
> Steps
> 1. Write function to search capital or small letter start username
> 2. Test the function.
> 
> ### Screenshots
> ![Screenshot 2023-07-20 183257](https://github.com/narayan954/dummygram/assets/104631882/032630f2-4e3f-4dec-a5db-6e9b3418a39d)
> 
> _No response_
> 
> ### Desktop (please complete the following information)
> 
> _No response_
> 
> ### Smartphone (please complete the following information)
> 
> _No response_
> 
> ### Additional information
> 
> _No response_
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I have checked the existing issues
> - [X] I'm a GSSoC'23 contributor
> - [X] I want to work on this issue

Hi @BhartiNagpure this is duplicate issue actually, will have to close ;-;
