### ISSUE TITLE
ThemeButton icon not perfectly centered

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#890]
### Description

themebutton not centered 

### Steps to reproduce

1.Login 
2.See themebutton  on the right side of the navbar

### Screenshots

How it's looking
![Screenshot (8)](https://github.com/narayan954/dummygram/assets/64495368/2e1d1dcb-6462-4617-93b2-f99f03b094ca)

How it should be
![Screenshot (9)](https://github.com/narayan954/dummygram/assets/64495368/9a5edab4-acef-4733-b858-d0aa9cc42f3d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can work on this!
