### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#891]
### Description

Whenever we click on comment there are so many error messages in the console.

### Steps to reproduce

- Go to /dummygram/
- Click on any post's comment button
- Error messages will appear in the console.

### Screenshots

![Screenshot (619)](https://github.com/narayan954/dummygram/assets/116902573/9ae107b9-b455-4da8-829d-e0601fcbfe36)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Yes, you can work on this!
