### ISSUE TITLE
User image on profile page

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#892]
### Description

Its very shrinked like its in a post

### Steps to reproduce

- Go to user profile
- The image will be shrinked and user display name also lost its styling.

### Screenshots

![Screenshot 2023-07-20 225533](https://github.com/narayan954/dummygram/assets/116902573/f4cd437a-5091-4c3c-8851-9d9b8de38125)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
What happened?

**Comment by narayan954** [comment]
This issue exists, right?

**Comment by Palakkgoyal** [comment]
No, I don't know it somehow get solved. Might be due to when you reverted back a commit during that community chat PR

**Comment by narayan954** [comment]
> No, I don't know it somehow get solved. Might be due to when you reverted back a commit during that community chat PR

![image](https://github.com/narayan954/dummygram/assets/77617189/a7da0718-6d13-41fd-858f-b6a1176477b2)
It's still the same as you raised, right?? I doubt if this got resolved ;-;

**Comment by Palakkgoyal** [comment]
Is it let me check. Actually, I was out and now, I have to check what is updated here, so that I can start working again.

**Comment by narayan954** [comment]
> Is it let me check. Actually, I was out and now, I have to check what is updated here, so that I can start working again.

it's fixed now :)

**Comment by Palakkgoyal** [comment]
Ohk, that's great.
