### ISSUE TITLE
Long post messing due to their image

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#893]
### Description

In the multi-column view long post are messing with other. I want to give the post content a fixed height and also provide the image a height also maintaining their aspect ratio

### Steps to reproduce

Click on multi column layout

### Screenshots

![Screenshot (620)](https://github.com/narayan954/dummygram/assets/116902573/b17828fc-05f8-49cf-9d52-c48d4fc1c2d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal #859 is onto solving this problem, Im closing this as duplicate
