### ISSUE TITLE
css alignment issue chat Section

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#895]
### Description

css alignment issue chat Section and redesign 
I'm a GSSoC'23 contributor please assign me this task under GSSoC label 

### Steps to reproduce

go to website and click on chat 

### Screenshots

before :- 
<img width="739" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/6d3b8bec-d142-4add-9075-b2a9fd0fb5aa">

after :- 
<img width="744" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/31eb6db1-43ca-460b-9335-7f4aed80bdb1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!

**Comment by narayan954** [comment]
> you can go ahead!

also, please test for longer messages as well

**Comment by biplavmz** [comment]
ok @narayan954
