### ISSUE TITLE
Post delete cleanup

### ISSUE THREAD

**Issue by narayan954** [narayan954/dummygram#897]
### Description

When a user deletes a post, it's static data is removed but not the resources like post image or it's presence in someone's favourite list or it's ref from the user's document.

### Steps to reproduce

check what create post does.
check what the delete function did.
delete a post(after noting down it's field values)
check perhaps your user collection, favourites list

### Additional information

Not cleaning up everything might be feasible/easy, like for example post's ref in favourites list.
Adapt accordingly. 
Main focus could be removing the post images and post ref from user's collection(if it exists)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Palakkgoyal** [comment]
Can I work on this?

**Comment by narayan954** [comment]
> Can I work on this?

Of course you can! :)

**Comment by narayan954** [comment]
do check the info I provided and verify them and then take actions!

**Comment by Palakkgoyal** [comment]
Ohk sure.
