### ISSUE TITLE
sidebar fix on mobile devices

### ISSUE THREAD

**Issue by fiskryeziu** [narayan954/dummygram#899]
### Description

the sidebar is a little bit off 

### Steps to reproduce

1.Login
2.Resize browser window under 800px or use phone
3.See sidebar

### Screenshots

without fix:
![Screenshot (12)](https://github.com/narayan954/dummygram/assets/64495368/48ec628d-5ee8-47d9-a198-a0226350c77c)

with fix: 
![Screenshot (15)](https://github.com/narayan954/dummygram/assets/64495368/4965b0ab-9e1f-4204-a633-ef05e0ab3fa7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can go ahead! Thanks for picking it out!
