### ISSUE TITLE
[FEATURE] Emoji in comment box

### ISSUE THREAD

**Issue by Sheikh566** [narayan954/dummygram#90]
### Description

Currently, there is only an icon for the emoji picker.
We should have a working Emoji picker to add emoji in comments

### Screenshots

![Capture](https://user-images.githubusercontent.com/62289744/197340062-55e1729e-09e0-4629-8eaa-c26dbb06e3c2.PNG)

**Comment by Sheikh566** [comment]
I would like to work on this. Can you assign it to me?

**Comment by narayan954** [comment]
sure, go ahead!
