### ISSUE TITLE
[DOCS] Readme update

### ISSUE THREAD

**Issue by khushimarothi** [narayan954/dummygram#900]
### Description

The readme is so long and the contributors section is adding more to its length. I want to make it toggle type o if user wants to see they can click it and view the contributors or else it will remain closed.

### Screenshots

![Screenshot (170)](https://github.com/narayan954/dummygram/assets/85816852/fb917e3a-aca0-4a43-b2f4-c8a001f19892)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> 
> The readme is so long and the contributors section is adding more to its length. I want to make it toggle type o if user wants to see they can click it and view the contributors or else it will remain closed.
> 
> 
> 
> 
> ### Screenshots
> 
> ![Screenshot (170)](https://github.com/narayan954/dummygram/assets/85816852/fb917e3a-aca0-4a43-b2f4-c8a001f19892)
> 
> 
> ### Additional information
> 
> _No response_
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I have checked the existing issues
> - [X] I'm a GSSoC'23 contributor
> - [X] I want to work on this issue

you can go ahead!
