### ISSUE TITLE
Hovering the navbar items doesnt show proper color

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#902]
### Description

On hovering over the toggle button and chat button, icons turn black in dark mode and remain black in light mode.
On hovering, It should turn blue in dark mode and light mode just like the sidebar links.

### Steps to reproduce

Go to website 
hover over the toggle button and chat button in both the modes.

### Screenshots

https://github.com/narayan954/dummygram/assets/66116440/3c8a32de-566d-49e9-bbeb-11e2d6483b20

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Correct! You can go ahead!
