### ISSUE TITLE
[FEATURE] Profile page UI

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#904]
### Description

- Current UI is not much user friendly and attractive.
- I would like to 

1. increase the size of the profile icon and change its position to top left.
2. add edit profile option near the profile pic as the current edit icon doesn't give clarity of what it will update
3. change the font weight as currently name and bio holds same weight. 
4. remove the username which shows the user id instead of username.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by anamika7153** [comment]
@narayan954  do you have anything else in mind for the profile page information ?

**Comment by narayan954** [comment]
> ### Description
> * Current UI is not much user friendly and attractive.
> * I would like to
> 
> 1. increase the size of the profile icon and change its position to top left.
> 2. add edit profile option near the profile pic as the current edit icon doesn't give clarity of what it will update
> 3. change the font weight as currently name and bio holds same weight.
> 4. remove the username which shows the user id instead of username.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

I agree on those points but'd like to add a correction to 4th point. Actually it's showing the username only, but currently the default assigned username is uid of users. This username is to be made changeable. It had to be a unique identifier so we used uid as default, while for signup using email you can select your own username as well.

**Comment by anamika7153** [comment]
> 

okay! we can get rid of this when we add update details option

**Comment by narayan954** [comment]
> > 
> 
> okay! we can get rid of this when we add update details option

alright, let's wait it out before we merge the pr #935 It solves that
