### ISSUE TITLE
[FEATURE] Profile page background and user info update option

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#905]
### Description

Currently, same image is displayed as the profile background. I would like to add the update option for the background image.
I would like to try adding the option to update user information.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Currently, same image is displayed as the profile background. I would like to add the update option for the background image. I would like to try adding the option to update user information.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

yes, there's two approach,provide pre added options or let user select them. Letting user select would attract compatibility issue, like sizing/aspect ration, but there again, that can be called user's fault. Pre added options would be highly compatible, but limited. 
What do you think suits? Anyways you can work on this! :)
