### ISSUE TITLE
Regarding the styling of eye icon in the password field

### ISSUE THREAD

**Issue by shruuti321** [narayan954/dummygram#907]
### Description

the eye icon field is not going well with the entire theme in the dark  mode.
I would like to make some changes to make it look better

### Steps to reproduce

I will change the css of the page

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/114770273/a4973a66-c885-480c-89ba-515ab4af32ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Yes, you can work on this!, and please check it for responsiveness and for both login and signup pages. 

Thank you!
