### ISSUE TITLE
Post caption Readmore not visible

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#909]
### Description

- On home page, post caption doesn't show 'read more'.
- I would like to add 'read more' and link that to the post page.

### Steps to reproduce

go to website
create a post with large content
see the post caption on home page

### Screenshots

| | |
|---|----|
| whole caption | incomplete caption without **readmore** |
| <img  alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/431fbf32-6bd4-4f53-834a-2b412447edd4"> | ![image](https://github.com/narayan954/dummygram/assets/66116440/f91ba390-edc0-4a22-8d96-dfe91a6b2ceb)|

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!
