### ISSUE TITLE
padding below post caption and on post page 

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#911]
### Description

- There is no padding below post caption on home page
- There is no proper padding in post page also.

### Steps to reproduce

go to website
see the post caption with longer caption

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/66116440/f84ef5af-5925-4d4e-b690-ce7b7e05072b)

<img width="956" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/188d7b2b-b8d1-43e6-a8d9-064760c7d3c0">

<img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/59ddedbc-f737-4321-845c-a0e75151c479">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
hi @anamika7153 can you please add another small issues to this one, this one seems a one liner fix :/

**Comment by anamika7153** [comment]
> hi @anamika7153 can you please add another small issues to this one, this one seems a one liner fix :/

let me see

**Comment by anamika7153** [comment]
@narayansoni check now

**Comment by narayan954** [comment]
> @narayansoni check now
> 

sure you can go ahead! :)
