### ISSUE TITLE
hide the three dot button in the profile page 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#912]
### Description

I am in the profile page of image posted user. we need to hide the view profile in that section.
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website click on the posted images click three dot and click on view profile in that profile we need to hide this feature 

### Screenshots

<img width="514" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/c2d56764-35eb-4628-b218-0f62b10f4c44">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!
