### ISSUE TITLE
In profile page on dark mode text color issue 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#913]
### Description

In profile page on dark mode text color issue 
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website and click on the post of view profile.

### Screenshots

<img width="465" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/17023544-c3f4-4695-9bd4-c87af334b202">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> In profile page on dark mode text color issue I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website and click on the post of view profile.
> 
> ### Screenshots
> <img alt="image" width="465" src="https://user-images.githubusercontent.com/68702055/255330582-17023544-c3f4-4695-9bd4-c87af334b202.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @biplavmz , there's actually an background image. Text's colour's fine, it's problem with some browsers I guess which is not loading the background image, I don't know why?
![image](https://github.com/narayan954/dummygram/assets/77617189/fa970bc8-2571-4a52-a456-ae02ca26a03f)

Can you try resolving this browser issue? I want to fix this issue instead of using an alternative, like different css to load background?

**Comment by biplavmz** [comment]
Hii @narayan954  can we use linear gradient hear 
<img width="466" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/ee69afea-a766-4535-802b-dfa79795aaea">

**Comment by biplavmz** [comment]
because images are breaking in the Microsoft edge

**Comment by narayan954** [comment]
I think if It doesn't affects the Ui, we can do this!! you can go ahead!

**Comment by biplavmz** [comment]
ok @narayan954
