### ISSUE TITLE
[FEATURE] want to add comment delete option  

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#914]
### Description

After commenting if i want to delete my comment.
we are unable to delete so i want to add one delete button feature so that i will delete it if i want to.

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Screenshots

<img width="533" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/3da5e7b0-35ed-462a-b014-03bdb3aede2f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
This option was always present, I can't recall where it got modified :/
I checked, implementation exists already, you just have to enable it.
You can work on this!
