### ISSUE TITLE
Grid post view responsiveness

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#916]
### Description

- When enabling the grid view of posts, posts are going behind the navbar. I checked and saw that someone messed up with the padding.

### Steps to reproduce

got to home page
enable the grid view
see the posts shifted upward behind the navbar

### Screenshots

<img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/5f0b2aff-dfbc-41ca-a5a3-703ad7504343">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Thanks for finding, you can work on this! :)
