### ISSUE TITLE
Id instead of user name in post page

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#918]
### Description

On post page, comment section displays user id instead of user name.
| | |
|---|----|
| <img width ="560" src="https://github.com/narayan954/dummygram/assets/66116440/c1e46c20-b044-453e-b50e-1679b77cbff6"> |<img width="957" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/e03dc524-beb2-4f19-9768-118b5eacefe3">|
|<img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/efdded25-d952-4b76-8dd3-448f38a5223d"> |  <img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/c321de83-bd28-4e2e-9185-ad67e456a1cf">|

### Steps to reproduce

go to website 
open any post with some comments
see the comment section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> On post page, comment section displays user id instead of user name.
> 
> <img alt="" width="560" src="https://user-images.githubusercontent.com/66116440/255376820-c1e46c20-b044-453e-b50e-1679b77cbff6.png">	<img alt="image" width="957" src="https://user-images.githubusercontent.com/66116440/255376421-e03dc524-beb2-4f19-9768-118b5eacefe3.png">
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/66116440/255376798-efdded25-d952-4b76-8dd3-448f38a5223d.png">	<img alt="image" width="960" src="https://user-images.githubusercontent.com/66116440/255376493-c321de83-bd28-4e2e-9185-ad67e456a1cf.png">
> ### Steps to reproduce
> go to website open any post with some comments see the comment section
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Yes, you can fix that! :)
