### ISSUE TITLE
Save button visibility

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#925]
### Description

Currently profile pic save button is much clear.
I would like to add some stylings to make it visible clearly.

### Steps to reproduce

select an image to update profile pic, see the save button

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/66116440/e87f9b3d-4d20-4314-8f35-afed4580d426)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Let's wait out for #935 for this. If this view still exists, we can work on this!

**Comment by SharmaDhruv2511** [comment]
want to work on this issue. Can you please assign it to me?

**Comment by narayan954** [comment]
> want to work on this issue. Can you please assign it to me?

Hi @SharmaDhruv2511 this issue is outdated and no longer required, so closing it.
