### ISSUE TITLE
on hover card image css breake 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#929]
### Description

on hover profile card profile image breaking.

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Steps to reproduce

go to website hover on card post profile.

### Screenshots

<img width="142" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/c3385856-6e88-4c76-9baa-ceaa21019ea0">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> on hover profile card profile image breaking.
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Steps to reproduce
> go to website hover on card post profile.
> 
> ### Screenshots
> <img alt="image" width="142" src="https://user-images.githubusercontent.com/68702055/255397732-c3385856-6e88-4c76-9baa-ceaa21019ea0.png">
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

you can work on this!
