### ISSUE TITLE
[FEATURE] Guidelines Page UI

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#932]
### Description

Current UI of Guidelines page doesnt look good.
I would like to work on it to make it attractive.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Great, you can go ahead!
