### ISSUE TITLE
[FEATURE]  add a edit button 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#934]
### Description

add a edit button  user can write his description 
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level

### Screenshots

<img width="577" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/1f8f9502-b14a-4a25-8076-148c0424a77f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @biplavmz pr #935 solves this, so closing this as not planned right now :)
