### ISSUE TITLE
[FEATURE] Set up pagination for chat

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#936]
### Description

Initially chat just show last 20 message. I want to set up pagination for it such that whenever someone scroll to top they get more messages loaded. And also the chat page starts from top and not from bottom like any other chat. I want to fix that also.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> Initially chat just show last 20 message. I want to set up pagination for it such that whenever someone scroll to top they get more messages loaded. And also the chat page starts from top and not from bottom like any other chat. I want to fix that also.
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Alright! as you see fit! :)
