### ISSUE TITLE
feedback responsiveness

### ISSUE THREAD

**Issue by Walexz01** [narayan954/dummygram#939]
### Description

the form margin top so it is under the header 
the textarea doesn't have a fixed size 

### Steps to reproduce

go to the feedback page

### Screenshots

![Screenshot_20230724_013510](https://github.com/narayan954/dummygram/assets/102121986/35083997-9947-48dd-a7d2-8b8afc6c620d)
![Screenshot_20230724_014122](https://github.com/narayan954/dummygram/assets/102121986/5ae43efc-d17c-464b-9f43-c44e6a9348e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can work on these! :) Also, do add character limit of your choice!

**Comment by Walexz01** [comment]
Ok sir
