### ISSUE TITLE
[FEATURE] Adding a grid view on profile

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#941]
### Description

I want to add a grid view on profile page for feed like instagram. 

### Screenshots

![Screenshot (623)](https://github.com/narayan954/dummygram/assets/116902573/bab718a4-4f77-4135-b5a9-3190e947299f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
right, it's not functional right now! ;-;
