### ISSUE TITLE
Enhancing footer container in sidebar

### ISSUE THREAD

**Issue by shruuti321** [narayan954/dummygram#944]
### Description

The footer container in the sidebar is not properly organised.
I have attached a screenshot of enhanced footer in sidebar so that looks organised and efficiently spaced.

### Screenshots

Before
![image](https://github.com/narayan954/dummygram/assets/114770273/44ddfdb5-1ff8-4b63-bac6-af59db78943f)
After
![image](https://github.com/narayan954/dummygram/assets/114770273/329a8e80-d0a4-4115-95bd-7abf34299893)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Great! @shruuti321 you can go ahead with the pr! also try to place it at the bottom, as it's not entirely at bottom but floating in between

**Comment by shruuti321** [comment]
@narayan954  while pushing the commits I am getting this error which I never encountered before.Please help
![image](https://github.com/narayan954/dummygram/assets/114770273/e5382c6d-1a8c-408b-b243-35154f322c3e)
