### ISSUE TITLE
profile modal and update button

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#947]
### Description

profile pic update modal's edit button not working.
i propose on removing the edit button from the modal and giving it some stylings (it's too enlarged right now)

### Steps to reproduce

go to your profile
try editing your pic by clicking the avatar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi due to recent changes such as story feature, this option was removed, but if there's no story , we should allow to see them, or there should be option to view either of them in case story exists. What do you think?
