### ISSUE TITLE
[FEATURE] separate edit pic functionality

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#949]
### Description

- Currently, edit profile pic feature is not user friendly in the edit information modal.
- User gets to know about it only after clicking the avatar.
-  I would like to add an edit button on the top right of the avatar on the profile page's avatar and modal avatar.
- Edit information gives the option to edit profile pic but I would like to add an edit profile pic option separately too for user ease.

### Screenshots

- something like this:
<img width="314" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/1fb84f98-00bc-4624-a8a9-6e92d1bcc270">

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead!
