### ISSUE TITLE
[FEATURE] Remove followers and following 

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#952]
### Description

- Currently, on hovering the user profile, it displays dummy followers and following.
- Since, accepting follow requests is not yet implemented, it should be removed.

### Screenshots

<img width="605" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/91fb3f33-cf6e-4628-ba34-982485ddf1f6">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> * Currently, on hovering the user profile, it displays dummy followers and following.
> * Since, accepting follow requests is not yet implemented, it should be removed.
> 
> ### Screenshots
> <img alt="image" width="605" src="https://user-images.githubusercontent.com/66116440/255845605-91fb3f33-cf6e-4628-ba34-982485ddf1f6.png">
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Yes, we may not remove it but hide/comment for now, also as its a 1 line fix, can you please add other small issues to this? Like maybe displaying the actual bio if it exists, as bio feature has been implemented!?

**Comment by anamika7153** [comment]
> > ### Description
> > 
> > * Currently, on hovering the user profile, it displays dummy followers and following.
> > * Since, accepting follow requests is not yet implemented, it should be removed.
> > 
> > ### Screenshots
> > <img alt="image" width="605" src="https://user-images.githubusercontent.com/66116440/255845605-91fb3f33-cf6e-4628-ba34-982485ddf1f6.png">
> > ### Additional information
> > _No response_
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [x]   I have checked the existing issues
> > * [x]   I'm a GSSoC'23 contributor
> > * [x]   I want to work on this issue
> 
> Yes, we may not remove it but hide/comment for now, also as its a 1 line fix, can you please add other small issues to this? Like maybe displaying the actual bio if it exists, as bio feature has been implemented!?

sure :)
