### ISSUE TITLE
Remove the delete option on story for other users

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#976]
### Description

Currently, anyone can delete story of any user.

### Steps to reproduce

- Go to user profile who has posted a story
- You will see a delete icon there
- You can click on it and delete other user story

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
Hi @Palakkgoyal , this is a really small issue, please combine it with other small issues, you can go ahead!
