### ISSUE TITLE
Fetch dynamic data for profile dialog box

### ISSUE THREAD

**Issue by Palakkgoyal** [narayan954/dummygram#978]
### Description

I am bit confused in this cause the need to fetch dynamic data for profile dialog box is just for the bio and nothing else. Should I add this now or later?
![Screenshot (625)](https://github.com/narayan954/dummygram/assets/116902573/2207354d-13b1-4cf0-9fd3-dc75dbb7bcd3)

### Steps to reproduce

Hover over user avatar on post.
It will open a dialog box which will contain a static bio.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I am bit confused in this cause the need to fetch dynamic data for profile dialog box is just for the bio and nothing else. Should I add this now or later? ![Screenshot (625)](https://user-images.githubusercontent.com/116902573/256153785-2207354d-13b1-4cf0-9fd3-dc75dbb7bcd3.png)
> 
> ### Steps to reproduce
> Hover over user avatar on post. It will open a dialog box which will contain a static bio.
> 
> ### Screenshots
> _No response_
> 
> ### Desktop (please complete the following information)
> _No response_
> 
> ### Smartphone (please complete the following information)
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Sorry but this has just been resolved with a merged pr #993 :)
 The data included username,displayname,bio,location,etctetc

**Comment by narayan954** [comment]
closing as duplicate to #952 (perhaps it was not updated and that was a mistake, sorry)

**Comment by Palakkgoyal** [comment]
No need to say sorry. Its absolutely fine. Thanks for informing.
