### ISSUE TITLE
🐛There is no close button for chat 

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#981]
### Description

There should be a close button for chat unable to close the chat.

### Steps to reproduce

go to website and click on chat icon
I'm a GSSoC'23 contributor pls assign me under GSSoC'23 label and level.

### Screenshots

<img width="734" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/66490aa9-d3f9-472e-96f4-74040b7624cb">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead! 😄
