### ISSUE TITLE
want edit button to edit the banner

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#982]
### Description

want edit button to edit the banner

### Steps to reproduce

go to profile 

### Screenshots

<img width="714" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/08592339-4a5f-4ecf-b070-746487281f4c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
hi @biplavmz this issue has been raised and claimed in #905 . I'll have to close this as duplicate please
