### ISSUE TITLE
Login page background color and margin

### ISSUE THREAD

**Issue by shruuti321** [narayan954/dummygram#984]
### Description

I would like to change the login page background colors to more vibrant colors as below;
Also there is no margin at the top of login page.
![image](https://github.com/narayan954/dummygram/assets/114770273/6112b507-0ffc-4b2a-9e27-2c9c7dd52bbe)

### Screenshots

![image](https://github.com/narayan954/dummygram/assets/114770273/48b807a2-5416-4b6c-88c0-3a9dd9946746)
![image](https://github.com/narayan954/dummygram/assets/114770273/01193848-6a80-47d8-8b40-6c20164a2f47)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> I would like to change the login page background colors to more vibrant colors as below; Also there is no margin at the top of login page. ![image](https://user-images.githubusercontent.com/114770273/256236538-6112b507-0ffc-4b2a-9e27-2c9c7dd52bbe.png)
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/114770273/256236249-48b807a2-5416-4b6c-88c0-3a9dd9946746.png) ![image](https://user-images.githubusercontent.com/114770273/256236443-01193848-6a80-47d8-8b40-6c20164a2f47.png)
> 
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

Hi @shruuti321 you can go ahead! :)
Also, check [this pallete](https://colorhunt.co/palette/35394126282b5f85db90b8f8) for two blacks, if they work fine it'd be better, else your changes are awesome as well
