### ISSUE TITLE
[FEATURE] Story UI

### ISSUE THREAD

**Issue by anamika7153** [narayan954/dummygram#988]
### Description

I would like to change the position of delete button and close icon to make it more accessible.
Also if caption is longer, it's not completely visible.
I would like to change the UI and make everything properly visible.

### Screenshots

<img width="957" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/e7820675-dc7c-467b-9046-3e063104b427">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
You can go ahead! :)
