### ISSUE TITLE
activetab

### ISSUE THREAD

**Issue by BhartiNagpure** [narayan954/dummygram#995]
### Description

Activetab css is not show to profile. and also need to remove horizontal line of profile page.

### Steps to reproduce

go to profile page 
set the active class css
remove horizontal line 

### Screenshots

![Screenshot 2023-07-27 104713](https://github.com/narayan954/dummygram/assets/104631882/86b53696-8896-40b2-864c-d24cd2dca1fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
you can go ahead! :)
