### ISSUE TITLE
want to add search Feature for contributors

### ISSUE THREAD

**Issue by biplavmz** [narayan954/dummygram#999]
### Description

want to add search Feature for contributors

I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Screenshots

<img width="893" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/d20a6ccf-8999-4f28-bcbb-3daad36f016d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by narayan954** [comment]
> ### Description
> want to add search Feature for contributors
> 
> I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.
> 
> ### Screenshots
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/68702055/256495117-d20a6ccf-8999-4f28-bcbb-3daad36f016d.png">
> ### Additional information
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSoC'23 contributor
> * [x]  I want to work on this issue

sure, you can work on this!
